js/danoni_main.js

他に以下を変更しています。
- 通常時のみ、ステップゾーンヒット時の色を判定色に合わせて付加
- キー押しっぱなしでステップゾーンがヒット中になり続ける現象を解消

[ver0.51.0] 判定キャラクタ 及び ステップゾーンヒット時のモーションをタイマーに変更

---

js/danoni_main.js

ライフゲージ(数字)に対してバーの追加
先の実装が仮実装のため（今回も仮だが）
これを正規にするかどうかは今後検討

ライフゲージバー仮実装

---

js/danoni_main.js

ライフゲージのボーダーラインの位置調整
ボーダーラインを超えてもFailed位置にいるときがあるため、位置調整を行う。

[ver0.76.3] ライフゲージバーの位置調整

---

js/danoni_main.js

結果画面表示のColor:OFFの表示不具合を修正
表示不具合のFix

[ver0.77.2] 結果画面表示のColor:OFFの表示不具合を修正

---

css/danoni_main.css
js/danoni_main.js

- Cleared/Failed条件追加
- No Recovery, SuddenDeathの実装
- リザルト画面の変更
- クリア成功・失敗条件の実装がゲーム成立の条件として必要なため
- 従来のCleared/Failed演出は、リザルト画面に統合しました。

[Feature/result] Cleared/Failed条件追加

---

js/danoni_main.js

- 厳密等価演算子 === と !== を使うように変更
- 真偽値の比較に等価演算子を使わないように変更
- 設定画面のSpeed, Adjustmentの上限・下限値の直接指定を見直し
- 等価演算子を使った比較の際、内部的に型変換が行われ、
意図しない比較結果が返ることを防ぐため。
- 将来的な速度上限、Adjustment上限の変更に対応するため、定数化できる箇所を今のうちに変更。

[ver1.4.0] 厳密等価演算子 === と !== を使うように変更　他

---

js/danoni_main.js

- base64エンコードしたmp3への対応
- 下記のようなjsファイルをmusicフォルダ(既定)に入れて、
musicUrlでjsファイルとして指定することで、
base64エンコードしたmp3が読み込まれるようになります。
```
function musicInit(){
g_musicdata='base64エンコードされた音楽データ';
}
```
- mp3の利用条件によっては、直接mp3ファイルをファイルサーバへ
アップロードすることが禁止されている場合があるため、その対応
- 互換性のため、既存の機能もそのまま生かしています。
mp3ファイルとして上げる場合は、
.htaccessでmp3にアクセス制御を掛けるなどの措置を取ることを強く推奨します。

[audioEnc:0.1.0] オーディオエンコード実装（jsファイル指定）

---

js/danoni_main.js

1. 判定名をカスタムできるように変更
1. リザルト画面の右上のクリアマークについて、
パーフェクト・フルコンボの表記ができるよう追加
1. 判定名が作品毎に異なる場合があるため
1. CLEAREDだけではリザルトの詳細がわかりにくいため

[ver1.13.0] 判定名をカスタムできるように変更

---

js/danoni_main.js

#162 の再提案です。
テンプレート文字列への変更だけ抜き出しました。

Fix strings. Use template literals.

---

js/danoni_main.js

- #108 の変更を戻しました。
#164 v2.0.0からIE11非対応のため、不要な処理になりました。

Revert. #108

---

js/danoni_main.js

- デフォルト背景が前に見えてしまう不具合を修正
- 上記の通り。

[ver2.1.1] デフォルト背景が前に見えてしまう不具合を修正

---

js/danoni_custom.js
js/danoni_main.js

1. Ready表示の反映漏れを修正
1. デフォルトのReady表示が事実上使用できなくなってしまうため。

[ver2.1.2] Ready表示の反映漏れを修正

---

js/danoni_main.js

dos入力用inputにファイル名が指定されたとき、外部ファイルから譜面データを読み込むようにしました。
```
<input type="hidden" name="dos" id="dos" value="filename.txt">
```
\*.txtまたは\*.jsのときだけ外部読み込みを行い、それ以外では従来通りHTMLから読み込みます。
外部ファイル側には次のように記述します。
```
function externalDosInit() {
g_externalDos = `
(譜面データ)
`;
}
```
HTMLと違って&が特殊文字ではないので、従来の&区切りでも動くようにしています。
issue #145

譜面データの外部ファイル化に対応 (issue #145)

---

js/danoni_main.js

- 譜面データの外部ファイル化対応
- 譜面データを外部ファイル化することで、エディターからのテキスト出力に対応しやすくするため

[ver2.3.0] 譜面データの外部ファイル化対応 (issue #145)

---

danoni/danoni2.html
js/danoni_main.js

- Pull Request #180 を参照のこと。
- Shift-JISの外部譜面データを読込できるようにするため。

[ver2.5.0] 外部譜面データ読込時の文字コード設定を追加

---

js/danoni_main.js

開始位置、楽曲再生位置の設定の条件式を修正 ( Pull Request #192 )
issue #176

 [ver2.6.1] フェードイン時間がblankFrameより小さい時にタイミングがずれる問題を修正

---

js/danoni_main.js

楽曲の再生にWeb Audio APIを使用するように変更　( Pull Request #195 )
issue #176

[ver2.7.0] 可能な場合にWebAudioAPIで楽曲を再生するように変更

---

js/danoni_main.js

譜面ヘッダで再生速度を指定できるようにしました。
~~~
|playbackRate=0.7|
~~~
難譜面のテストプレイ時に便利だと思います。
多少ずれますが、譜面のタイミングには音声やキー入力の遅延の補正が通常含まれていて、これらの遅延が再生速度に依存しないため、倍率をかけたときにその分ずれるのだと思います。
おそらく環境依存があるので機械的に補正するのは難しそうです。

譜面ヘッダで再生速度を指定できるように変更

---

js/danoni_main.js

- 譜面ヘッダで再生速度を指定できるように変更 ( Pull Request #199 )
- ソース更新年を表記するように変更
- Pull Request #199 を参照

 [ver2.8.0] 譜面ヘッダで再生速度を指定できるように変更　他

---

js/danoni_main.js

再生速度変更時にフェードアウトが正常に動作しない問題を修正しました。
fadeOutFrameにplaybackRateを考慮していませんでした。
また、C_FRM_AFTERFADEにplaybackRateがかかっていました。
何度もすみません…。

再生速度変更時のフェードアウト動作の修正

---

js/danoni_main.js

- Pull Request #201 を参照。
- ver2.8.0関連の修正です。

 [ver2.8.1] 再生速度変更時のフェードアウト動作の修正

---

js/danoni_custom.js
js/danoni_custom2.js
js/danoni_main.js

ロード画面をカスタムする以下の関数をdanoni_custom.jsに追加する。
- customLoadingProgress
- customLoadingProgress2
- ロード画面にオリジナリティを持たせるため。
イベントプロパティを引数にセットしているため、
loadedプロパティ・totalプロパティの利用も可能です。

[customLoad:0.1.0] カスタム用ローディングを追加

---

js/danoni_custom.js
js/danoni_custom2.js
js/danoni_main.js

- Pull Request #203 を参照。
- Pull Request #203

 [ver2.9.0] ロード画面をカスタムできるように変更

---

js/danoni_main.js

- Pull Request ( #208 ) を参照。
- Pull Request ( #208 )
- この変更により、ロード時間が若干長くなります。

[ver2.9.2] 急いでプレイ開始すると曲時間がNaNになる不具合の修正

---

js/danoni_main.js

- 共通系関数のIE特殊対応を削除
- Pull Request #165 等と同じ理由で、IE11互換になっていた記述を削り、簡素化しました。

[ver2.9.3] 共通系関数のIE特殊対応を削除

---

js/danoni_custom.js
js/danoni_custom2.js
js/danoni_main.js
js/danoni_setting.js

Pull Request #210 を参照。
Pull Request #210 を参照。
- danoni_setting.js という外部ファイルが1つ増えていること、
また近いうちに他の規模の大きい機能 ( Pull Request #209 )が控えていることを踏まえ、
メジャー番号を上げる対応とします。

[ver3.0.0] 製作者別設定ファイルを追加 

---

danoni/danoni1.html
js/danoni_main.js

Styleオプション(Mirror,Random,Random+,S-Random,S-Random+)を実装しました。
7key高難易度等のやり込み要素としてあるといいかなと思いました。
動作確認用譜面を作りました。
https://gist.github.com/suzme/c99d2b0ef412ba9b9e24ac87d58a90a0

ミラー・ランダムの実装

---

js/danoni_main.js
js/danoni_setting.js

Pull Request #217 を参照。
Pull Request #217 を参照。

[ver3.1.2] ローディング100%で数秒止まる問題の修正

---

js/danoni_main.js

Pull Request #219 を参照。
issue #206 関連

[ver3.1.3] 不正な歌詞データで止まらないように修正

---

js/danoni_main.js

Pull Request #223 を参照。
Pull Request #223 を参照。

 [ver3.2.0] 曲名のWebフォント対応＆グラデーション設定の追加

---

js/danoni_main.js

- Display画面のデザイン修正
- Display画面について、今後の設定画面の確保のためデザインを変更。

[setting-design] Display画面のデザイン修正

---

danoni/danoni1.html
js/danoni_main.js

- 曲名タイトル（デフォルト）の複数行対応 ( #229 )
- Pull Request #229 を参照。

[ver3.5.0] 曲名タイトル（デフォルト）の複数行対応

---

danoni/danoni1.html
js/danoni_custom.js
js/danoni_main.js
js/danoni_setting.js

- 設定ファイル ( danoni_setting.js )のデフォルト値を指定 ( #232 )
- カスタムデザインの有無を設定ファイルで一律指定できるように変更 ( #232 )
- 総ノート数が0のときスコアがNaNになる不具合の修正 ( #231 )
Pull Request #231 , #232 を参照。

[ver3.6.0] 設定ファイルのデフォルト値を指定　他

---

js/danoni_main.js

- Pull Request #245 を参照。
- Pull Request #245 を参照。

[ver3.12.0] キーコンフィグ画面にデフォルト色を指定できるように変更 (ColorTypeの追加)

---

js/danoni_main.js

- Pull Request #247 を参照。
- Pull Request #247 を参照。

[ver3.13.0] ColorTypeがDefault以外の場合、Display:ColorをOFFにするよう修正

---

js/danoni_main.js

Pull Request #252 を参照。
Pull Request #252 を参照。

[ver4.0.0] 複数曲の読込に対応、譜面別に曲名を複数表示できるように変更

---

js/danoni_main.js

- Pull Request #255 を参照。
- Pull Request #255 を参照。

[ver4.1.0] ローカルストレージ設定（作品別）を追加

---

js/danoni_main.js

- Display画面からプレイ開始できない問題を修正
- ver4.0.0で曲の読込タイミングが変更になったことによる修正漏れを修正しました。

[ver4.1.1] Display画面からプレイ開始できない問題を修正

---

js/danoni_main.js

- ハイスコア機能の実装
- 譜面毎にハイスコアを保存するようにしました。
ただし、以下の場合は保存されません。
- AutoPlayが「ON」の場合
- Shuffleが「OFF」以外の場合
- Flash版に存在する機能で未実装分の実装となります。
- ハイスコアの保存状況の表示は現状、結果画面のみです。
今後、表示場所の拡大等については別途検討します。

[storage-local] ハイスコア機能の実装

---

js/danoni_main.js

Pull Request #263 を参照。
Pull Request #263 を参照。

 [ver4.3.1] ハイスコアデータの初期化忘れを修正

---

js/danoni_main.js

Pull Request #265 を参照。
Pull Request #265 を参照。

[ver4.3.2] カスタムスコアの場合、ハイスコア差分が正しく反映されない問題を修正

---

js/danoni_main.js

Pull Request #272 を参照。
Pull Request #272 を参照。

[ver4.5.0] キー毎にリバース、キーコンフィグを自動保存するように変更

---

js/danoni_main.js

- ローカルストレージの保存有無ボタンの追加
- キー別のローカルストレージ名を変更
- キーコンフィグを変更した場合に、変更後のキーコンフィグが既存キーパターンに継承されてしまう問題を修正
- ver4.5.0関連の不具合及び仕様の見直しのため。
- キー別のローカルストレージ名は、データの格納元がわかるような名前に変更しました。
- 変更前) 7k
- 変更後) danonicw-7k

[storage-local] localStorage保存有無ボタン追加、キー別のlocalStorage名を変更

---

js/danoni_main.js

- 譜面合初期情報ロード許可フラグの不具合を修正
- 先のPull Request #274 の追加修正です。

[storage-local] 譜面合初期情報ロード許可フラグの不具合を修正

---

js/danoni_main.js

- Display画面からEnterキーで開始すると画面が止まる問題を修正
- Display画面からEnterキーで開始した際、曲を読み込む処理を入れていなかったため。
ver4以降で発生する問題です。

[ver4.9.1] Display画面からEnterキーで開始すると画面が止まる問題を修正

---

js/danoni_main.js

- Pull Request #291 を参照。
- Pull Request #291 を参照。

[ver5.0.0] 設定画面のスクリプトを整理

---

js/danoni_main.js

- 特殊キーが既存キーと同一の場合に、設定画面で止まる問題を修正
- 上述の通り。

[ver5.0.2] 特殊キーが既存キーと同一の場合に、設定画面で止まる問題を修正

---

danoni/danoni1.html
js/danoni_main.js

- Pull Request #297 を参照。
- Pull Request #297 を参照。

[ver5.1.0] 複数行別々のグラデーションの実装

---

js/danoni_main.js

- バージョン名の追記（本来はdevelopにて設定の予定だったが誤り）

[ver5.2.0] ---

---

js/danoni_main.js

- Pull Request #309 を参照。
- Pull Request #309 を参照。

[ver5.3.0] 曲名タイトルのline-heightの指定値が小さい場合に文字欠けする問題を修正

---

css/danoni_main.css
js/danoni_main.js

- Pull Request #311 を参照。
- Pull Request #311 を参照。

[ver5.4.0] 歌詞表示(word_data)の複数階層化対応 #307

---

js/danoni_custom.js
js/danoni_custom2.js
js/danoni_main.js

- Pull Request #313 を参照。
- Pull Request #313 を参照。

[ver5.5.0] フリーズ開始判定が取れるようにカスタム関数を追加

---

js/danoni_main.js

- Pull Request #321 を参照。
- Pull Request #321 を参照。

 [ver5.6.5] 歌詞表示のフェードイン・アウトのモーションをlinearに変更

---

js/danoni_main.js

- 背景画像表示（デフォルト）のコード見直しを行いました。
基本、`drawDefaultBackImage(param)`で呼び出す形式に変えています。
- 同じコードの集約。
以前から記載があった箇所にもかかわらず、同じコードが多々あったため。
- 今後も関数への集約、クラスへの転換を進めていきます。
今回は影響が小さいところを修正しました。

[Feature/0015-code-refactoring] 背景画像表示（デフォルト）のコード見直し

---

js/danoni_main.js

- Pull Request #328 を参照。
- Gitter要望より。

[ver5.8.0] 譜面データの区切り文字のON/OFF追加、譜面データのURIデコード処理の追加

---

danoni/danoni1.html
js/danoni_main.js

- ステップゾーン位置がずれている問題を修正
- posXの値を大きくすると、ステップゾーン位置が左寄りになっていました。
（逆に小さくすると右寄りに）

[ver5.8.1] ステップゾーン位置がずれている問題を修正

---

danoni/danoni1.html
js/danoni_main.js

- Pull Request #331 を参照。
- Pull Request #331 を参照。

 [ver5.9.0] 独自キーの2段目のpos最終番号を指定できるように変更 他

---

js/danoni_main.js

PageUp・PageDown・End・Homeをキーブロック対象に追加しました。
gitterより。
誤ってスクロールするのを防ぐためです。

PageUp・PageDown・End・Homeをキーブロック対象に追加

---

danoni/danoni1.html
js/danoni_main.js

- Pull Request #336 , #337 を参照。
- Pull Request #336 , #337 を参照。

[ver5.11.0] キーブロック追加、リトライ・タイトルバックをキー毎に設定できるように変更

---

js/danoni_main.js

- Pull Request #343 を参照。
- Pull Request #343 を参照。

[ver5.12.2] フリーズアローのみの譜面がプレイできない問題を修正

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
js/danoni_main.js

1. 配点・最大スコアの変数化 ( #350 )
2. ダミーフリーズアロー用関数の一部引数間違いを修正
1. Pull Request #350 を参照。
2. 処理が無いため影響はないが、念のため修正

[ver6.2.0] 配点・最大スコアの変数化、ダミーフリーズアロー用関数の一部引数間違いを修正

---

js/danoni_main.js

- Pull Request #355 を参照。
- Pull Request #355 を参照。

 [ver6.2.1] 独自キーが2譜面目以降にある場合に読み込みできない場合がある問題を修正

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
js/danoni_main.js

- Pull Request #357 を参照。
- Pull Request #357 を参照。

[ver6.3.0] リバース用背景・マスクモーション、リザルトモーションの実装

---

js/danoni_main.js

- Pull Request #359 を参照。
- Pull Request #359 を参照。

[ver6.4.0] masktitle_dataの実装

---

js/danoni_main.js

- Pull Request #363 を参照。
- Pull Request #363 を参照。

[ver6.5.1] フェードイン時に個別加速が掛からない問題を修正　他

---

js/danoni_main.js

1. 特殊キーのキーコンフィグ保存機能を実装。
- 特殊キーの場合は作品毎に設定を変えることが可能なため、
キー毎のローカルストレージではなく、作品別のローカルストレージへ保存しています。
2. キーコンフィグが保存されていない初回のみ、
変更したキーコンフィグ内容が反映されない問題を修正。
1. 特殊キーでも通常キーと遜色なくキーコンフィグを使用できるようにするため。
2. 不具合修正。
2.についてはローカルストレージを使用しているバージョンにも対処が必要。
（ver4以上が該当）

[0030-storage-extrakeys] 特殊キーのキーコンフィグ保存機能実装

---

README.md
js/danoni_main.js

- Pull Request #365 を参照。
- Pull Request #365 を参照。
- ver4.10.14, ver5.12.5

[ver6.6.0] 特殊キーに対してローカルストレージを実装

---

js/danoni_main.js

1. ボタン色を見直し
2. ボタン色を変更可能に（const→let化）
1. 全体的に暗く、見づらい配色だったため明るくしました。
2. 作品によって配色を変えられるよう、letに変更しました。

[0032-button-graphic] ボタン色を見直し

---

js/danoni_main.js

- 矢印・フリーズアローのCSSモーションのON/OFFボタンを追加
- ver7.0.0にて矢印・フリーズアローのCSSモーションを追加したが、
プレイ側でOFFにする機能が無かったため。

[0023-arrow-style(2)] 矢印・フリーズアローのCSSモーションのON/OFFボタンを追加

---

css/danoni_main.css
js/danoni_main.js

1. 主要ボタンにアニメーションを挿入
2. Escキーのキーコンフィグ割り当てを禁止
1. 二重クリックによるプレイ開始といった誤爆を抑止するため
2. Escキーを使用すると画面が止まる問題があるため
1. CSSファイルの更新が必要となります。

[0034-button-ui] 主要ボタンにアニメーションを挿入

---

README.md
css/danoni_main.css
js/danoni_main.js

- Pull Request #375 を参照。
- Pull Request #375 を参照。

[ver7.2.0] ボタンUIにアニメーションを挿入

---

js/danoni_main.js

- Pull Request #381 を参照。
- Pull Request #381 を参照。

[ver7.3.1] Display画面へ遷移したときにボタンアニメーションが解除されない問題を修正

---

js/danoni_main.js

- Pull Request #386 を参照。
- Pull Request #386 を参照。

[ver7.5.0] 譜面ヘッダー:preloadImagesの複数まとめ記述の実装

---

js/danoni_main.js

- Pull Request #388 を参照。
- Pull Request #388 を参照。

[ver7.5.1] back_data, mask_dataで0フレームが指定された場合の不具合を修正

---

js/danoni_main.js

- 複数譜面時に2譜面目以降が読み込めない問題を修正
- ver7.7.0の変更に伴う問題の修正。

[0046-flexible-reload] 複数譜面時に2譜面目以降が読み込めない問題を修正

---

js/danoni_main.js

- Pull Request #400 を参照。
- Pull Request #400 を参照。

 [ver7.7.1] 複数譜面時に2譜面目以降が読み込めない問題を修正

---

js/danoni_main.js

- Pull Request #402 を参照。
- Pull Request #402 を参照。

[ver7.8.0] リザルトモーション周りの仕様変更

---

js/danoni_main.js

- Pull Request #404 を参照。
- Pull Request #404 を参照。

[ver7.8.1] 位置調整によらず見た目の曲時間を表示するように変更

---

js/danoni_main.js

- Pull Request #406 を参照。
- Pull Request #406 を参照。

[ver7.8.2] キーコンフィグの別パターンが選択できない問題を修正

---

js/danoni_main.js

- Pull Request #411 を参照。
- Pull Request #411 を参照。

[ver7.9.1] コメント行にカンマを入れたときの不具合を修正

---

js/danoni_main.js

- endFrame指定時に強制フェードアウトする問題を修正
- Pull Request #419 の不具合修正。

[0057-result-motion-div(2)] endFrame指定時に強制フェードアウトする問題を修正

---

js/danoni_main.js

- Pull Request #430 を参照。
- Pull Request #430 を参照。

[ver8.0.3] fadeFrameが譜面数に到達しない場合にプレイが止まる問題を修正

---

js/danoni_main.js

- Pull Request #435 を参照。
- Pull Request #435 を参照。

[ver8.1.0] タイトル文字の重ね順を変更

---

js/danoni_main.js

- コードの整理
- 曲中ショートカット移動後のkeyUpイベントを無効化
- keyUpイベントでたまにエラーを出していることがあったため。

[0064-code-refactoring] コード整理、曲中ショートカット移動後のkeyUpイベントを無効化

---

danoni/danoni3.html
js/danoni_main.js

- 譜面変更用セレクターの実装 ( #441 )
- 曲中ショートカット移動後のkeyUpイベントを無効化 ( #442 )
- Pull Request #441, #442 を参照。

[ver8.3.0] 譜面変更セレクターの実装　他

---

js/danoni_main.js

- Pull Request #444 を参照。
- Pull Request #444 を参照。

[ver8.4.0] 譜面変更用のセレクターに、キー別のフィルターボタンを追加

---

js/danoni_main.js

- Pull Request #450 を参照。
- Pull Request #450 を参照。

[ver8.5.1] （外部）譜面データの一時クリア条件を緩和

---

danoni/danoni0.html
danoni/danoni1.html
danoni/danoni2.html
danoni/danoni3.html

- IEなど、HTML5の記述に対応していないブラウザに対して警告文を表示するメッセージを追加しました。
- ソース本体の更新はありません。
- IEの場合、エラーも表示されずプレイもできない状態のため。

[0069-sample-backup] サンプルHTMLの更新

---

danoni/danoni0.html
danoni/danoni1.html
danoni/danoni2.html
danoni/danoni3.html
js/danoni_main.js

- Pull Request #452, #453 を参照。
- Pull Request #452, #453 を参照。

[ver8.5.2] scoreIdをクエリ指定した場合の初期速度の不具合を修正　他

---

js/danoni_main.js

- Pull Request #455 を参照。
- Pull Request #455 を参照。

[ver8.6.0] 本来booleanで設定すべき変数の型変更

---

js/danoni_main.js

1. エラーリストが表示されない問題を修正
2. ファイル読込失敗した場合のエラーメッセージを追加
1. バージョンが進むにつれ、ファイルの読込位置が変わりエラーメッセージが表示されないようになっていたため。（エラーメッセージ作成後にウィンドウをクリアしていた）
2. ファイル読込失敗した場合のメッセージが無かったため。
- 1.については過去バージョンの一部にも同様の事象が発生している可能性があります。

[0073-error-lists] エラーリストが表示されない問題を修正　他

---

js/danoni_main.js

- clearWindow() の指定場所誤りを修正
- 上述の通り。メッセージが表示される前にウィンドウをクリアしていた問題を修正。

[0073-error-list(2)] clearWindow() の指定場所誤りを修正

---

js/danoni_main.js

- Pull Request #459, #460を参照。
- Pull Request #459, #460を参照。（Issue #458 関連）

[ver8.6.1] エラーメッセージが表示されない不具合を修正　他

---

js/danoni_main.js

- ゲージ設定が一部初期値になる問題を修正
- Gitterの報告より。

[gauge-setting] ゲージ設定が一部初期値になる問題を修正

---

js/danoni_main.js

- Pull Request #462 を参照。
- Pull Request #462 を参照。

[ver8.6.2] ゲージ設定が一部初期値になる問題を修正

---

js/danoni_main.js

- Pull request #467, #468 を参照。
- Pull request #467, #468 を参照。

[ver8.7.0] ローカルストレージ（作品別）のキーからscoreIdを除去　他

---

js/danoni_main.js

- Pull Request #470 を参照。
- Pull Request #470 を参照。

[ver8.7.1] fpsが小数の場合にタイマーが作動しない問題を修正

---

js/danoni_main.js

- Pull Request #472, #473 を参照。
- Pull Request #472, #473 を参照。

[ver8.7.2] エスケープ文字の適用順序誤りを修正

---

js/danoni_main.js

- Pull Request #477 を参照。
- Pull Request #477 を参照。

[ver8.7.3] 速度変化が同一フレームにあると正常に動作しなくなる不具合の修正

---

css/danoni_main.css
js/danoni_main.js
js/danoni_setting.js

- Appearanceオプションの実装 ( #476 )
- Pull Request #476 を参照（Issue #475 より）
- Hidden/Suddenの他、Slit (Blinkに相当)を追加しています。
- #476 にもある通り、矢印・フリーズアローのオブジェクトルートが変わっているので注意してください。

[ver9.0.0] Appearanceオプションの実装

---

danoni/danoni3.html
js/danoni_main.js

- Pull Request #483 を参照。
- Pull Request #483 を参照。

[ver9.0.2] ダミー譜面指定の譜面ヘッダー誤りを修正

---

js/danoni_main.js

- Pull Request #485 を参照。
- Pull Request #485 を参照。

[ver8.0.3] ダミー矢印用カスタム関数が定義できない問題を修正

---

js/danoni_main.js

1. 2譜面目以降で背景、矢印モーションが指定されていない場合、1譜面目のデータを読み込むように変更 ( #487 )
2. back/mask_dataにおいてオールクリアできない問題を修正 ( #488 )
- Pull Request #487, #488 を参照。

[ver9.1.0] 矢印・背景モーションの補完機能追加　他

---

js/danoni_main.js

- Pull Request #492 を参照。
- Pull Request #492 を参照。

[ver9.2.0] フリーズアローヒット部分の描画変更 他

---

js/danoni_main.js

1. キーコンフィグ画面からDisplay画面にも戻れるように対応 ( #494 )
2. Ready表示の遅延フレーム設定を追加 ( #495 , Issue #491 )
3. リバース用のword_dataを実装 ( #497 )
- Pull Request #494, #495, #497 を参照。

[ver9.3.0] Ready表示の遅延フレーム設定　他

---

css/danoni_main.css
js/danoni_main.js
js/danoni_setting.js

- Pull Request #496 を参照。
- Pull Request #496 を参照。

[ver9.4.0] カスタムゲージの実装

---

js/danoni_main.js

- Pull Request #500, #501 を参照。
- Pull Request #500, #501 を参照。
- いずれも過去バージョンには関係しない修正です。

[ver9.4.1] 個別色変化時のフリーズアロー(AA)ヒット時の色が変化しない問題を修正　他

---

js/danoni_main.js

- Pull Request #500, #501 を参照。
- バージョン番号の上げ忘れ。

[ver9.4.1] 個別色変化時にフリーズアロー(AA)ヒット時の色が変わらない問題を修正 他

---

js/danoni_main.js

- Ready?の遅延フレーム設定でAdj.が反映されていない問題を修正しました。
readyDelayFrameが0以上の場合のみ、Adjustmentを反映してReady?を遅延させます。
- Adjustmentを足した結果遅延フレームがマイナスになる場合は特に補正を行いません。
- Adjustmentが0以外の場合、想定されたタイミングでReady?表示がされないため。
なお、0の場合はタイミングを意図したものではないものもあることから、そのままとする。

[0092-ready-delay-adjustment] Ready?の遅延フレーム設定でAdj.が反映されていない問題を修正

---

js/danoni_main.js
js/danoni_setting.js

- Pull Request #504, #505 を参照。
- Pull Request #504, #505 を参照。
- danoni_setting.js の差し替えがあります。

[ver9.4.2] Ready?の遅延フレーム設定でAdj.が反映されていない問題を修正 他

---

css/danoni_main.css
js/danoni_main.js

- Pull Request #508 を参照。
- Pull Request #508 を参照。

[ver9.4.3] ゲージ設定明細のレイアウトを修正

---

js/danoni_main.js

- ライフ固定/変動フラグを記述しているコードを集約
- コード整理のため。

[0095-gauge-initial] ライフ固定/変動フラグを記述しているコードを集約

---

js/danoni_main.js

1. iOS時の警告メッセージを追加しました。
1. ロードが途中で止まる理由が示されないため。

[0108-fix-iOS(2)] iOS時の警告メッセージを追加

---

css/danoni_main.css
js/danoni_main.js

1. iOSでロードが止まる問題を一部解消 ( #523, #525 )
2. skinTypeがdefault以外の場合、背景オブジェクトを作成するよう変更 ( #524 )
- Pull Request #523, #524, #525 を参照。

[ver10.1.0] iOSでロードが止まる問題を一部解消　他

---

js/danoni_main.js

- Pull Request #527 を参照。
- Pull Request #527 を参照。

[ver10.1.1] macOS/iOSにおける動作不具合対応

---

js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #537 を参照。
- Pull Request #537 を参照。

[ver10.2.3] ぃょぅがギコの画像になっている問題を修正

---

js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #539 を参照。
- Pull Request #539 を参照。

[ver10.2.4] 譜面選択リストの長さ間違いを修正

---

js/danoni_main.js

1. 重複記述部分のコードを整理しました。
1. 冗長な記述を除去し、コードを見やすくするため。

[0118-code-refactoring] 重複記述部分のコードを整理

---

js/danoni_main.js

1. 重複記述部分のコードを整理しました。
1. 冗長な記述を除去し、コードを見やすくするため。

[0118-code-refactoring(2)] 重複記述部分のコードを整理

---

js/danoni_main.js

1. 重複記述部分のコードを整理しました。
1. 冗長な記述を除去し、コードを見やすくするため。

[0118-code-refactoring(3)] 重複記述部分のコードを整理

---

README.md
js/danoni_main.js

- Pull Request #541, #542, #543を参照。
- 冗長な記述を除去し、コードを見やすくするため。機能変更はありません。

[ver10.3.0] 重複記述部分のコードを整理 

---

js/danoni_main.js

[0121-code-refactoring2] コードを整理

---

js/danoni_main.js

[0121-code-refactoring3] コードを整理

---

js/danoni_main.js

[0121-code-refactoring4] 先頭大文字化のコード整理

---

js/danoni_main.js

1. ハイスコア差分、スコア表示のid重複を解消 ( #545, #546 )
2. 矢印のヒット部分を押したタイミングに応じて変わるように変更 ( #547 )
3. コードを整理 ( #548, #549, #550 )
- Request #545, #546, #547, #548, #549, #550 を参照。

[ver10.4.0] 矢印のヒット部分を押したタイミングに応じて変わるように変更 他

---

js/danoni_main.js

[0122-code-refactoring5] 判定部分のコード整理　他

---

js/danoni_main.js

1. リザルト用ラベルの指定間違いを修正 ( #553 )
2. 判定部分のコード見直し ( #552 )
- Pull Request #552, #553 を参照。

[ver10.4.1] リザルト用ラベルの指定間違いを修正　他

---

js/danoni_main.js

- フルコンボ・パーフェクト演出のコード見直しを行いました。

[0127-code-refactoring] コード見直し

---

js/danoni_main.js

1. ファイル読込関係のコードを整理 ( #560 )
2. Localhostアクセス時にフレーム数を表示するように対応 ( #561 )
3. ラベル重複を修正 ( #557 )
4. リザルト画面のカスタム関数の位置見直し ( #557 )
- Pull Request #557, #560, #561 を参照。

[ver10.5.0] コード整理、localhost対応、ラベル重複修正

---

js/danoni_main.js

[ver10.5.1] fileでも起動可能なようにcrossorigin属性の付加条件を変更

---

js/danoni_main.js

1. 結果画面の曲名表示のid名の重複を修正しました。
1. 上述の通り。

[0131-fix-dupli-label] id名の重複を修正

---

js/danoni_main.js

1. 実装途中の未定義関数を除去しました。
1. 低速でかつ、フレーム数調整が発生した場合にエラーが発生し、続行不能になるため。

[0134-undefined-func] 実装途中の未定義関数を除去

---

js/danoni_main.js

1. キーコンフィグがundefinedになる場合がある問題を修正 ( #569 )
2. 実装途中の未定義関数を除去 ( #570 )
- Pull Request #569, #570 を参照。

[ver11.0.2] 未定義関数の除去　他

---

js/danoni_main.js

- Pull Request #573, #574 を参照。
- Pull Request #573, #574 を参照。

[ver11.1.0] 下側の歌詞表示位置をステップゾーン位置に追随させる設定を追加　他

---

js/danoni_main.js

[ver11.1.1] ライフ0が反映されない問題を修正（再）

---

js/danoni_main.js

- buttomWordSet -> bottomWordSet に変更

[lyrics-reverse-pos:0.2.1] スペルミスを修正

---

js/danoni_main.js

[ver11.1.2] 譜面ヘッダーのスペルミスを修正

---

js/danoni_main.js

- キーブロックする処理を修正しました。
- Firefoxでセミコロンが反応しない問題を修正しました。
- 重複記述している箇所を整理するため。
- `evt.which` と `event.keyCode`を統一した関係の修正です。
- #580 のコード修正に関連した修正です。

[0137-keyblock] キーブロックする処理の見直し

---

js/danoni_main.js

- Pull Request #581, #582, #583 を参照。
- Pull Request #581, #582, #583 を参照。

[ver11.2.0] キーブロックする処理の見直し　他

---

js/danoni_main.js

[0139-code-refactoring] メイン画面初期化のコード整理

---

js/danoni_main.js

- loadCustomjs関数のコードを整理しました。
引数をtrue/falseから、後続処理に変更しています。
- 今後、異なるルートでこの関数が呼び出される可能性があるため。

[0146/customjs-refactoring] loadCustomjsのコード整理

---

js/danoni_main.js

- Pull Request #595 を参照。
- Pull Request #595 を参照。

[ver11.3.1] 最大密度に色が付かない問題を修正

---

js/danoni_main.js

- Pull Request #597 を参照。
- Pull Request #597 を参照。

[ver11.4.0] 譜面明細画面に補足情報を追加

---

js/danoni_main.js
js/lib/danoni_constants.js

- レベル計算ツール表示部分のデザインを修正しました。
- 他画面との整合のため。

[0154/include-dif-tools] レベル計算ツールのデザイン修正

---

js/danoni_main.js

[ver12.0.2] 矢印グラデーションを利用時、KeyConfig関連の不具合を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

[ver12.1.0] 矢印描画サイズを可変にする設定を追加

---

SECURITY.md
js/danoni_main.js

[ver12.1.1] スコア上書き時ハイスコア差分が計算されない問題を修正

---

SECURITY.md
js/danoni_main.js

[ver12.1.2] titlegrdが1行分だけ指定されているとき曲名の2行目が表示されない問題の修正

---

js/danoni_main.js

1. 背景・マスクモーション部分のコードを整理しました。
1. コードの重複解消のため。

[0160/code-refactoring] 背景・マスクモーション部分のコード整理

---

SECURITY.md
js/danoni_main.js

[ver12.2.1] ダミー矢印のヒット位置が前の通常矢印に引きずられる問題を修正

---

SECURITY.md
js/danoni_main.js

- Pull Request #626, #633, #634 を参照。

[ver13.0.0] 矢印・フリーズアロー(塗りつぶし部分)の初期色設定実装　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

[ver13.1.1] フリーズアロー色（ヒット時）のデータ補完処理を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

[ver13.2.0] Hidden+, Sudden+の実装

---

SECURITY.md
js/danoni_main.js

[ver13.3.1] キーコンフィグ画面でdeleteキーが使用できない問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #649, #650 を参照。

[ver13.4.0] Hid&Sud+の実装、Display:Judgmentを種別ごとに分離

---

js/danoni_setting.js

- Pull Request #649, #650, #652 を参照。

[ver13.4.0] Hid&Sud+の実装、Display:Judgmentを種別ごとに分離（再）

---

js/danoni_main.js

1. 厳密等価演算子が未使用の箇所を見直しました。
1. 厳密等価演算子が使われていないことにより、意図しない処理が発生することを防止するため。
1. 過去バージョンにも影響する可能性があります。

[0184/equal-fix] 厳密等価演算子が未使用の箇所を見直し

---

SECURITY.md
js/danoni_main.js
js/danoni_setting.js
js/lib/danoni_constants.js
skin/danoni_skin_default.css
skin/danoni_skin_light.css
skin/danoni_skin_skyblue.css

- Pull Request #654, #655, #656 を参照。

[ver13.5.0] Opacity設定、Display:FilterLine実装 他

---

SECURITY.md
js/danoni_main.js

[ver13.5.1] Opacity仕様を一部変更

---

js/danoni_main.js

[ver13.6.0] start/fade/endFrameの疑似タイマー対応

---

js/danoni_main.js

- botton -> button への修正。
- コード統一のため。
- カスタムファイルへの影響は無いため、次回バージョンにて反映します。

[0191/refactoring-spell] 変数名のスペルミスの修正

---

css/danoni_main.css
js/danoni_main.js
js/lib/danoni_constants.js

Reverts cwtickle/danoniplus #677
-> #677 の変更で直らなかったため、一旦コミットを戻します。

Revert "[0198/filter-line] Appearance設定で矢印が画面上に残る事象を修正"

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
js/lib/danoni_constants.js

- 先の修正では問題解決しなかったため、一旦すべて戻します。

[ver14.1.x] ver14.1.0に状態を戻す

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #681, #682 を参照。

[ver14.2.0] 高速(5x以上)で矢印を見逃したとき、画面上に矢印が残ることがある事象を修正 他

---

js/danoni_main.js

コード整理（内容は随時更新）
変更例：
```javascript
// Before
const frzBar = document.querySelector(`#${_name}Bar${_j}_${_k}`);
const frzRoot = document.querySelector(`#${_name}${_j}_${_k}`);
const frzBtm = document.querySelector(`#${_name}Btm${_j}_${_k}`);
const frzBtmShadow = document.querySelector(`#${_name}BtmShadow${_j}_${_k}`);
// After
const frzNo = `${_j}_${_arrowCnt}`;
const frzBar = document.querySelector(`#${_name}Bar${frzNo}`);
const frzRoot = document.querySelector(`#${_name}${frzNo}`);
const frzBtm = document.querySelector(`#${_name}Btm${frzNo}`);
const frzBtmShadow = document.querySelector(`#${_name}BtmShadow${frzNo}`);
```
- display:none, visibility:hiddenで置き換えても影響が無い箇所はそのように直します。
変更例：
```javascript
// Before
document.querySelector(`#frzTop${_j}_${_k}`).style.opacity = 0; …
```

[0201/code-refactoring] コード整理

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #684, #685, #686 を参照。

[ver14.3.0] Fast/Slowカウンタ追加、透明度設定の一部見直し　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #688 を参照。
Pull Request #684, #685, #686 も参照してください。（v14.3.0分）

[ver14.3.1] パイプ、アンパサンド等の特殊文字の置き換え

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

[ver14.3.2] カンマ文字のエスケープ対応

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #692, #693 を参照。

[ver14.3.3]  Fast/Slowカウントの誤りを修正　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

[ver14.3.4] countFastSlowの引数忘れを修正

---

SECURITY.md
js/danoni_main.js

- Pull Request #696 を参照（ Issue #697 )

[ver14.4.0] 特殊文字のエスケープ対応

---

SECURITY.md
js/danoni_main.js

[ver14.5.1] エスケープ処理関連の修正、特殊文字対象追加

---

js/danoni_main.js

1. 右下にバージョン比較用リンクを作成しました。
1. 現在のバージョンとの差異をわかるようにするため。

[0219/version-comparison] バージョン比較用リンクを作成

---

SECURITY.md
js/danoni_main.js

[ver14.5.2] バージョン比較用リンクを作成

---

js/danoni_main.js

1. 色変化関係のコードを見直しました。
1. ネストが深い処理の整理のため。

[0220/code-refactoring] 色変化関係のコード見直し

---

js/danoni_main.js

1. back/mask_dataにおいてleft/topについても数式対応しました。
1. Pull Request #718 と同様の理由です。

[0224/animation-frame-calc2] back/mask_dataのleft/topの数式対応

---

SECURITY.md
js/danoni_main.js

[ver15.1.2] 特殊キーの後に通常キーの譜面があると譜面選択できない問題を修正

---

SECURITY.md
js/danoni_main.js

[ver15.1.3] フリーズアローヒット時の矢印色が変化しない問題を修正

---

SECURITY.md
js/danoni_main.js

[ver15.2.1] キーコンフィグ保存時の問題を修正

---

README.md
js/danoni_main.js

- CONTRIBUTING.mdへのリンクが切れていたのでfixします
- リポジトリ内をCONTRIBUTINGで検索して引っかかった限りでURLを直しました。
- issueしたりPR出したりしてみようとCONTRIBUTING.mdを探したときに気づきました。

fix CONTRIBUTING.md url

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
SECURITY.md
js/danoni_main.js

- Pull Request #750, #751, #752 を参照。
- 直接的な変更には関係しませんが、Issue Template, Pull Request Templateを見直しています。
少しだけわかりやすく（？）なりました。

[ver15.3.0] Reverse時に歌詞を上下逆の位置に表示するよう変更（条件あり）他

---

SECURITY.md
js/danoni_main.js
js/danoni_setting.js

- Pull Request #755 を参照。
- danoni_setting.js のテンプレートを更新しています。

[ver15.4.0] Reverse時の歌詞の自動反転制御設定を追加

---

js/danoni_main.js

- 外部リンク時、rel="noopener"を追加するよう変更しました。
- Resolves #781 
- 特にありません。

[0248/link-noopener] 外部リンクにrel属性を追加

---

js/danoni_main.js
js/lib/danoni_constants.js

- タイトル画面にオンマウス説明を追加しました。
- Resolves #765 
- 過去バージョンへの反映予定は未定です。

[0250/add-description] タイトル画面にオンマウス説明を追加

---

README.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #777, #780, #782, #784 を参照。
- バージョンとは関係ないですが、readmeの記述を一部変更しています。

[ver15.7.0] Win+Shiftキーでキーコンが反応しないようにする変更　他

---

js/danoni_main.js

- ライフ初期値について、小数第2位まで使用できるように変更しました。
- Resolves #787 
-

[0251/lifeinit-decimal] ライフ初期値の小数対応

---

js/danoni_main.js

- ゲームエリア（横幅）を設定できる機能を追加しました。
```
|playingX=30|        // プレイ画面のX軸
|playingWidth=600|   // プレイ画面の横幅
```
- Resolves #789 
-

[0252/playing-width] ゲームエリアのX軸調整機能の実装

---

js/danoni_main.js

- Shift+Deleteキーの組み合わせが利かない問題を修正しました。
- Resolves #792 
- v16のみ発生する問題です。

[0253/shift-delete] Shift+Deleteキーの組み合わせが利かない問題を修正

---

SECURITY.md
js/danoni_main.js

[ver16.0.1] Shift+Deleteキーの組み合わせが利かない問題を修正

---

js/danoni_main.js

- 結果画面のキーコード置換漏れを修正しました。
- 他の処理との整合が合わないため、揃えます。
- v16のみ。ただし、大きな影響は無し。

[0259/fix-keydown] 結果画面のキーコード置換漏れを修正

---

SECURITY.md
js/danoni_main.js

- Pull Request #818, #820 を参照。

[ver16.3.0] Ready表示に関する拡張機能を実装

---

js/danoni_main.js
js/lib/danoni_constants.js

- 結果画面部分のコードを整理しました。
- 繰り返しコード解消のため。

[0265/code-refactoring] 結果画面部分のコード整理

---

js/danoni_main.js
js/lib/danoni_constants.js

- パーフェクト演出系のコードを整理しました。
- 同種の記述が複数に散らばっているため。
- 特になし

[0288/result-constants] パーフェクト演出系のコード整理

---

js/danoni_main.js
js/lib/danoni_constants.js

- 総矢印数をグローバル変数で管理するよう変更しました。
- 総矢印数を参照している箇所が複数存在するため。
- 特になし

[0289/full-arrows] 総矢印数をグローバル変数で管理するよう変更

---

README.md
SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #825, #826, #827, #828, #829, #830 を参照。
- readme.mdの変更があります。

[ver16.4.0] リザルト表示に対する遅延フレーム設定を実装　他

---

js/danoni_main.js

- ラベル作成部の関数`createDivLabel`, ボタン作成関数`createCssButton`, 色付きオブジェクト作成関数`createColorObject`を作り直しました。従来の関数は残しています。
- `setColorList`, `makeColorGradation`関数についても引数初期値を設定します。
- `getTitleDivLabel`関数を拡張し、CSSクラスを付加できるようにしました。
- preload関連のコードを整理しました。
- 座標、サイズ、フォントなどを設定したラベル用div要素を作成します。
- 従来の属性値に加え、CSSに対応した属性名に対応する設定が行えます。
|引数|型|必須|指定内容|
|_id|string|*|ラベルのID名|
|_text|string|*|表示する文字列|
|_obj|object||`x`:  X座標(0), `y`:  Y座標(0), `w`: 幅(210), `h`: 高さ(23),<br>`siz`: フォントサイズ(17), `align`: 文字位置(中央寄せ), <br>`(属性名)`: (属性に対する設定)|
|_classes|...any||CSSクラス名　※複数指定可|
```javascript
createDivCss2Label(`lblComment`, tmpComment, {
x: 0, y: 70, w: g_sWidth, h: g_sHeight - 180, siz: C_SIZ_DIFSELECTOR, align: C_ALIGN_LEFT,
overflow: `auto`, background: `#222222`, color: `#cccccc`, display: …
```

[0271/code-label] ラベル・ボタン作成部の関数を置き換え

---

js/danoni_main.js

- 譜面データが無い時に画面が止まる事象を修正しました。
- 譜面データが未定義の場合に、変数の一部がundefinedとなり処理が止まっていたため。
- 特になし

[0272/preset-undefined] 譜面データが無い時に画面が止まる事象を修正

---

js/danoni_main.js

- 矢印・フリーズアローフレーム処理部分を統一しました。
- 処理のほとんどが同じ処理であり、メイン処理にほぼ影響を与えないため。
- 特になし

[0273/code-refactoring] 矢印・フリーズアローフレーム処理部分を統一

---

SECURITY.md
js/danoni_main.js

- Pull Request #832, #834, #835, #837 を参照。
- 不具合修正の #832 については従来バージョンv16に反映します。

[ver17.0.0] ラベル作成・ボタン作成関数を見直し　他

---

js/danoni_main.js

- 一部矢印が無い場合のロード処理誤りを修正しました。
- 一部矢印が無い場合にロード画面で止まるため。
- 特になし

[0274/calc-notes] 一部矢印が無い場合のロード処理誤りを修正

---

SECURITY.md
js/danoni_main.js

- Pull Request #839 を参照 ( #838 も参照してください )
- xxxx (懸念事項などがあれば記述 / Add any other context about the pull request here.)

[ver17.0.1] 一部矢印が無い場合のロード処理誤りを修正

---

SECURITY.md
js/danoni_main.js

- Pull Request #841, #842 を参照。

[ver17.1.0] ボタン処理の割り込み制御の実装　他

---

js/danoni_main.js

[0277/code-refactoring] コード整理

---

js/danoni_main.js

- innerHTML, innerTextのプロパティを指定している箇所のうち、
HTML指定不要な箇所についてtextContentに変更しました。
https://developer.mozilla.org/ja/docs/Web/API/Node/textContent
- HTMLとして解析する必要の無いコードの見直しによる、レスポンスの改善のため。
- 特になし

[0279/text-contents] innerHTML, innerText -> textContentに一部置き換え

---

js/danoni_main.js

- 0未満の値の初期化処理を`roundZero`関数に集約しました。
- 重複コードの解消のため。
- 特になし

[0280/code-refactoring] 0未満の値の初期化処理を集約

---

.github/workflows/codeql-analysis.yml
SECURITY.md
js/danoni_main.js

- Pull Request #844, #846, #847, #848 を参照。
- 主にコード集約とそれに付随した変更が主となります。
コード変更量が一定あるため、バグフィックス扱いにはしません。
- 特になし

[ver17.2.0] コード整理、クエリ取得方法見直し、url未指定時の初期値変更

---

js/danoni_main.js

- レベル計算部分のコード整理を行いました。
- コード重複の解消のため。
- 特になし

[0283/code-refactoring] レベル計算部分のコード整理

---

js/danoni_main.js

- 階層スプライト作成部分、ゲージ設定部分のコード集約を行いました。
- 重複コードの解消のため。
- 特になし

[0284-code-refactoring] 階層スプライト作成部分、ゲージ設定部分のコード集約

---

SECURITY.md
js/danoni_main.js

- Pull Request #850, #851, #852, #853 を参照。
- 特になし

[ver17.3.0] titlefont, titlepos拡張、コード整理

---

js/danoni_main.js

- strictモード有効化に伴い初期化されていない変数を見直しました。
- strictモード有効化で一部機能が動かなくなるため。 ( Reference #855 )
- strictモードを過去バージョンに強いるのはさすがに厳しいので、
過去バージョンの修正は初期化不備の見直しに留めることにします。

[0285/strict-code] strictモード有効化に伴い初期化されていない変数を見直し

---

SECURITY.md
js/danoni_custom.js
js/danoni_custom2.js
js/danoni_main.js
js/danoni_setting.js
js/lib/danoni_constants.js
js/lib/danoni_legacy_function.js
js/lib/danoni_localbinary.js
skin/danoni_skin_background.js
skin/danoni_skin_blank.js
skin/danoni_skin_default.js
skin/danoni_skin_light.js
skin/danoni_skin_skyblue.js

- Pull Request #855, #856, #857, #858 を参照。
- 特になし

[ver17.4.0] strictモードを有効化　他

---

js/danoni_main.js

- 結果画面のショボーンのラベルID誤りを修正しました。
- 動作影響は無いのですが、結果画面をカスタムした場合に
ショボーンのラベルのみ位置ズレが起こる可能性があります。
- 動作影響は無いため、次回バージョンにて反映とします。
過去バージョン影響はありません。
- この問題の混入はver17.2.0です。PR #844 が該当します。

[0288-result-shobon-label] 結果画面のショボーンのラベルID誤りを修正

---

js/danoni_main.js

- 最後の矢印を取り忘れてクリアするとundefinedになる問題を修正しました。
- 上述の通りです。
- 特になし。v17のみ発生します。

[0290/cleared-view] 最後の矢印を取り忘れてクリアするとundefinedになる問題を修正

---

js/danoni_main.js
js/lib/danoni_constants.js

- コード整理の一環で、利用頻度の低い変数を整理しました。
- コードの見やすさのため。
- 特になし

[0289/code-refactoring] 利用頻度の低い変数を整理

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #860, #861, #862 を参照。
- 特になし

[ver17.4.1] 最後の矢印を取り忘れてクリアするとundefinedになる問題を修正　他

---

js/danoni_main.js

- danoni_setting.js で定義する `g_presetOverrideExtension`が有効で、
かつサーバーにアップした場合に使用する変数が未定義でした。
- strictモードを有効にしたことによる影響です。

[0291/undefined-variables] 未定義変数を修正

---

SECURITY.md
js/danoni_main.js

- Pull Request #864 を参照。
- #863 も参照してください。

[ver17.4.2] strictモード有効に伴い未定義の変数を修正

---

js/danoni_main.js

- DataSaveをOFFにしたとき、Reverseを変更して設定画面に戻ると
styleが反映されない問題を修正しました。
- 上述の通りです。
- 影響範囲はv17のみ。過去バージョンの影響はありません。

[0293/reverse-style] DataSaveをOFFにしたとき、Reverseのstyleが反映されない問題を修正

---

js/danoni_main.js

- Reverseボタン周りのコードを整理しました。
- 上述の通りです。
- 特になし

[0294/reverse-code] Reverseボタン周りのコード整理

---

SECURITY.md
js/danoni_main.js

- Pull Request #866, #867 を参照。
- 特になし

[ver17.4.3] 矢印塗りつぶし有、ステップゾーンをOFFにした場合の表示問題を修正 他

---

js/danoni_main.js

1. 長い名前の関数を全体的に見直しました。
2. Node.appendChild()を多々利用している部分について、ParentNode.append()に置き換えました。
1. コードの見やすさの一環です。
2. コードの簡便さのため。なお、後でNode.appendChild()へ戻せるように、multiAppend自体は残しています。
- 特になし

[0296/replace-function] 長い名前の関数を全体的に見直し

---

js/danoni_main.js

- 二重定義していた箇所を見直しました。
- コード整理の一環です。
- 特になし

[0297/code-refactoring] コード整理

---

SECURITY.md
js/danoni_main.js

- Pull Request #871, #872, #873 を参照。
- 特になし

[ver17.5.0] ボタン作成処理に右クリック処理、イベント引数を追加　他

---

js/lib/danoni_constants.js

- カンマのエスケープ間違いを修正しました。
- v17.5.0でコード移行中の誤りです。
- 特になし

[0299/escape-comma] カンマのエスケープ間違いを修正

---

js/danoni_main.js
js/lib/danoni_constants.js

1. 判定、ランク部分のコードを見直しました。
2. 矢印・フリーズアロー初期色の情報をconstantsへ移動しました。
1. 冗長なコードの見直しのため。
2. コードというよりは設定値のため。
- 一部eval関数を使用しているため、可能であれば見直す予定です。

[0298/judge-code] 判定、ランク部分のコード見直し

---

js/danoni_main.js

1. 矢印・フリーズアロー個別属性の設定方法を変更しました。
従来、`setAttribute()`や`getAttribute()`を使っていた箇所をオブジェクトに変更しています。
詳細はIssueをご覧ください。
2. 判定処理で`eval()`を使用している箇所を見直しました。
3. 歌詞表示関連のコードを整理しました。
4. 変数の存在チェック用関数：`hasVal`を追加しました。
5. 新キー設定箇所において詳細スクロール・アシスト設定の初期設定を集約しました。
1. Resolves #878 
2. コード記述をわかりやすくするため。
3. 冗長なコードの見直しのため。
4. `undefined`及び空チェックを行っている箇所が多々存在していたため。
5. 類似コード解消のため。
- フリーズアローヒット時の座標ズレが起きています。解消方法が見つかるまではマージしません。
⇒　解決しました。

[0300/arrow-attr] 矢印・フリーズアローの属性設定方法を変更　他

---

SECURITY.md
js/danoni_main.js

- Pull Request #882 を参照。
- 特になし

[ver18.0.1] 複数曲搭載時に曲名の2段目がundefinedになる問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #884, #885 を参照。
- 特になし

[ver18.1.0] Display設定周りのローカルストレージ対応 他

---

js/danoni_main.js

- ColorTypeをローカルストレージ対象に追加しました。
- Gitter要望より。
- 特になし

[0307/color-type-storage] ColorTypeをローカルストレージ対象に追加

---

js/danoni_main.js

1. Display:Colorのボタンが無効化されていた場合に
ColorTypeの挙動により、Display:Colorの切り替えができてしまう問題を修正しました。
2. ColorType初期値に「*」を付与するように変更しました。
3. Display設定の初期値適用処理で、二重処理が入っていた箇所を解消しました。
1. ColorTypeは「Type1」「Type2」のときにDisplay:Colorを強制OFFにします。
この設定がDisplay:Colorのボタン無効化時も有効になっていました。
2. 他の設定仕様と統一を図るため。
3. 冗長処理解消のため。
- 1は過去バージョンでも発生しうる現象。ただし、発生頻度は限定的。

[0308/display-init] Display:Colorのボタン無効化時のColorTypeの挙動修正　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #891, #892, #893 
- 特になし

[ver18.3.0] 背景・マスクのsvgファイル対応、ColorTypeのローカル保存実装　他

---

SECURITY.md

- Pull Request #895, #896 
- Security.mdの更新です。

[ver18.4.0] 背景・マスクモーションにおいてタグを許容するよう変更 (Security.md更新)

---

SECURITY.md
js/danoni_main.js

- Pull Request #908, #910
- #908 については過去バージョンにも影響するため同様の修正を行っています。

[ver18.6.0] ライフ制ゲージ設定にHeavyを追加　他

---

SECURITY.md

- Pull Request #908, #910
- Security.mdの更新忘れによるPRです。

[ver18.6.0] ライフ制ゲージ設定にHeavyを追加　他 (security.md更新)

---

SECURITY.md
js/danoni_main.js

[ver18.6.1] 追加した画像ファイルがある場合、Firefoxでプレイできない問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #915, #916, #917

[ver18.7.0] ColorType: 2のおにぎりの初期色変更　他

---

README.md
SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

[ver18.8.0] Gitter、ゲーム画面説明へのリンクを追加

---

README.md
SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

[ver18.8.1] 画像拡張子指定時に画像読込チェックに失敗する問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

[ver18.8.2] 一部のキーを押すと全押し状態になる問題を修正

---

SECURITY.md
js/danoni_main.js

[ver18.9.0] タイトルアニメーションの設定を拡張（クラス設定他）

---

js/danoni_main.js

- PR #929 の再修正です。
- PR #929 のコメントを参照してください。
- 特になし

[0325/judge-arrow-frz] PR #929 の再修正

---

SECURITY.md
js/danoni_main.js

- PR #929, #930 
- 過去バージョンの修正対象ですが、修正方法がv17以前とv18では異なるため先に
v18のみ反映します。

[ver18.9.1] 同一レーン上に通常矢印とフリーズアローが短い間隔で存在するときの問題を修正

---

SECURITY.md
js/danoni_main.js

[ver19.2.0] タイトルの背景矢印の透明度設定を有効化　他

---

.github/RELEASE_TEMPLATE.md

- リリース用テンプレートを追加しました。
- リリースに記述する必要のある事項が増えてきているため。

[0329/release-template] リリース用テンプレートの追加

---

.github/RELEASE_TEMPLATE.md

- リリース用テンプレートの更新。
Files changedからAssetsへの直接リンクを貼りました。
- 1画面でダウンロードできるようにするため。

[0339/release-template] リリース用テンプレートの更新

---

.github/RELEASE_TEMPLATE.md

- リリース用テンプレートの更新。
ファイル比較リンクを見直し、danoni_setting.jsについては比較がわかるように変更しました。
- ファイルごとの変化点がわかりにくいため。
特にdanoni_setting.jsはそのまま入れ替えすることが少ないため、比較リンクが必要。

[0340/release-template] リリース用テンプレートの更新

---

js/danoni_main.js

- changeStyleのコードミスを修正しました。
- 優先度低ですが、過去バージョンにも同様の修正が必要です。

[0344/filter] changeStyleのコードミスを修正

---

.github/RELEASE_TEMPLATE.md

- RELEASE_TEMPLATE.mdにおけるダウンロードパス誤りを修正しました。
- 上述の通り。
- 間違いが多いため、一通り落ち着いてからマージする予定です。

[0342/release-template] ダウンロードパス誤りを修正 (RELEASE_TEMPLATE.md)

---

js/danoni_main.js
js/lib/danoni_constants.js

1. 画像のルートパス部分の処理をメインへ移動しました。
1. PR #955 関連。ルートパス指定がdanoni_constants.js直指定でしたが、それを拡張子設定と同じように
メイン側で処理するように変更しています。

[0345/root-path-common] 画像のルートパス部分の処理をメインへ移動

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #964, #965, #966

[ver19.5.0] 画面別ショートカットキーの実装　他

---

js/danoni_main.js
js/lib/danoni_constants.js

1. ショートカット表示部分などで使用している共通文字を定数化・変数化しました。
2. 変数を組み合わせて結合している箇所を見直しました。
1. 変数化して`danoni_constants.js`に記載しているため上書き定義しやすくなります。
2. コードの見やすさ、使いまわしのしやすさの向上のため。

[0351/sc-constants] ショートカット系の共通文字を集約

---

js/danoni_main.js

1. 判定周りのコードを整理しました。
1. コードの見やすさ改善のため。

[0352/code-refactoring] 判定周りのコード整理

---

js/danoni_main.js
js/lib/danoni_constants.js
js/lib/danoni_legacy_function.js

1. 判定キャラクタを管理する変数 `C_JCR_II`, `C_JCR_SHAKIN`, ... を廃止し、`g_lblNamesObj` へ集約しました。
|旧変数|新変数|
|----|----|
|C_JCR_II|g_lblNamesObj.ii|
|C_JCR_SHAKIN|g_lblNamesObj.shakin|
|C_JCR_MATARI|g_lblNamesObj.matari|
|C_JCR_SHOBON|g_lblNamesObj.shobon|
|C_JCR_UWAN|g_lblNamesObj.uwan|
|C_JCR_KITA|g_lblNamesObj.kita|
|C_JCR_IKNAI|g_lblNamesObj.iknai|
2. 各種設定を管理する変数群 `g_speeds`, `g_motions`, `g_scrolls`, ... を廃止し、`g_settings`へ集約しました。
|旧変数|新変数|
|----|----|
|g_speeds|g_settings.speeds|
|g_speedNum|g_settings.speedNum|
|g_motions|g_settings.motions|
|g_motionNum|g_settings.motionNum|
|g_scrolls|g_settings.scrolls|
|g_scrollNum|g_settings.scrollNum|
|g_reverses|g_settings.reverses|
|g_reverseNum|g_settings.reverseNum|
|g_shuffles|g_settings.shuffles|
|g_shuffleNum|g_settings.shuffleNum| …

[0354/move-old-function] 古い関数・変数の整理、単独変数のオブジェクト集約

---

js/danoni_main.js

1. 細かい部分のコード整理を行いました。
1. コードの見やすさのため。

[0356/code-refactoring] コード整理

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #973, #974, #975

[ver20.1.0] フォントサイズの自動取得方法を変更　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #977 
- ver20.1.0 のPR #973, #974, #975 の変更を含みます。

[ver20.1.1] 設定画面内の譜面名のMakerViewのフォントサイズ変更に対応

---

js/danoni_main.js

1. 設定画面内の譜面名のMakerViewのフォントサイズ変更のコードを修正しました。
1. CodeQLの指摘への対応です。
- xxxx (懸念事項などがあれば記述 / Add any other context about the pull request here.)

[0359/dif-dfsize] 設定画面内の譜面名のMakerViewのフォントサイズ変更のコード修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- Pull Request #979 
- PR #978 も参照してください。

[ver20.1.2] 設定画面内の譜面名のMakerViewのフォントサイズ変更に対応

---

js/danoni_main.js
js/lib/danoni_constants.js

1. PR #981, #983 の変更をver19のサポートブランチへマージします。
1. 不具合修正のため。

[ver17.5.4] #981, #983 の差分コミット

---

js/danoni_main.js

- #988 imgタグ生成時においてcrossOrigin属性を付与するよう変更

[ver14.5.18] imgタグ生成時においてcrossOrigin属性を付与するよう変更

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- #986 KeyConfig画面のTo Settingsボタンにg_lblNameObjが適用されていない問題を修正
- #987 ショートカット表示部分のフォーマットを拡張
- #988 imgタグ生成時においてcrossOrigin属性を付与するよう変更
- #989 preloadFile関数においてas:image以外が来た時の問題を修正

[ver20.2.1] imgタグ、preloadの設定、ショートカット表示に関する修正・見直し

---

js/danoni_main.js

1. カラーコードの前パディング処理を集約しました。
1. CodeClimateにて以前より警告が出ていたため。

[0370/color-padding] カラーコードの前パディング処理を集約

---

js/lib/danoni_constants.js

1. g_hidSudObjの定義方法を変更し、まとめて定義するようにしました。
1. コード整理の一環です。
- danoni_constants.jsのみの変更です。

[0377/hidsud-obj] g_hidSudObjの定義方法変更

---

.github/RELEASE_TEMPLATE.md

1. RELEASE_TEMPLATE.mdを現バージョンに合わせて更新しました。
- Files changed を先頭に移動しました。
- 最新版(もしくはブランチ最新)からのコミット数表示に対応しました。
1. 次回以降リリースする際の作業の簡略化のため。

[0375/release-template] RELEASE_TEMPLATE.mdの更新

---

.gitattributes
SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- #1005 RELEASE_TEMPLATE.mdの更新
- #1006 キーコンフィグ画面内のコード整理（eval関数の排除）
- #1007 g_hidSudObjのコード整理
- #1008 グラデーション周りのコード見直し
- #1009 Baseエンコードした曲データを直接デコードするよう変更

[ver20.5.0] コード整理、Base64エンコードした曲データを直接デコードするよう変更

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- #1005 RELEASE_TEMPLATE.mdの更新
- #1006 キーコンフィグ画面内のコード整理（eval関数の排除）
- #1007 g_hidSudObjのコード整理
- #1008 グラデーション周りのコード見直し
- #1009 Baseエンコードした曲データを直接デコードするよう変更
- #1011 グラデーション変数の初期化漏れを修正

[ver20.5.1] コード整理、Base64エンコードした曲データを直接デコードするよう変更

---

SECURITY.md
js/danoni_main.js

- #1014 グラデーションにdeg/radなどが入っているときに文字が表示されない問題を修正

[ver20.5.2] グラデーションにdeg/radなどが入っているときに文字が表示されない問題を修正

---

js/danoni_main.js

1. レベル計算ツール周りのコード整理を行いました。
makeDifInfoLabel関数について、他の関数と同様にappendするdiv子要素を返却するようにしました。
2. 関数名を変更しました。関数の中身は変更ありません。
(makeScoreDetailLabel -> updateScoreDetailLabel)
1. 類似の処理がバラバラに記述されていたため。
2. 他のmakeXXX系と役割が異なるため。

[0382/cr-difinfo] レベル計算ツール周りのコード整理

---

js/danoni_main.js
js/lib/danoni_legacy_function.js

1. 以下の関数をdanoni_legacy_function.jsへ移動しました。
- checkArrayVal, getStrLength, paddingLeft, createDivCustomLabel
1. v21以降で使用する見込みのない関数のため。

[0383/legacy-func] 非推奨関数をlegacy_functionへ移動

---

js/danoni_main.js

1. 矢印・フリーズアローモーションについて、20以上のキーに対応しました。
1. #812 の派生対応です。

[0386/ex-motion] 矢印・フリーズアローモーションの20以上のキー対応

---

js/danoni_main.js

1. 改行コード区切りの配列展開処理を集約しました。
1. Code Climateからの指摘より。

[0387/cr-splitLF] 改行コード区切りの配列展開処理を集約

---

js/danoni_main.js

1. 文字列関連のコード整理を行いました。
1. Code Climateからの指摘より。

[0390/str-join] 文字列関連のコード整理

---

js/sample/danoni_custom-003.js

1. danoni3.htmlで使用しているカスタムjs (sample/danoni_custom-003.js) を現在の関数に置き換えました。
1. v0～v1のときの非推奨関数が多く、エラーが出ていたため。

[0395/sample-update] danoni3.html のカスタムjsを更新

---

js/danoni_main.js

1. 多次元配列コピー処理を関数化しました。
1. 類似の処理が多々発生しており、何を実行しているかが明確でなかったため。
また、将来的に関数を置き換える場合にもまとめて変更できるメリットがあるため変更しました。

[0403/copy-array2d] 多次元配列コピー処理を関数化

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
js/lib/danoni_constants.js
skin/danoni_skin_default.css
skin/danoni_skin_light.css
skin/danoni_skin_skyblue.css

- #1040 キーコンフィグの対応キー箇所をボタン化
- #1041 キー数周りのコード整理
- #1042 特殊キーのキーコンフィグが初期化できない問題を修正 ( #1041 に対する修正 )
- #1043 多次元配列コピー処理の関数化
- #1044 空の矢印データを含む譜面にS-Randomをかけるとフルコン演出が早まることがある問題を修正
- #1045 矢印数サマリ処理に関するコード修正
- #1046 警告ウィンドウに対するデザイン、コード修正
- 変更ファイルが多いため、リリース時の注意書きに留意すること。

[ver21.4.0] キーコンフィグの対応キー箇所をボタン化　他

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
js/lib/danoni_constants.js
skin/danoni_skin_default.css
skin/danoni_skin_light.css
skin/danoni_skin_skyblue.css

- #1048 明背景時、キーコンフィグ画面の文字が薄い問題を修正
- そのほかの変更については #1047 を参照してください。

[ver21.4.1] キーコンフィグの対応キー箇所をボタン化　他（再）

---

js/danoni_main.js

1. ローカルストレージの初期値設定に関するコードを見直しました。
1. CodeClimateによる指摘のため。

[0409/cr-local] ローカルストレージの初期値設定に関するコード見直し

---

js/danoni_main.js

1. 共通部分のコード整理を行いました。
1. コード重複排除による見やすさのため。
- xxxx (懸念事項などがあれば記述 / Add any other context about the pull request here.)

[0415/cr-common] 共通部分のコード整理

---

js/danoni_main.js
js/lib/danoni_legacy_function.js

1. 非推奨関数 (createSprite) をdanoni_legacy_function.jsへ移動しました。
1. danoni_main.jsで使用しない関数のため。

[0416/legacy-func] 非推奨関数をlegacy_functionへ移動

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
js/lib/danoni_legacy_function.js

- #1059 シャッフルグループの複数化対応（通常キー）
- #1060 一時的に初期矢印色の割当先を変更できる機能を実装
- #1061 共通部分のコード整理
- #1062 非推奨関数をlegacy_functionへ移動

[ver22.0.0] シャッフルグループの複数化（通常キー）、通常矢印色の一時割り当て変更　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- #1064 シャッフルグループが複数の場合、「Random+」「S-Random+」の表記を統一
- #1066 Shuffle設定でシャッフルグループ内の入れ替えのみ可能な設定を追加 ( Issue #1065 )
- #1067 非対称ミラーの実装
- Add: getShuffleName

[ver22.1.0] シャッフル設定の部分適用設定、非対称ミラーの実装　他

---

js/danoni_main.js

1. カーソル処理を`nextPos`関数に集約しました。
```javascript
/**
* 次のカーソルへ移動
* @param {number} _basePos 現在の位置
* @param {number} _num スクロール数
* @param {number} _length ループ周期
* @returns 
*/
const nextPos = (_basePos, _num, _length) => (_basePos + _length + _num) % _length;
```
1. 同じような処理を繰り返し使っているため。

[0427/cr-cursor] カーソル処理のコード集約

---

CONTRIBUTORS.md
README.md

1. CONTRIBUTORS.md を追加しました。
1. 開発者クレジットの場所がReleaseページのみで、分散していたため。
- 名前は昇順（ownerを除く）で表示しています。

[0460/contributors] CONTRIBUTORS.md の追加

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- #1132 を参照（バージョンテキストの上げ忘れを修正）

[ver23.4.0] ランクAPの実装、 プレイ画面に譜面名を追加　他（バージョン名のみ）

---

SECURITY.md
js/danoni_main.js

[ver23.4.1] 矢印データが昇順で無い場合の問題を修正

---

SECURITY.md
js/danoni_main.js

[ver24.0.2] Firefox時、警告ウィンドウの高さが最小化される問題を修正

---

js/danoni_main.js

1. 配列の初期化方法を見直しました。
```javascript
const abc = [];
const def = [];
for (let j = 0; j < len; j++){
abc[j] = 0;
def[j] = [];
}
```
```javascript
const abc = [...Array(len)].fill(0);
const def = [...Array(len)].map(_ => []);
```
2. 影響が少ない部分の条件式を見直しました。
```javascript
let dosCssMotionData;
if (_dosObj[`${_header}Motion${_scoreNo}_data`] !== undefined) {
dosCssMotionData = _dosObj[`${_header}Motion${_scoreNo}_data`];
} else if (_dosObj[`${_header}Motion_data`] !== undefined) {
dosCssMotionData = _dosObj[`${_header}Motion_data`];
}
```
```javascript
const dosCssMotionData = _dosObj[`${_header}Motion${_scoreNo}_data`] || _dosObj[`${_header}Motion_data`];
```
3. makeWarningWindow関数の引数の一部をオブジェクト引数を変更しました。
`_resetFlg`をオブジェクト引数へ移動しています。
```javascript
function makeWarningWindow(_text = ``, { resetFlg = …
```

[0475/cr-initial] 配列などの初期化方法を見直し

---

js/danoni_main.js
js/lib/danoni_constants.js

1. コードの整理を行いました。冗長な条件式や記述を見直しています。
1. コードの見やすさのため。

[0476/cr-common] コードの整理

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- #1151 
- 音楽ファイル指定が無いときに止まる問題を修正
- ローカルファイル起動時のコードを見直し
- 音楽ファイルが無いとき、Backボタンで復帰できるように変更
- musicUrlが未指定で強制スタートした場合、nosound.mp3を見るように変更
- #1152 
- #1153 
- 判定キャラクタ位置（X座標）とコンボ位置の間を少し広げるよう変更
- 英語時の判定名を大文字のみ⇒小文字混じりに変更
- #1154 
- #1155

[ver24.1.0] 判定キャラクタ位置調整、音楽ファイル無し時の挙動見直し　他

---

SECURITY.md
js/danoni_main.js

[ver24.2.0] 歌詞表示、背景・マスクモーションの多言語対応　他

---

danoni/danoni0.html
js/danoni_main.js

1. コメント文について、多言語対応できるようにしました。
ロケール設定に合わせ、commentValJa (日本語), commentValEn (英語) が使えます。
従来の commentVal は共通で、Ja/Enのどちらも指定が無い場合に使用します。
1. コメント文についても多言語化が必要になる場合があるため。

[0480/comment-lang] コメント文の多言語対応

---

SECURITY.md
danoni/danoni0.html
js/danoni_main.js

- #1157 
- #1158 
- #1159 
- #1161

[ver24.2.1] 歌詞表示、背景・マスクモーション、コメント文の多言語対応 他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- #1163 
- スクロール拡張、アシスト設定において名称縛りを廃止
- 特殊キーでスクロール拡張、アシスト設定を行う際に
同じ設定を二重に指定した場合、二重にリスト登録されないように変更
- 9ikey, 17keyに対して部分的にスクロール拡張を追加
- #1164

[ver24.3.0] キーコンフィグパターン個別にスクロール拡張、アシスト設定が行える機能を実装　他

---

js/danoni_main.js

1. 譜面ヘッダー：autoPreloadをデフォルト有効に変更しました。
1. ほとんどの場合で有効にすることが多いため。

[0486/preload-default] autoPreload設定をデフォルト有効に変更

---

js/danoni_main.js

1. #1171 で追加したラベル名を一部見直しました。
- lnklockBtn -> lnkLockBtn
1. 記述の仕方が他と異なっていたため。
- 他のラベル名もキャメル式に沿っていない名前がありますが、
このタイミングでは直しません。

[0488/label-name] ラベル名の修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- #1171 
- Hidden+/Sudden+/Hid&Sud+の初期位置の設定、ロック機能を実装
- createGeneralSetting関数で真ん中のボタンに対してボタン拡張が行えるように変更
- #1172

[ver24.5.0] Hidden+/Sudden+の初期位置・ロック機能の実装

---

js/danoni_main.js

1. PR #1177 に伴って不要となった関数を削除しました。
1. 未使用関数のため。

[0493/sc-group3] コードの見直し（不要関数の整理）

---

SECURITY.md
js/danoni_main.js

- #1174 
- #1175 
- #1176 
- #1177 
- #1178

[ver24.5.1] シャッフルグループ・カラーグループに関する挙動不具合を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- #1189 
- キーコンフィグが隠れる場合に横スクロールできるよう対応
- 設定画面間のページ移動を関数化

[ver25.2.0] キーコンフィグが隠れる場合に横スクロールできるよう対応　他

---

SECURITY.md
js/danoni_main.js

[ver25.3.1] g_scoreObj.baseFrameの設定誤りを修正

---

js/danoni_main.js

1. 0フレーム指定の色変化、モーションデータの指定が可能になりました。
```
|color_data=0,20,#ffffff|
|arrowMotion_data=0,20,toSpin|
```
1. プレイ開始直後から設定を変えたい場合に対応するため。
また、フェードイン時でも矢印到達に間に合わないタイミングのデータが抜け落ちる可能性がありました。

[0504/zeroframe-color] 0フレーム指定の色変化、モーションデータに対応

---

SECURITY.md
js/danoni_main.js

[ver25.3.2] 0フレーム指定の色変化、モーションデータに対応　他

---

SECURITY.md
js/danoni_main.js

[ver25.3.3] skinTypeがDefaultのとき、divBackが作成されない場合がある問題を修正

---

SECURITY.md
js/danoni_main.js

[ver25.4.1] http環境でクリップボードコピーに失敗する問題を修正

---

SECURITY.md
js/danoni_main.js

[ver25.5.2] シャッフル・カラーグループを変更した際にその内容が反映されない問題を修正　他

---

SECURITY.md
js/danoni_main.js

[ver26.0.0] ダミーエフェクト（色変化・モーションデータ）の実装

---

CONTRIBUTORS.md
SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js

- #1220 
- #1221 
- #1222 
- #1223 
- #1224

[ver26.1.0] 推定Adjの計算方法変更、密度グラフの表記拡張　他

---

js/danoni_main.js

1. 推定Adjの計算式を修正しました。
1. Gitterでの指摘より。
https://gitter.im/danonicw/community?at=6203b7a1708e9c3dd76da0d5

[0522/estimated-adj] 推定Adjの計算式を修正

---

SECURITY.md
js/danoni_main.js

[ver26.1.1] 推定Adjの計算式を修正

---

js/danoni_main.js

1. メッセージインポート部分のコード整理を行いました。
1. CodeClimateからの指摘より。

[0529/cr-msg-import] メッセージインポート部分のコード整理

---

js/danoni_main.js

1. 譜面ロード部分をasync/await形式に書き換えました。
PR #1236 とは異なり、譜面ロード関数をそのまま外部で使用することは考えにくいため、関数の置き換えを行っています。
|以前の関数名|変更後の関数名|関数概要|
|initControl<br>loadBaseFiles|initControl|初期読込（js, css, 譜面ファイルの読み込みを含む）|
|loadDos<br>reloadDos|loadChartFile<br>getScoreDetailData<br>resetColorAndGauge|譜面ファイルの読み込み<br>譜面読込後処理（譜面明細情報取得、初期色＆ゲージ情報取得）|
1. 譜面読込部分が煩雑で、前後関係がわかりにくいため。
変更後の関数は基本的に非同期関数となり、読み出し時にawaitをつけて呼び出すことを想定しています。
- 譜面ファイル読込部分は途中の割り込み処理は無いため、大きな問題は出ないと考えています。

[0530/loading-chart] 譜面ロード部分をasync/await形式に書き換え

---

SECURITY.md
js/danoni_main.js
package.json

[ver26.4.0] 譜面ファイル読込部分のコード整理　他

---

js/danoni_main.js

1. 音楽再生準備部分の関数の順序を見直しました。プレイ開始の前に配置しています。
1. 実装当初、タイトル画面前に読み込んでいたが、現状は異なるため。
順序が異なることで、コードが追いにくくなることを避けるため。
- 関数順序を変えているだけのため、処理には影響しません。

feat: [0535] 関数の順序を見直し

---

SECURITY.md
js/danoni_main.js
package.json

- #1244 
- #1245 
- #1246 
- #1247

[ver26.5.0] カスタムキー定義のpos項目について小数点に対応　他

---

.github/CONTRIBUTING.md
SECURITY.md
js/danoni_main.js
package.json

[ver26.6.0] functionをアロー関数に置き換え

---

SECURITY.md
js/danoni_main.js
package.json

[ver26.6.1] マターリを出すとキーが利かなくなる問題を修正

---

js/danoni_main.js

1. ローカル時にリザルトコピー内容にURL情報を付加しないよう変更しました。
1. Resolves #1253

feat: [0539] ローカル時にリザルトコピー内容にURL情報を付加しないよう変更

---

CONTRIBUTORS.md
SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver26.7.0] ローカル時にリザルトコピー内容にURL情報を付加しないよう変更 他

---

js/danoni_main.js
js/lib/danoni_legacy_function.js

1. v27以降非推奨の関数をdanoni_legacy_function.jsへ移動しました。
1. 本体ソースでは使用しないため。

refactor: [0543] 非推奨関数をlegacy_function.jsへ移動

---

js/danoni_main.js

1. 共通部分のコードを整理しました。
1. CodeClimateからの指摘より。

refactor: [0544] コードの整理

---

js/danoni_main.js
js/lib/danoni_constants.js

1. 値変換処理、div要素削除処理のコード整理を行いました。
2. 固定ウィンドウサイズの設定を danoni_constants.js へ移動しました。
1. コード簡略化のため。
2. 具体的な数値での設定は danoni_constants.js に記載した方が望ましいため。

refactor: [0546] 値変換処理のコード整理

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
js/lib/danoni_legacy_function.js
package.json

- #1256 
- #1258 
- #1259 
- #1260 
- #1261 
- #1262 
- #1263

[ver27.0.0] プレイ画面からリザルト画面移行時の100ミリ秒を廃止　他

---

js/danoni_main.js

1. setVal関数変換先のデフォルト値をstringに設定しました。
1. デフォルト値を指定することで記述量を少なくするため。

refactor: [0549] setVal関数の変換先のデフォルト値を設定

---

js/danoni_main.js

1. colorpicker周りのコードを整理しました。
1. CodeClimateからの指摘より。

refactor: [0554] colorpicker周りのコード整理

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver27.2.0] ColorType:1～4に対してColorPickerに対応　他

---

js/danoni_main.js

1. キーコンフィグ(ColorPicker)、リザルトモーション周りのコードを整理しました。
1. コードの見やすさのため。

feat: [0555] キーコン、リザルト周りのコード整理

---

js/danoni_main.js
js/lib/danoni_constants.js

1. ラベル・ボタンの座標・サイズ設定をdanoni_constants.jsへ移動しました。
1. 座標・サイズ設定の多くが処理では無く設定であり、
設定系はdanoni_constants.jsへ移動する方針としたいため。

refactor: [0556] ラベル・ボタンの座標・サイズ設定をdanoni_constants.jsへ移動

---

js/danoni_main.js
js/lib/danoni_constants.js

1. コードを整理しました。
1. コードの見やすさ、Code Climateの指摘より。

refactor: [0557] 全体的なコードの整理

---

js/danoni_main.js

1. カレントパス取得部分をURIエンコードするよう変更しました。
1. Code scanningからの指摘より。
https://github.com/cwtickle/danoniplus/security/code-scanning/9

fix: [0558] カレントパス取得部分をエスケープする対応

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1274 
- #1275 
- #1276 
- #1277

[ver27.3.0]  ラベル・ボタンの座標・サイズ設定をdanoni_constants.jsへ移動　他

---

js/lib/danoni_constants.js

1. g_customJsObjの未定義箇所を修正しました。
1. PR #1278 で変数未定義が発生したため、その対応です。
- xxxx (懸念事項などがあれば記述 / Add any other context about the pull request here.)

fix: [0560] g_customJsObjの未定義箇所を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1280 
- #1274 
- #1275 
- #1276 
- #1277 
- #1278

[ver26.3.1] g_customJsObjの未定義箇所を修正　他

---

js/danoni_main.js

1. CSSクラスリセット部分のコードを整理しました。
1. 一部で冗長な記述になっていたため。

refactor: [0564] CSSクラスリセットのコード整理

---

SECURITY.md
js/danoni_main.js
package.json

[ver27.5.1] カレントパス取得部分のURIエンコード処理を元に戻す

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver27.6.0] デフォルトイベントを一部抑止、カスタムキーのパターン追記方法を拡張

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1295 
- danoni_constants.jsのみの変更です。

[ver27.7.0] Dランク追加、B, Cランク基準見直し

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver27.8.0] 譜面明細画面周りのボタン仕様、ショートカットキー仕様を見直し

---

SECURITY.md
js/danoni_main.js
package.json

[ver27.8.1] 重複するID名の解消

---

.github/workflows/codeql-analysis.yml
CONTRIBUTORS.md
README.md
SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver28.0.0] 譜面明細画面でカーソル移動用のショートカットを追加　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver28.0.1] ローカルファイル時にAdjustmentの小数設定ボタンの非表示化を取り止め

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver28.1.0] カラーセットの一括保存対応（キー別）

---

SECURITY.md
js/danoni_main.js
package.json

[ver28.1.1] ColorType: Type0が既定値にならない問題を修正

---

js/danoni_main.js

1. カスタムキーにおいてカラー・シャッフルグループの複数化に対応しました。
スラッシュを入れることでカラー・シャッフルグループを複数指定できます。
```
|shuffle8i=1,1,1,2,0,0,0,0/1,1,1,1,0,0,0,0|  <- スラッシュで複数化
|shuffle8i=1,1,1,2,0,0,0,0/1,1,1,1,0,0,0,0$1,1,1,2,0,0,0,0/1,1,1,1,0,0,0,0| <- 複数化＆キーパターン毎に指定($区切り)
|shuffle8i=1,1,1,2,0,0,0,0/1,1,1,1,0,0,0,0$8i_0| <- 複数化＆キーパターン毎に指定($区切り、略記指定)
```
1. カスタムキーのみカラー・シャッフルグループの複数化に対応できていなかったため。
これにより、既存キーと同等の設定がカスタムキーでも可能になります。

[0587] カスタムキーにおいてカラー・シャッフルグループの複数化に対応

---

SECURITY.md
js/danoni_main.js
package.json

- #1317 
- #1318 
- #1319 
- #1320 
- 追加／廃止された関数
|----|----|
|Add|newKeyTripleParam, changePattern|
|Change|searchPattern|
|Delete|copyChildArray|

[ver28.2.0] カスタムキーのカラー・シャッフルグループの実装　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1325 
- #1326 
- #1328 
- #1329 
|----|----|
|Add|changeConfigColor, changeShuffleConfigColor|
|Change|ー|
|Delete|ー|

[ver28.3.0] シャッフルグループのデフォルトからの差分に対して色付け　他

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1331 
- #1332 
- #1333 
- #1334

[ver28.3.1] Display画面の特定項目未使用時に非表示化する設定を追加　他

---

CONTRIBUTORS.md
SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1336 
- #1337 
- #1338 
- #1339 
- CONTRIBUTORS.md の更新あり
|----|----|
|Add|getBoostTrace, getBrakeTrace, g_motionFunc|
|Change|ー|
|Delete|ー|

[ver28.4.0] Motionの軌道加算仕様変更、Hi-Boost追加　他

---

SECURITY.md
js/danoni_main.js
package.json

- #1341 
- #1342 
- #1343 
|----|----|
|Add|ー|
|Change|judgeNextFunc|
|Delete|ー|

[ver28.5.0] 矢印について強制的に判定を移す処理を追加　他

---

SECURITY.md
js/danoni_main.js
package.json

- #1345 
- この設定はローカルのみ動作します。リモートでは表示されません。

[ver28.5.1] 左上のフレーム数表記をbaseFrameに変更

---

SECURITY.md
js/danoni_main.js
package.json

[ver28.6.0] 左上のフレーム数、左下の経過時間表記を譜面データ基準(baseFrame)に変更

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

1. Issue Template, Pull Request Templateの仕様を見直しました。
1. 手動で文言を消すといった手間があるため。
また、意図が伝わりやすいように記述内容を見直しました。

chore: [0610] 各種テンプレートの見直し

---

js/danoni_main.js
js/lib/danoni_constants.js

1. 共通的な部分のコード整理を行いました。
1. コードの見通し整理のため。

refactor: [0611] コードの整理

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1350 
- #1351 
- #1352 
- #1353 
- #1355

[ver29.0.1] フリーズアロー（始点）に対してFast/Slowをカウントするよう変更、始点判定範囲を拡大　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver29.1.0] 曲名クレジットの多言語対応、途中終了時でもクリア判定を行うよう変更

---

js/danoni_main.js

1. 制作者クレジットについて多言語表記に対応しました。
なお、共通設定用として`danoni_setting.js`側にも追加しています。
```
|tuning=ティックル,https://...|
|tuningEn=tickle,https://...|
```
||通常設定|多言語版設定(日本語)|多言語版設定(英語)|
|譜面ヘッダー版|tuning|tuning**Ja**|tuning**En**|
|共通設定ファイル<br>(danoni_setting.js)|g_presetObj.tuning|g_presetObj.tuning**Ja**|g_presetObj.tuning**En**|
1. 必要に応じて多言語用のサイトやクレジットに対応する可能性があるため。

feat: [0617] 制作者クレジットについて多言語表記に対応

---

SECURITY.md
js/danoni_main.js
package.json

- #1361 
- #1362 
|----|----|
|Add|ー|
|Change|ー|
|Delete|countFastSlow|

[ver29.2.0] 制作者クレジットについて多言語表記に対応　他

---

js/danoni_main.js

1.  タイトル文字関連の多言語表示に対応しました。
|通常設定|多言語版設定(日本語)|多言語版設定(英語)|
|titlesize|titlesize**Ja**|titlesize**En**|
|titlefont|titlefont**Ja**|titlefont**En**|
|titlepos|titlepos**Ja**|titlepos**En**|
|titlelineheight|titlelineheight**Ja**|titlelineheight**En**|
2. 多言語表示関連のコード整理を行いました。
1. タイトル文字の横幅が言語により変わるため、それに伴うヘッダーも言語別に設定が必要になりました。
2. 多言語表示設定の譜面ヘッダーが増えてきたため。

feat: [0619] タイトル文字関連の多言語表示対応 及び コード整理

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1364 
- #1365 
- #1366 
- 矢印・フリーズアロー処理部分のコード整理
- Motionオプションを使用し、フリーズアローについてタイミングをずらして押したとき、そのズレの中にストップが含まれていると、処理が止まる可能性がある問題を修正
|----|----|
|Add|getHeader|
|Change|ー|
|Delete|ー|

[ver29.3.0] タイトル文字関連の多言語表示対応 及び コード整理　他

---

README.md

- 作成方法の英語版リンクの貼り忘れに対応しました。
- PR #1369 のリンク忘れへの対応です。

chore: [0623] readme.mdの更新

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver29.3.4] 同時押し関連の英訳を見直し

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver29.4.0] フリーズアロー始点に対するモーションを実装

---

js/danoni_main.js
js/lib/danoni_constants.js

Reverts cwtickle/danoniplus#1380
本来必要と思っていた機能が不要になったため、取り消します。

Revert "feat: [0628] フリーズアロー始点に対するモーションを実装"

---

js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver29.3.5] divXの第2要素がposX末尾要素の最大値で無い場合の問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver29.4.1] 拡張スクロール設定に「Reverse」を追加するとReverse設定を無効化するよう変更　他

---

js/danoni_main.js

1. div要素のスタイル変更箇所を$idに統一しました。
1. 記述に統一感が無く、最近のコード修正で使用頻度が減っていたため。

refactor: [0639] div要素のスタイル変更箇所を$idに統一

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1396 
- #1397 
- ver30.0.0 の PR #1395 も参照してください。

[ver30.0.1] shuffleUse=false時にキーコンフィグ画面が動作しない問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver30.1.2] ScrollがDefault以外のときに別キーモード用のデータが取得されない問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver30.2.0] 矢印・フリーズアローのスクロール方向を反転する機能を実装　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver30.2.3] カスタムキーのdivX, shuffleXが未定義のときの問題を修正　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver30.6.0] キーコンフィグ画面でキー割り当て先をクリックしたときの挙動を変更　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver31.0.1] 譜面リスト中、上下キーを使って選択した譜面がキー数違いのときの問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver31.1.0] 譜面密度グラフについて、上位3番目まで色付けするよう変更　他

---

SECURITY.md
js/danoni_main.js
package.json

- #1451 
- 関数として getRefData, makeBackgroundData に変更がありますが、
いずれも外部からアクセスできないため影響はありません。

[ver31.2.0] 譜面エフェクトデータに別の変数が入っていた場合、その変数を参照するよう変更　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver31.3.0] keyExtraListの任意化、位置管理系変数をdanoni_constants.jsに集約　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver31.4.1] カスタムキーのposXに空が指定されたときに初期化されるよう処理を改善

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver31.5.0] 別キーモード、ミラー時のハイスコア保存に対応　他

---

js/danoni_main.js

1. PR #1466 のコードを一部修正しました。
1. PR #1469 がcloseとなったため、コード整理部分のみ変更しています。

improve: [0689] コードの整理

---

js/danoni_main.js

1. 大小比較部分について、`Math.max`や`Math.min`を使う方法に変更しました。
1. コードの見やすさ向上のため。

refactor: [0691] 大小比較部分のコード整理

---

js/danoni_main.js

1. 譜面選択部分について、カスタムJs側で可変できるように対応しました。
これまでは`difData`に基づく譜面情報順に表示するだけでしたが、
今後は `g_headerObj.viewLists` で定義した値に基づいて表示します。
デフォルトは`difData`に基づく譜面情報順になるよう番号を自動で振ります。
```javascript
g_headerObj.keyLabels = [`7`, `7`, `7`, `7i`, `7i`, `7i`];   // 7key3譜面、7ikey4譜面のリスト
g_headerObj.viewLists = [0, 1, 2, 3, 4, 5];  // 画面表示する譜面番号のリスト（デフォルト） 
```
1. 隠し譜面や選曲機能などを入れたい場合に、これまでの場合は複雑な方法を取る必要があったため。
ヘッダー指定についてはまだ未整理のため、現状はカスタムJsからの制御のみです。
- カスタムJs側で`g_headerObj.viewLists`を強制的に変えた場合、
表示する内容がそれに応じて変わるようになります。
- 下記右側は、`g_headerObj.viewLists = [1, 2, 3, 4, 5, 6];` と指定した場合の動きです。

feat: [0692] 譜面選択部分の可変対応

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver31.7.0] フリーズアローヒット時の割込み処理を実装、譜面選択部分の可変対応　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver32.0.0] Shift, Ctrl, Altキーの左右キーの割り当てを分離　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver32.1.0] ボタンのデフォルト処理を参照する機能を追加　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver32.2.0] 速度変化の平均値表示を追加、Asym-Mirrorの仕様変更 他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver32.2.1] 譜面明細画面でQキーを押してもカーソル移動しない問題を修正 他

---

SECURITY.md
js/danoni_main.js
package.json

[ver32.2.2] blankFrameが未指定のときにblankFrameが正しく反映されない問題を修正

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
package.json

[ver32.6.0] フリーズアローの始点判定時の判定数表記の仕様を変更　他

---

js/danoni_main.js
js/lib/danoni_constants.js

1. 配列定義周りのコードの整理を行いました。
2. 矢印・フリーズアローが削除されたとき、それに付属するg_attrObjの値を動的に削除する処理を追加しました。
1. 似たようなコードの記述を除去することで見通しをよくするため。
2. g_attrObj実装前は矢印・フリーズアローの属性として定義しており、
矢印・フリーズアロー削除と合わせて消去されていたため。

refactor: [0718] コード整理

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver32.6.1] コード整理、Excessive設定にショートカットキーを割り当て

---

js/danoni_main.js

1. splitLF, splitLF2関数について引数がundefinedの場合に対応しました。
2. 配列周りのコードを整理しました。
1. 関数の使いやすさの向上のため。
2. 重複している記述の解消により、今後の機能追加をしやすくするため。

refactor: [0720] コードの整理

---

js/danoni_main.js
js/lib/danoni_constants.js

1. タイトル表示系及びカスタム関数設定について多言語化に対応しました。
また、他の名前と同じようなキャメル表記も指定できるようにしました。
|譜面ヘッダー名|代替名|
|----|----|
|titlesize(Ja, En)|titleSize(Ja, En)|
|titlefont(Ja, En)|titleFont(Ja, En)|
|titlegrd(Ja, En)|ー|
|titlearrowgrd(Ja, En)|titleArrowgrd(Ja, En)|
|titlepos(Ja, En)|titlePos(Ja, En)|
|titlelineheight(Ja, En)|titleLineHeight(Ja, En)|
|titleanimation(Ja, En)|titleAnimation(Ja, En)|
|titleanimationclass(Ja, En)|titleAnimationClass(Ja, En)|
|customjs(Ja, En)|customJs(Ja, En)|
|customcss(Ja, En)|customCss(Ja, En)|
|scoreDetailUse(Ja, En)|chartDetailUse(Ja, En)|
1. タイトル表示系及びカスタム関数設定については言語別の設定が必要となることがあるため。

feat: [0719] タイトル表示系及びカスタム関数設定の多言語化対応

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1516
- #1517 
- danoni_constants.js に変更がありますが、行削除のみのため変更しなくても影響はありません。

[ver32.7.0] タイトル表示系、カスタム関数設定の多言語化対応 他

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
package.json

[ver33.1.1] 背景・マスクモーションのフレーム計算誤りを修正 他

---

SECURITY.md
js/danoni_main.js
package.json

[ver33.1.2] フリーズアローの終点と次のフリーズアローの始点が近い場合の判定不具合を修正

---

CONTRIBUTORS.md
SECURITY.md
js/danoni_main.js
package.json

[ver33.1.3] リザルト画像コピー用のテキストのエスケープ文字が戻されていない問題を修正

---

js/danoni_main.js

1. キー変化(keych_data)でadjustmentやplaybackRateが反映されない問題を修正しました。
1. Discord上での指摘より。
他のエフェクト系の設定と異なる実装となっていたため、対応が漏れていました。

fix: [0730] キー変化でadjustmentやplaybackRateが反映されない問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver33.1.4] キー変化でadjustmentやplaybackRateが反映されない問題を修正

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
package.json

[ver33.2.0] 画面の上下に共通の枠線を一律追加　他

---

js/template/danoni_setting.js

1. danoni_setting.js の下記の設定をboolean型に変更しました。
- excessiveJdgUse
- frzStartjdgUse
- customDesignUse
1. 他の設定との整合のため。なお、settingUseについては文字列としても使用するため据え置きにします。
ちなみに後でboolean型に変換しているので、従来通りstringで指定しても支障はありません。（互換性あり）

improve: [0736] 一部設定のstring型をboolean型に変更

---

js/danoni_main.js

1. カスタムキー位置について、下段の相対位置を定義できるようにしました。
下段への折り返し位置(divXの1番目)が定義されている前提で、
`b7`のように`b`+下段開始からの相対位置を指定することができます。
折り返し位置が未定義の場合は、折り返し位置を0として扱います。
```
|div11x=7,b6|
-> |div11x=7,13|
|pos11x=0,1,2,3,4,5,6,b0,b1,b5,b6|
-> |pos11x=0,1,2,3,4,5,6,7,8,12,13|
```
1. Resolves #1545 
トランスキーなど複雑なキーを定義する場合に、折り返し位置を途中で変更することがあり、
その場合、従来の方法では下段位置を全て変える必要が出てくるため。

improve: [0738] カスタムキー位置の下段略記対応

---

SECURITY.md
js/danoni_main.js
package.json

[ver33.4.1] ショートカットキーエリア有効時、背景・マスクの表示位置がずれることがある問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver33.5.0] リザルトコピー用画像のプレビュー機能を追加　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver33.5.1] グラデーション記法のセパレート文字を見直し

---

CONTRIBUTORS.md
SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver33.6.0] ウィンドウの高さやY座標調整ができる機能を実装

---

js/danoni_main.js

1. 全体的にコードを整理しました。
2. 内部関数名`getTimingData`を`calcBoostData`に変更しました。
1. コードを整理することで、他機能実装の際の弊害にならないようにするため。
2. 他の関数名と名前が紛らわしいため。内部関数のため、カスタム系への影響はありません。

refactor: [0746] コードの整理

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver34.0.0] 歌詞表示、背景・マスク・スタイルデータについてキー名・キーパターン毎に設定する機能を追加　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver34.1.0] 歌詞表示及びタイトル曲名・アーティスト名表示で、条件付きでカンマが使えるよう変更

---

js/danoni_main.js

1. 単位付き部分の関数化、コード整理を行いました。
1. 単位指定部分が全て直書きとなっていたため。

refactor: [0752] 単位付き部分の関数化、コード整理

---

js/danoni_main.js

1. コードの整理を行いました。
1. 分割不要な関数や条件分岐等が存在したため。

refactor: [0753] コードの整理

---

SECURITY.md
js/danoni_main.js
package.json

- #1571 
- #1572 
- #1573 
- #1575

[ver34.3.0] difDataで指定したノルマが反映されない問題を修正　他

---

js/danoni_main.js

1. startFrame未指定時に起動に失敗する問題を修正しました。
1. PR #1573 のコード整理時の考慮漏れと思われます。
- ver34.3.0のみで発生する問題です。

fix: [0756] startFrame未指定時に起動に失敗する問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver34.3.1] startFrame未指定時に起動に失敗する問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver34.3.2] HitPosition設定が機能していない問題を修正

---

js/danoni_main.js

1. 色変化が一部のレーンに適用されない問題を修正しました。
1. PR #1551 のコード整理の影響です。filter->forEachに書き換えた際に、forEach側に元の配列の添え字を使っていたことが原因と思われます。
- ver33.5.0以降で発生する問題です。

fix: [0759] 色変化が一部のレーンに適用されない問題を修正

---

js/danoni_main.js

1. 環境により右シフトキーが動作しない問題を修正しました。
右シフト＋Deleteで結果画面に移動しない問題も修正しています。
1. PR #1581 の修正が中途半端な設定になっていたため。
右シフトとそれ以外のUnknownキーを区別するようになります。
- 「need-to-fix-supportVer.」タグを一旦つけていますが、いろいろな処理を加えているため
今回の変更で過去バージョンに適用するかどうかは保留とします。

improve: [0760] 環境により右シフトキーが動作しない問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver34.4.0] 環境により右シフトキーが動作しない問題を改善　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver34.4.1] R-ShiftキーとUnknownキーが分離できていない問題を修正

---

js/danoni_main.js

1. undefined周りのコード整理を行いました。
1. コードの整理により、機能拡張をしやすくするため。

refactor: [0762] undefined周りのコード整理

---

js/danoni_main.js

1. キーコントロール系のコード整理を行いました。
2. divタグのid取得処理を`document.getElementById`に統一しました。
1. コードの整理により、機能拡張をしやすくするため。
2. 記述方法がバラバラになっていたため。

refactor: [0763] キーコントロール系のコード整理

---

SECURITY.md
js/danoni_main.js
package.json

[ver34.4.2] コードの整理

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver34.5.0] 譜面明細子画面のレーン別矢印数で最大・最小がわかるよう表示を追加　他

---

js/danoni_main.js

1. 右シフトキー対応のコード整理を行いました。
1. 右シフトキー対応として除外設定を行っていましたが、
従来の`transCode`関数を使用することでシンプルに記載できるため、書き直しました。
過去バージョンの対応についてもこの方法で対応しています。
- この変更に伴いキーコード:260は使用しなくなります。
- KeyboardEvent.code='' 、KeyboardEvent.key="Shift"のパターンも
`R)Shift`と表示されるようになります。

refactor: [0766] 右シフトキー対応のコード整理

---

SECURITY.md
js/danoni_main.js
package.json

[ver34.5.1] 右シフトキー対応のコード整理　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1597 
- #1598 
- #1599 
- #1600

[ver34.6.0] 譜面番号固定時に他の譜面ファイル番号や譜面番号を参照できる機能を追加　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver34.6.1] 譜面リスト、キー別フィルターの画面位置調整

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver34.7.0] デフォルトのタイトル矢印の回転・種別を自由に決められるよう変更

---

SECURITY.md
js/danoni_main.js
package.json

[ver35.1.0] keyGroupOrderをカスタムキー定義の1項目として追加

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver35.2.0] カスタムキー用に一部の部分キー定義を標準実装　他

---

js/danoni_main.js

1. posXの略記記法について下段記法にも対応しました。
```
|pos20=0...3,5...8,10...13,b0...+11$|
```
1. 下段記法の組み合わせに対応できていなかったため。

feat: [0779] posXの略記記法について下段記法にも対応

---

SECURITY.md
js/danoni_main.js
package.json

[ver35.3.0] カスタムキーの略記指定の組み合わせに対応

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver35.4.0] FlatMode実装、キーパターン略記仕様変更　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver35.4.2] 環境によりタイトルの背景矢印が表示されない問題を修正

---

js/danoni_main.js

1. フリーズアロー判定部分にコメントを入れました。
1. フリーズアロー判定部分がやや複雑になってきたため、見返し用として必要と考えて入れました。

chore: [0785] フリーズアロー判定部分のコメントを補完

---

SECURITY.md
js/danoni_main.js
package.json

[ver35.4.3] 一つ前のフリーズアローの判定条件の問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver35.4.4] カスタムキー定義のkeyGroupOrderXのローカル保存後、その情報が取り出せない問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1632 
- ver35.4.4 ( PR #1631 )

[ver35.4.5] カスタムキー定義のflatModeXのローカル保存後、その情報が取り出せない問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver36.0.0] 色変化の新記述仕様を追加　他

---

js/danoni_main.js

1. フリーズアローのヒット時の帯に関する個別色変化の動作仕様を変更しました。
フリーズアロー個別にヒット時の色を持たせ、ヒット時に変わったときに全体色変化が絡んでいなければ、その値を継続するように見直しました。
以前はヒット時に変わったタイミングの色を取るようにしていましたが、個別色変化かつヒット時の色についてはv7～v35まで指定したフレーム数を出現時まで遡らないようにする措置が取られていたため、大きな問題になっていませんでした。v36にてその仕様を元に戻したことで、その問題が顕在化した形です。
2. 譜面ヘッダー：colorDataTypeを廃止しました。
1. Discord指摘より。フリーズアローのヒット時の個別色変化に関する潜在的不具合です。
ただ、v7～v35までは上述の通り暫定措置が取られているため、過去バージョンへの修正は行いません。
また、v36.0.0で実施していた旧仕様（color_data）でフリーズアローのヒット時の場合に全体色変化に切り替える仕様も不要となったため、合わせて取り止めています。
2. 1.の変更によりcolorDataTypeで行っていた互換性の維持が不可能になったため。
ただ、殆どの場合でこの設定が使用されていることはほぼ無いため、廃止しても支障は無いと考えます。

improve: [0792] フリーズアローのヒット時の帯に関する個別色変化の動作仕様変更

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
package.json

[ver36.1.0] フリーズアローのヒット時における個別色変化の動作仕様を変更 他

---

js/lib/danoni_constants.js

1. キーコンフィグエラー部分の文言を見直しました。
1. エラー内容がキーコードを使った例になっていますが、
英語化対応している今となってはキーコードだとかえってわかりにくいため。

improve: [0793] キーコンフィグエラー部分の文言を見直し

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver36.2.0] 譜面明細画面にハイスコア表示を実装　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver36.2.1] Accuracyが計算外のときに結果画面でエラーになることがある問題を修正

---

js/danoni_main.js

1. キーコンフィグのコメントを追加しました。
1. PR #1650 で追加したボタンの補足情報が無かったため。

chore: [0798] キーコンフィグのコメントを追加

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver36.3.0] カラーグループ数を5から10に拡張　他

---

js/danoni_main.js
js/lib/danoni_constants.js

1. キーコンフィグ画面のスクロールバーが出ないことがある問題を修正しました。
また、キーコンフィグ画面のオブジェクトが縮小された状態でも、スクロールバーが上に移動しないように位置を調整しました。
1. PR #1650 の考慮漏れです。

fix: [0800] キーコンフィグ画面のスクロールバーが出ないことがある問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver36.3.2] キーコンフィグ画面のスクロールバーが出ないことがある問題を修正

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
js/lib/danoni_constants.js
package.json
skin/danoni_skin_default.css
skin/danoni_skin_light.css
skin/danoni_skin_skyblue.css

[ver36.4.0] 譜面明細画面の各ボタンのオンマウス説明文追加　他

---

README.md
SECURITY.md
js/danoni_main.js
package.json

[ver36.4.2] 不要な文字までトリムしてしまう問題を修正　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver36.5.0] シャッフル設定に矢印・フリーズアローが散らばるS-Randomの設定（Scatter/Scatter+）を追加

---

js/lib/danoni_constants.js

1. Xのポスト用URLを次のように変更しました。
- 変更前: `https://x.com/intent/tweet?text=...`
- 変更後: `https://x.com/intent/post?text=...`
1. リダイレクトされるので現在は影響ありませんが、今後リダイレクトが切られる可能性を考慮して変更します。

improve: [0809] Xのポスト用URLの変更

---

.github/PULL_REQUEST_TEMPLATE.md

- 従来のテンプレートが最近の使い方と乖離してきたため、テンプレートを更新しました。
- 「変更内容 / Details of Changes」の内容がそのままリリースノートの
Remarkで使えるフォーマットに変更しています。
- また、Pull Requestテンプレートが日本語だけになっていた箇所を見直し、英語も併記するようにしました。
（Pull Requestについて、英語併記を勧めるものではありません。説明書きのみ。
　従来通り、日本語のみ・英語のみでOKです）
```md
```
1. Pull Requestの記述精度を上げて、リリースノートでの書き直しを減らすため。

chore: [0812] Pull Requestのテンプレートを更新

---

.github/PULL_REQUEST_TEMPLATE.md
SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1671 
- #1672 
- #1673 
- #1674

[ver36.6.0] シャッフルグループ数の上限を見直し、ミラー譜面のハイスコア保存条件を変更　他

---

js/danoni_main.js
js/lib/danoni_constants.js

- すでに付属を止めている `danoni_legacy_function.js` の読込停止と、
未使用定数の削除を行いました。
1. Resolves #1662

improve: [0814] 未使用定数及びdanoni_legacy_function.jsを削除

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver37.0.0] キー数変化で同時に複数のキーを共存させる機能を実装　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver37.0.1] Reverseのときに歌詞表示の自動反転が効かない問題を修正　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver37.1.0] 速度変化グラフにおいて最低/最高変化量を表記するように変更　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver37.2.0] playbackRateの値に合わせてAdjustmentの設定幅を伸縮するよう変更　他

---

SECURITY.md
css/danoni_main.css
js/danoni_main.js
package.json

[ver37.2.1] mask, background-clipについてベンダープレフィックスの互換設定を元に戻す

---

SECURITY.md
js/danoni_main.js
package.json

[ver37.3.0] 同一フレームでY座標違いの場合でも矢印・フリーズアローを区別して生成できるよう対応

---

SECURITY.md
js/danoni_main.js
package.json

[ver37.3.1] フリーズアローの終端がいない場合に末尾のフリーズアロー始端を自動除去するよう修正　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver37.6.0] カスタムキーの単位名を変更できる設定を追加　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver37.6.1] JSDocで記述する引数定義を最新化、古い関数の代替処理のコード整理

---

SECURITY.md
js/danoni_main.js
package.json

[ver37.6.2] ImgTypeで拡張子の指定がないときに、強制的に他の拡張子に変更する機能の問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver37.7.0] コードの整理、JSDocの追記

---

SECURITY.md
js/danoni_main.js
package.json

[ver37.7.1] 色変化（ncolor_data）で矢印種類を省略したときに色変化対象が正しく反映されない問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
js/lib/legacy_functions.js
js/template/danoni_setting.js
package.json

- #1716 
- #1717 
- #1718 
- #1719 
- #1720

[ver38.0.0] ゲージ設定で数式が使えるよう変更 他

---

SECURITY.md
js/danoni_main.js
package.json

[ver38.0.1] 結果画面で定義前に使われている定数がいる問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/legacy_functions.js
package.json

[ver38.0.2] 旧関数のボタン作成処理の引数間違いを修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver38.0.3] 色変化（ncolor_data）で矢印種類を省略したときに色変化対象が正しく反映されない問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver38.1.1] Fountainで全体変速が1倍未満、個別加速が1倍以上のときにモーションが見づらくなる問題を修正

---

js/danoni_main.js
package.json

[ver38.1.2] 加算するモーションフレーム数の計算方法の誤りを修正、Fountainの軌道の問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver38.2.0] Scatterオプションのシャッフル方法を一部見直し

---

README.md
SECURITY.md
js/danoni_main.js
package.json

[ver38.2.1] 色変化(ncolor_data)でキーパターンを変えると適用する矢印グループが想定と異なる問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver38.2.2] 色変化(ncolor_data)で別キーモードにしか存在しないレーンを含む矢印グループ指定ができるよう修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver38.3.0] プレイ中ショートカットの変更に対応

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver39.1.0] StepArea設定の仕様を一部見直し　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver39.2.0] Appearance用のフィルターを階層別に定義するよう変更

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver39.3.0] StepArea: 2Step実装、Mismatched, R-Mismatchedの一部仕様変更　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1756 
- #1757 
- #1758 
- #1759

[ver39.4.0] X, Y座標の管理関数を分離、設定分岐部分をObjectからMapに変更　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver39.4.1] CSSのpointer-event属性のデフォルト値を種別ごとに設定するよう変更　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver39.4.2] overflow: autoを適用している箇所が動かない問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver39.4.3] フェードイン、Appearanceのフィルター位置が動作しない問題を修正　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver39.5.0] データ管理用の画面を追加

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver39.6.0] ローカルストレージ情報を使わないセーフモードの実装　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver39.7.0] Data Managementのレイアウト及びフォーマット表示関数の仕様変更

---

SECURITY.md
js/danoni_main.js
package.json

[ver39.7.1] Data Management画面の実際の割り当てキーがカスタムキーの場合に表示されない問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver39.8.0] ローカルストレージ情報のコピー機能を追加

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver39.8.1] Data Management画面における表示エリア・ボタンの高さ可変対応

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1799 
- #1800 
- #1801 
- #1802

[ver40.1.0] 特定ドメインにのみ常時デバッグモードにするよう変更　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver40.2.0] 前提条件画面からDataManagementへのリンクを追加　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver40.3.0] エディターのカスタムキー定義を自動生成する機能を追加　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver40.3.1] formatObject関数の処理を整理、速度変化・色変化の装飾追加

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver40.4.0] CDNとしてjsdelivrをリモート対象に追加　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver40.4.2] リモート接続時、共通設定ファイルを自サーバーから参照するように変更

---

SECURITY.md
js/danoni_main.js
js/template/danoni_cdn.js
package.json

- #1817 
- #1819 
- ver40.4.2と合わせてリリースします。

[ver40.4.3] リモート接続時、共通設定ファイルがデフォルトのときに自サーバーから参照できない問題を修正

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1821 
- #1822 
- npm検証でver40.5.0～40.5.1は使用済みのため、ver40.5.2としてリリースします。

[ver40.5.2] リモート接続時の画像ファイルについて、カスタム分は自サーバーから取得するよう変更

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver40.7.0] ダンおに譜面作成エディタ ver3フォーマットの自動生成機能を実装　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver40.7.1] 初期ロード方法をwindow.onloadからreadyStateをチェックする方法に変更

---

js/danoni_main.js

- 色変化やモーションデータ、ダミーノートが存在しない場合に、
不要なg_workObjのプロパティを動的に削除するよう変更しました。
- 合わせて、プロパティが削除されても動作するように各所のコードを修正しています。
- 直接指定している`(..)`（カレントディレクトリ指定文字列）を定数に置き換えました。
1. 不要なプロパティを削除することでオブジェクト構造を見やすくするため。
2. コードの見やすさのため。
- プロパティの動的削除を行っているため、カスタムJSにて依存した処理を記述している場合、
見直しが必要になる場合があります。
- mkColor
- mkColorCd
- mkColorShadow
- mkColorShadowCd
- mkScrollchArrow
- mkScrollchStep
- mkScrollchArrowDir
- mkScrollchStepDir
- mkScrollchArrowLayer
- mkScrollchStepLayer
- mkFColorNormal
- mkFColorNormalCd
- mkFColorNormalBar
- mkFColorNormalBarCd
- mkFColorNormalShadow
- mkFColorNormalShadowCd
- mkFColorHit
- mkFColorHitCd
- mkFColorHitBar
- mkFColorHitBarCd
- mkFColorHitShadow
- mkFColorHitShadowCd
- mkArrowCssMotion
- mkArrowCssMotionName
- mkFrzCssMotion
- mkFrzCssMotionName
- mkArrowColorChangeAll
- …

improve: [0917] 不要なg_workObjのプロパティを動的に削除、コードの整理

---

SECURITY.md
danoni/danoni0.html
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1836 
- #1837 
- #1838 
- #1839

[ver41.0.0] 選曲機能を実装　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver41.0.2] ゲージ設定の許容ミス数が表示されない問題を修正、選曲画面の曲表示部分の高さ修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver41.1.0] 選曲モードで複数楽曲を部分的にまとめる機能を実装　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

- #1850 
- #1851
- #1852 
- #1853

[ver41.2.0] 選曲画面時にBGMを流す処理を実装　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver41.2.1] 設定画面で表示する曲名のエスケープ文字が残ってしまう問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver41.3.0] 選曲画面のBGM音量のローカル保存に対応　他

---

SECURITY.md
js/danoni_main.js
package.json

[ver41.3.2] 楽曲情報（musicTitle）で定義している以上のmusicNoを指定したときに処理が止まる問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver41.4.0] 必要以上にキャッシュクリアを行わないよう処理を見直し

---

js/danoni_main.js

- listMatching関数の呼び出し方法に誤りがあり、キャッシュクリア条件が利いていない箇所がありました。
1. PR #1864 の考慮漏れです。

fix: [0935] キャッシュクリア条件の誤りを修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver41.4.1] キャッシュクリア条件の誤りを修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver42.1.1] 音楽データの読み込みパスの仕様を他のファイルと統一

---

js/lib/danoni_constants.js

- 削除済みの設定値のプロパティを削除しました。
1. 未使用のプロパティを削除することで見通しをよくするため。

refactor: [0948] 未使用プロパティを削除

---

SECURITY.md
js/danoni_main.js
package.json

[ver42.2.4] layerGroupXに対するlayerTransXの対応間違いを修正

---

js/danoni_main.js
js/lib/danoni_constants.js

- StepAreaの設定「2Step」「Mismatched」「R-Mismatched」「X-Flower」において、
従来は多層レイヤーの作品を想定していない実装になっていましたが、
3層以上のレイヤーの場合でもレイヤー分割されるように変更しました。
- 仕組み的には、元々の譜面で使用するレイヤーを倍化して、
一部のレーンをその倍化したレイヤーに移すことで対応しています。
- スクロール反転・階層変更によるレイヤー位置変更にも対応しています。
- `scrollch_data`を拡張して、レイヤー移動先のTransitionを指定できるようにしました。
- フレーム数、対象、スクロール方向、移動先階層グループ、移動先レイヤーのTransitionの順に指定します。
一番最後の項目が追加要素です。
```
|scrollch_data=
0,12,-1
0,13,-1
0,14,-1
0,15,-1
0,16,-1
0,17,-1,3,rotateX(60deg)
0,18,-1,3
1000,17,1,3,rotateX(60deg)
1000,17,1,3
|
```
- 省略した場合は、前のTransition内容を継承します。
- 削除はされないので、元に戻したいときは`rotateX(0deg)`など明示する必要があります。
- Transitionを重ね掛けしたい場合は、スペース区切りで指定して下さい。
例）`rotateX(30deg) roteteY(20deg)`
- 階層グループは2層で1組ですが、ここで指定できるのは1層分だけです。
反転先でもTransitionを掛けたい場合は、上記のように反転時にTransitionを指定してください。
1. 今後、多層に対応した作品が出てきたときの弊害になりそうなため。
2. …

feat: [0952] StepArea設定において多層レイヤーに対応、レイヤー変更においてTransition指定に対応

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver42.3.0] StepArea設定において多層レイヤーに対応、レイヤー変更においてTransition指定に対応

---

js/danoni_main.js

- jsdocの不足している項目の追加や、説明の追加、コードのリファクタを行いました。
1. コードの見やすさと関数の役割を明確にするため。

refactor: [0954] jsdocの見直し、コードのリファクタ

---

SECURITY.md
js/danoni_main.js
package.json

[ver42.4.0] 1譜面目のみに適用する初期色設定（setColor1/frzColor1）の実装　他

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver42.5.0] 譜面番号固定時に分割したファイル側からも初期色が定義できるよう変更

---

SECURITY.md
js/danoni_main.js
package.json

[ver42.5.2] 全体色変化と個別色変化が短いスパンで変わるとき、前の色に戻ることがある問題を修正

---

SECURITY.md
js/danoni_main.js
package.json

[ver42.5.3] musicTitleの4番目要素の反映方法における問題を修正

---

js/lib/danoni_constants.js

- Shaking設定にDrunkに「X-Horizontal」と「X-Vertical」を足した「S-Drunk」を追加しました。
1. 遊び方の拡充のため。

feat: [0966] Shaking設定にS-Drunkを追加

---

SECURITY.md
js/danoni_main.js
js/lib/danoni_constants.js
package.json

[ver43.1.0] StepArea設定にAlt-Crossing、Shaking設定に複数オプションを追加

---

js/lib/danoni_constants.js

- 他の設定については定義がありましたが、StepArea設定のみ定義がありませんでした。
- 無くても影響はありませんが、他と合わせて対応します。
1. StepArea設定の名前を変更したい場合に、他の設定と同様に対応できるようにするため。
- v39で追加した設定のため、v39以降で影響があります。

improve: [0968] g_lblNameObjにStepAreaの設定値を追加
