js/danoni_main.js
- 再代入しない変数と定数はconstで宣言
- 再代入する変数はletで宣言
ここでのconst/letの使い分けの決め手は再代入しないか、するかです。
ソースコード上の文脈は無視しています。
ので、定数はconst、変数はletで宣言するということはありません。
ECMAScript 2015からconst/let変数宣言が使えます。
Chrome, Firefox, EdgeおよびIE11が対応しています。
const/letで変数宣言すると、
- その変数は同名で再宣言できません
- 既にある変数を知らずに別の用途で再宣言する間違い・起因する不具合を防げます
- これらはエラーになるので、隠れた間違いについて懸念をすることがありません
特にconstで変数宣言すると、
- その変数は再代入できません
- 変数の中身が保証されるので、null/undefinedを参照してしまう可能性が減ります
- 宣言を見れば値が分かるので、不確定な値について懸念をすることがありません
Dancing☆Onigiri (CW Edition)について言えば、
今回も規模の大きいソースコードですので、
全部を読んで理解してから改造するダンおに制作者は居ないと思います。
ので、上記の利点は今後のダンおに制作の助けになるはずです。
IE11には、for文の初期化式中にconst/letで変数宣言しても、その変数のスコープが曖昧な不具合があるようです。
どんな具合なのか確認する環境が手元にないので、for文の初期化式中では引き続きvarで変数宣言しています。
IE11をサポートしないなら、const/letに切り替えて構いません。
=> varではなくconst/letで変数宣言するように変更

js/danoni_main.js
- ゲーム中の経過時刻の取得にはperformance.now()を使う
- new Date()はカレンダー的な意味での現在日時取得に使う
new Date()は毎フレーム呼び出すには重い処理なので、代替メソッドを使います。
performance.now()は経過時刻の取得のために最適化されたメソッドです。
https://developer.mozilla.org/ja/docs/Web/API/Performance/now
=> ゲーム中の経過時刻の取得にperformance.now()を使うように変更

js/danoni_custom.js
タイトル文字はdanoni_custom.jsの領域であり、  
利用者で自由に変えることのできる領域のため、特に縛りをつける必要はないが、  
実装の簡易さから利用される可能性が大きい。  
ただ、そのまま利用するとフォントの関係で横にはみ出る問題が発生する。  
このため、標準テンプレートの一部として、titlesize変数を追加する。
譜面データ内に下記を記載することで、  
自動で指定したサイズではなく記載したサイズに変更される。  
ただし、danoni_custom.jsを書き換え、フォントサイズを自分で書き直した場合はこの限りではない。  
```
|titlesize=40|
```
=> [custom 0.2.0] カスタム変数：titlesizeを追加

js/danoni_custom.js, js/danoni_custom2.js, js/danoni_main.js
- Displayオプション(従来のDarkオプション＋Col.Change＋Sp.Changeに相当)画面を追加
- 画面が増えたため、danoni_custom.jsの以下の関数追加を推奨（背景が消える）
<pre>
/**
* 表示変更(初期表示) [Scene: Settings-Display / Lemon]
*/
function customSettingsDisplayInit() {
// レイヤー情報取得
var layer0 = document.getElementById("layer0");
var l0ctx = layer0.getContext("2d");
// 画面背景を指定 (background-color)
var grd = l0ctx.createLinearGradient(0, 0, 0, g_sHeight);
grd.addColorStop(0, "#000000");
grd.addColorStop(1, "#222222");
l0ctx.fillStyle = grd;
l0ctx.fillRect(0, 0, g_sWidth, g_sHeight);
}
</pre>
- 今後、同様にライフゲージオプションが別メニュー化する可能性あり
- 画面の見せ方については今後も検討予定
=>  [ver0.74.1] Displayオプションを追加

css/danoni_main.css, js/danoni_main.js
- Fadeinオプションの数値をスライダーで変更できるようにした
- ±5, ±25のボタンを廃止し±1のボタンを追加した
- ワンタッチで1%単位での変更を可能とするため
- 動作保証外のブラウザですがFirefox用のデザイン対応も含んでいます
=> Fadeinオプションにスライダーを実装

js/danoni_main.js
- ライフゲージOFF時の非表示対象を修正
- ライフゲージOFF時、間違ったオブジェクトに対して非表示指示をしていた
=> [vr0.76.2] ライフゲージ非表示時の記述ミスを修正

js/danoni_main.js
- リザルト画面に、曲名・譜面名・プレイスタイル・ディスプレイ設定の内容を追加
- リザルト画面だけでは、プレイの詳細状況がわからないため
- 従来の表示は冗長で長くなりがちなため、できるだけ簡易な書き方に変更している
=> リザルト画面のデザインを変更（曲名他を追加）

js/danoni_main.js
- リザルト画面に、曲名・譜面名・プレイスタイル・ディスプレイ設定の内容を追加
- リザルト画面だけでは、プレイの詳細状況がわからないため
- 従来の表示は冗長で長くなりがちなため、できるだけ簡易な書き方に変更している
=> [ver0.77.0]  リザルト画面のデザインを変更（曲名他を追加） 

js/danoni_main.js
- 事前読み込み対象にライフボーダー用画像を追加
- 画像追加時に事前読み込み対象に足してなかったため（更新漏れ）
=> [ver0.77.1] 事前読み込み対象にライフボーダー用画像を追加

js/danoni_main.js
- IE11向けに、動作しないnew CustomEvent()の代替処理を追加
これは 557a064 の変更以降、IE11だけで起きる問題です。
IE11でも、ひとまず譜面が見れる程度の動作を望むならば、修正が必要だと思います。
IE11を完全にサポートしない、それこそ画面に何も表示されなくてもいいならば、
このコミットは取り込まなくて大丈夫です。
IE11をサポートするかどうかで、今後のコードの書き方が変わってきます。
=> IE11でゲームが開始直後に止まる問題を修正

js/danoni_main.js
1.  ゲージ設定で、譜面変更ボタンからリセットするとゲージ設定がリセットされない問題を修正
2.  フリーズアローのヒット開始位置をステップゾーン上になるように位置調整
1.  不具合修正
2. ParaFlaソース時代の仕様に合わせる
=> [ver1.0.2] ゲージ設定簡素化＆フリーズアローのヒット開始位置を固定化

js/danoni_main.js
- Edge V18以降のときの矢印色の挙動をChrome他に合わせる対応
- 曲時間直指定時、終了時間指定がおかしくなることがある不具合を修正
- Edge V18より、css-maskが対応したため色変化設定をChrome他に合わせる
- 曲時間計算で、一部文字列結合されており表記がおかしくなっていたため
=> [ver1.1.0] Edge V18以降のときの矢印色の挙動をChrome他に合わせる対応、終了時間指定がおかしくなることがある不具合を修正

js/danoni_main.js
- フリーズアローヒット時に後続矢印位置が補正されない問題を修正
- フリーズアローヒット時、先頭矢印は位置がステップゾーン上に来るが、  
それに伴って後続矢印の位置がずれてしまっていた
（フリーズアローの長さが補正されておらず、ずれた分だけ長く or 短くなっていた）。
=> [ver1.1.1] フリーズアローヒット時に後続矢印位置が補正されない問題を修正（ver1.0.2に対する修正）

js/danoni_main.js
- 個別加速(boost_data)のみ、データリセットされない問題を修正
- 上記の通り。  
boost_dataは1) 一時変数に格納された後、さらに2) g_workObj.boostDataに格納される。
Speed: OFFのときなどは 1)のタイミングで一旦一時変数を空にするが、
2)の処理前に 1)のデータが空であればスキップする処理を行っていたため、
2)にデータが残っていると、速度変化が残ってしまうことになっていた。
```
tmp2 = [300, 1.25];
tmp = []; // ここで一旦空になる
if(tmp != undefined && tmp.length >= 2){  // tmpが空なら素通りする処理
tmp2 = tmp.concat();
}
console.log(tmp2); // [300,1.25]が出力される
```
=> [ver1.1.2] 個別加速(boost_data)のみ、データリセットされない問題を修正

js/danoni_main.js
- Firefoxで楽曲が遅れて再生される問題を修正
- Firefoxの場合、即時に音楽再生を要求しても再生されないため。
- 読み込み中に音楽をミュート再生して、プレイ開始時にミュート解除を行う。
=> [ver1.1.3] Firefoxで楽曲が遅れて再生される問題を修正

js/danoni_main.js
1. 曲時間表示の位置を修正
1. 独自キーの変数の数値変換不具合の修正
1. 再生時間が10分以上の場合、表示が崩れるため
1. 独自キーの取り込み変数で、本来数値の部分が文字列に変換されていたため。
具体的には、posXを設定したときに下段の表示が出ない不具合がある。
=> [ver1.1.4] 曲時間表示位置の修正、独自キーの変数の数値変換不具合の修正

js/danoni_custom.js, js/danoni_custom2.js, js/danoni_main.js
1. タイトルにリロード(キャッシュ無視)ボタンを追加
1. danoni_custom.js にローカルバージョンを指定可能に変更
1. zIndex指定されていた個所を削除
1. F5キーをデフォルト無効化しており、その代替が必要なため。
キャッシュを削除してリロードするケースがありえるため。
1. danoni_custom.jsごとにバージョン管理が必要なケースがあるため。
1. 深度を意図的に変える処理を入れることで、
オブジェクトの前後関係がわかりにくくなるため、必要時以外、danoni_main.jsでは使用しない。
- Chromeではキャッシュ無視リロードは適用されない※が、
通常リロードボタンとして利用できるため、そのままとしておく。
※Chromeでは location.reload(true); は使用できない。
=> [ver1.2.0] タイトルにリロード(キャッシュ無視)ボタンを追加　他

js/danoni_main.js
1. 譜面名の文字サイズ調整
1. フリーズアローのヒット時のデフォルト色を変更
1. ゲージ設定に「Practice」を追加（ライフ制選択時）
1. キーコンフィグのカーソル移動をアニメーション化
1. 合作（持ち寄り等）で譜面名が長くなる場合があり、
譜面名の長さによりサイズを小さくできるようにするため。
1. 矢印のヒット数カウンタと同じ色のため、被って見えない場合があるため。
1. ライフ制ゲージの場合、途中終了するオプションしか存在しなかったため。
1. キーコンフィグのカーソル位置をより明確に見せるため。
=> [ver1.3.0] 譜面名の文字サイズ調整、フリーズアローの初期色変更　他

js/danoni_main.js
- ゲージ設定を2系統に分離
- ライフ制：「Borderless」「Light」「No Recovery」「SuddenDeath」
- ノルマ制：「Normal」「Easy」「Hard」「SuddenDeath」
- ゲームオーバー条件の変更
- ライフ制/ノルマ制で区切らず、クリアボーダー(g_workObj.lifeBorder)が0かどうかで判定
- 現状のFlash(ParaFla)版の実態に合わせた変更
- ライフ制・ノルマ制を示す変数表記が実態と乖離しているため、様子を見て直す予定
=> [ver1.5.0.pre] ゲージ設定の見直し

js/danoni_main.js
- SuddenDeathで1ミスFailedにならない問題を修正
- ノルマ制のSuddenDeathで、矢印数が1000を超える場合、1ミスFailedとならない。
- ノルマ制の場合、矢印数が1000を超えるとライフ減少量の変動で、減少量が1000未満となるため。
=> [ver1.5.1.pre] SuddenDeathで1ミスFailedにならない問題を修正

js/danoni_main.js
- ゲージ設定の名称変更（Borderless→Original）
- ゲージ設定「Light」の既定を見直し（ダメージ半減 → 回復量2倍）
- ノルマのないゲージ設定がすでに存在するため
- ゲージの軽さという意味に反した設定になっていたため（ダメージ半減→回復量倍増）
=> [ver1.6.0] ゲージ設定の名称変更（Borderless→Original）他

js/danoni_main.js
- base64エンコードしたmp3への対応
- 下記のようなjsファイルをmusicフォルダ(既定)に入れて、
musicUrlでjsファイルとして指定することで、
base64エンコードしたmp3が読み込まれるようになります。
```javascript
function musicInit(){
g_musicdata='base64エンコードされた音楽データ';
}
```
- mp3の利用条件によっては、直接mp3ファイルをファイルサーバへ
アップロードすることが禁止されている場合があるため、その対応
- 互換性のため、既存の機能もそのまま生かしています。
mp3ファイルとして上げる場合は、
.htaccessでmp3にアクセス制御を掛けるなどの措置を取ることを強く推奨します。
=> [ver1.7.0] オーディオエンコード実装（jsファイル指定）

js/danoni_main.js
- base64エンコードデータをtxtファイルでも取り込み可能に変更
- jsファイルの場合、簡易的なテキストエディタでは開けない場合があるため
=> [audio:0.1.1] base64エンコードデータをtxtファイルでも取り込み可能に変更

js/danoni_main.js
- base64エンコードしたデータについてtxtファイルでも取り込み可能に変更
- txtファイルの方がメモ帳などで開くことができ、手軽であるため
=> [ver1.7.1] base64エンコードしたデータについてtxtファイルでも取り込み可能に変更

js/danoni_main.js
- Tweet内容にPlaystyleを表示するように変更
- 設定画面で変更した内容が反映されず、どのようにプレイされたかがわからないため。
- キーコンフィグパターンは、別のキー割り当てに変更できてしまうため表示対象外とする。
- Displayオプションについては、Twitterの文字数制限の関係もあり、
Resultの表示情報では情報過多になると思われる。現時点では表示対象から見送る。
=> [ver1.8.0] Tweet内容にPlaystyleを表示するように変更

js/danoni_main.js
1. 歌詞表示の中央寄せ・右寄せ設定実装 (left, center, right)
1. 歌詞表示を2箇所→4箇所に拡大 (歌詞表示範囲：0～3)
1. 歌詞表示サイズ変更（横サイズにより自動変更）
1. 場面により、一時的に歌詞を中央寄せ・右寄せする需要があるため
1. 上記に伴い、左右寄せ同時に表示するケースが考えられるため
1. 中央寄せ時、そもそも歌詞表示が真ん中になっていなかったため
- 歌詞表示の拡張は互換性保持のため、0/2が上側、1/3が下側となる。
- そのまま表示すると表示が重なるため、
どちらか片方はあらかじめ[right]を指定して右寄せするなどの工夫が必要。
- キーワード[left][center][right]は、[fadein][fadeout]と同じ使い方。
=> [ver1.9.0] 歌詞機能強化

js/danoni_main.js
- endFrameを譜面ごとに設定できるように変更
- フェードアウトタイミングは譜面ごとに切り替えることができるが、
曲終了タイミングが譜面ごとに切り替えられないため
（元々は曲終了タイミングの調整機能としての利用だったが、
　リザルト画面移行＆曲流しっぱなしの機能が付加されたことで必要となった）
- 従来の使い方も利用可能（指定が無ければ、自動的に1譜面目の値を使用する）
=> [ver1.10.0] endFrameを譜面ごとに設定できるように変更（従来の使い方も使用可）

js/danoni_main.js
- 歌詞表示(追加分)についてフェードイン・アウトが利いていない問題を修正
- 歌詞表示の拡張をver1.9.0で行ったが、フェードイン・アウトの設定が反映されていなかったため
=> [ver1.10.1] 歌詞表示(追加分)についてフェードイン・アウトが利いていない問題を修正

js/danoni_custom.js, js/danoni_custom2.js, js/danoni_main.js
1. 判定処理のカスタム処理分離 (Fixes #151)
1. ライフ表示の小数点切り捨て表示 (issue #150 -2)
1. ボーダーラインのフォントサイズを指定 (issue #150 -3)
issue #150, #151 への対応
=> [ver1.11.0] 判定処理のカスタム処理分離 (issue #151)、ライフ表示の小数点切り捨て表示 (issue #150 の一部)

js/danoni_main.js
1. Adjustment値によって曲時間が変化する問題を修正
1. 曲時間に補正を掛ける変数名を変更（preblankFrame → preblankFrameForTime)
1. Adjustmentがマイナスのとき、曲時間にAdjustmentが加算され曲時間が短くなる現象が生じる。
Adjustmentが変わっても、曲時間には影響しないため本来は不要。
1. 譜面読込の箇所で同じ"preblankFrame"という変数名を使っており、
内容は（結果として）同じだが混同を避けるため。
=> [ver1.11.1] adjustment値によって曲時間が変化する問題を修正

js/danoni_main.js
1. タイトル以外の基本フォントの可変対応 ( fixed #124 )
1. 外部jsファイルのキャッシュ無視対応
1. Issue #124 への対応
1. 外部jsファイルのキャッシュが残ることがあるため、その対策
=> [ver1.12.0] タイトル以外の基本フォントの可変対応＆外部jsファイルのキャッシュ無視対応

js/danoni_main.js
1. 外部jsファイルの乱数制御方法変更（時刻制御）
1. Tweetスコアの表示変数変更
1. 外部jsファイルのキャッシュ無視対応
1. スコア表示にグローバル変数を使うことで、外部jsからの制御を容易にするため
=> [ver1.12.1] 外部jsファイルの乱数制御方法変更（時刻制御）、Tweetスコアの表示変数変更

js/danoni_main.js
- フルコンボ演出の表示切替を行えるように変更
- フルコンボ演出が不要な場合に対応するため
フルコンボ演出が消えるだけで判定表示は残るので、
その表示も消したい場合はカスタムjs側で設定が必要。
=> [ver1.15.0] フルコンボ演出の表示切替を行えるように変更

js/danoni_main.js
1. フェードアウト中にリザルト画面へ移行させた場合の音量不具合を修正
1. 初期ライフ量が整数値になるように修正
1. fadeFrameとendFrameを両方指定して、Volumeを100%より小さい値でプレイすると、
リザルト画面突入時のフェードアウトが通常より早く終了してしまう。
1. 改造の仕方により、初期ライフ量が無限小数表示されるケースがあるため。
=> [ver2.0.2] フェードアウト中にリザルト画面へ移行させた場合の音量不具合を修正　他

js/danoni_main.js
譜面ヘッダに|adjustment=-3|のように記述することでタイミングを調整できるようにしました。
移植時など、譜面完成後にタイミング調整が必要になった際、セーブデータや外部ツール無しで簡単にできるようにしたいです。
=> 譜面ヘッダでのタイミング調整を実装

js/danoni_main.js
- new Array() -> []
- array.concat() -> JSON.parse(JSON.stringify(array))
- getElementById()/getElementsByTagName() -> querySelector()/querySelectorAll()
- for (var ...) -> for (let ...)
- function(param ...) { ... } -> (param ...) => { ... }
ソースコードの見通し改善のためです。
- 配列初期化の記述が混在していたので統一しました。
- concat()は完全なディープコピーではないので※、代替しました。
- ※元配列の要素が配列やオブジェクトだった場合、それらはコピーされず、
元配列の要素と同一のものを参照するので、予想しない不具合の原因になります。
- var -> let を完全に置き換えます。
- 即時関数の記述が簡潔になります。
=> 一部記述の置き換え.

danoni/danoni2.html, js/danoni_main.js
外部譜面データ読み込み時の文字コードを指定できます。
~~~
<input type="hidden" name="externalDosCharset" id="externalDosCharset" value="Shift_JIS">
~~~
ダンおに譜面エディタはShift_JISで出力するものが多く、UTF-8等のページでは文字化けを起こすため。
loadScriptの引数名が命名ルールに合っていなかったので修正しています。
=> 外部譜面データ読み込み時の文字コード設定を追加

js/danoni_main.js
- フェードインのスライダー処理について、
アロー関数から従来の無名関数に戻します。
- この処理についてアロー関数に置き換えた場合に、
thisの参照先が固定されて値が取得できない問題があるため。
thisを使用している箇所はこの部分のみのため、他の影響はありません。
=> [ver2.5.1] フェードインのスライダー処理の不具合を修正

js/danoni_main.js
- PF/F/X以外のとき、リザルト画面に遷移できない不具合を修正
- var から letに変更した際、varの変数をループ外で使用していたため。
=> [ver2.5.2] リザルト画面に遷移できない不具合を修正

js/danoni_main.js
フェードインスライダーのイベント処理をアロー関数に戻し、this.valueの代わりにfadeinSlider.valueを参照するようにしました。
なるべく統一したほうがいいと思いました。
スタイルの問題なので不要なら取り下げます。
=> フェードインのスライダー処理にアロー関数を使うように変更

js/danoni_main.js
- フェードインのスライダー処理の記述方法変更
- ver2.5.2で一旦記述を戻したが、アロー関数による解消方法が判明したため。
=>  [ver2.5.3] フェードインのスライダー処理の記述方法変更

js/danoni_main.js
- ロード画面の実装 (Pull Request #190 も参照)
- base64読み込みの場合など、ロードが長い場合があり、
ロードの成功有無を確認するため。
- カスタムを考慮し、Pull Request #190 のデザインを少し変更しています。
（全体的に右下に配置）
=> [ver2.6.0] ロード画面の実装

js/danoni_main.js
開始位置、楽曲再生位置の設定の条件式を修正しました。
issue #176
他にもずれるケースがあるので完全解決ではないのですが、fadein 1%で大きくずれるのは直ったと思います。
=> フェードイン時間がblankFrameより小さい時にタイミングがずれる問題を修正

js/danoni_main.js
楽曲の再生にWeb Audio APIを使用するように変更しました。
ローカルでmp3直置きの場合には使用できないため、従来の方法で動作します。
issue #176
私の環境では[rainy beauty](http://sound.jp/suzume/rainybeauty/)でfadein 80%のとき12f程度ずれるのですが、[この修正を適用したもの](http://sound.jp/suzume/rainybeauty/webaudioapi.html)ではずれなくなりました。
厳密な検証は困難ですが、おそらく解決できたのではないかと思います。
=> 可能な場合にWebAudioAPIで楽曲を再生するように変更

js/danoni_main.js
同期の基準時間をメイン画面開始時から曲再生開始時に変更しました。
メイン画面開始後、曲再生開始前に処理落ちが発生すると譜面がずれる場合があります。
Playを押したあとウィンドウを最小化し、しばらくしてから復帰するとよく起こります。
issue #176 のたまにずれる問題の原因が処理落ちなら直るかもしれません。
=> 楽曲再生前に処理落ちすると譜面がずれる問題の修正

js/danoni_main.js
- Pull Request #197 を参照。
- ローカル環境かどうかの判定条件を統一（location.hrefを見るように）
- Firefoxかつローカル環境のとき、非推奨として表示するように変更。
- issue #176 関連の修正。
- Firefox65以降、ローカル環境のみ矢印が非表示となる問題があるため。
（解消可能だが、configファイルの変更が必要で注意を要するため）
=> [ver2.7.1] 楽曲再生前に処理落ちすると譜面がずれる問題の修正

js/danoni_main.js
- back_data利用時、フレーム計算が失敗しエラーとなる問題を修正
- 変数のスペルミスにより、エラーが発生している状態だったため。
=> [ver2.9.1] back_data利用時、フレーム計算が失敗しエラーとなる問題を修正

js/danoni_main.js
ローディングでdecodeAudioDataの完了を待つように変更しました。
WebAudioAPI使用時、decodeAudioData完了前にプレイ開始すると曲時間がNaNになり、リザルトへ移行しませんでした。
余分に待ち時間が発生するのがちょっと嫌な感じかもです…。
=> 急いでプレイ開始すると曲時間がNaNになる不具合の修正

js/danoni_main.js, js/danoni_setting.js
- Gauge設定についても、ver3.1.0同様の設定可否を指定できるように変更
- 設定不可時の表示オブジェクト名を設定可のものと同じ名前に揃える
- AutoPlayとセットで、ゲージ固定とするケースが考えられるため。
- 譜面名の変更でGauge設定が変わることがあるため、その対応。
他のオプションについても、同様の設定とした。
issue #212
=> [ver3.1.1] Gauge設定についても設定可否を指定できるように変更

js/danoni_main.js
ローディング画面でdecodeAudioDataを待たず、完了時にcanplaythroughを発生させるようにしました。
PR #208 の影響でローディング100%で数秒の待ち時間が発生しています。
=> ローディング100%で数秒止まる問題の修正

js/danoni_main.js
word_dataに不正なFrameやPositionが指定された場合に無視するようにしました。
issue #206 関連です。
word_dataにカンマが余分に入ってしまった場合などに画面が止まってしまいます。
差分の行数が多いですが、大部分はifの追加によるインデントです。
=> 不正な歌詞データで止まらないように修正

js/danoni_main.js
シャッフルグループの読み込み部分を修正しました。
2番目のキーのシャッフルグループがNaNになっています。
parseIntに引数が2つあることを知りませんでした…。
=> 追加キー定義でシャッフルグループが正しく読み込めない問題の修正

js/danoni_main.js
- Pull Request #221 を参照。
- 2番目のキーのシャッフルグループがNaNになるため。
=> [ver3.1.4] 追加キー定義でシャッフルグループが正しく読み込めない問題の修正

js/danoni_main.js
・タイトル画面の曲名にフォントを指定した場合に、読み込みのラグの関係で初回に指定したフォントが適用されない問題を修正しました。
・また、タイトル画面の曲名にかかるグラデーションを、譜面ヘッダで指定できるようにしました。
タイトル画面が一番見られるのは初回時、結果画面から2回目以降を見られることは少ないため。
曲名表示で出来る表現の幅を広げるため。
曲名フォントを初回から適用させるにあたり、従来の
「グラデーションを作成→createLabel関数内でfillTextメドットを用いて塗りつぶし」
ではなく、「createDivLabel関数でdiv要素を作成 → 変数を用いてcssを指定」
という形にして初回から反映させるようにしています。
また、cssによるグラデーション指定の実装にあたり、利便性のためいくつか例外処理を仕込んでいます。
まず基本の使用方法ですが、譜面ヘッダでは
|titlegrd=#DDDD99,#ffff00|
という表記で指定します。
3色以上のグラデーションも可能で
|titlegrd=#ff0000,#ff4500,#ffff00,#008000,#00ffff,#0000ff,#800080|
と指定すればタイトル文字が虹色になります。
今回cssグラデーションの実装にあたり使用したlinear-gradient()関数では
角度を省略した場合は上から下へとグラデーションがかかるため、
角度を指定せず色コードの書いた場合≒1文字目が 「#」 の場合は
先頭に「to right , 」を追加して、従来どおり左から右へグラデーションするようにしています。
グラデーションの方向を変えたい場合は
|titlegrd=to top right,#DDDD99,#ffff00|
|titlegrd=45deg,#DDDD99,#ffff00| …
=> 曲名のフォントを初回から反映するように・グラデーション設定の追加

js/danoni_main.js
- 矢印毎にスクロール情報を保持するように変更
- 具体的には、矢印毎の変数「boostSpd」にスクロール情報を含めるようにしました。
- 曲中でスクロール変化を行う場合でも、矢印の挙動がおかしくならないようにするため。
原理としては矢印の個別加速（矢印個別に速度成分を持つ）と同じです。
=> [ver3.4.0] 矢印毎にスクロール情報を保持するように変更

danoni/danoni1.html, js/danoni_main.js
1. タイトル文字（デフォルト）について、2行目を指定できるようにしました。
musicTitleの1つ目の変数について、&lt;br&gt;を指定することで2行目へ折り返しできます。
```
|musicTitle=Over the Rave<br>Original Mix,takoyaki_o,http://...|
```
2.  1行目、2行目の文字サイズを変更できるようにしました。
カンマ区切りで2行目のフォントサイズを指定します。
指定しない場合は1行目のフォントサイズに調整します。
```
|titlesize=40,20|
```
3. 1行目と2行目の間の数値を変更できるように、変数を設定しました。
指定しない場合は1行目のフォントサイズ＋10pxが指定されます。
```
|titlelineheight=50|
```
- 曲名が長い曲に対して、表示位置を調整しやすくするため。
結果画面も2行対応させています。
- これまでの line-heightの方法ではなく、display:flex （flexbox）を使用することで
中央寄せを実現しています。
この方法により、複数行の中央寄せが容易になります。
=> [titleView] タイトル文字の複数行対応

js/danoni_main.js
スコアがNaNになったときは0にするように変更しました。
総ノート数が0のときスコアが0/0でNaNになります。
=> 総ノート数が0のときスコアがNaNになる不具合の修正

danoni/danoni1.html, js/danoni_custom.js, js/danoni_main.js, js/danoni_setting.js
1.  設定ファイル(danoni_setting.js) のデフォルト値を指定
2.  カスタムデザインの設定をdanoni_setting.js へ移動
3.  カスタムデザインの設定の既定値を一律「false」に設定
1. danoni_setting.js をそのまま利用するとノルマ制ゲージになるため、
デフォルト値を指定しない場合、ライフ制になるように修正。  
2. danoni_custom.js で設定する内容ではないため。
3. ver1の互換設定として残していたが、デフォルトのまま使用する状況が増えてきたため。
=> [setting-default:0.1.0] 設定ファイルのデフォルト値を指定　他

js/danoni_main.js
- カスタムデザイン（背景）の使用について、メインとそれ以外で設定を分離
オリジナル背景を使用する場合、下記2か所の両方を`true`にする必要があります。
```javascript
g_headerObj.customBackUse = `false`;            // メイン画面以外の背景設定
g_headerObj.customBackMainUse = `false`;    // メイン画面の背景設定
```
- これまでは g_headerObj.customBackUse のみでどの画面でも
背景をオリジナルにするかどうかを指定することができましたが、
g_headerObj.customBackMainUse の扱いが曖昧で、わかりにくいため明確に分離します。
=> [ver3.7.0] カスタムデザイン（背景）の使用について、メインとそれ以外で設定を分離

js/danoni_main.js, js/sample/danoni_custom-003.js
- タイトル画面のカスタム部分の表示深度が手前になるように変更
- タイトル画面のデフォルトの曲名表示を利用すると、
カスタムボタンが手前に来ないため、ボタンを押すことができない仕様になっていた。
=> [ver3.8.0] カスタム部分の表示深度変更

js/danoni_main.js
Parafla版に存在したパターン付きのキー指定(9A-2など)のパターン部分(-2)を無視します
また、"9"や"15"が指定されたとき"9A"、"15A"として扱います
移植時にそのままだとプレイ不可になってしまうためです
=> パターン付きのキー指定(9A-2など)のパターン部分を無視するように変更

css/danoni_main.css, danoni/danoni1.html, js/danoni_main.js, js/sample/danoni_custom-003.js
1. パターン付きのキー指定を自動修正 ( #238 )
1. CSSモーションパターンを追加し、デフォルトの曲名表示に対してモーションを指定
1. ParaFlaソース時代に指定していた旧キー表記をそのまま移植すると、動作しない不具合があるため。
例）DPkey, 9key, TPkeyなど
2. CSSモーションをより使いやすくするため。
=> [ver3.9.0] パターン付きのキー数自動修正＆cssモーションパターン拡張

js/danoni_main.js
1. 複数譜面で歌詞表示（wordX_data）が無い場合、自動的に1譜面目のword_dataも見るように変更。
2. 速度変化、色変化、歌詞表示のセット毎改行区切りに対応
今後は以下の記述が可能です。（これまでの書き方も可能）
```
|color_data=
300,20,#ffff99
400,20,#99ffff
|
|word_data=
300,0,歌詞を表示
400,0,変更した歌詞を表示
500,0,
|
```
1. これまでは歌詞表示で複数譜面の場合、譜面毎にwordX_dataを作成する必要がありましたが、
実質同じものを表示するケースが多いため。
2. 歌詞表示（・色変化）では対応するエディターが無いため、
慣例的に1セット1行で改行区切りを行い、末尾にカンマをつけていることが多いです。
改行区切りかつ行末カンマを不要とすることで手打ちによる誤りを防ぎます。
=> [lyrics-auto] 歌詞表示の自動補完、セット毎の改行区切り対応

danoni/danoni1.html, js/danoni_main.js
1. 全ての矢印を判定させていれば、フェードイン位置によらずクリアと見做すように変更
2. 譜面ヘッダー「startFrame」について、譜面毎に設定できるように変更
※fadeFrame, endFrame同様に、譜面毎の設定が可能になります。
　startFrameを1つだけ指定した場合で複数譜面の場合は、
　これまで通り全譜面同じ値が適用されます。
```
|startFrame=0$2000|
```
1. 曲の事情でフェードイン開始する作品があるが、
これまでは曲の最初の部分を切り取るしか方法が無かったため。
2. fadeFrame, endFrameが譜面毎に設定できるのに対して、startFrameだけ全譜面共通だったため。
譜面により曲の開始位置が変わることもありうると考えたため。
=> [clear-condition:0.1.0] クリア条件を見直し、startFrameの機能拡張（譜面毎設定）

js/danoni_main.js
- 画像ファイル読込(preloadImages)時にjsエラーになる問題を修正
- preloadImages未使用時はエラーにならないが、
使用時にjsコードミスがあり、エラーとなってしまうため。
=> [ver3.11.1] 画像ファイル読込(preloadImages)時にjsエラーになる問題を修正

js/danoni_main.js, js/sample/danoni_custom-003.js
- 矢印色の基本値をキーコンフィグ画面から指定できるように変更（ColorType）。
作品固有（Default）／Type1／Type2の中から指定できる。
- Issue #182 関連。
デフォルト色を決めておくことで、特殊キーで色と配置の組み合わせを認識しやすくする。
=> [Feature/color-type] 矢印色の基本値を選択できるように変更

js/danoni_main.js
- ColorTypeがDefault以外の場合、Display:ColorをOFFに自動修正するよう変更
※Display:ColorをONに戻すこともできます。
- ColorTypeだけを変えるとcolor_dataやacolor_dataにより色変更が発生することがあるため。
=> [color-type:0.4.0] ColorTypeがDefault以外の場合、Display:ColorをOFFにするよう修正

js/danoni_main.js
譜面ヘッダでstartFrameが指定されなかったとき0にします
PR #242 以降、譜面ヘッダでstartFrameが指定されていないとプレイ開始時に止まってしまいます
=> startFrameが指定されないとき0にする

js/danoni_main.js
- startFrameが指定されないときにプレイ画面で止まる問題を修正 ( #250 )
- Pull Request #250 を参照。
Pull Request #242 以降、譜面ヘッダでstartFrameが指定されていないと
プレイ開始時に止まってしまうため。
=> [ver3.13.1] startFrameが指定されないときにプレイ画面で止まる問題を修正

js/danoni_main.js
- 譜面別の複数曲読込に対応しました。
譜面ヘッダーを拡張し、複数曲の読込に対応しています。
- musicTitle, musicUrlは曲毎に"$"区切り。
musicNoは譜面毎に"$"区切りで、どの曲を読み込むか指定します。
1つ目の曲＝0, 2つ目の曲＝1のように指定します。
下記の例では、1・2譜面目は1つ目の曲、3譜面目は2つ目の曲を読み込みます。
```
|musicTitle=曲名タイトル,アーティスト1,URL1,曲名1$曲名2,アーティスト2,URL2|
|musicUrl=music1.mp3$music2.mp3|
|musicNo=0$0$1|
```
- 1作品に複数曲（関連曲）を入れるケースがあるため。
将来的に選曲できるようにすることを見据え、曲切り替えできるようにします。
- この変更により、プリロード位置がタイトル前からプレイ前に変更となります。
=> [music-branch] 複数曲の読込に対応、譜面別に曲名を複数表示できるように変更

js/danoni_main.js
- back_dataでOpacityが機能していない問題を修正
- back_dataでX/Y座標の整数値制限を緩和（小数が使えるように）
- back_dataのOpacity項目にて小数値が許可されていなかったため、実質使用できていませんでした。
同様の修正を、過去バージョンにも適用します。（⇒ v1.15.3, v2.9.5, v3.13.2）
https://twitter.com/sssyouta/status/1121988665889050624
=> [ver4.0.1] back_dataでopacityが機能していない問題を修正、X/Y座標の整数値制限を緩和

js/danoni_main.js
- ローカルストレージ(作品別)に「Adjustment」「Volume」を追加します。
- Keyを作品URLとすることで、作品別の設定を実現します。
- 毎回プレイの度に設定するのが手間が掛かるため。
=> [storage-local] ローカルストレージ設定を追加

js/danoni_main.js
- マスク表示(mask_data)で、背景表示(back_data)より深度が大きいものを指定した場合、
プレイ時に止まる問題を修正。
- ライフ(数字)が常に前面に出ていた問題を修正。
- Javascriptエラーの解消のため。
- フレーム数表記はこれまで通り前面に来ます。
ローカル時のみ表示されるものなので、これ自体は仕様扱いとします。
=> [ver4.2.1] マスク設定によってはJSエラーになる問題を修正

js/danoni_main.js
- ハイスコアデータの初期化忘れを修正
- localStorageが設定されていない作品の場合、結果画面に移行後画面が止まる問題がありました。
=> [storage-local] ハイスコアデータの初期化忘れを修正

js/danoni_main.js
- スコア算出方法を独自に決めている場合、
ハイスコアの差分が正しく反映されない問題を修正しました。
- ライフの初期反映値がデフォルト値により異なっていた問題を修正しました。
- 上述の通り。
=> [storage-local] カスタムスコアの場合、差分が正しく反映されない問題を修正

js/danoni_main.js
- ローカルストレージ設定のクリアボタンを追加
厳密にはローカルストレージの削除ではなく、初期化処理を行います。
- 何らかの理由でローカルストレージの整理が必要な場合に、対処するボタンが無いため。
=> [storage-local] ローカルストレージ設定のクリアボタンを追加

js/danoni_main.js
g_volumeNumをLocalStorageから読み込んだVolume値に合わせるようにしました。
g_volumeNum=0(100%)で初期化されているため、保存されている値に関わらずボタンを押したときの挙動がVolume100%のときと同じになっています。
=> Volumeのカーソル位置をLocalStorageから読み込んだ値に合わせるように修正

js/danoni_main.js
1. Volumeのカーソル位置をLocalStorageから読み込んだ値に合わせるように修正 ( #270 )
1. startFrameがundefined以外でかつ、未指定の場合にエラーとなる問題を修正
1. Pull Request #270 を参照。
1. 譜面ヘッダーでstartFrameを複数指定した場合に、一方を無指定とする場合があり、
その際に曲開始できない問題がある。これを回避するため。
=> [ver4.4.1] Volumeのカーソル位置をLocalStorageから読み込んだ値に合わせるように修正 他

js/danoni_main.js
- (ドメイン別)キー毎にリバース、キーコンフィグを自動保存するように変更。
- キーコンフィグはキーの1パターンとして保存します。
プレイ開始直後に保存され、次回以降そのままの設定で開始できます。
- ただし、keyExtraListに登録されている特殊キーは自動保存されません。
- キーコンフィグ画面において、変更・自動保存色を設定。
- 変更したキーは黄色、自動保存したキーは薄青色で表示されます。
- キー毎にリバースやキーコンフィグを毎回設定するのが手間のため。
- 特殊キーについては、以下の理由で共通性を保証できないため、除外としました。
- 作品によってキーパターン数や仕様を作品により異なるように設定できる
- 既存キーの場合でも、設定を上書きして設定できる
- localStorageの制約により、ドメインを跨いだ共通設定はできません。
設定はドメイン毎に格納されます。
=> [storage-local] キー毎にリバース、キーコンフィグを自動保存するように変更

js/danoni_main.js
- ローカルストレージ保存有無ボタンの追加 ( #274 )
- キー別のローカルストレージ名を変更 ( #274 )
- キーコンフィグを変更した場合に、変更後のキーコンフィグが既存キーパターンに継承されてしまう問題を修正 ( #274, #275 )
Pull Request #274, #275を参照。
=> [ver4.6.0] localStorage保存有無ボタン追加、キー別のlocalStorage名を変更 他

js/danoni_main.js
- ローカルストレージとキーコンフィグで設定の際、
Shuffle配列がコピーされない可能性がある問題を修正
- 上述の通り
=> [ver4.6.1] ローカルストレージとキーコンフィグで設定の際、Shuffle配列がコピーされない可能性がある問題を修正

js/danoni_main.js
- 速度、ゲージ、リバース設定が初期化されることがある問題を修正
- ローカルストレージの更新を反映したタイミングでも
速度・ゲージ・リバース設定が初期化されるようになっていたため。
ローカルストレージの読込条件と初期化条件を分離しました。
=> [ver4.6.2] 速度、ゲージ、リバース設定が初期化されることがある問題を修正

js/danoni_main.js
- ライフ回復・ダメージ量計算でフリーズアローのカウントが間違っていたのを修正
- バグフィックスです。
フリーズアローが極端に大きい場合、ノルマ制の場合にノルマに達しないことがあります。
=> [ver4.8.1] ライフ回復・ダメージ量計算でフリーズアローのカウントが間違っていたのを修正

js/danoni_main.js
1. タイトル画面において、Maker, Artistが空のときに空ウィンドウを表示しないように修正
1. キーコンフィグ画面において、別キーモード時のメッセージを追加
1. MakerやArtistのサイトが無いなどの事情によりURLが無いケースがあるため。
1. 別キーモード時にデータ保存しないことを表示する方法が無かったため。
=> [ver4.9.0] Maker, Artistが空のときに空ウィンドウを表示しないように修正、別キーモード時のメッセージを追加

js/danoni_main.js
1. 曲中リトライ以外のタイミングで曲の再読み込みを行う仕様に変更 ( #288 )
1. ローディングバーについて、Canvas描画からdiv要素へ変更 ( #288 )
1. fadeFrameとendFrameが同時指定された場合、endFrameの時間を優先するように変更
1, 2 については Pull Request #288 を参照。
3. fadeFrameとendFrameが同時指定された場合、endFrameに420フレーム(7秒)が加算されるようになっており、直感的な指定で無かったため。
=> [ver4.10.0] 曲の読込タイミング変更　他

js/danoni_main.js
- fadeFrameとendFrameが同時指定された場合の条件を修正
- fadeFrameが指定ありで、かつendFrameが無指定のときにはendFrameを優先するよう
ver4.10.0 ( #289 )にて修正を行ったが、endFrameが配列長(で無指定)となっている場合に対処できていなかった。
=> [ver4.10.1] fadeFrameとendFrameが同時指定された場合の条件を修正

js/danoni_main.js
- 設定画面のスクリプトを整理
- ボタン部分を一部（譜面選択、フェードイン）を除きsetSetting関数に集約しました。
- 変数名の変更
- 上記の関数集約に伴い、変数名の一部を変更しています。
|変更前|変更後|
|----|----|
|g_stateObj.auto|g_stateObj.autoPlay|
|g_stateObj.lifeId|g_gaugeNum|
|g_stateObj.lifeSetName|g_stateObj.gauge|
- 設定画面で使用するボタンの操作を単純化し、将来的に拡張しやすくするため。
=> [0002/settings-func] 設定画面のスクリプトを整理

js/danoni_main.js
1. ゲージ設定の表示誤りを修正 (Issue #293 対応)
1. 音量表示のボタン制御が逆順だった問題を修正 (Issue #293 対応)
1. 音量0.25%の廃止
1, 2 Issue #293 対応。
3 音量0.25%の利用頻度が薄いと感じたため。
=> [ver5.0.1] ゲージ設定の表示誤り修正、音量表示のボタン制御誤りを修正

js/danoni_main.js
- LocalStorageのリバース設定が元に戻ってしまう問題を修正
- リバース設定を保存しているにも関わらず、タイトルを経由した場合に
リバース設定が元に戻ってしまうため。
今回の設定画面見直しに伴う不具合。
=> [ver5.0.3] LocalStorageのリバース設定が元に戻ってしまう問題を修正

danoni/danoni1.html, js/danoni_main.js
1. 譜面ヘッダー：titlegrdの複数行対応
1. titlegrdについて、他の変数と同じように0x, #始まりどちらでも指定できるように変更。
1. 曲名が2行にわたっている場合、
グラデーションをそれぞれの行で分けることができなかったため。
1. 他の変数の仕様とずれていたため、合わせる。
=> [titlegrd-double:0.1.0] 複数行グラデーション対応

js/danoni_main.js
- LocalStorageが設定されていないキーのときにReverseが初期化されない問題を修正
- 譜面によってキーが変わる場合に、保存済みのキーがReverse:ONの場合で
保存されていないキーが後続にある場合、Reverse:ONが元に戻らずにONのままとなってしまう。
この問題を修正する。
=> [ver5.1.1] LocalStorageが設定されていないキーのときにReverseが初期化されない問題を修正

js/danoni_main.js
1. back_data, mask_dataのフレームが小さすぎる場合に画面が止まる問題を修正
1. 既存キーの譜面から特殊キーへ移るときにリバースの設定がリセットされない問題を修正
1. 指定されたフレーム数が矢印到達フレームより小さい場合、
矢印到達フレームに合わせて自動調整処理を行うが、その際に配列を再生成している。
その配列を元の配列に再コピーする際、
`JSON.parse(JSON.stringfy(obj))`によるディープコピーを使用すると
未使用部分にもnullが入り、結果として処理が止まってしまう問題がある。
```javascirpt
g_scoreObj.maskData = JSON.parse(JSON.stringify(tmpObj.maskData)); // NG
g_scoreObj.maskData = tmpObj.maskData.concat(); // OK
```
2. 既存キーのリバース保存設定が「ON」の場合、
特殊キーのリバース設定が未設定であるために、リバース「ON」が引き継がれるようになっていた。
本来は「OFF」に戻すのが正しい。
- back_dataを使用しているバージョン（v2, v3, v4）に影響する。
v1は`JSON.parse(JSON.stringfy(obj))`を使用していないため対象外。
=> [ver5.2.1] back_data, mask_dataのフレームが小さすぎる場合に画面が止まる問題を修正　他

README.md, js/danoni_main.js
- titlesizeを64以上に指定すると文字欠けが起こる問題を修正
- titlesize未指定時に自動でMAX64pxになるように調整していたが、
titlesizeの指定・未指定によらず、titlelineheightに影響する仕様になっていた。
- izkdicさんgitterコメントより
>|titlesize=80|
のようにタイトルフォントサイズを大きな値にすると、spanの描画枠からはみ出て見切れてしまう現象が発生します。
>コードを見る限り、titlesizeの指定によってline-heightがtitlesize + 10に自動調整されてそうに見えるのですが、実際は|titlesize=80|と定義してもline-heightは74（デフォルトの最大サイズ64に10を加えたもの）のままになっています。)
- line-heightの仕様で、titlelineheightを極端に小さい値を指定した場合、
文字欠けが起こる可能性がある。
こちらについては、line-heightを使用しない方法を取ることで別途対応中（ver5.3.x以降予定）。
=> [ver5.2.2] titlesizeを64以上に指定すると文字欠けが起こる問題を修正

js/danoni_main.js
- 曲名タイトル（デフォルト）のline-heightの指定値が小さい場合に
文字欠けする問題を修正しました。Pull Request #308 の派生対応です。
- CSSのline-heightで対応するのではなく、相対位置を計算して表示する仕様に変更しました。
曲名の1行目(2行目を包含)を表示しているspanに対して、
CSSのline-height属性に1行目のフォントサイズ+10pxを設定。
曲名の1行目、2行目が中央に来るように、
1行目・2行目のフォントサイズに合わせてY座標を修正。
- CSSのline-heightを使用した場合、line-heightの小さい値に合わせて
フォントサイズの縦幅が決まってしまうため、文字欠けが発生してしまう。
- この変更により、一部作品にて譜面ヘッダーの「titlelineheight」の値の変更が
必要になる場合がある。
=> [titlepos-relative] 曲名タイトルのline-heightの指定値が小さい場合に文字欠けする問題を修正

css/danoni_main.css, js/danoni_main.js
- 歌詞フェードイン・アウトのCSS化対応 ( Issue #307 )
- 歌詞の複数階層化に対応 ( Issue #307 )
- 経緯は Issue #307 を参照。
CSS化することで歌詞表示系の構造を単純化し、多層構造に耐えられるようにする。
=> [lyrics-css] 歌詞フェードイン・アウトのCSS化対応、複数化対応

js/danoni_custom.js, js/danoni_custom2.js, js/danoni_main.js
- フリーズ開始判定が取れるようにカスタム関数を追加
- フレーム開始判定に対して、矢印同様の判定を行う作品が存在するため。
=> [frzstart-custom:0.1.0] フリーズ開始判定が取れるようにカスタム関数を追加

js/danoni_main.js
1. 歌詞フェードイン・アウトの時間を可変にできるようにしました。
word_dataの4番目の項目にて、フレーム数で指定します。
（word_dataを行毎の改行区切りにしないと対応しません）
```
|word_data=
3000,0,[fadein],45
3000,0,歌詞テスト
|
```
2. 歌詞データのフェードイン・アウトのデフォルト時間を30→60Frameに変更しました。
1.  歌詞フェードイン・アウトで状況によりフェード時間を変える場合に対応するため。
2.  CSSアニメーションに変わったことにより、
従来のフェード時間から感覚的に早まったため、60Frame(1秒)に変更する。
=> [wordfade-duration] 歌詞フェードイン・アウトの時間を可変対応、デフォルトの時間を60Frameに変更

js/danoni_custom.js, js/danoni_custom2.js, js/danoni_main.js
1. 歌詞フェードイン・アウトの時間の可変対応 ( #315 )
2. 歌詞データのフェードイン・アウトのデフォルト時間を30→60Frameに変更 ( #315 )
3. 譜面変更ボタン(setDifficulty)に対してカスタム関数を追加
- customSetDifficulty(_initFlg, _canLoadDifInfoFlg),  customSetDifficulty2(_initFlg, _canLoadDifInfoFlg)にて定義することで対応できます。
1, 2 Pull Request #315 を参照。
3 譜面変更に関して特殊設定が必要なパターンに対応するため。
=> [ver5.6.0] 歌詞フェードイン・アウトの時間の可変対応 他

js/danoni_custom.js, js/danoni_custom2.js, js/danoni_main.js
1. 譜面変更ボタン(setDifficulty)のカスタム関数で条件により通過できない不具合を修正
2. フリーズ開始判定用カスタム処理の見直しのため、一時的にカスタム処理を削除
1. 上述の通り。
2. 関数内容の見直し（パラメータ不足）のため、一時削除します。
=> [ver5.6.1] 譜面変更ボタン(setDifficulty)のカスタム関数で条件により通過できない不具合を修正　他

js/danoni_main.js
- 判定基準位置が1フレーム手前になっている問題を修正。
矢印・フリーズアロー生成時の矢印保持時間を1フレーム増やすように修正しました。
- 上述の通り。
- v1～v4の過去バージョンについても同様の修正を行っています。
=> [ver5.6.2] 判定位置の調整

js/danoni_main.js
- ver5.6.2にて判定位置の調整を行ったが、それにより譜面データが全体的に-1される事象が発生する。
このための補正をblankFrameおよびblankFrameDefに対して適用する。
- 上述の通り。
v1～v4に対しても同様の修正を行う。
=> [ver5.6.3] 判定位置の調整に伴うblankFrameの補正値追加

js/danoni_main.js
- #319 の変更を取り消します。
- Adjustment方向が逆だったことと、
v4以降はAdjustmentが保存されるため、ソースの煩雑性を避けて取り止めとしました。
=> Revert #319

js/danoni_main.js
- 歌詞表示のフェードイン・アウトのモーション方法を変更しました。
CSSの`animation-timing-function`を`linear`に変更し、フェード時間を30Frameにしました。
- CSSの`animation-timing-function`は未指定の場合`ease`となり、
想定より早くフェードされるように見える。
従来の歌詞表示フェードはopacityを単純減算させるように作っていたため、
挙動としては`animation-timing-function`を`linear`にした方が良い。
=> [fix-lyricsfade:0.1.0] 歌詞表示のフェードイン・アウトのモーションをlinearに変更

js/danoni_main.js
- 同時押しの数によって矢印タイミングがずれる問題を修正しました。
- 到達フレーム数を表す `g_workObj.arrivalFrame[g_scoreObj.frameNum]` が同時押し数が増えるごとに
インクリメントされる仕様になっていた。
正しくは同時押し数に関わらず 
`g_workObj.arrivalFrame[g_scoreObj.frameNum] + 1`とするのが正しい。
=> [ver5.6.6] 同時押しの数によって矢印タイミングがずれる問題を修正

js/danoni_main.js, js/danoni_setting.js
・フリーズ始点での通常判定の追加(dotさんソース方式)
・演出用のactualFrame変数をmain.jsに格納
・通常矢印の移動処理にて、Autoの処理とウワァン判定の処理を分離
・フリーズ始点での通常判定の追加(dotさんソース方式)
主に蒼宮あいすさんの作品用に。
Gitterで提案されたように譜面ヘッダー内にて
|frzStartjdgUse=true|
と追加することでフリーズ始点でも通常判定が行われます。
・演出用のactualFrame変数をmain.jsに格納
元々はティックルさんのdanoniplus-custom
( https://github.com/cwtickle/danoniplus-custom )
内の演出サンプル用custom.jsに書かれていたものです。
演出作品で個別のcustom.jsを作るたびに、actualFrameを毎回定義するのは
無駄が多いだろうという意見をいただいたので
本体のmain.jsに格納しました。
また、合わせて演出サンプル用custom.jsでは
「オプション画面でのAdjustment( g_stateObj.adjustment )」は計算されているが
「譜面ヘッダーで定義されるAdjustment( g_headerObj.adjustment )」が計算されておらず
演出のタイミングがズレる場合があったので移植と同時に計算を追加しています。
・通常矢印の移動処理にて、Autoのジャスト判定処理と見逃しウワァン判定の処理を分離
かなり特殊な事例ですが、演出作品で曲中にAuto処理をOnOffする作品の時に
( 例：WALL BATTLE / ルゼ http://mfv2.sakura.ne.jp/do/_cumulo/?id=wallbattle  ) …
=> フリーズ始点での通常判定の追加(dotさんソース方式)、演出用のactualFrame変数をmain.jsに格納

js/danoni_custom.js, js/danoni_custom2.js, js/danoni_main.js
1. フリーズ開始判定の実装 ( #324 )
1. 見かけフレーム数(g_workObj.baseFrame)の実装 ( #324 )
1. デフォルト背景画像描画部分のコード整理 ( #325 )
1. フリーズ開始判定する作品に対応するため。
1. 演出用作品で、見かけのフレーム数をベースにアクションを起こる処理が必要なため。
これまでcustom側で実装していた部分を、main側に寄せる。
1. 繰り返しコード除去のため。
=> [ver5.7.0] フリーズ開始判定、見かけフレーム数の実装

js/danoni_main.js
- 譜面データのURIデコードに対応しました
たとえば「%26」が「&」に変換されます。
HTML側に以下を追加することで有効になります。
```
<input type="hidden" name="enableDecodeURI" id="enableDecodeURI" value="true">
```
- 譜面データの&区切り可否を切り替え可能にしました
単に「&」が使えるほか、「&amp;comma;」などの文字参照が使えるようになります。
(URIデコードを使って「%26comma;」でも出来ますが)
HTML側に以下を追加することで無効化できます。
```
<input type="hidden" name="enableAmpersandSplit" id="enableAmpersandSplit" value="false">
```
- 外部dos読み込み処理中の&を|に置き換えるreplaceを削除しました
記述が間違っていて1個しか置き換えないのと、dosConvert側に正しい処理があります
- setValをbooleanに対応しました
上記設定のtrue/false読み込みのためです
gitterでの要望より。
=> 譜面データのURIデコード対応 ほか

js/danoni_main.js
1. 独自キーの2段目のpos最終番号を指定できるように変更しました。
下記のように、divXの2番目要素を指定します。(Xはキー名)
```
|divX=7,14|
```
2. KeyConfigがReplacedの場合で、代替キーが2段目にしかない場合に
カーソルがおかしくなる問題を修正しました。
3. コードの整理
1. 独自キーで下段右側にスペースのあるキーが作成できなかったため。
2. 上述の通り。
3. ver5.8.1が暫定修正のため、一部オンコードになっていた箇所を修正しました。
=> [key-div2nd] 独自キーの2段目のpos最終番号を指定できるように変更

js/danoni_main.js
- フリーズアローの許容フレームを譜面ヘッダーから指定できるように変更しました。
譜面ヘッダーより変更できます。単位はフレーム数。
```
|frzAttempt=7|
```
- Gitter要望より。
=> [flex-frzAttempt] フリーズアローの許容フレームを譜面ヘッダーから指定できるように変更

js/danoni_main.js
- プレイ中のショートカットキーを設定できるように変更しました。
譜面ヘッダーより設定できます。キーコード（数字）を指定します。
```
|keyRetry=16|            // リトライに対応するキーコード
|keyTitleBack=46|        // タイトルバックに対応するキーコード
```
- Gitter要望より。
=> [let-shortcut] プレイ中のショートカットキーを設定できるように変更

js/danoni_main.js
1.  フリーズアローの許容フレームを譜面ヘッダーから指定できるように変更 ( #333 )
1.  プレイ中のショートカットキーを設定できるように変更 ( #334 )
- Gitter要望より。詳細はPull Requestに記載しています。
=>  [ver5.10.0] フリーズアロー許容フレーム数、タイトルバック・リトライキーの変更を譜面ヘッダーより制御する設定を追加

danoni/danoni1.html, js/danoni_main.js
- キー毎にタイトルバック、リトライ設定を行えるように
あらかじめmain側でキー毎の変数を設定しました。
```javascript
g_keyObj.keyRetry8_0 = 9;
g_keyObj.keyTitleBack8_0 = 46;
```
特殊キーの場合は譜面ヘッダーで設定できます。
```
|keyRetry6=9|
```
- customjsで設定しなくても済むようにしました。
=> [key-shortcut] キー毎にタイトルバック、リトライ設定を行えるように変更

js/danoni_main.js
・通常矢印の内側を塗りつぶす機能
背景や演出付きの作品で、背景で矢印が見えづらくなる場合があったため
譜面ヘッダーにて
|ShadowColor=#000000|
という感じでカラーコードで指定できます。(0xから始まるカラーコードにも対応済み)
また、例外処理を1つだけ仕込んであり
|ShadowColor=Default|
と指定することでベースの矢印色と同色にすることも出来ます。
あと、矢印の縦連やおにぎり等AAの視認性の観点から
塗りつぶし部分の透明度を0.5で指定してあります。
=> 通常矢印の内側を塗りつぶす機能

js/danoni_main.js
- フリーズアローのみの譜面がプレイできない問題を修正
- 矢印毎の譜面格納ループ条件が矢印のレーン数となっているため、
矢印が存在しない場合にはレーン数が０となっていた。
このためフリーズアローのみの譜面の場合、譜面格納が行われず、
譜面がプレイできない状況になっていた。
=> [fix-frzonly:0.1.0] フリーズアローのみの譜面がプレイできない問題を修正

js/danoni_custom.js, js/danoni_custom2.js, js/danoni_main.js
1. ダミー矢印・フリーズアローに対してS-Random/S-Random+を実装
※ただし、通常矢印/フリーズアローとダミー矢印/フリーズアロー間の重なりは考慮されません。
2. ダミーフリーズアローの判定用カスタム関数を実装
3. コード整理
1. ダミー矢印・フリーズアローに対するShaffle対応が不十分だったため。
2. ダミー矢印のみ判定用カスタム関数が存在していたため。
3. 矢印・フリーズアロー消去用関数をほぼ1か所に統一し、コードの散らばりを抑止する。
=> [0003-dummy-arrows] ダミー矢印・フリーズアローのS-Random実装、カスタム関数拡張

js/danoni_main.js
判定ごとの配点`g_pointAllocation`と最大スコア`g_maxScore`をスコア計算に使用するようにしました。
配点や最大スコアをcustom.jsで設定できるようになります。
例として、MFV2さんによるparafla版と同等の設定にするにはcustomTitleInit内で次のようにします。
```
g_pointAllocation.ii = 10;
g_pointAllocation.shakin = 6;
g_pointAllocation.matari = 3;
g_pointAllocation.kita = 10;
g_pointAllocation.sfsf = 5;
g_pointAllocation.maxCombo = 0;
g_pointAllocation.fmaxCombo = 0;
g_maxScore = 100000;
```
=> 配点と最大スコアの変数化

js/danoni_main.js
1. 通常キー（キーコンフィグ保存済み）が1譜面目、独自キーが2譜面目の場合に
譜面の読み込みやキーコンフィグの設定ができない問題を修正しました。
2. `danoni_setting.js` の `g_presetGaugeCustom` において0が指定できない問題を修正しました。
1. 通常キーでキーコンフィグ設定済みの場合、キーパターンは`-1`に設定されます。
独自キーの場合、譜面変更時にキーパターンを初期化する処理が抜けており、
独自キーにキーパターン`-1`が定義されていなかったため、エラーとなっていました。
2. `g_presetGaugeCustom` の存在条件に厳密等価演算子を使用していなかったため、
0と空白が同一と見做され、適用できない状態になっていました。
- ver4, 5の両方に影響する不具合です。
=> [fix-gauge-custom:0.1.0] 独自キーが2譜面目以降にある場合に読み込みできない場合がある問題を修正　他

js/danoni_custom.js, js/danoni_custom2.js, js/danoni_main.js
1. メイン画面で使用する`back_data`、`mask_data`に対して
リバース用の背景・マスクモーションを実装しました。
背景用が`backRev_data`、マスク用が`maskRev_data`です。
使い方は`back_data`、`mask_data`と同じです。
未指定の場合、`back_data`、`mask_data`がリバース時でも表示されます。
2. リザルト画面に対して、リザルトモーションを実装しました。
背景用の`backresult_data`とマスク用の`maskresult_data`があります。
使い方は`backtitle_data`と同じです。
- Gitter要望より。
=> [0024-sprite-data] リバース用背景・マスクモーション、リザルトモーションの実装

js/danoni_main.js
1. masktitle_dataの実装
2. masktitle_data, maskresult_dataについてボタンの前面に出るように修正。
その代わりにボタンが押せなくなる対策として、以下の変数を追加。
```
|masktitleButton=false|
|maskresultButton=false|
```
それぞれ、タイトル・リザルトでボタンをマスクするか（無効にするか）を設定できます。
デフォルトは`false`(マスクしない・有効)。
1, 2　マスクが不十分で、画面全体をマスクできなかったため。
=> [0026-sprite-data2] masktitle_dataの実装

js/danoni_main.js
1. フェードイン時に個別加速が掛からない問題を修正
2. 譜面ヘッダー：frzAttemptが掛からない問題を修正
1. Gitter以下コメントより。
> izkdic @vdos2643_twitter 16:24
> ver6.5.0で、個別加速（boost_data）が1回以上適用された後の地点からFadeinで始めると、以降の個別加速が反映されないようです。
> （|boost_data=1000,2,1500,1,2000,2,2500,1|となっているときに、500Fから始めた場合は問題ないのですが、たとえば1600Fから始めると2000Fの2倍速が反映されない）
2. Gitterコメントより。
keyUpFrameが文字列として扱われていたため。
=> [fix-boost-frzAttempt:0.1.0] フェードイン時に個別加速が掛からない問題を修正　他

js/danoni_main.js
- 個別色変化（フリーズアローヒット時）のタイミングを変更し、
この場合のみ、個別色変化のための逆算をしないように変更。
- Issue #354 より。
- 個別色変化（フリーズアローヒット時）を設定する場合、ステップゾーン到達時を基準にすれば良くなりました。
ただし押したタイミングにより、ステップゾーン到達時より手前でフリーズアローがヒット中になることがあります。
実際に設定する場合は、キターの判定領域分だけ値を小さくすることを推奨します。
=> [0031-frzhit-colors] 個別色変化（フリーズアローヒット時）のタイミング変更

js/danoni_main.js
- word_dataの3番目の要素を省略できるように変更（4番目未指定の場合）
- word_dataが改行区切り可となった関係で、
3番目の要素を省略すると`undefined`という文字が表示されるようになっていました。
=> [0033-fix-lyrics] word_dataの3番目の要素を省略できるように変更（4番目未指定の場合）

js/danoni_main.js
- 矢印・フリーズアローのCSSモーションがデフォルトOFFになっていた問題を修正
- 変数名の初期化誤りによるものです。
=> [ver7.1.1] 矢印・フリーズアローのCSSモーションがデフォルトOFFになっていた問題を修正

danoni/danoni1.html, js/danoni_main.js
- キーコンフィグ画面のボタン配置を見直しました。
以下の変更を行っています。
1. キーコンフィグ画面におけるボタンアニメーションを廃止
2. キーコンフィグ画面のボタン配置を見直し
- 設定画面でKeyConfigボタンがあった場所（中央下段）に戻るボタンを配置
- PtnChangeボタンをキーコンフィグパターンを変更する2つのボタンに分割し、左右上段に配置。片側は逆回しボタン。
- Resetボタンを左下段へ移動
3. 現在選択しているキーコンフィグパターンと、別キーモード状態を表示するように変更。以下のように表示します。
- KeyPattern : Self     // 保存したキーコンフィグ
- KeyPattern : 1
- KeyPattern : 2
- KeyPattern : 3(9B)   // 別キー: 9Bモード
- Gittter要望より。
=> [0034-button-ui(2)] キーコンフィグ画面のボタン配置見直し

js/danoni_main.js
- ver7.1.0 ( #369 )にて、個別色変化（フリーズアローヒット時）のタイミング変更を実装したが、
過去作品においてはタイミングを修正しなければならず、数が多い場合手間となる。
これを省略するため、以下の設定を譜面ヘッダーに入れることで
従来の個別色変化（フリーズアローヒット時）を実装する。
```
|colorDataType=v6|
```
- 上述の通り。
=> [0035-color-legacy] 色変化の過去バージョン互換対応

js/danoni_main.js
URLのクエリから譜面番号を取得し、オプション画面にて該当の譜面を選択状態にする機能を追加しました
難易度表や多鍵DBなど、譜面単位でリンクを貼りたいときの使用を想定しています
`http://cw7.sakura.ne.jp/danoni/2013/0237_Cllema.html?score_id=1`
のように指定すると、オプション画面で2譜面目の「7key / Rhythm」が選択された状態になります
指定されていない場合や該当する譜面がない場合は、通常通り1譜面目が選択されます
=> デフォルトで選択状態にする譜面をURLで指定できる機能を実装

js/danoni_main.js
1. キーコンフィグ画面のボタン配置見直し ( #377 )
2. 色変化の過去バージョン互換対応 ( #379 )
3. デフォルトで選択状態にする譜面をURLで指定できる機能を実装 ( #378 )
- それぞれのPull Request詳細を参照。
3.について、クエリ文字列を`score_id`から`scoreId`に変更しています。
=> [ver7.3.0] ボタンUI見直し、色変化の互換設定　他

js/danoni_main.js
- Display画面へ遷移したときにボタンアニメーションが解除されない問題を修正
- Setting -> Display -> Settingと遷移した場合にアニメーションが残ってしまう。
=> [0034-button-ui(3)] Display画面へ遷移したときにボタンアニメーションが解除されない問題を修正

js/danoni_main.js
1. リザルト画面へ移行後に楽曲フェードアウトできるように変更
2. リザルト画面で、フェードアウト中にTitleBack/Retryするとフェードアウト状態が引き継がれてしまう問題を修正
いずれもGitter要望・報告より。
1. リザルト画面へ移行した後からフェードアウト開始する設定に対応するため。
2. 通常、リザルト画面でフェードアウト状態が残っていると、
`g_timeoutEvtId`がフレーム毎に更新され（フェードアウト処理を行い）、音量が０になったときにクリアされる。
途中でイベントが入った場合には`g_timeoutEvtId`がクリアされずにタイトル・メイン画面へ移行するため、最初からフェードアウトが始まってしまう現象が発生する。
2. については過去バージョンへの影響が考えられるため、修正を検討する。
=> [result-fadeout:0.1.0] リザルト画面へ移行後に楽曲フェードアウトできるように変更

SECURITY.md, js/danoni_main.js
1. カラーコードの左パディング機能を実装 ( #383 )
2. F5キーのキーブロックを解除 ( #383 )
3. リザルト画面へ移行後に楽曲フェードアウトできるように変更 ( #384 )
4. リザルト画面で、フェードアウト中にTitleBack/Retryするとフェードアウト状態が引き継がれてしまう問題を修正 ( #384 )
- Pull Request #383, #384を参照。
=> [ver7.4.0] カラーコードの左パディング機能を実装 他

js/danoni_main.js
- 譜面ヘッダーのpreloadImagesにおいて、限定用途で複数ファイルをまとめて記述できるようにしました。
例えば以下のように記述すると、file1.png～file4.pngまでを読み込むようになります。
```
|preloadImages=file*.png@4|
```
- アスタリスク（*）の部分が4桁の連番に置き換わり、
アットマーク（@）以後の数字が連番の上限値を表します。
- 連番は1からカウントします。
- また、開始・終了点を指定して、範囲指定することもできます。
連番の桁数は、大きい方に合わせて0で左詰めされます。
意図的に0を入れて、桁数を増やすこともできます。
```
|preloadImages=file*.png@2-9|   // -> file2.png ~ file9.png
|preloadImages=file*.png@5-10|     // -> file05.png ~ file10.png
|preloadImages=file*.png@01-08|     // -> file01.png ~ file08.png
```
- 画像ファイルが多い場合の手間を軽減するため。
- jsの制約上、今のところ動的にできるのは数字だけです。
- アスタリスクを複数指定することはできません。
=> [0039-preload-numbering] 譜面ヘッダー:preloadImagesの複数まとめ記述の実装

js/danoni_main.js
- 譜面読込画面に入ったときに譜面データを再読込できるように変更しました。
譜面データの読込タイミングが初回のみだったものが、リトライ時も含め毎回読込に変わります。
ただし、譜面ヘッダーは置き換えません。
- ローカルやリモートで譜面再読込の際の手間を軽減するため。
- 読込画面に入ったタイミングで譜面データを再度読み込みます。
具体的には、`g_rootObj`の中身が読込画面に入るたびに更新されます。
譜面ヘッダー群 `g_headerObj` やキーオブジェクト群 `g_keyObj`などは更新されません。
もし、`g_rootObj`に対して後付けで更新を掛ける操作を入れている場合、
修正が必要となる可能性があります。
=> [0044-flexible-reload] 譜面読込画面に入ったときに譜面データを再読込できるように変更

js/danoni_main.js
1. 歌詞表示・背景/マスクモーションにおいて同一フレームの同時描画に対応しました。
2. また、背景/マスクモーションにおいて、深度に「ALL」を指定することで、
全てのオブジェクトを一斉クリアできるようになりました。（歌詞表示は未対応）
例）3200,ALL,
1. これまでは同一フレームの指定時はフレームを1フレームずつずらして描画していたため、
表示対象が多い場合、表示遅延が発生していました。
2. 背景/マスクモーションにおいてオブジェクトが多くなりやすい傾向にあったため。
1. 同時描画に対応しましたが、極端に多い場合は処理落ちが懸念されます。
利用側である程度、分散しても良い部分は自主的に分散するなどの工夫が必要となります。
=> [0045-back-allclear] 歌詞表示・背景/マスクモーションにおいて同一フレームの同時描画に対応

js/danoni_main.js
1. 譜面読込画面に入ったときに譜面データを再読込できるように変更 ( #397 )
2. 歌詞表示・背景/マスクモーションにおいて同一フレームの同時描画に対応 ( #398 )
3. 背景/マスクモーションにおいて、深度に「ALL」を指定することで、
全てのオブジェクトを一斉クリアできるように対応 ( #398 )
- Pull Request #397, #398 を参照。
=> [ver7.7.0] 読込画面移動時に譜面を再読込する仕様に変更　他

js/danoni_main.js
1. 楽曲の終了判定タイミングを秒単位からフレーム単位に変更。
合わせて、Adjustment値を楽曲終了位置に加算するように変更。
2. リザルトモーションをDisplay:Backgroundと連動してON/OFFする仕様に変更。
- 従来のように連動させない場合は、譜面ヘッダー:resultMotionSetをfalseにすることで実現可能。
3. リザルトモーションを譜面データ同様に、毎回読み直す仕様に変更（動的に変わるのは外部譜面ファイル（externalDos）が指定された場合のみ）。
4. リザルトモーションで0フレームを指定した場合に、結果画面が一瞬表示される事象を修正。
5. その他、結果画面の処理を一部見直し。
Twitter要望より。
メイン画面のマスク・背景とリザルトモーションが連動するケースが考えられるため。
=> [0048-animation-result] リザルトモーション周りの仕様変更

js/danoni_main.js
- 位置調整によらず見た目の曲時間を表示するように変更。
あくまで見た目だけで、実際には設定画面のAdjustmentが補正されるようになっています。
- 実際の曲時間に対して、Adjustmentの値により変動することがあるため。
=> [0049-nominal-time] 位置調整によらず見た目の曲時間を表示するように変更

js/danoni_main.js
- キーコンフィグの別パターンが選択できない問題を修正。
- ver7.7.0より、譜面を毎回再読込する仕様に変更したが、
その際にキーコンフィグパターンも初期化していたため、
別パターンでプレイできない状態になっていた。
- ver7.7.0以降で発生します。
=> [0050-reset-keypattern] キーコンフィグの別パターンが選択できない問題を修正

js/danoni_main.js
- クリア失敗時のリザルトモーションを実装。
以下のように使い分けます。
|名称|用途|
|----|----|
|back(mask)result_data|クリア成功時のリザルトモーション<br>※失敗時のモーションが指定されていない場合も適用されます。|
|back(mask)failedS_data|途中終了時のリザルトモーション|
|back(mask)failedB_data|ノルマ制ゲージで、ノルマに達しなかった場合のリザルトモーション|
- Twitter要望より。
=> [0052-back-failed] クリア失敗時のリザルトモーションを実装

js/danoni_main.js
- 速度変化・色変化・歌詞表示のコメント行にカンマを入れたときの不具合を修正
- コメント行中のカンマが区切り文字として見做されていたため。
今後は2番目の要素がハイフンだった時点で、読み飛ばしを行う。
=> [0053-back-comment] コメント行にカンマを入れたときの不具合を修正

danoni/danoni1.html, js/danoni_main.js
1. リザルトモーションを譜面別に区別できるように変更
- リザルトモーションを譜面別に拡張しました。
|画面|背景用モーション|マスク用モーション|
|リザルト(クリア時)|backresult_data<br>backresult2_data<br>...|maskresult_data<br>maskresult2_data<br>...|
|リザルト(途中終了時)|backfailedS_data<br>backfailedS2_data<br>...|maskfailedS_data<br>maskfailedS2_data<br>...|
|リザルト(ノルマ失敗時)|backfailedB_data<br>backfailedB2_data<br>...|maskfailedB_data<br>maskfailedB2_data<br>...|
指定が無い場合、例えば 2譜面目のリザルト(ノルマ失敗時) については以下の順で適用されます。
|適用順|適用モーション|意味|
|1|backfailedB2_data|リザルト(ノルマ失敗時)の２譜面目|
|2|backfailedB_data|リザルト(ノルマ失敗時)の１譜面目|
|3|backresult2_data|リザルト(クリア時)の２譜面目|
|4|backresult_data|リザルト(クリア時)の１譜面目|
2. タイトル・リザルトモーションの音楽同期に対応
- メイン画面と同様に、フレーム毎の処理時間を考慮して時間計算するようになりました。
1. リザルトモーションの場合、譜面本体の背景・マスクモーションと一体で動くことが多いと思われるため。
2. リザルトモーションの範囲に音楽が流れ込むケースが発生しているため。 …
=> [0057-result-motion-div] リザルトモーションの複数譜対応・音楽同期対応

js/danoni_main.js
1.  楽曲のフェードアウト長を指定できるように変更
- 譜面ヘッダーの`fadeFrame`を拡張し、楽曲のフェードアウト長を指定できるようになりました。
カンマで区切った2要素目にフェードアウト長（フレーム数）を指定します。
指定しない場合はこれまで通り、420フレーム（7秒）がフェードアウト長です。
```
|fadeFrame=7200,700$7200|
```
- Issue #413  より。
=> [0055-fadeout-length] 楽曲のフェードアウト長の変更 #413

js/danoni_main.js
- リザルト画面突入後もフェードアウト長を考慮して曲終了するように変更
- 先のPull Request #420 の修正漏れ。
=> [0055-fadeout-length(2)] リザルト画面突入後もフェードアウト長を考慮して曲終了するように変更

js/danoni_main.js
1. 速度変化表記 (speed_data/change)の統一
- キーの種類によらず、`speed_data`, `speed_change` のどちらでも途中変速として認識するようになりました。
1. Issue #416 より。
=> [0056-speed-common] 速度変化表記 (speed_data/change)の統一

js/danoni_main.js
- ステップゾーン(下)位置を変更できる設定を追加
指定した分だけ下側のステップゾーンだけ下がり（上がり）ます。
```
|stepYR=-100|
```
1. ステップゾーン(下)のエリアの確保が必要なケースがたまにあるため。
- Y座標に沿って変わります。
数字はプラスにすると下がり、マイナスにすると上がります。
大きくすると画面から外れるのでご注意ください。
=> [0054-object-pos-change] ステップゾーン(下)位置を変更できる設定を追加

danoni/danoni1.html, js/danoni_main.js
1. タイトル／リザルトモーションの音楽同期対応 ( PR #419, #423 )
2. リザルトモーションを譜面別に作成できるように対応 ( PR #419 )
3. 楽曲のフェードアウト長を指定できるように変更 ( Issue #413, PR #420 )
4. 速度変化表記 (speed_data/change)の統一 ( Issue #416, PR #421 )
5. ステップゾーン(下)位置を変更できる設定を追加 ( PR #424 )
PR #419, #420, #421, #424 を参照。
=> [ver8.0.0] リザルトモーションの音楽同期対応、楽曲フェードアウト長の設定　他

js/danoni_main.js
setSpeedOnFrameを修正しました。
速度変化が補正込みで負のフレームにあるとき(たとえば`|speed_change=0,0.5|adjustment=-1|`)
それ自身を含め以降の速度変化が発生しません。
=> 速度変化が補正込みで負のフレームにあるとき適用されない不具合の修正

js/danoni_main.js
- ゲームオーバー時にリザルト画面へ移動する際の200ミリ秒遅延をカット
- Gitter報告より。
- 途中で死亡するゲージ設定の時に、ライフが0になってからリザルトに行くまでの間に判定が発生すると死体蹴りが起き、リザルト画面が2回起動します。
この際、nullのgetAttributeErrorが発生します。
当方のバージョンは7.5.1ですが、8.0.1でも起きるようです。
- 死亡してからリザルトに行くまでに、setTimeOutで0.2秒の猶予時間があり、
それが悪さをしている可能性が高いという見解をMFV2さんが示されていました。
・ゲームオーバー時、1回目のリザルトでハイスコアが記録される
・死体蹴りで2回目のリザルトに行く
・1回目死んだ時に記録されたハイスコアを参照する
・結果、ハイスコアが全て±0 で結果が出力される
という現象が発生しています。
原因を調べた所、lifeDamage関数内の
```
setTimeout(_ => {
clearWindow();
g_gameOverFlg = true;
g_finishFlg = false;
resultInit();
}, 200);
```
という記述で、死んだ瞬間に結果画面に行かず、
setTimeout関数で200msのディレイをかけてる間に
矢印が流れてくるのが死体蹴りの原因と見ました。
ここのsetTimeout関数内に置いてある処理を外に出して
```
if (g_workObj.lifeBorder === 0) {
g_audio.pause();
clearTimeout(g_timeoutEvtId);
clearWindow();
g_gameOverFlg = true;
g_finishFlg = false;
resultInit();
}
``` …
=> [0058-failed-blank] ゲームオーバー時の200ミリ秒遅延をカット

js/danoni_main.js
- ゲームオーバー時の200ミリ秒遅延により、
ハイスコア表示がおかしくなることがある問題を修正 ( #428 ) 
- Pull Request #428 を参照。
=> [ver8.0.2] ゲームオーバー時の200ミリ秒遅延により、 ハイスコア表示がおかしくなることがある問題を修正

js/danoni_main.js
- fadeFrameが譜面数に到達しない場合にプレイが止まる問題を修正
- 上述の通り。
- ver8.0.0のフェードアウト長指定に伴う不具合の修正です。
以前のバージョンでは発生しません。
=> [0059-fade-setting] fadeFrameが譜面数に到達しない場合にプレイが止まる問題を修正

js/danoni_main.js
loadMusic呼び出し時にonkeydownイベントリスナを削除するようにしました。
ロード画面でEnterを押すと複数回ロードが発生し、正常にプレイ開始できなくなります。
=> ロード画面でEnterを押すと複数回ロードが発生する問題の修正

js/danoni_main.js
- 曲中リトライキーが押しっぱなしにできる問題を修正しました。
曲開始（もしくは、フェードイン完了）までは曲中リトライできなくなります。
- 曲中リトライキーが押しっぱなしにできるために、
曲の再生リセットが行われず譜面ズレが起きる可能性があります。
完全な対策にはなっていませんが、問題の大半を解消できると思います。
=> [0060-double-push-shortcut] 曲中リトライキーが押しっぱなしにできる問題を修正

js/danoni_main.js
- ロード画面でEnterを押すと複数回ロードが発生する問題の修正 ( #432 )
- メイン画面で曲中リトライキーが連続的に発生することによる不具合の修正 ( #433 )
- Pull Request #432, #433 を参照。
=> [ver8.0.4] キー押しっぱなしによる譜面再生不具合を修正

js/danoni_main.js
- backtitle_dataが"Dancing☆Onigiri"や曲名文字より裏側に表示されるよう変更
- この変更により、並び順が以下のように変わります。
- 背景矢印＜backtitle_data＜「Dancing☆Onigiri」＜曲名文字＜ボタン類＜masktitle_data
- Twitter要望より。
- 背景矢印の位置がそのままなので、置き換えた場合の影響は少ないと考えています。
=> [0061-titlepos-front] タイトル文字の重ね順を変更

js/danoni_main.js
- 曲名（複数行）を結合する場合の半角スペース抜き表記に対応
- 複数行曲を1行に表記する場合（メイン画面・リザルトコピー）に、
2行を結合するときに半角スペースを入れるかどうかをタグで区別する。
```
|musicTitle=曲名が長い曲<br>半角スペース入り,アーティスト,http://|
```
- 1行にすると「曲名が長い曲_半角スペース入り」("_" は半角スペース)と表記される。
```
|musicTitle=曲名が長い曲<nbr>半角スペース抜き,アーティスト,http://|
```
- 1行にすると「曲名が長い曲半角スペース抜き」と表記される。
- 譜面ヘッダーの`musicTitle`で、曲名（複数行）時の場合でもメイン画面では1行に表示する。
その場合には半角スペースを挟む仕様になっており、その必要がない曲に対応できていなかった。
=> [0062-musicname-split] 曲名（複数行）を結合する場合の半角スペース抜きに対応

js/danoni_main.js
- 譜面別データ(LocalStorage)に制作者名を付加できるように変更
- 先の変更で譜面名が同一になる可能性があったため、
譜面ヘッダー：makerViewを`true`にすることで、LocalStorageの譜面別設定名を変更できます。
|makerViewの値|LocalStorage(譜面別)のキー名|
|----|----|
|false (デフォルト)|キー数-譜面名|
|true|キー数-譜面名-制作者名|
- 既存作品に適用すると、ハイスコアが初期化されます。
適用する場合はご注意ください。
=> [0063-multi-makers-result(2)] 譜面別データ(LocalStorage)に制作者名を付加できるように変更

js/danoni_main.js
1. 曲名（複数行）を結合する場合の半角スペース抜き、全角スペース置換表記に対応 ( #437 )
2. 制作者表示の複数化に対応（設定・結果画面、リザルトコピー）( #438 )
3. 譜面別データ(LocalStorage)に制作者名を付加できるように変更 ( #439 )
- Pull Request #437, #438, #439 を参照。
=> [ver8.2.0] 曲名（複数行）を結合する場合の半角スペース抜きに対応　他

danoni/danoni3.html, js/danoni_main.js
- 譜面変更用セレクターの実装
- 設定画面の譜面名をクリックすると譜面の一覧が表示され、
対象の譜面をクリックするとその譜面の設定が反映されるセレクターを作成しました。
数が多い場合は自動で縦スクロールが出るようになっています。
譜面ヘッダー「difSelectorUse」を`true`にする必要があります。
- 持ち寄り合作などで多くの譜面を選ぶときに使用することを想定しています。
- セレクター表示中は他の設定を変更できないようにしています。
画面移動するか、もう一度譜面名を押すと元に戻ります。
=> [0065-scorelist] 譜面変更用セレクターの実装

js/danoni_main.js
- 譜面リストにキー別フィルターを追加
- ver8.3.0で実装した譜面変更用のセレクターに、キー別のフィルターボタンを追加しました。
- 数が多い合作の場合、キー種で絞るケースも考えられるため。
=> [0066-scorelist-filter] 譜面リストにキー別フィルターを追加

danoni/danoni2.html, js/danoni_main.js
- 相対パス指定時に外部譜面ファイル取り込みが失敗する問題を修正しました。
- また、サンプル２の譜面分割フラグの初期値を`false`に戻しました。
- ドット( . )で単純分割していたため、相対パスのドットを拾っていました。
末尾のドットのみを拾うように修正しました。
=> [0067-multiple-files(2)] 相対パス指定時にファイル取り込みが失敗する問題を修正

js/danoni_main.js
- 外部dosが存在する場合の譜面データの一時クリア条件を「譜面ファイル分割時」「譜面番号固定時」に限定するように変更
- 埋め込みdosにある譜面データがクリアされ、プレイできない可能性があるため。
=> [0068-score-clear] 譜面データのクリア条件を緩和

js/danoni_main.js
1. scoreIdをクエリ指定した場合の初期速度の不具合を修正
- クエリ指定した場合に常時1譜面目の速度になってしまう問題を修正しました。
2. ゲージ設定について、処理が二重定義されている箇所を見直し
1. Gitter指摘より。
2. `headerConvert`で定義しているゲージの初期設定が、
`setDifficulty`で定義している設定と重複しているため、集約しました。
=> [0070-speed-initial] scoreIdをクエリ指定した場合の初期速度の不具合を修正

js/danoni_main.js
- 本来Booleanで定義すべき変数を変更、変数型の定数化
- string型の「true」とboolean型の「true」が混在しているため。
- ただし、矢印のプロパティで定義されている一部変数はstring型のままとする。
- 過去(ver3.5以前)の経緯で danoni_custom.js に以下を指定していることがありましたが、
今後は除去しないと動かなくなります。
```javascript
g_headerObj.customTitleUse = `false`;
g_headerObj.customTitleArrowUse = `false`;
g_headerObj.customBackUse = `false`;
g_headerObj.customBackMainUse = `false`;
g_headerObj.customReadyUse = `false`;
```
=> [0071-stringToBoolean] 本来Booleanで定義すべき変数を変更、変数型の定数化

js/danoni_main.js
1. 初回読込時のclearWindowをカット
1. ローカルmp3の読込失敗時のメッセージ追加
1. 初回読込時に一瞬消えたような挙動になるのと、
そのタイミングでdivRoot以外のオブジェクトが参照されたときにエラーとなるため。
1. ローカルmp3の読込失敗時のメッセージを確認する方法が無かったため。
=> [0075-clear-window] 初回読込時のclearWindowをカット 他

js/danoni_main.js
1. 作品別ローカルストレージのキーとして使用しているURLからscoreIdを取り除くようにしました。
2. 作品別ローカルストレージの初期設定部分を関数化しました。
1. 同じ作品でもscoreIdによって保存先が異なっていたためです。
2. 1.の処理に伴う一時変数をグローバルに置かないためです。
=> 作品別ローカルストレージのキーからscoreIdを取り除く

js/danoni_main.js
1. PR #467 に関連して、リザルトコピーのURL表示からscoreIdを除去するようにしました。
1. scoreId=Xのように指定したとしても、別の譜面が選択できてしまうため。
その場合でもscoreId=Xと表示されることから、除去することにしました。
- scoreIdのみを除去するので、他のクエリには影響しません。
=> [0078-result-url] リザルトコピーのURL表示からscoreIdを除去

js/danoni_main.js
1. 時間表示の処理を毎フレーム行うようにしました
2. 秒の計算に切り捨てを追加しました
g_fpsに小数を指定すると現在時間表示が「-:--」のまま動かなくなります。
[twitterより](https://twitter.com/MFV2_/status/1180322959992295424)
=> fpsが小数の時に時間表示が動かなくなる不具合の修正

js/danoni_main.js
1. エスケープ文字の適用順序誤りを修正
「&」->「<」->「>」->「\`」の順に適用するように変更しました。
1. 「<」->「>」->「\`」->「&」の順にエスケープ処理を行っていたが、
この順序の場合、前3つがエスケープされた後、「&」が合致するため
二重にエスケープされてしまう。これを回避する。
- back/mask_dataで「>」や「<」を使った場合に発生します。
=> [0080-escape-html] エスケープ文字の適用順序誤りを修正

js/danoni_main.js
1. エスケープ文字の修正
1. ver2以降で文字列の括りをダブルクォートからバッククォートへ変更したが、
その時に合わせてバッククォートをエスケープするようになっていたため。
=> [0080-escape-html(2)] エスケープ文字の修正

js/danoni_main.js
flowTimeline内の速度変化の処理を修正しました。
速度変化が同一フレームにあると1番目だけが処理され、
以降の速度変化が適用されず、画面上の矢印と判定位置がずれてしまいます。
譜面データ側に問題が無くてもAdjustmentやFadeinの値によって、
開始フレームでの初期速度設定(Line 6611~6612)と重なると発生します。
[再現用譜面データ](https://gist.github.com/suzme/45371c57117bea22ffc1579d2aa38e88)
Adjustment=0,Fadein=0で再現すると思います。
=> 速度変化が同一フレームにあると正常に動作しなくなる不具合の修正

js/danoni_main.js
- 低速時かつフリーズアロー開始判定時にPF判定が早まる問題を修正
- フリーズアロー開始判定時の矢印数加算を`scoreConvert`関数内へ移動する。
- 低速時、`scoreConvert`関数が2回以上動くことがあるが、
2回以上動いた後にフリーズアロー開始判定分を加算していないため、ズレが起こる。
- 実装時点からの不具合と思われます。
=> [0081-frzstart-calc] 低速時かつフリーズアロー開始判定時にPF判定が早まる問題を修正

danoni/danoni3.html, js/danoni_main.js
- ダミーIDの譜面ヘッダー誤りを修正しました。
- dummyScoreNo -> dummyId
- Wikiに記載している譜面ヘッダーと記載内容が異なっていたため。
=> [0082-dummyId] ダミーIDの譜面ヘッダー誤りを修正

js/danoni_main.js
- ダミー用カスタム変数が定義できない問題を修正しました。
- customJudgeDummyArrow(difFrame), customJudgeDummyFrz(difFrame)の引数が未定義だったため。
=> [0083-dummy-frame] ダミー用カスタム変数が定義できない問題を修正

js/danoni_main.js
- back/mask_dataにおいてオールクリアできない問題を修正
- back/mask_dataにおいて深度にALLを指定すると背景もしくはマスクが全て消えることになっているが、実行時、spriteUpper変数が存在せずエラーとなってしまう。
=> [0084-mask-clear-all] back/mask_dataにおいてオールクリアできない問題を修正

js/danoni_main.js
2譜面目以降で以下の画面効果が指定されていないとき、1譜面目の情報を読み込むようにしました。
- mask(Rev)_data
- back(Rev)_data
- arrowMotion_data
- frzMotion_data
画面効果を全譜面統一したい場合の多重指定の手間を省くため（word_data 等に合わせる形）
mask_data に関して、2譜面目以降のリバース時には以下の優先順位で読み込んでいます。
back_data も同様。
1. maskRev(譜面番号)_data
2. maskRev_data
3. mask(譜面番号)_data
4. mask_data
=> 2譜面目以降で背景、矢印モーションが指定されていない場合、1譜面目のデータを読み込むように変更

js/danoni_main.js
- 従来は一定時間経過で強制的にフレームカウントしていましたが、
ゲーム終了条件を満たした場合はフレームカウントしないように変更しました。
- フリーズアローヒット部分をステップゾーン位置へ分離配置しました。
これにより、Hidden時でもフリーズアローがヒット中かどうかを判別できるようになります。
- 矢印のヒットモーションと同じように、ステップゾーン上に常時配置されて表示・非表示が切り替わるイメージです。
- (追記) ダミーフリーズアローではこの分離したオブジェクトは使用しません。
末尾矢印と同様に作用します。
（Hiddenと併用した場合はステップゾーン上には表示されません）
- 矢印やその周辺描画で使用していた、
`createArrowEffect` 並びに `createColorObject`を簡素化しました。
CSSの`mask-image`を使用した方法に統一しています。
- フリーズアローバーの透明度を常時75％に設定しました。
1. 意図しないタイミングでフレームカウントした結果、
不具合を起こす可能性を少しでも減らすため。
2.   Hidden時にフリーズアローがヒットしたかどうかがわからないため。
また、フリーズアロー本体個々に行っていたヒット時描画をやめることによる
処理負荷軽減（わずかですが）を図るため。
3. 以前よりIEは動作対象外としており、
この対応を切ったとしても影響はほぼないと考えられるため。
Edgeについても、今後はChromiumへ移行するためほぼ影響はないと考える。
4. ParaFla版では透明度設定されていたが、これまでCW Editionではされていなかったため
移植作でフリーズアローバーが白色の場合、矢印ヒット色と重複していた。
=> [0085-code-refactoring] コード見直し

js/danoni_main.js
- キーコンフィグ画面からDisplay画面にも戻れるようにしました。
- Display画面からキーコンフィグ画面へ移動した後、
戻った先が現在Settings画面しかなく、一度Settings画面を経由する必要があるため。
=> [0086-switch-button] キーコンフィグ画面からDisplay画面にも戻れるように対応

js/danoni_main.js
- Ready表示の遅延フレーム設定を追加
以下のように設定します。遅延させるフレーム数を指定します。
デフォルトは0フレームです。
```
|readyDelayFrame=100|
```
- 音楽に合わせてReady表示を行いたい場合があるため。（ Issue #491 ）
=> [0087-ready-delay] Ready表示の遅延フレーム設定を追加

js/danoni_main.js
- リバース用のword_dataを実装しました。
`wordRev_data`, `wordRev2_data`, ...のように使用し、
リバースがONの場合のみ適用されます。
`back_data`などと同様に、指定が無ければ`word_data`や`word2_data`を参照します。
適用の優先順序についても`back_data`等と同じです。
- 使い方は`word_data`の書式と変わりません。
- Twitter要望より。
`back_data`や`mask_data`にあって`word_data`だけリバース版の書式が無かったため。
=> [0089-reverse-lyrics] リバース用のword_dataを実装

css/danoni_main.css, js/danoni_main.js, js/danoni_setting.js
- 譜面側からゲージ設定を丸ごと設定できる譜面ヘッダーを追加します。
以下のように、`customGauge`を指定します。
「ゲージ名::回復/ダメージ量設定」の組み合わせで設定します。
回復/ダメージ量設定は、「F」なら矢印数によらず固定、「V」なら矢印数により変動します。
```
|customGauge=Original::F,Normal::V,Escape::V|
|gaugeOriginal=x,4,60,25$x,3,20,25|
|gaugeNormal=50,70,1,25$x,3,25,25|
|gaugeEscape=0,1,50,100$x,5,30,25|
```
なお、ライフ制/ノルマ制の区別は各個別のゲージ設定にて行います。
このため、ノルマ制ながら回復/ダメージ量は固定にするといった設定が可能になります。
また、`danoni_setting.js`の`g_presetGaugeCustom`に追加するゲージ設定を記載することで
どの作品に対してもカスタムゲージを適用できるようになります。
```javascript
// ゲージ設定（デフォルト以外）
const g_presetGaugeCustom = {
// (省略)
Escape: {
Border: 70,
Recovery: 1,
Damage: 50,
Init: 70,
},
};
```
- 新たに NoRecovery, SuddenDeath, Practiceを追加しています。
- ゲージ設定詳細を表形式に変更しました。
回復・ダメージ量が矢印数により変動する場合は、オレンジ色で表記します。
- 表示例：
|Start<br>(初期ライフ/最大ライフ)|Border<br>(クリアボーダー)|Recovery<br>回復量(率)|Damage<br>ダメージ量(率 …
=> [0088-custom-gauge] カスタムゲージの実装

js/danoni_main.js
- 個別色変化時にフリーズアロー(AA)ヒット時の色が変わらない問題を修正しました。
v9.2.0で、ステップゾーン上に分離したヒット時のAAを指しています。
矢印では起こりません。
- 全体色変化のタイミングでのみ、ヒット時の色が変わるようになっていた。
フリーズアロー(AA)のヒット時タイミングでも変わるように変更する。
=> [0090-frzhit-colors] 個別色変化時にフリーズアロー(AA)ヒット時の色が変わらない問題を修正

js/danoni_main.js
- ゲージ詳細のライフ初期値を整数に変更しました。
- ライフ初期値が最大ライフの関係で小数の場合、小数で表示されますが
メイン画面上には小数表記は出てこないため。
- 内部計算上は小数で計算されます。
これは、回復・ダメージ量についても同じです。（表示上は小数第1位で丸め）
=> [0091-gauge-start] ゲージ詳細のライフ初期値を整数に変更

js/danoni_setting.js
- danoni_setting.jsのSuddenDeath初期値を変更しました。
g_headerObjではなく、g_rootObjから取得するように変更しています。
- danoni_setting.js読込タイミングでは、g_headerObjは未定義のため。
=> [0093-gauge-initial] danoni_setting.jsのSuddenDeath初期値を変更

css/danoni_main.css, js/danoni_main.js
- ゲージ設定明細のレイアウトを修正しました。
- Start, Border : 整数で丸め
- Recovery, Damage : 小数第2位で丸め
|Start|Border|Recovery|Damage|
|250/1000|777|0.25|7.5|
- StartやBorderの値の幅に対して、Recovery, Damageの表記が粗いため。
- Borderに関しては、ライフ上限値×ノルマ（%）の値に対して丸めます。
このため、ライフ上限が1000でノルマが77.7％なら、Border表記は777となります。
=> [0094-gauge-improve] ゲージ設定明細のレイアウトを修正

danoni/danoni1.html, js/danoni_main.js
- 背景・マスクモーションに対象拡張子のデータがあれば、自動でpreloadするように変更
（譜面ヘッダー：`autoPreload`を`true`にする必要があります）
- 以下のようなケースの場合、preloadImagesに追加しなくても自動でpreloadします。
```
|autoPreload=true|
|back_data=
200,0,testA.png,...// 途中略
400,1,../img/testB.jpg,... // 途中略
800,1,../img/testB.jpg,... // 途中略
|
```
この場合、以下の設定が自動で設定されます。（下記の記載は不要）
```
|preloadImages=testA.png,../img/testB.jpg|
```
- preloadImagesに追加する手間を省くため。
- Chrome系のブラウザのみpreloadします。Firefoxではデフォルト無効です。（従来通り）
- 背景・マスクモーション（タイトル・リザルト含む）に記載の画像ファイルが対象です。
それ以外で定義した画像ファイルは対象外です。
=> [0097-auto-preload] 背景・マスクに対象拡張子のデータがあれば、自動でpreloadするように変更

js/danoni_main.js
- タイトルのコメントを一部見直しました。
- 構築当初のコメントとなっており、現在コーディング用のページも別にある中、
冗長と考えたため。
- 機能ではなく、コメントのみの修正です。
=> [0103-fix-comment] タイトルのコメントを一部見直し

js/danoni_main.js
1. 矢印オブジェクトの生成処理を `createColorObject` に統一しました。
2. 矢印等の回転数を管理するオブジェクトを
ステップゾーン・ヒットゾーン・矢印の3つに分離しました。
`g_workObj.stepRtn`, `g_workObj.stepHitRtn`, `g_workObj.arrowRtn` に分離しています。
1. 矢印生成処理である、`createArrowEffect`と役割がほぼ同じため。
2. 今後、ステップゾーン・ヒットゾーン・矢印のオブジェクトが途中変更する
オプションの追加を見据えた変更です。
- `createArrowEffect`関数は未使用となりますが、当面は残します。
=> [0102-rotation-branch] 矢印オブジェクトの生成処理統一　他

danoni/danoni0.html, danoni/danoni1.html, danoni/danoni2.html, js/danoni_main.js, skin/danoni_skin_default.css, skin/danoni_skin_light.css
1. 設定画面で、設定項目ごとにdiv要素をまとめるように変更しました。
2. 汎用項目の関数を集約して設定できるように変更しました。
ただし、Difficulty, Gauge, Fadeinは特殊な設定があるためそのままです。
3. 設定画面の項目を囲うオブジェクト(optionsprite)の位置を中央揃えになるように調整しました。
1. スキンとして、設定項目ごと（ラベル・ボタン群）をまとめて
座標移動させることがありえるため。
2. 共通している箇所が多いため。
3. optionspriteの背景に色付けするケースが考えられるため。
=> [0104-setting-layer] 設定毎にdiv要素をまとめるように変更

css/danoni_main.css, js/danoni_main.js
1. iOSの場合にロードで止まってしまう問題を一部修正しました。
iOSの場合は、ロード画面でPLAYボタンを押すとプレイできます。
2. iOSの場合にAppearanceが動作しない問題を修正しました。
1. iOSの場合に再生ができない問題が発生していたため。
2. Safariの場合、CSSの`clip-path`が未対応のため。
代替として、ベンダープリフィックスをつけた`-webkit-clip-path`を利用しています。
- base64エンコードされたデータには対応していません。
HTML5のAudio機能にて代替しています。
=> [0108-fix-iOS] iOSの部分対応（ロードで止まってしまう問題を一部修正）

js/danoni_main.js
1. skinTypeがdefault以外の場合、背景オブジェクト(divback)を作成するよう変更しました。
背景オブジェクトに背景色が設定されていた場合、Canvas上の背景情報は無視されます。
1. v9まででCanvasタグを使っていることが多く、後から削除するのが容易ではないため。
=> [0107-skin-divback] skinTypeがdefault以外の場合、背景オブジェクトを作成するよう変更

js/danoni_main.js
1. MacOS, iOS (Safari)においてWeb Audio APIが動作しない問題を修正しました。
2. iOS (iPod, iPhone, iPad)において音量が調整できない問題を修正しました。
1, 2. MacOS/iOS (Safari)における動作不良のため。
- Safariでは Web Audio API がベンダープレフィックス必須となっており、
Chromeで使用されている`AudioContext`が使用できず、
`webkitAudioContext`を使用する必要がありました。
- また、すでに曲が止まっている状態（一度`g_audio.pause()`を実行）で再度`g_audio.pause()`を行うとSafariでは止まる問題があったため、以下の対処を行っています。
- 楽曲終了まで到達した場合の`g_audio.pause()`を除去
- 楽曲途中で終了した場合の「Back」「Retry」ボタンによる`g_audio.pause()`を除去
=> [0109-ios-webaudioapi] MacOS/iOSにおける動作不具合を修正

js/danoni_main.js
1. 矢印と同様、ステップゾーンについてもオブジェクトをグループ化しました。
一律、`stepRootX`のidで取得可能です。(Xは数字)
- step (ステップゾーン本体)
- stepDiv (ステップゾーン空押し時の色)
- stepHit (ステップゾーンヒット時モーション)
- stepShadow (ステップゾーン塗りつぶし部分)
1. ステップゾーンについて複数のオブジェクトが個別管理されているが、ステップゾーン移動時に煩雑になるため。
- 演出でステップゾーンの位置変更している作品は注意すること。
=> [0112-scroll-extension(2)] 矢印と同様、ステップゾーンについてもオブジェクトをグループ化

js/lib/danoni_constants.js
- ぃょぅがギコの画像になっている問題を修正しました。
- 7i/11i/11Wkeyのぃょぅの参照先がギコの画像になっていたため。
=> [0116-fix-image-name] ぃょぅがギコの画像になっている問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
- 譜面選択リストの長さ間違いを修正しました。
- 設定画面のボタンサイズを変えたことで影響した部分を修正するため。
=> [0117-fix-difselector-width] 譜面選択リストの長さ間違いを修正

js/danoni_main.js
- ハイスコア差分を表示する部分のidを変更しました。
- lblIiS -> lblIiLS
- lblShakinS -> lblShakinLS
- 実スコアとid名が重複していたため。
=> [0119-resultdiff-rename] ハイスコア差分のidを変更

js/danoni_main.js
- リザルト画面のId重複を修正しました。
プレイスタイルの2行目のIdが1行目と重複していました。
- lblDisplayData
- lblDisplay2Data
- 先の #545 の修正漏れです。
=> [0119-resultdiff-rename(2)] リザルト画面のid重複を修正

js/danoni_main.js
- 矢印のヒット部分を押したタイミングに応じて変わるように変更しました。
常時ステップゾーンの真上だったものから変更しています。
- 押したタイミングによって位置補正されてしまい、ズレがわかりにくくなるため。
最初期のソース仕様に近い状態になっています。
=> [0120-hitpos-change] 矢印のヒット部分を押したタイミングに応じて変わるように変更

js/danoni_main.js
- リザルト用ラベルの指定間違い（MaxCombo, FreezeCombo）を修正しました。
- 先のver10.4.0でコード見直しを行った際の指定ミスです。
=> [0123-fix-result-label] リザルト用ラベルの指定間違いを修正

js/danoni_main.js
1. 結果画面（Cleared/Failed表示）のラベル重複を解消しました。
2. リザルト画面のカスタム関数の位置を修正しました。
1. ラベル重複により、Id指定ができない箇所があるため。
2. 他の画面と同様に、ボタン以外のオブジェクトへ容易にアクセスできるようにしました。
=> [0126-fix-result-label2] ラベル重複の修正、リザルト画面のカスタム関数の位置見直し

js/danoni_main.js
1. Localhost時にフレーム数を表示するように対応
1. 今後ローカルサーバーが作成の中心になることを見据え、
localhost時にフレーム数を表示するように対応しました。
=> [0128-fix-localhost] localhost時にフレーム数を表示するように対応

js/danoni_main.js
1. file起動以外の場合にpreloadにcrossOrigin属性「anonymous」を追加しました。
1. 同一オリジンであっても本来指定が必要なため。
なお、まだhtmlファイル直起動があることを考慮し、htmlファイル直起動のときは
crossOrigin属性を指定していません（同一オリジンで無いため、画像が取得できない）。
=> [0129-crossorigin-enabled] file起動以外の場合にpreloadにcrossOrigin属性を追加

js/danoni_main.js, js/lib/danoni_constants.js
1. Displayオプションのデフォルト設定ができるように変更しました。
`false`にした場合、OFFにするだけでなくON/OFF設定自体が無効化されます。
```
|stepZoneUse=false|
|judgementUse=false|
|lifeGaugeUse=false|
|musicInfoUse=false|
|speedUse=false|
|colorUse=false|
|lyricsUse=false|
|backgroundUse=false|
|arrowEffectUse=false|
```
2. カスタム用のDisplayオプション「Special」を追加しました。
`g_stateObj.d_special`の`ON`, `OFF`で制御できます。
Displayオプションのデフォルト設定にも対応しています。
```
|specialUse=false|
```
3. 判定キャラクタの下にFast/Slow/Just表記を追加しました。
1. 作品により、DisplayオプションのON/OFF制御が必要な作品があるため。
2. 特殊な作品の演出のON/OFFが必要な場合に備えて実装しました。
3. プレイ中の早押し・タイミング遅れを把握できるようにするため。
=> [0125-display-extensions] Displayの拡張設定を追加

js/danoni_main.js
1. Fast時のときの差分フレーム数のスペルミスを修正しました。
1. 上述の通り。
=> [0130-fix-fast-spell] fast時のときの差分フレーム数のスペルミスを修正

js/danoni_main.js
1. 特定のキーに後から代替キーが追加された場合に、
キーコンフィグが保存された状態でキーコンフィグ画面に移動すると
undefinedが表示される問題を修正しました。
1. キーコンフィグ画面でundefinedが表示されている場合、
代替キーの割り当てができないことがあるため。
=> [0132-check-keyconfig] キーコンフィグがundefinedになる場合がある問題を修正

js/danoni_main.js
1. ライフが0になるときにライフの数値表示が反映されない問題を修正しました。
1. 上述の通り。
- ver10でも同様の修正が必要です。
=> [0135-life-zero] ライフ0が反映されない問題を修正

js/danoni_main.js
1. ライフが0になるときにライフの数値表示が反映されない問題を修正しました。
（idを指定する書き方に変更）
1. 上述の通り。
=> [0135-life-zero(2)] ライフ0が反映されない問題を修正（再）

js/danoni_main.js
1. 下側の歌詞表示位置をステップゾーン位置に追随させる設定を追加しました。
譜面ヘッダー`buttomWordSet`にて設定します。
下側のステップゾーン位置を`stepYR`で調整できるので、その位置に追随するようになります。
```
|buttomWordSet=true|
|stepYR=-20|
```
2. 判定キャラクタ、ReadyのY座標を下側のステップゾーン位置(stepYR)に合わせて
自動調整するように変更しました。
1. 下側の歌詞表示位置が楽曲クレジットによりカバーできないことがあるため。
2. 下側のステップゾーン位置のみを変更することは可能でしたが、
判定キャラクタ位置、Readyが自動調整できなかったため、手動で直す必要がありました。
=> [0136-lyrics-reverse-pos] 下側の歌詞表示位置をステップゾーン位置に追随させる設定を追加　他

js/danoni_main.js
1. ライフ0が反映されない問題を修正を再修正しました。
1. ライフゲージバーが反映されていなかったため。
=> [0135-life-zero(3)] ライフ0が反映されない問題を修正（再）

js/danoni_main.js
ロード画面に特殊キーのブロック処理を追加しました
#432 で`onkeydown={}`にしてしまったのでロード画面で特殊キーがブロックされません
=> ロード画面に特殊キーのブロック処理を追加

js/danoni_main.js
- 譜面名未指定のときに、リザルトコピー時のクレジットが
undefinedになる問題を修正しました。
- 上述の通り。
=> [0138-undefined-creator] 譜面名未指定のときにリザルトコピー時のクレジットがundefinedになる問題を修正

js/danoni_main.js
1. loadDos関数を見直しました。
- 第1引数：後続処理（関数など）
- 第2引数：初期化フラグ
（デフォルト：指定された譜面番号のものを読込／true：常時1譜面目を読込）
2. 速度グラフ表示の分割dosに対応しました。
3. 譜面ヘッダーを speedGraphUse から scoreDetailUse に変更しました。
1. 初期化・譜面読込以外の用途に対応するため。
2. 速度グラフ表示について、外部dosが分割された場合に対応するため。
3. 速度グラフ表示の他にツール値などを表示する可能性があるため。
=> [0143-load-dos-refactoring] loadDos関数の整理、速度グラフ表示の分割dos対応

js/danoni_main.js
- リザルト画面においてコードが二重になっている箇所を見直しました。
- コードメンテナンス改良のため。
- 追加でコード整理を行う可能性があります。
=> [0141-code-refactoring] リザルト画面のコード整理

js/danoni_main.js
1. 譜面密度グラフにおいて、最大密度部分に色が付かない問題を修正しました。
2. startFrameの値に応じて速度変化・譜面密度グラフの位置が変わるように修正しました。
1. 譜面を16分割する際、最大フレーム数を16分割していたため
最大フレームのときのみ17番目に現れてしまい、うまく表示されない。
2. 作品として意図的にstartFrameをずらしている作品の場合、
譜面密度が全体的に1を超えてしまい、平均表示にならないため。
=> [0147/fix-graph] 最大密度に色が付かない問題を修正

js/danoni_main.js
1. 譜面明細画面で速度変化数・プレイ時間・APM・
総矢印／フリーズアロー数を表示するように対応しました。
速度変化グラフにおいてSpeed/Boost数の表示、
譜面密度グラフにおいてAPM(Arrows Per Minute)、プレイ時間、
総矢印／フリーズアロー数の表示を追加しています。
2. 譜面明細表示のオブジェクト構造を一部変更しました。
- 速度変化グラフ
scoreDetail -> detailSpeed (div要素)-> graphSpeed (canvas)
- 譜面密度グラフ
scoreDetail -> detailDensity (div要素) -> graphDensity (canvas)
3. createGraph関数をcreateScoreDetail関数に変更しました。
また引数に `_graphUseFlg`を追加し、グラフのない画面も作成できるようにしました。
1. Issue #417 の一環です。
2. 文字表示部分(div要素)とグラフ描画部分(canvas)を分離し、
グラフとそれ以外の部分を扱いやすくするため。
3. レベル計算ツールの値を表示するための画面を準備するため。
- 今後、レベル計算ツールの値をSpeedやDensityとは別の画面で表示することを想定しています。
表示内容は、ツール値、同時押し補正、縦連補正、矢印毎のノート数 及び
ハイスコア、ハイスコア日時（※別途取得必要）です。
矢印毎のノート数に関しては、今回の対応でデータが取れるように設定しています。
変数名は`g_workObj.arrowCnt[j]`と`g_workObj.frzCnt[j]`です。（`j`は矢印番号を表します）
=> [0143/graph-details] 速度変化数・プレイ時間・APMの表示対応

js/danoni_main.js
1. 速度変化、譜面密度関連のデータを譜面毎に再取得ではなく事前読込するよう変更しました。
2. loadDos関数の引数を変更しました。
- 変更前：_afterFunc (関数後に実行する処理), _initFlg (1譜面目を読み込みするかどうか)
- 変更後：_afterFunc (関数後に実行する処理), _scoreId (譜面番号　※デフォルト：１)
3. setScoreIdHeader関数の引数を変更しました。
- 変更前：なし
- 変更後：_scoreId (譜面番号), _scoreLockFlg (譜面番号固定フラグ　※デフォルト：false)
4. 譜面番号固定時、リザルトモーションが反映されないことがある問題を修正しました。
1. 将来的にツール値を実装する際に、html側からデータ取得できる余地を残すため。
2. `g_stateObj.scoreId`に依存した関数になっていることで、融通が利かない関数になっていたため。
3. 2.と同上
4. 譜面番号固定時の条件が一部抜けていたため。
- 1.の変更により、譜面明細画面に表示している情報の更新タイミングが
リロード時に限定されます。
サーバ上では譜面が常時変わることはないため、それほど影響はないと考えています。
=> [0150/preload-dos] 速度変化、譜面密度関連のデータを事前読込へ変更

js/danoni_main.js
1. 譜面詳細情報取得時、キー数が異なるとデータがおかしくなる問題を修正しました。
2. scoreConvert関数が譜面番号依存だった問題を修正しました。
引数を以下のように変更しました。
- 変更前：_dosObj (譜面情報), _scoreNo (譜面番号添え字), _preblankFrame, _dummyNo, _scoreAnalyzeFlg
- 変更後：_dosObj (譜面情報), **_scoreId (譜面番号)**, _preblankFrame, _dummyNo, 
**_keyCtrlPtn (キー数・パターン)**, _scoreAnalyzeFlg
3. 共通で使用する以下の関数の引数に、keyCtrlPtn (キー数・パターン) や
scoreId (譜面番号) を追加しました。
- getLastFrame
- getStartFrame
- getFirstArrowFrame
4. loadScript関数を改良し、読込成功・失敗をフラグで持たせました。
g_loadObj[ファイル名]で取得可能です。（true: 読込成功、false: 読込失敗)
また、ファイルが取得できない場合に読み込んだ譜面データを上書きしないよう対応しました。
5. loadDos関数について、必要に応じて再帰呼び出しする仕様に変更しました。
1. キー数指定に`g_stateObj.scoreId`を指定していましたが、
譜面を全て取り込む場合、常に最初に指定したキーで固定されてしまうため。
2. 1.の問題に付随した修正です。
キー数指定に同じく`g_stateObj.scoreId`を指定していました。
3. 1.の問題に付随した修正です。
4. 読込成功・失敗を管理できるようにするため。
5. …
=> [0151/preload-dos] scoreConvert関数が譜面番号依存だった問題を修正

js/danoni_main.js
- setColor, frzColor, color_data, acolor_dataに対応しています。
※titlegrdにも対応しました。詳細は3. にて。
- `グラデーション記述@グラデーションの種類`
※グラデーション記述はカンマではなくコロン`:`で区切る
※グラデーション種類のうち、`linear-gradient`は省略可
```
|setColor=#9999ff:#ffffff@radial-gradient,#99ffff:#ffffff@radial-gradient,#ffffff|
|color_data=300,20,45deg:#ffff99:#ffffff:#9999ff@linear-gradient|
|color_data=300,20,#ffff99:#ffffff:#9999ff@radial-gradient|
|acolor_data=300,20,#ffff99:#ffffff:#9999ff@conic-gradient|
```
- グラデーション種類を省略した場合：linear-gradient が指定されます。
- linear-gradient でグラデーション方向を省略した場合：`to right`が指定されます。
- 矢印色1種類を指定した場合：グラデーションのない単色になります。
（実際はlinear-gradientで開始色と終了色が同じ）
- 矢印色1種類を指定した場合、
自動で下記に設定する譜面ヘッダー｢defaultColorgrd｣を追加しました。
｢true｣で有効化します。
`linear-gradient(to right, 矢印色, #ffffff, 矢印色)`
- 今回の変更に合わせ、仕様を統一しました。 …
=> [0152/color-gradation] 色変化のグラデーションに対応

js/danoni_main.js, js/lib/danoni_constants.js
- 矢印色・フリーズアロー色のグラデーション実装 ( #601 )
- レベル計算ツール++移植 ( #602 )
- それぞれのPull Requestを参照。
=> [ver12.0.0] 矢印色のグラデーション実装、レベル計算ツール++移植

js/danoni_main.js
1. setColorの1・3番目に方向(to rightなど)が指定された場合で、titlearrowgrdが未指定の場合
タイトルの背景矢印が表示されない問題を修正しました。
1. 上述の通り。
1. v12.0.0に起因する不具合の修正です。
=> [0155/color-gradation] setColorの1・3番目に方向が指定された場合の問題を修正

js/danoni_main.js
1. 譜面詳細用データを全て読み込んでからタイトルへ移動するよう変更しました。
`loadDos`関数で譜面詳細用データを取り切った後、`titleInit`を処理するよう変更しています。
1. `loadDos`関数が非同期処理にも関わらず、`titleInit`と同時に処理するようになっていました。
これにより、`loadDos`関数（実際には`reloadDos`）の処理がデータ出力を作成する`makeDifInfo`関数の開始に間に合わず、一部の譜面データが未出力となる事象が発生していました。
- この変更で、譜面数が多い作品のタイトル画面の表示が若干遅くなる可能性がありますが
気にするレベルでは無いと思います。
=> [0156/synchronized-loading-dos] 譜面詳細用データを全て読み込んでからタイトルへ移動するよう変更

js/danoni_main.js
1. レベル計算中の無効な値を対象にしないよう修正しました。
- |left_data=|のように数値以外の空データが入った場合
- 同一レーン上に同一フレームの矢印・フリーズアローがある場合
※同一レーンのフリーズアロー中に矢印があるケースは検知しません。
2. 3つ押しが無い場合、リストに「None」と明記するよう変更しました。
3. 不要なコードを削除しました。
1. 無効な値があることが理由で、レベル計算できないケースがあるため。
2. 該当なしであることを明示するため。
3. コード整理のため。
=> [0157/fix-dif-tools] レベル計算中の無効な値を対象にしないよう修正

js/danoni_main.js
1. カラーグラデーションを利用時、KeyConfigでColorTypeを変更して一周させると
矢印に色が適用できなくなる問題を修正しました。
1. 上述の通り。
=> [0158/color-type-reset] KeyConfigでColorType利用時の不具合を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 矢印描画サイズを可変にする設定を追加しました。
`danoni_constants.js`内の`g_keyObj.scaleX_Y`にて設定します。
```javascript
g_keyObj = {
scale: 1,
scale_def: 1,
scale17_0: 0.85,
};
```
指定が無い場合は`scale_def`の値（1倍）が指定されます。
独自キーにも対応しており、|scale16=0.9| のような指定の仕方が可能です。
1. 17keyの横幅が長い問題を解消するため。
17keyのデフォルトを0.85倍に設定することで、
横幅を900px⇒750pxに狭めることを可能にします。
なお、影響のない17keyのAlternate版は1倍のままです。
1. 矢印描画範囲を縮小すると、上下に描画が無い部分が増えます。
そのためあまり小さくしすぎた場合、ステップゾーン位置が見た目下に来るように見えます。
その場合は、譜面ヘッダー：stepYやstepYRを使って調整してください。
=> [0161/main-sprite-expansion] 矢印描画サイズを可変にする設定を追加

js/danoni_main.js
1. スコア上書きのためにハイスコア差分が計算されない問題を修正しました。
カスタムイベントの位置を以下のように見直しています。
- ハイスコア差分のdiv要素作成
- カスタムイベント
- ハイスコア差分の値計算、ハイスコアdiv要素の作成及び値計算
1. ver10.5.0において #557 を修正したことの影響修正です。
=> [0162/score-override] スコア上書きのためにハイスコア差分が計算されない問題を修正

js/danoni_main.js
titlegrdの2行目分($区切り以降)省略時、1行目分の値を使うようにしました。
以下のように指定するとタイトル1行目(foo)のみが表示され、2行目(bar)が表示されません。
```
|titlegrd=#ff0000|
|musicTitle=foo<br>bar|
```
[MFV2さんのツイートより](https://twitter.com/MFV2_/status/1233047646505275393)
=> titlegrdが1行分だけ指定されているとき2行目が表示されない問題の修正

css/danoni_main.css, js/danoni_main.js
1. ゲージ詳細テーブルをdiv要素に変更しました。
1. table要素を別にCSSクラスで定義していた場合、スタイルが上書きできないため。
=> [0163/div-gauge-table] ゲージ詳細テーブルをdiv要素に変更

js/danoni_main.js
1. ダミー矢印のヒット位置が前の通常矢印のヒット位置に引きずられる問題を修正しました。
直前の通常矢印でマターリを出していた場合、
その後のダミー矢印のヒットモーションで実際にはジャストタイミングであるにも関わらず、
マターリのようなヒットモーションになっていました。
1. 上述の通り。
- v10.4.0にて実装した内容の修正です。v11への修正も必要です。
=> [0165/dummy-step-hit] ダミー矢印のヒット位置が前の通常矢印に引きずられる問題を修正

js/danoni_main.js
1. Fast/Slowの表示をcustom関数の前に来るように修正しました。
1. Fast/Slowの表示がcustom関数の後にあったため、設定を上書きすることができませんでした。
今回の変更以降は上書きが可能になります。
```javascript
function customJudgeIi(difFrame){
document.querySelector(`#diffJ`).innerHTML = ``;
}
```
=> [0166/judge-diff] Fast/Slowの表示をcustom関数の前に来るように修正

js/danoni_main.js
- 矢印塗りつぶし部分の初期色に対してグラデーション他に対応しました。
以下の変更を行っています。
1. `setShadowColor`についても`setColor`の順序付けと連動し、
グループごとに色分けができるようになります。
1番目の要素のみ指定された場合は、すべての要素が1番目の要素に適用されます。
※Defaultを1番目の要素に指定した場合は、すべての要素がDefaultになります。
```
|setShadowColor=Default|
|setShadowColor=#ffff99,#880000,#990000|
```
2. カラーコード8桁と連動し、末尾2桁の透明度を`setShadowColor`についても
適用できるようにします。
通常のカラーコード6桁の場合は、自動で透明度を50%に調整します。
```
|setShadowColor=#ffff9955|
```
3. `setShadowColor`についても、`setColor`と同様にグラデーションが適用できるようになりました。
```
|setShadowColor=to left:#ff9999:#99ffff|
```
1～3. 塗りつぶし矢印に対して、通常の矢印と同様の拡張性を持たせるため。
- 将来のために、塗りつぶし矢印に対する色変化用の配列を作成しています。
=> [0167/shadow-color-alpha] 矢印塗りつぶし部分の初期色拡張、色変化対応

js/danoni_main.js
1. フリーズアロー初期色 (frzColor)が未定義の場合、
矢印初期色 (setColor) の値から適用する形式に変更しました。
2. 矢印初期色 (setColor)及びフリーズアロー初期色 (frzColor)の一部が未定義の場合の処理を変更しました。
- 一部しか定義されていない場合
```
|setColor=#ffff77,#ff99ff|
-> |setColor=#ffff77,#ff99ff,#ffff77,#ff99ff,#ffff77| と同義になります。
```
- 中間部省略の場合
```
|setColor=#ffff99|
|frzColor=,,#ffff33,#ffff99|
-> |setColor=#ffff99,#ffff99,#ffff99,#ffff99,#ffff99|
-> |frzColor=#ffff99,#ffff99,#ffff33,#ffff99$#ffff99,#ffff99,#ffff99,#ffff99$...| と同義になります。
```
1, 2 . 矢印色の記述方法を変えることで、使いやすさを上げるため。
=> [0170/frz-color-initialize] フリーズアロー初期色が未定義の場合の処理を追加

js/danoni_main.js
1. フリーズアローの塗りつぶし部分に対する設定を追加しました。
frzColorと同様、`$`区切りでグループごとに区切ります。
`通常時,ヒット時`のペアで表現します。
またsetShadowColorと同様、`Default`指定で`frzColor`の色（透明度：50%）になります。
```
|frzShadow=Default$Default$Default|
|frzShadow=#339999,#999933|
|frzShadow=#339999,#999933$#333399,#999933$#999999,#999933$...|
```
2. `defaultColorgrd`が有効のとき、フリーズアローが失敗したときの色までグラデーションを掛けないようにしました。
1. フリーズアローの塗りつぶし部分に関する機能拡張のため。
2. `defaultColorgrd`が無効のとき、フリーズアローが失敗したときの色にグラデーションを掛ける手段が無いため、仕様を合わせます。
1. frzShadowの`Default`指定を全てのグループに適用する場合は、
`$`区切りで全て指定が必要です。
=> [0171/frz-shadow-color] フリーズアロー(塗りつぶし部分)の初期色設定実装

js/danoni_main.js, js/danoni_setting.js
1. フリーズアロー(矢印)の塗りつぶし部分について、
6桁カラーコードで指定した場合に透明度が0.5⇒1になるように修正しました。
2. 従来の`frzColor`補完がされる設定を追加しました。デフォルトは`true`です。
```
|defaultFrzColorUse=false|
```
danoni_setting.js からも設定できます。
その場合の変数名は `g_presetFrzColors` です。
1. フリーズアロー(矢印)の塗りつぶし部分は通常、透明度100％のため。
2. 従来のfrzColorの省略形に対応するため。
=> [0172/color-gradation-alpha] frzShadowColorを6桁カラーコードで指定した場合の問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. フリーズアロー色（ヒット時）の色補完処理で、`defaultFrzColorUse`が有効のとき、
デフォルトのフリーズアローセットから取得できない問題を修正しました。
2. 一部変数のconstをletに変更しました。
- C_FRM_HITMOTION, C_FRM_JDGMOTION
1. 上述の通り。
2. カスタム側の実装緩和のため。
=> [0173/frzhit-color-etc] フリーズアロー色（ヒット時）の処理間違いを修正　他

js/danoni_main.js, js/lib/danoni_constants.js
1. Appearance設定に「Hidden+」「Sudden+」を追加しました。
隠れる箇所が可動フィルターとなっており、「pageUp」「pageDown」を押すことで
フィルターが上下に1%ずつ移動します。
- 初期値は10%(通常50px)です。可動域は0～100%の間で移動可能となっています。
- 「pageUp」「pageDown」はバーの横にパーセント表示がついている側を基準に上下させます。
（逆側は、それに合わせて反転して動きます。）
- リロードする間、フィルター範囲は保存されます。
- なお、Hidden+/Sudden+でフィルター範囲は共通となっています。
Hidden+のフィルター範囲を変えれば、Sudden+も連動して変わるようになっています。
- リザルトのTweetに、どのくらいフィルターを掛けたかをパーセント表示で表示します。
1. apoiさん要望より。
- プレイ中にpageUp, pageDownを押しっぱなしにすると動作が重くなることがあります。
ある程度フィルター位置を調整してから、
リトライを掛けて再プレイすることをおススメします。
=> [0174/appearance-filter] Hidden+, Sudden+の実装

js/danoni_main.js
1. 設定画面のフェードイン表示箇所のId変更（lblFadein -> lnkFadein）
2. キーコンフィグ画面のColorTypeボタンのId変更（lnkKcType -> lnkColorType）
1, 2 . いずれもID重複解消のため。
- 過去バージョンでも同様の修正が必要です。
=> [0176/duplicate-id] Id名の重複解消

js/danoni_main.js
1. 矢印色を優先してセットした場合のフリーズアロー色適用ルールを一部変更しました。
`danoni_setting.js`で定義された`g_presetFrzColors`が`false`、
もしくは譜面ヘッダー`defaultFrzColorUse=false`のとき、
frzColorが1要素でも定義されていれば、そのfrzColorの値を使用するよう変更しています。
```
|setColor=a,b,c,d,e|
|frzColor=A,B,C,D|
-> |frzColor=A,B,C,D$A,B,C,D$A,B,C,D$A,B,C,D$A,B,C,D|
|setColor=a,b,c,d,e|
|frzColor=A,B|
-> |frzColor=A,B,A,B$A,B,A,B$A,B,A,B$A,B,A,B$A,B,A,B|
|setColor=a,b,c,d,e|
|frzColor=,,A,B|
-> |frzColor=a,a,A,B$b,b,A,B$c,c,A,B$d,d,A,B$e,e,A,B|
|setColor=a,b,c,d,e|
-> |frzColor=a,a,a,a$b,b,b,b$c,c,c,c$d,d,d,d$e,e,e,e|
```
1. ParaFla作品からの移植の場合、frzColorが1要素だけ定義されているケースが多いため。
=> [0179/frz-color-complement] 矢印色を優先してセットした場合のフリーズアロー色適用ルールを一部変更

js/danoni_main.js
1. キーコンフィグ画面でdeleteキーが使用できず、キー無効化ができない問題を修正しました。
1. 上述の通り。
=> [0180/enabled-delete] キーコンフィグ画面でdeleteキーが使用できない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. Hidden+とSudden+を同時適用する「Hid&Sud+」を実装しました。
「pageUp」「pageDown」キーにて上下のフィルターを同時に操作します。
※上下のフィルターを個別に変えることはできません。
2. Hidden+, Sudden+適用時、適用するフィルターが片方しかない場合は
もう片方のフィルターの境界線を非表示にするよう変更しました。
3. Hidden+, Sudden+のショートカットをDisplay画面に表示するようにしました。
4. Appearance設定の順序を変更しました。
Visible -> Hidden -> Hidden+ -> Sudden -> Sudden+ -> Hid&Sud+ -> Slit
1. Hidden+とSudden+を同時に使用する需要を考慮。
2. 関係のないフィルターの境界線により、画面が見づらい可能性があるため。
3. ショートカットキーがわかりにくいため。
4. 関連性のある順番にするため。
- Hid&Sud+の可動域は0～50%です。
前回プレイでHidden+, Sudden+を選択しており、その際に51～100%にしていた場合、
強制的に50%に修正されます。
=> [0181/appearance-filter-plus] Hidden+&Sudden+の実装

js/danoni_main.js, js/lib/danoni_constants.js
1. Display:Judgementを種別ごとに分離しました。
合わせて、Judgementのスペルをアメリカ式(Judgment)に変更しています。
- Judgment (判定キャラクタ・コンボ)
- FastSlow (差分フレーム数表示)
- Score (現時点の判定数)
2. 1の変更に伴い、新たにDisplayオプションに応じた以下の設定ができるようになります。
```
|judgmentUse=false|
|fastSlowUse=false|
|scoreUse=false|
```
3. 過去互換として、|judgementUse=false|を指定した場合に限り
Judgment, FastSlow, Score を全て無効化するようにしました。
1. 判定表示を個別に非表示にするニーズに対応するため。
2. 1の変更に伴って実装。
3. 過去互換のため。
=> [0182/display-judgment] Display:Judgmentを種別ごとに分離

js/danoni_setting.js
- Displayオプションを一律無効化する設定について、
danoni_setting.jsのテンプレートを更新しました。
- Displayオプションを一律無効化するテンプレートが無かったため。
- danoni_setting.jsのみの変更です。
=> [0183/display-settings] Displayオプションのテンプレートを更新

js/danoni_main.js, js/lib/danoni_constants.js
1. Displayオプションに「filterLine」を追加しました。
「Hidden+」「Sudden+」「Hid&Sud+」設定時に表示するフィルターの境界線が消せるようになります。
2. 「pageUp」「pageDown」の説明文を簡略化しました。
1. フィルターの境界線が無くても、パーセント表記があれば判別がつく場合があるため。
2. 横幅が500pxのとき、説明文が2段になってしまうため。
=> [0183/display-replace] Display:filterLine実装、Displayオプションの配置変更

js/danoni_main.js, js/lib/danoni_constants.js, skin/danoni_skin_default.css, skin/danoni_skin_light.css, skin/danoni_skin_skyblue.css
1. 判定表示、歌詞表示、Hidden+/Sudden+用の境界線表示、
フィニッシュ演出の透明度を全体的に変更できる設定「Opacity」を追加しました。
Display画面から変更可能で、「10%」「25%」「50%」「75％」「100%(デフォルト)」
から選択できます。
2. Displayボタンを作成するコードを見直しました。
1. 矢印やフリーズアローを目立たせる手段の拡充のため。
2. 今後、ON/OFF以外のパターンを作成する場合に備えるため。
- 設定追加のため、skinデータの更新が入ります。
```css
.settings_Opacity::first-letter {
color:#999999;
}
```
=> [0186/display-alpha] Opacity設定を実装

js/danoni_main.js
1. Opacityオプションの仕様を一部変更しました。
judgeSpriteに対して一律透明度を設定するのではなく、
判定キャラクタ・Fast/Slow・Hidden+/Sudden+の境界線表示に絞って透明度を掛けるように変更しています。
1. judgeSprite, wordSprite（歌詞表示）は画面全体に透明度が掛かり
動作に影響するため。
=> [0187/display-alpha2] Opacity仕様を一部変更

js/danoni_main.js
1. startFrame/fadeFrame/endFrameの疑似タイマー表記に対応しました。
`|endFrame=分:秒.補正フレーム数|` の形式で記述します。
下記の2つの指定は同じ意味です。
```
|endFrame=1:30|
|endFrame=5400|
```
- なお、フレーム数レベルで調整したい場合は以下のように記述します。
(タイマーを入れた後、後ろにドット(.)を入れてその後ろに補正フレーム数を入れます)
```
|endFrame=3:02.30|
```
- もちろん、譜面毎の設定も可能です。
```
|endFrame=1:35.20$3:50.20|
```
1. 疑似タイマー表記は厳密には最終フレーム数ではないですが、
startFrame, fadeFrame, endFrameを手軽に使用できるようにするため。
1. 疑似タイマーのため、以下のような記述をしても一応動きます。
（混乱のもとになるので、やむを得ない事情を除いてはやらないことをおススメします）
```
|endFrame=:55| -> 0:55と同じ
|endFrame=0:90| -> 1:30と同じ
```
2. blankFrame, adjustmentは疑似タイマー非対応です。
これらは疑似タイマーよりもフレーム数を使用する傾向が強いため。
=> [0188/endframe-expantion] startFrame/fadeFrame/endFrameの疑似タイマー表記に対応

js/danoni_main.js
1. キーコンフィグ画面で、ローカルストレージに保存されている割り当てキー数が
対象キーの割り当て数に満たない場合（後で割り当て数を変えた場合など）に
undefinedが表示されてしまう問題を修正しました。
1. 上述の通り。
=> [0192/keyconfig-undefined] キーコンフィグ画面でundefinedが表示されることがある問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 上下非対称時のAppearance設定の挙動を変更しました。
stepYRが指定され上下スクロールで距離が異なる場合に、
上スクロール距離が下スクロール距離と同一になるように
可視範囲のフィルターを入れています。(stepYが大きい場合にも同様)
2. ステップゾーン位置関連の変数を`g_posObj`へ集約しました。
当面、既存変数は残します。
|旧変数|新変数|意味|
|g_stepY|g_posObj.stepY|ステップゾーン位置(上段)|
|g_distY|g_posObj.distY|矢印出現からステップゾーンまでの距離|
|g_stepYR|g_posObj.stepYR|ステップゾーン位置(下段)の補正値|
|g_reverseStepY|g_posObj.reverseStepY|ステップゾーン位置間(上段・下段)の距離|
1. stepYRが指定されると、上下のスクロール量に開きが出て
上スクロールが有利となってしまうため。
また、Hidden/Sudden時の位置が想定しない位置になってしまう。
2. コード整理、分類のため。
- 17keyの場合、フィルターの都合で横幅が最低800px必要になります。
- 今回の変更で、stepYが70以外を指定した場合、mainSpriteのサイズが変わります。
あまりないケースだと思いますが、このときmainSpriteの座標操作をしていると
位置ズレが起きる可能性があります。
=> [0195/appearance-filter-posdif] 上下非対称時のAppearanceの挙動変更

js/danoni_main.js, js/lib/danoni_constants.js
1. Display: MusicInfo適用時、最初の4秒のみ表示する形式に変更しました。
1. 元々は上下でスクロール表示量に開きが出ないよう調整するためのオプションだったが、
クレジット表記を残したことで問題がそのままになっていたため。
その代わり、cssアニメーションを利用し、最初の4秒ほどクレジットを表記することで、
何の曲か/誰の曲かがわかるように留意する。
=> [0196/display-musicinfo] Display:musicInfo時の挙動変更

css/danoni_main.css, js/danoni_main.js, js/lib/danoni_constants.js
1. Visible, Hidden, Suddenで矢印を見逃した場合に
矢印が画面にしばらく残ってしまう問題を修正しました。
2. 1.に伴い、Appearance「Silt」を廃止しました。
1. 上述の通り。
2. 1.の変更でHidden+/Sudden+の仕様に寄せたため、
フィルター仕様が複雑なSlitは一旦実装を見送ります。
- danoni_main.css にて下記の記述が不要になる予定。
```css
.Hidden0 {
clip-path: inset(50% 0% 0% 0%);
-webkit-clip-path: inset(50% 0% 0% 0%);
}
.Hidden1 {
clip-path: inset(0% 0% 50% 0%);
-webkit-clip-path: inset(0% 0% 50% 0%);
}
.Sudden0 {
clip-path: inset(0% 0% 40% 0%);
-webkit-clip-path: inset(0% 0% 40% 0%);
}
.Sudden1 {
clip-path: inset(40% 0% 0% 0%);
-webkit-clip-path: inset(40% 0% 0% 0%);
}
.Slit0 {
clip-path: polygon(5% 0%, 100% 0%, 100% 30%, 5% 30%, 5% 45%, 100% 45%, 100% 55%, 5% 55%, 5% 70%, 100% 70%, 100% 100%, 5% 100%);
-webkit-clip-path: polygon(5% 0%, 100% 0%, 100% 30%, 5% 30%, 5% 45%, 100% 45%, 100% 55%, 5% 55%, 5% 70%, …
```
=> [0198/filter-line] Appearance設定で矢印が画面上に残る事象を修正

css/danoni_main.css, js/danoni_main.js, js/lib/danoni_constants.js
1. 高速(5x以上)で矢印を見逃したとき、画面上に矢印が残ることがある事象を修正しました（再）。
フィルターの境界線を6.25%の透明度で表示するようにしました。
2. Appearance「Slit」を削除しました。
1. 上述の通り。
ChromeやFirefoxの場合、opacity=0やdisplay=noneでは解消されないことを確認済み。
2. 1.の変更でHidden+/Sudden+の仕様に寄せたため、
フィルター仕様が複雑なSlitは一旦実装を見送ります。
- danoni_main.css にて下記の記述が不要になります。
```css
.Hidden0 {
clip-path: inset(50% 0% 0% 0%);
-webkit-clip-path: inset(50% 0% 0% 0%);
}
.Hidden1 {
clip-path: inset(0% 0% 50% 0%);
-webkit-clip-path: inset(0% 0% 50% 0%);
}
.Sudden0 {
clip-path: inset(0% 0% 40% 0%);
-webkit-clip-path: inset(0% 0% 40% 0%);
}
.Sudden1 {
clip-path: inset(40% 0% 0% 0%);
-webkit-clip-path: inset(40% 0% 0% 0%);
}
.Slit0 {
clip-path: polygon(5% 0%, 100% 0%, 100% 30%, 5% 30%, 5% 45%, 100% 45%, 100% 55%, 5% 55%, 5% 70%, 100% 70%, 100% 100%, 5% 100%);
-webkit-clip-path: polygon(5% 0%, 100% …
```
=> [0199/filter-line-re] Appearance設定で矢印が画面上に残る事象を修正

js/danoni_main.js
1. APM表記をレベル計算ツール++に寄せるよう修正しました。
※startFrameを譜面開始位置、LastFrameを譜面最終位置＋1フレームとしています。
※LastFrameで1フレーム足している理由は譜面密度分割上の都合で、
　数値影響はほぼないと思います。
1. 最初の空白を含めてしまうことで、譜面密度の波に影響が出ることがあるため。
- g_detailObjの一部変数を変更しています。
- g_detailObj.playingFrame[_scoreId] 
-> 譜面開始位置～譜面最終位置(+1)までのフレーム数
- g_detailObj.playingFrameWithBlank[_scoreId] 
-> startFrame～譜面最終位置(+1)までのフレーム数
※従来のg_detailObj.playingFrame[_scoreId]
- 速度変化グラフはそのままです。
=> [0200/apm-calc] APM表記をレベル計算ツール++に寄せるよう修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 誤差1フレームでもFast/Slowを表示するように変更しました。
※現状ローカル時のみ。サーバ上はこれまで通り2フレーム以上の誤差があった場合に
　Fast/Slowを表示します。
　誤差の表示幅については、変更できる余地を残しています。
2. ±1フレーム以内で表示するJust表記を廃止しました。
3. Fast/Slowをカウントし、リザルトへ表示するようにしました。
1. Adjustmentの調整に必要という意見があるため。
2. Justだけ文字情報が他と違う等の理由で見づらいという意見があるため。
3. Fast/Slowを表示しているのに、どれだけ早いか遅いかを示す情報が無かったため。
- オート時はFast/Slowの表示は不要　⇒　対応済
- Fast/Slow非表示のときでも表示は行うか？　⇒　行う
- プレイ中でもFast/Slowの表示は必要？　⇒　現状は表示しない
（⇒既存作品のデザインに影響を与える可能性があり、当面は実装しない方が良さそう）
- Fast/Slowを表示幅をローカルとサーバ上で変える必要があるか？
⇒　ローカルは0フレーム、サーバ上は1フレーム以内で設定
- リザルトのFast/Slow表示により判定数の横幅が足りなくなるため、
`resultWindow`の横幅を360px⇒400pxへ変更します。
- また、Fast/Slow用に以下のラベルが増えます。
`lblFast`, `lblFastS`, `lblSlow`, `lblSlowS`
- 見逃しウワァンはカウントしません（変更しました）。
フリーズアローはFast/Slowの対象外です。
※フリーズアローの押し始めを判定する場合はFast/Slowのカウント対象です。
- `g_headerObj.justFrames` …
=> [0202/fastslow-setting] Fast/Slowのカウンタ追加、1フレーム誤差のFast/Slow表示

js/danoni_main.js
1. Twitter投稿用リザルトのURL表示に譜面番号を付加するようにしました。
下記のように、`scoreId=1`のようなクエリを付加します。
```
【#danoni】Combative InstinctⅡ(14k-Normal)/ティックル/Rank:F/Score:0/Playstyle:2.5x/0-0-0-0-0/0-0/0-0 http://localhost/danoniplus/danoni/danoni2.html?scoreId=1
```
- このクエリの付加方法は、URLクラスを利用しています。
すでに他のGETクエリがあった場合でも、その部分を保持しながらscoreIdを付与します。
```javascript
const twiturl = new URL(g_localStorageUrl); // scoreIdを除去したURL
twiturl.searchParams.append(`scoreId`, g_stateObj.scoreId);
// twiturl.toString() がTwitter用のパスに指定される
```
1. 1作品に譜面が複数入っていた場合に、
どれをプレイしたかをダイレクトパスで指定できるため。
`scoreId=2`（3譜面目）でアクセスしていながら実際には2譜面目をプレイした場合、
`scoreId=1`（2譜面目）をクエリに付加します。
=> [0203/twitter-url-query] Twitter投稿用リザルトのURL表示に譜面番号を付加

js/danoni_main.js
1. パイプ、アンパサンド等の特殊文字へ置き換えるための代替文字を準備しました。
|指定文字|代替先|
|----|----|
|\*pipe\*|\||
|\*amp\*|&amp;|
|\*rsquo\*|&rsquo;|
|\*quot\*|&quot;|
- 区切り文字等で使用しており、値に使用できなかったため。
=> [0204/pipe-escape] パイプ、アンパサンド等の特殊文字の置き換え

js/danoni_main.js
1. カンマのエスケープ対応を行いました。
|指定文字|代替先|
|----|----|
|\*comma\*|\,|
1. カンマを曲名に充てるケースがそれなりにあるため。
=> [0205/comma-escape] カンマのエスケープ対応

js/danoni_main.js
1. Appearanceで使っているフィルターの仕様をv14.2.0に戻しました。
1. v14.3.xで、一旦枠の上下の境界線を`visibility:hidden`に変更しましたが、
v14.1.0の問題が再発したため、元に戻します。
=> [0206/filter-cover] Appearanceで使っているフィルターの仕様をv14.2.0に戻す

js/danoni_main.js
1. Fast/Slowカウントの誤りを修正しました。
1. サーバ上でプレイしたときに、Slowが過剰にカウントされるようになっていました。
=> [0207/fast-slow-cnt] Fast/Slowカウントの誤りを修正

js/danoni_main.js
1. countFastSlowの引数忘れを修正しました。
1. 上述の通り。
これをしないとサーバ上でのFast/Slow数が0フレーム以外カウントとなってしまう。
=> [0208/fast-slow-cnt2] countFastSlowの引数忘れを修正

js/danoni_main.js
1. 特殊文字のエスケープ対応を行いました。
カンマやアンパサンドが使えるように必要箇所にエスケープするよう修正しています。
|指定文字|変換先|読み方や意味|
|\*pipe\*|\||パイプ|
|\*amp\*|&amp;|アンパサンド、and|
|\*rsquo\*|&rsquo;|シングルクォート、アポストロフィ|
|\*quot\*|&quot;|ダブルクォート|
|\*comma\*|\,|カンマ|
|\*dollar\*|$|ドル|
1. 必要箇所に対してエスケープを掛けないと想定した文字が使用できないため。
=> [0209/escape-keys] 特殊文字のエスケープ対応

js/danoni_main.js
1. `danoni_setting.js`で`g_presetSettingUse`に対してdisplay設定を有効にした場合、
ボタンの初期値がOFFになってしまう問題を修正しました。
（ボタンは押せる状態）
```javascript
const g_presetSettingUse = {
fastSlow: `true`,
filterLine: `true`,
};
```
1. `g_presetSettingUse`のdisplay設定における2要素目未指定時の値補完ミス。
なお、`true`という指定は指定しない（コメントアウト）状態と同じため、
現行バージョンでもコメントアウトすれば、この問題は発生しません。
```javascript
const g_presetSettingUse = {
// fastSlow: `true`,
// filterLine: `true`,
};
```
- そこまで大きな問題ではないため、次のリリースにて合わせて対応予定です。
- また、実装方法が違うため過去バージョンでは発生しません。
=> [0210/default-display-setting] setting.js側で本来不要なdisplay設定を行ったときの挙動を修正

js/danoni_main.js
1. Tweet投稿リザルトで曲名・制作者名の後に半角空白を追加しました。
1. 曲名・制作者名が日本語（全角）のとき、その後続データが半角が多い関係で、
意図しない箇所で改行されてしまうため、区切り用の半角スペースを設ける。
=> [0212/tweet-split-blank] Tweet投稿リザルトで曲名・制作者名の後に半角空白を追加

js/danoni_main.js
1. 譜面数が5を超える場合、自動で譜面セレクターを使用するよう変更しました。
譜面数が5を超える場合で譜面セレクターを使用したくない場合は、
譜面ヘッダーにて以下の設定が必要となります。
```
|difSelectorUse=false|
```
1. 譜面数が多い場合、譜面セレクターを使用した方が利便性が高いため。
=> [0213/auto-difselector] 譜面数が5を超える場合、自動で譜面セレクターを使用するよう変更

js/danoni_main.js
1. 歌詞表示の一部でエスケープ処理が利いていない問題を修正しました。
1行当たりの歌詞項目数が4～5のときに発生します。
2. tuningに対してエスケープ処理を追加しました。
3. 以下の文字に対して新たに特殊文字として追加しました。
|指定文字|変換先|読み方や意味|
|\*rsquo\*|’|アポストロフィ　※分離|
|\*squo\*|'|シングルクォート|
|\*bkquo\*|`|バッククォート|
1. 上述の通り。エスケープ処理の入れ忘れです。
2. tuningに対してエスケープ処理が無かったため。
3. アポストロフィ、シングルクォートが厳密には異なる文字だったため。
=> [0215/lyrics-replace] 歌詞表示の一部でエスケープが利いていない問題を修正

js/danoni_main.js
1. 外部リンクに対してオンマウスでURLを表示するように変更しました。
1. リンク先がデッドリンクかどうかを判断するための情報が現状無いため。
=> [0216/link-hover] 外部リンクに対してオンマウスでURLを表示

js/danoni_main.js
1. ロード画面の譜面読込前にカスタム関数を追加しました。
1. 将来的にエディター用スキンを作成することを想定し、
譜面読込前に譜面データを割り込ませることで譜面プレビューできる余地を作ります。
=> [0217/custom-preload] ロード画面の譜面読込前にカスタム関数を追加

js/danoni_main.js
1. フリーズアロー始点判定時の矢印分がライフ増減値に反映されない問題を修正しました。
1. 上述の通り。
- 影響範囲は ver15.0.0 のみです。
=> [0221/calc-lifeval] フリーズアロー始点判定時の矢印分がライフ増減値に反映されない問題を修正

SECURITY.md, js/danoni_main.js
=> [ver15.0.1] [ver15.0.1] フリーズアロー始点判定有効時の矢印分がライフ増減値に反映されない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 以下の譜面データでフレーム・深度等に数式が使えるよう変更しました。
- speed_data(change), boost_data のフレーム数、速度
- color_data, acolor_data のフレーム数、矢印種別
- word_data のフレーム数、深度
- back_data, mask_data のフレーム数、深度
※タイトル・リザルトモーション及びリバース・Alt系の対応を含みます。
```
|back_data=
200,0,（省略）
200+40,0,（省略）
200+60,0,（省略）
|
```
2. setVal関数に数式に変換するオプションを追加しました。
typeに`C_TYP_CALC`と指定します。
setVal関数内で、数式に変換後計算した値を返却します。
- undefined, null, 空値をチェックします。
- 数式が間違っている場合はデフォルト値を適用します。
1. FrameNumが変わった場合に一括置換しやすくするため。
後で見返した場合に同じ系統の表示かどうかの判別がつきやすくなるため。
2. 1.の対応に伴い追加しました。
=> [0222/animation-frame-calc] 譜面効果データでフレーム・深度等に数式が使えるよう変更

js/danoni_main.js
1. タイトル文字(#lblmusicTitle)のサイズを見直しました。
1. タイトル文字(#lblmusicTitle)位置について、
過去の経緯で横幅が枠の3倍に設定されており、テーブルタグが使いにくい状況のため。
=> [0228/musictitle-pos] タイトル文字のサイズを見直し

js/danoni_main.js
1. MaxComboが初期化されない問題を修正しました。
1. PR #715 で、コード整理を行った際のコードミスの修正です。
- v15.1.0に対する修正です。他のバージョンには影響しません。
=> [0229/maxcombo] MaxComboが初期化されない問題を修正

js/danoni_main.js
1. 特殊キーの後に通常キーの譜面があると譜面選択できない問題を修正しました。
1. g_localKeyStorageが未定義のタイミングで`g_localKeyStorage.reverse`に値を格納しているため。
1譜面目の場合、setDifficultyの_initFlgが`false`であり、
通常/特殊キーによらずこの格納処理が素通りされるため問題は発生しない。
- 過去バージョンでも再現あり。修正が必要です。
=> [0230/extra-key-after] 特殊キーの後に通常キーの譜面があると譜面選択できない問題を修正

js/danoni_main.js
1. フリーズアローヒット時の矢印色が変化しない問題を修正しました。
1. ver15.1.0にてコード整理の一環で`changeFrzColors`関数を整理しましたが、
その際の条件式に誤りがありました。
=> [0231/frzcolor-changed] フリーズアローヒット色の変化誤りを修正

js/danoni_main.js
1. Background:OFF時にjdgYを初期化する処理を追加しました。
1. Issue #714 より。
背景・マスク表示による判定キャラクタ位置を調整するため、
arrowJdgY / frzJdgY という判定・コンボ位置の調整機能があるが
Background: OFF時は元に戻した方がいいことが多いため。
=> [0232/jdgY-reset] Background:OFF時にjdgYを初期化する処理を追加

danoni/danoni0.html, js/danoni_main.js, js/sample/danoni_custom-003.js
1. コメント文をタイトルに表示する機能を実装しました。
譜面内に下記のように記載することでコメントエリアがタイトル画面に表示され、
その中にコメントが表示されます。
改行すると`<br>`タグが自動で付加される仕様です。タグも使用可能にしています。
```
|commentVal=
このような形で
コメントを入れます。
|
```
2. 自動で`<br>`を入れたくない場合は下記のように指定できるようにしました。
※デフォルトは`true`(自動改行タグ挿入が有効)です。
```
|commentAutoBr=false|
```
3. コメントをタイトル画面からのボタンではなく、
ダンおに本体の外部に置きたい場合は下記の譜面ヘッダーを指定します。
※デフォルトは`false`(コメントをタイトル画面内に配置する)です。
```
|commentExternal=true|
```
外部化する場合、html側で次の指定を行います。
指定した箇所が、コメント部に置き換えられます。
```html
<span id="commentArea"></span>　※divタグでも問題ありません。
```
1. コメント表示を手軽に載せる需要より。
2. 移植等で、すでに`<br>`を入れている可能性があるため。
3. html本体を簡素化し、譜面本体で制御できるようにするため。
- 特殊文字は[Wiki](../wiki/SpecialCharacters)を参考にエスケープが必要です。
（特にシングルクォート、バッククォートには要注意）
ダブルクォートは譜面データの区切り文字には使用されていないため、必須ではありません。
=> [0233/title-comment] コメント文をタイトルに表示する機能を実装

js/danoni_main.js
1. 通常キーであらかじめデフォルトセットされているキーコンフィグパターンと
異なるキーを割り当てた際、初回保存時のみそのキーがリセットされる問題を修正しました。
1. 上述の通りです。
なお、独自キーの場合はこの事象は発生しません。
- 影響範囲、起因となったバージョンは調査中です。
=> [0235/keyconfig-iniset] キーコンフィグ保存時の問題を修正

js/danoni_main.js
プレイ中の画面で `Event.preventDefault()` を呼ぶようにしました。
プレイ中にブラウザショートカットが発火したりするのを防ぐため。
一応動作確認は入れていますが、問題あれば取り下げてください。
=> プレイ中に他のキーイベントが呼ばれないようにする

js/danoni_main.js
- 共通設定ファイル `danoni_setting.js` にて`g_presetOverrideExtension` に`png`を設定した場合、
キーコンフィグ画面で使用するカーソルが `cursor.png`ではなく`cursor.svg` を使用する問題を修正しました。
- また合わせて、上記の際にpngファイルではなくsvgファイルをpreloadしてしまう問題を修正しました。
- Resolves #746 
- preloadの問題に関しては下記のように修正しています。
- v15.1.0の問題に対する修正です。
=> [0236/svg-cursor] 主要画像がpngのときの参照誤りを修正

js/danoni_main.js
- CustomGauge使用時にクリア失敗時のリザルトモーションが使用できない問題を修正しました。
- Resolves #749 
- v9, v13, v14にも修正が必要です。
=> [0237/failed-animation] Failed時のリザルトモーションがカスタムゲージで使用できない問題を修正

js/danoni_main.js
- 歌詞表示について、次の条件を全て満たした場合のみ、歌詞表示の上下を反転します。
- 上下スクロールを挟まないキーに限定（5key, 7key, 7ikey, 9A/9Bkeyなど）
- リバース・スクロール拡張用の歌詞表示（wordRev_data / wordAlt_data）が設定されていない作品
- SETTINGS 画面で Reverse：ON、Scroll：`---` (指定なし) を指定してプレイ開始した場合
- 歌詞表示がすべて1段表示の場合（2段の場合、反転すると文字が重なる場合があるため）
- Resolves #747 
- 歌詞表示＆2段の場合の取り扱いを考慮する必要があります。
=> [0238/reverse-lyrics] Reverse時に歌詞を上下逆の位置に表示するよう変更（条件あり）

js/danoni_main.js, js/danoni_setting.js
- Issue #747 にて、Reverse時に歌詞表示を条件付きで反転する機能を実装しましたが（ver15.3.0）、
back/mask_dataとの兼ね合いや、word_dataの歌詞以外の使われ方により
意図せず反転されてしまうケースがあるため、個別/全体にこの自動制御ができるようにします。
- 譜面ヘッダー仕様（作品個別用）：wordAutoReverse
- danoni_setting.js（作品全体）：g_presetWordAutoReverse
|値|既定|内容|
|auto|*|Reverse時に歌詞表示を条件付きで反転する|
|OFF||Reverse時に歌詞表示を反転しない|
|ON||Reverse時に条件を満たさなくても歌詞を反転する　※|
※スクロール拡張（Cross, Splitなど）を設定している場合や、
　wordRev_dataが含まれている場合は反転しません。
　11keyなど本来適用しないキーや、歌詞が2段になっているケースが反転可能です。
- Resolves #754 
- 特にありません。
=> [0239/reverse-lyrics-setting] Reverse時の歌詞の自動反転制御設定を追加

js/danoni_main.js
- word_data で使用するフォントのサイズを変更できる設定を追加しました
- `[fadein]`や`[center]`等と同様に`[fontSize=XX]`として指定します
例
```
400,0,[fontSize=20]
```
歌詞表示全体をデフォルトサイズ(14px)以外で統一したい場合、
全ての歌詞に対してHTMLタグの付与が必要であることから記述簡略化のため
- 理論的には`[fontSize=XX]`という歌詞を持つ作品が存在すれば影響を与えますが、考慮しなくていいでしょう
=> word_data でフォントサイズの変更を可能にする

js/danoni_main.js
- バージョン比較リンクの代わりに、Security Policyへリンクするよう変更しました。
- アイコンについても、&#x2194;`&#x2194;`から&#x1f6e1;`&#x1f6e1;`へ変更しています。
- Resolves #759 
- 過去バージョンへも反映が必要です。
=> [0240/security-link] SecurityPolicyへのリンクを追加

js/danoni_main.js
- キーコンフィグ画面のConfigTypeを変更する際、カーソル位置が極力、元に戻らないよう変更しました。
- キーコンフィグ関係のコード重複を一部改善しました。
- Resolves #767 
- 特にありません。
=> [0244/reset-keyconfig] ConfigType変更時のカーソル挙動改善

js/danoni_main.js
- ゲージ明細画面の各要素にidを割り振りました。
- Resolves #778 
-
=> [0247/gauge-details-id] ゲージ詳細表示部分のID割り当て

js/danoni_main.js
- 「Windows」キーと「Shift」キーが同時押しされている場合、キー割り当てされないよう変更しました。
- Resolves #776 
- キーコンフィグ本体の挙動を確認してからマージします。
=> [0245/keycon-capturing] Winキー+Shiftキーでキーコンが反応しないようにする変更

js/danoni_main.js
1. リトライ時に稀に早回しになる不具合を修正しました
2. キーリピートを無効化しました
3. 軽微な不具合を修正しました
原因として、リトライで`musicAfterLoaded`が呼び出されるときプレイ中の`keydown`イベントハンドラが残っており、
条件不明ですがここで`readyState === 4`になっていないと`canplaythrough`待ちが発生します。
そのときbackspaceキーによる`keydown`が発火すると`musicAfterLoaded`が複数呼び出され、
結果としてメインループが多重に走ってしまうようです。
以下のように意図的に遅延させると疑似的に再現できます。
```
function musicAfterLoaded() {
g_audio.load();
setTimeout(function () {
if (g_audio.readyState === 4) {
// (省略)
}
}, 1000);
}
```
上記問題を解決するため、`clearWindow`内で`keydown`イベントを初期化するように変更しました。
通常、画面遷移時はキーイベントを新しく設定すると思われるため、同様の不具合を防ぐ意味でここにしています。
上記問題の直接の原因ではありませんが、意図しない動作を起こしやすいため無効にしました。
`loadMusic`内の`keydown`イベントで`transCode`が抜けていたのを修正しています。
これは私が作ってしまったバグですかね……。
申し訳ないです。
=> リトライ時に稀に早回しになる不具合の修正 +α

js/danoni_main.js
- 20個以上のキーに対して、単発矢印・個別の色変化ができない問題を解消しました。
矢印番号に1000を足します。
グループ指定についてはこれまで通りです。
```
|color_data=200,2,#ff9966| <- 単発矢印の3番目の要素の色を変更します。
|color_data=200,1002,#ff9966| <- 単発矢印の3番目の要素の色を変更します。
|color_data=200,22,#ff9966| <- 矢印グループ2（斜め矢印すべて）の色を変更します。
|color_data=200,1022,#ff9966| <- 単発矢印の23番目の要素の色を変更します。
```
- Resolves #807 
- グループ指定については据え置き、そのままとします。
=> [0260/color-upper20] 20個以上のキーに対する色変化対応（単発矢印・個別）

js/danoni_main.js, js/danoni_setting.js
- リザルトデータ用フォーマットを実装しました。
```
|resultFormat=【#danoni[hashTag]】[musicTitle]([keyLabel]) /[maker] /Rank:[rank]/Score:[score]/Playstyle:[playStyle]/[arrowJdg]/[frzJdg]/[combo] [url]|
```
```javascript
const g_presetResultFormat = `【#danoni[hashTag]】[musicTitle]([keyLabel]) /[maker] /Rank:[rank]/Score:[score]-[exScore]/Playstyle:[playStyle]/[arrowJdg]/[frzJdg]/[maxCombo] [url]`;
```
- カスタム変数もリザルトデータに追加することができます。
共通設定 (danoni_setting.js)の`g_presetResultVals`のプロパティに追加します。
追加したプロパティは、`g_resultObj`配下に定義する必要があります。
（下記の場合、[exScore] とフォーマットに入れた場合、`g_resultObj.exScores`に置き換えられます。）
```javascript
const g_presetResultVals = {
exScore: `exScores`,
};
```
- Resolves #809 
- リザルトデータ用フォーマットでパイプなど特殊文字を使用する際は、
下記ページのルールに従います。
https://github.com/cwtickle/danoniplus/wiki/SpecialCharacters
=> [0261/result-format] リザルトデータ用フォーマットの実装

js/danoni_main.js
- スコアをカスタムした際にリザルトデータへ反映されない問題を修正しました。
- 先の #813 の実装により、リザルトデータがカスタムイベント前に移っていましたが、
この場合スコアを上塗りした場合に問題がありました。
=> [0262/fix-resultdata] スコアをカスタムした際にリザルトデータへ反映されない問題を修正

js/danoni_main.js
- フリーズアローが無い場合、スコア貼り付け用の書式を一部省略するよう変更しました。
```
Before: .../350-30-7-2-9/0-0/140-0/...
After : .../350-30-7-2-9//140/...
```
- Resolves #817 
- 結果画面本体に手を入れるかどうかは一旦保留します。
=> [0263/abbreviate-frz] リザルトデータでフリーズアローが無い時の表記を変更

js/danoni_main.js
1. Ready表示をカスタムjsの前に配置しました。
2. Ready表示に関するアニメーション設定を実装しました。（譜面ヘッダー）
3. フェードイン有効時はreadyDelayFrameを無効にする設定を追加しました。
|譜面ヘッダー名|用途|
|----|----|
|readyAnimationFrame|Readyをアニメーションするフレーム数（既定：150フレーム）|
|readyAnimationName|Readyのアニメーション名（既定：leftToRightFade）|
|readyColor|Readyの先頭色（既定：1番目の矢印色）|
1, 2. Ready設定を見直したい場合に見直す手段が無いため。
3. Resolves #819 
- 余力があれば、Readyの表示時間をヘッダーで変更できるようにします。⇒対応しました。
=> [0264/ready-pos] Ready表示に関するカスタム設定実装

js/danoni_main.js
1. Firefox使用時の表示位置補正を廃止
2. 不要コード削除、整理
1. 実装時はFirefoxのみでレイアウトがズレていたため補正していたが、
現在はブラウザのアップデートでズレがなくなっているため
2. changeイベントの発火条件はinputイベントに含まれているため削除
その他は可読性向上のため
- 特になし
=> Fadeinスライダーのデザイン修正、コード整理

js/danoni_main.js
- `location.reload`の引数をカットしました。
- `location.reload`の引数が現状のブラウザでは無効になっているため、外します。
- 現状、リロードボタン・ローカルデータ削除時に使用しています。
- 特にありません。
=> [0266/reload] location.reloadの引数をカット

js/danoni_main.js
- リザルト表示（CLEARED / FAILED）に対する遅延フレーム設定を実装しました。
下記のように使用します。
CSSの`animationDelay`属性を利用した遅延設定です。
0フレーム（デフォルト）の場合、途中終了した場合は`animationDelay`属性の設定自体を行いません。
```
|resultDelayFrame=1000|
```
- Resolves #824 
- 特になし
=> [0267/result-delay] リザルト表示に対する遅延フレーム設定を実装

js/danoni_main.js
- CSSの`user-select`について、`webkit-`プレフィックスを戻し、
`khtml-`プレフィックスを削除しました。
- CSSの`user-select`はSafariでは`webkit-`プレフィックスが必要なため。
非推奨となっているが、互換として残すようにします。
一方、`khtml-`プレフィックスは「Can I Use」でも使っているところが無いため、削除します。
https://caniuse.com/?search=user-select
- 特になし
=> [0270/user-select] user-selectのwebkit-を戻し、khtml-を削除

js/danoni_main.js
- フェードイン時、フリーズアローの計算処理で止まる問題を修正しました。
- ver17.0.1の #839 の修正漏れです。
- 特になし
=> [0276/calc-frz] フェードイン時、フリーズアローの計算処理で止まる問題を修正

js/danoni_main.js
1. 既存のボタンの処理に対して追加カスタム処理を挿入できる機能を実装しました。
customjsのそれぞれの画面別関数にて設定します。
```javascript
function customTitleInit() {
g_btnDeleteFlg.btnStart = true;  // g_btnDeleteFlg.(ボタンID) = true でボタンIDが行っている処理をやめる
g_btnAddFunc.btnStart = _ => {
commentInit(); // g_btnAddFunc.(ボタンID) に関数を定義することでその処理を後から挿入
};
}
```
2. ボタン及びラベルのスタイル一括変更関数を実装しました。
ボタンやラベルのIDを指定し、それに対して一括でスタイルを指定します。
中括弧部分の仕様は`createCss2Button`や`createDivCss2Label`の`_obj`と同じにしています。
なお、こちらは変更する前提のため初期値はありません。変更があった箇所のみ変更します。
```javascript
changeStyle(`btnSave`, {x: 20, y: 30, w:170, h:45, siz:14, align:C_ALIGN_RIGHT`});
```
参考：
https://github.com/cwtickle/danoniplus/wiki/fnc-c0002-createDivCss2Label
1. ボタン処理に対する割込み制御できる本来の方法が無かったため。
2. ボタンやラベルのスタイル変更をまとめて管理できるようにするため。
- ボタン処理を上書き（`g_btnDeleteFlg`を有効）にする場合、本来の処理が無くなるため …
=> [0275/button-expansion] ボタン処理の割り込み制御の実装

js/danoni_main.js
- 制作者URL, 楽曲提供者URLが入っていない場合、初期値を空にするよう変更しました。
- リンクを開く際、URL形式になっているかを簡易チェックするようにしました。
- getQueryParamVal関数をsearchParamを使って簡素化しました。
- デフォルトが自身のURLになっていましたが、本来リンクさせる必要が無いため。
- 特になし
=> [0278/fix-url-initial] URL初期値に自身のURLを充てないよう変更

js/danoni_main.js
- 譜面ヘッダー：`tuning`が単一指定され、URLの指定が無い場合に制作者リンクが出ない問題を修正しました。
- 上述の通り。
- 過去バージョンでも同様の事象になっている可能性があります。
=> [0281/creator-url:0.1.0] tuningのみ指定があった場合に制作者リンクが出ない問題を修正

js/danoni_main.js
1. titlefontについてフォントを複数指定できるよう変更しました。
```
|titlefont=Century$Century Gothic,Century|
```
2. titleposについて2行目を指定できるようにしました。
Y座標についてはtitlelineheightとは別指定で、両方指定された場合は両方適用されます。
※1行目位置を基準にずらします。
```
|titlepos=0,0$50,0| // 1行目のX, Y座標、2行目のX, Y座標の順に指定
|titlelineheight=40|
```
1. 2行目のフォント変更に対応するため。
2. 2行目の座標調整をしやすくするため。
- 特になし
=> [0282/title-2nd] タイトル文字の2行目文字に対する変更

js/danoni_custom.js, js/danoni_custom2.js, js/danoni_main.js, js/danoni_setting.js, js/lib/danoni_constants.js, js/lib/danoni_legacy_function.js, js/lib/danoni_localbinary.js, skin/danoni_skin_background.js, skin/danoni_skin_blank.js, skin/danoni_skin_default.js, skin/danoni_skin_light.js, skin/danoni_skin_skyblue.js
- strictモードが機能していなかったので修正しました
use strict はシングルorダブルクオートで囲う必要があるため
- strictモードが実行されることにより一件エラーが発生しましたが、単純な変数宣言漏れだったためついでに修正しています
=> strictモードが機能するよう修正

js/danoni_main.js
- カスタムゲージで一部未指定がある場合にボーダー値が反映されない問題を修正しました。
- gaugeXXXでボーダー値が未指定の譜面があった場合、ボーダーが0%になっていました。
- ver17.3.0のみに影響します。
=> [0286/reset-border] カスタムゲージで一部未指定がある場合にボーダー値が反映されない問題を修正

js/danoni_main.js
- ツール値出力時、時間表示がおかしくなることがある問題を修正しました。
- 最初の矢印を取得する処理で、初期値にInfinityが入っているため
データが無い場合に、時間表示を再計算する際にInfinityが入ってしまっていました。
- 過去バージョンも修正が必要です。（ver12以降）
=> [0287/copy-time] ツール値出力時、時間表示がおかしくなることがある問題を修正

js/danoni_main.js
- 矢印の塗りつぶしをしており、Display設定のStepZoneをOFFにしたとき
下段のステップゾーンが見える問題を修正しました。
- 背景グラデーションにより、背景が黒で無い場合やスキンのケースに
ステップゾーンの塗りつぶし部分が対応できていませんでした。
- 過去バージョンも修正が必要かもしれません。
=> [0292/reverse-stepshadow] 矢印塗りつぶし有、ステップゾーンをOFFにした場合の表示問題を修正

js/danoni_main.js
1. 複数子要素を親要素へ追加する処理を集約しました。
以下の関数で行います。
```javascript
multiAppend(親要素, 子要素1, 子要素2, ...);
```
2. ボタン作成関数 (createCss2Button) に右クリック時の処理を追加しました。
プロパティ：`cxtFunc`にて指定します。
```javascript
createCss2Button(`btnReverse`, `Reverse:${g_stateObj.reverse}`, evt => {
setReverse(evt.target);
}, {
x: 160, y: 0,
w: 90, h: 21, siz: C_SIZ_DIFSELECTOR,
borderStyle: `solid`,
cxtFunc: evt => setReverse(evt.target),
}, g_cssObj.button_Default, g_cssObj[`button_Rev${g_stateObj.reverse}`])
```
3. ボタンの追加処理と同様、右クリック時の追加処理を追加しました。
それぞれ以下で指定できます。
```javascript
g_cxtDeleteFlg.btnStart = true;  // g_cxtDeleteFlg.(ボタンID) = true でボタンIDの右クリック処理をやめる
g_cxtAddFunc.btnStart = _ => {
commentInit(); // g_cxtAddFunc.(ボタンID) に関数を定義することでその処理を後から挿入
};
```
1. ラベル・ボタンが多く、何度も`appendChild`を書く必要があるため。
2. 右クリック処理をボタン処理と分離して書く必要があったが、 …
=> [0295/multi-append] 複数子要素を親要素へ追加する処理を集約

js/danoni_main.js
- 複数曲搭載時、結果画面で2段目がundefinedになる問題を修正しました。
※元々2段目がある曲名の場合や、単一曲では発生しません。
- 上述の通り。
- v17でコード修正した影響のため、v17にも適用する必要があります。
=> [0301/2nd-title-undefined] 複数曲搭載時に2段目がundefinedになる問題を修正

js/danoni_main.js
- 速度データが空の場合、データがあると判断されてしまう問題を修正しました。
- 下記の場合に`speed_change`が優先されていました。
`g_rootObj`はデータの置き換えではなく上書き（マージ）を行うため、
譜面番号固定時に下記の事象が発生する場合がありました。
```
|speed_data=200,0.5,3000,1|
|speed_change=|
```
- 過去バージョンにも同様の記述があるため、見直しが必要です。
=> [0302/speed-blank] 速度データが空の場合、データがあると判断されてしまう問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. Display設定周りのローカルストレージ保存に対応しました。作品ごとに保管します。
- Appearance, Opacity設定及び、
DisplayのStepZone, Judgment, FastSlow, LifeGauge, Score, MusicInfo, FilterLineについて
ローカルストレージに保存する対象に追加しました。
2. Adjustment, Volume, Appearance, Opacityに限り、ローカル保存している設定を選択時に
アスタリスクを付けるように変更しました。
1. Resolves #881 
2. 保存値がデフォルトかどうかがわからないため。
なお、Reverseはキー毎のローカルストレージに保管されているため、アスタリスクは付きません。
スクロール拡張対応キーであれば、Reverse:ON時に色が付くので、そこまで問題にはならないと思います。
※スキンを考慮する必要があったため、色で分けずにアスタリスク表記にしました。
- Hidden+, Sudden+, Hid&Sud+で設定するフィルター範囲についても保存することを検討しましたが、
こちらはパラメーターが共通のため、対象からは外しています。
=> [0303/storage-display] Display設定周りのローカルストレージ対応

js/danoni_main.js, js/lib/danoni_constants.js
1. 強制的にグラデーションを反転 (defaultColorgrdを反転)にする設定を追加しました。
ColorType: Type0 が該当します。
Type0選択時は、色変化部分を含めて中央が白色のグラデーションが掛かります。
2. defaultColorgrdの2つ目の要素を追加しました。グラデーションで挟む色を指定できます。
この2つ目の要素は省略可能です。
```
|defaultColorgrd=true,#ffffcc|
```
3. ConfigType, Colortypeの逆回し操作に対応しました。右クリックにて逆回し可能です。
1. Issue #745 に関連した変更です。
色が見づらい場合の明暗設定の案の1つとして実装しています。
2. 明背景の場合の見づらさに対応するため。
3. パターンが増えた場合に備えるのと、他の設定項目と操作を共通化するため。
左右のボタンを追加するかどうかは一旦保留します。
- 元からグラデーションが掛かっている場合、「Default」と「Type0」が同じになる場合があります。
- Type1, Type2はそのままです。グラデーションしません。
- 明背景に対応するために、defaultColorgrdの引数拡張を予定しています。
=> [0305/grd-setting] 強制グラデーション設定の実装

js/danoni_main.js, js/lib/danoni_constants.js
1. 背景・マスクモーションの画像形式にsvg形式を追加しました。
2. 背景・マスクモーションの画像形式にjpg形式の他、jpeg形式にも対応しました。
1. ベクタ形式への対応のため。Gitter要望より。
2. jpg形式についてはたまにjpeg拡張子が存在するため。
これについては大文字のケース（例：BMP, JPG等）にも対応しました。
- danoni_constants.js に変更を加えています。
g_imgObj.imgExtensions に対象の拡張子名を設定することで対象を増やせるように改良しました。
=> [0306/image-group] 背景・マスクの画像ファイル対象にsvgを追加

js/lib/danoni_constants.js
- タグ用括弧のエスケープ文字を追加しました。
`*lt*`⇒`<`, `*gt*`⇒`>`に置き換えます。
- #895 の実装に伴い、タグ以外の意味で`<`や`>`を使う場合に支障が出るため、
代替文字を用意しました。
=> [0310/escape-bracket] タグ用括弧のエスケープ文字を追加

js/danoni_main.js
- Firefoxで画像のプリロードができるよう画像の読込処理を追加しました。
※その他のブラウザについてはこれまで通りです。
- Resolves #899 
- 処理影響は無いと思いますが、画像が多い場合、
Firefoxのプレイ開始に若干のラグが出る可能性があります。
=> [0314/preload-firefox] Firefoxで画像のプリロードを有効にする変更

js/danoni_main.js
- 曲終了判定時にキーイベントを初期化するようにしました
- 曲終了後、setTimeoutでリザルトに移行するまでの間、リトライキーを押すとリザルトの判定が全て0になります
- [izkdicさんの配信](https://twitter.com/vdos2643/status/1340684397381468166)
- [関連ツイート](https://twitter.com/vdos2643/status/1340689775565533184)
- setTimeoutの待ち時間を1000(ms)などにすると簡単に再現できます
- 超処理落ちや急加速は私は再現できず、原因も分かりませんでした
=> 曲終了直後にリトライキーを押すとALL0のリザルトが表示される問題の修正

js/danoni_main.js
1. ライフ制ゲージ設定にHeavyを追加しました。
- 初期値: 50%、回復: 2、ダメージ: 50に設定しています。
- 譜面ヘッダー：gaugeHeavyにて詳細の変更が可能です（他と同様）。
2. ゲージ設定順序を見直しました（ゲージが簡単な順にソート）。
- Resolves #909 
- Light, Easyゲージの初期値について、既定値と異なっていたため見直しています。
（基本は他の箇所で自動設定され、この設定値は採用されないので影響はありません）
=> [0315/gauge-heavy] ライフ制ゲージ設定にHeavyを追加、ゲージ設定順序の見直し

js/danoni_main.js
- 追加した画像ファイルがある場合、Firefoxでプレイできない問題を修正しました。
- 画像ファイルを読込確認するためのループ処理の前にループをやめる処理があったため、
処理が止まる問題が発生していました。
Firefoxブラウザのみ発生します。
- 特になし。
=> [0317/preload-firefox] 追加した画像ファイルがある場合、Firefoxでプレイできない問題を修正

js/lib/danoni_constants.js
- ColorType: 2のおにぎりの初期色を白から薄青に変更しました。
- 上下左右の色とおにぎりの色が同じになっており、
色でオブジェクトを判断する方が見づらい状況になっていました。
- danoni_constants.js のみの変更です。
=> [0319/onigiri-color-type2] ColorType: 2のおにぎりの初期色を白から薄青に変更

js/danoni_main.js
1. カスタムjs、スキンjsが二重読込されている問題を修正しました。
- 現状、初期（initAfterDosLoaded処理後）と楽曲ロード時（loadingScoreInit処理後）の
2回読み込んでいます。
後者はリトライごとに呼び出されるため、場合によっては何度も読込します。
2. loadingScoreInitとloadingScoreInit2を統合しました。
3. #915 の修正箇所と重なるため、マージしたものをPull Requestします。詳細は #915 を参照してください。
1. 上記が二重読込されることにより、
ファイル内でconstやletで定義している変数群がエラーになることを抑止します。
2. 1.に伴う、不要コードの整理のため。
3. 詳細は #915 を参照。
- ここの`g_loadObj.main`は、譜面ロードに失敗したときのみ`false`となるため、問題なし。
- ファイルが動的に変わるわけではないので、二重読込させる意味は無いと考えています。
- コード見直し時に混入した可能性があります。過去バージョンも要確認。
=> [0320/customjs-duplicated] customjsを二重読込している問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
- 結果画面にGitterへのリンクを追加しました。
- タイトル画面にゲーム画面説明リンクを追加しました。
- Issue #919 関連。
- 結果画面
- タイトル画面
- 技術系リンクは後回し。一旦結果画面を優先して対応します。
=> [0321/gitter-link] 結果画面にGitterへのリンクを追加

js/danoni_main.js, js/lib/danoni_constants.js
- `danoni_setting.js`で定義する`g_presetOverrideExtension`(画像拡張子指定)が有効のとき、
checkImage（画像読込チェック）に失敗する問題を修正しました。
- 下記、Gitterからの指摘より。
https://gitter.im/danonicw/community?at=5fe8ae4fdbb17f28c5a284ff
- g_imgObj の各プロパティ（ファイル名）に対して拡張子を付与しているが、
`g_imgObj.imgExtensions` のみファイル名ではなく配列であるため、
配列が文字列として扱われ、以後の処理で`g_imgObj.imgExtensions`が機能しなくなる。
```javascript
// 画像拡張子の設定 (サーバ上のみ)
if (typeof g_presetOverrideExtension === C_TYP_STRING && !location.href.match(`^file`)) {
let key;
for (key in g_imgObj) {
g_imgObj[key] = `${g_imgObj[key].slice(0, -3)}${g_presetOverrideExtension}`;
}
}
```
- 修正の方向性としては、imgExtensionsプロパティを`g_imgObj`から外して独立変数にする。
- 変数名を変更するため、この変数を上書き設定している場合は注意が必要。
=> [0322/image-extensions] 画像拡張子指定時に画像読込チェックに失敗する問題を修正

js/lib/danoni_constants.js
- プレイ中のキー押下処理で`_keyCode === ''`のとき処理を行わないようにします
- 無変換など一部の特殊キーを押したとき全押し状態になってしまいます
- キーコードが空文字で、無効化された代替キーに反応してしまうようです
- 環境依存かもしれません
=> 一部のキーを押すと全押し状態になる問題の修正

js/danoni_main.js
1. 譜面ヘッダー：titleanimationを拡張しました（4番目の要素にアニメーション方法を追加）。
※CSSで言うところの`animaton-timing-function`に相当
2. 譜面ヘッダー：titleanimationclassを追加しました。titleanimationで設定しきれないcss設定をまとめて設定するために使用することを想定しています。
```
|titleanimation=leftToRight,120,0,linear|
|titleanimationclass=title|
```
1. 現状の設定ではアニメーションをlinearにするといった設定ができないため。
2. 上記以外の項目にも対応できる余地を作るため。
=> [0324/ttile-expansion] タイトルアニメーションの設定を拡張（クラス設定他）

js/danoni_main.js
- 通常矢印とフリーズアローの矢印番号が別で管理されている関係で、通常矢印のショボーン判定以内にフリーズアローが存在する場合に、通常矢印の判定が優先されてしまう現象が発生するためこれを修正しました
例)
```
left_data=205
frzLeft_data=200,202
```
となっている場合、200F地点でキーを押下するとフリーズアローのキター判定が出ることが期待されますが、
実際には通常矢印のマターリ判定が出てしまっていました
正確にキーを押下しても想定したプレイができないため
- +ERABY+E CONNEC+10N [Death] http://ngtkd.starfree.jp/danoni/177_tera.html
- Vast Universe [S２６] http://www.ricetask68934.shop/ricetask68934.shop/danoni/DS357.html?scoreId=4
などで発生します
- 特になし
=> 同一レーン上に通常矢印とフリーズアローが短い間隔で存在するとき、通常矢印の判定が優先されてしまう現象を修正

js/danoni_main.js
- Code Climateで指摘のあったコードに対して一部修正を実施しました。
- 上述の通り。
- 重複コードは避けますが、なるべく設定系はdanoni_constants.jsへ持っていくようにする予定です。
=> [0323/code-refactoring] コード整理

js/danoni_main.js
- 空押し時のヒットモーションが一部動かない問題を修正しました。
- ver18.9.1の修正 #929, #930 にて judgeArrow関数を修正しましたが、
オブジェクトが存在する際に空押し時のヒットモーションが動かないようになっていました。
- 過去バージョンにも修正が必要ですが、対応済みです。
=> [0326/judge-keydown] 空押し時のヒットモーションが一部動かない問題を修正

js/danoni_main.js
- `g_appearanceNum`と`g_opacityNum`をLocalStorageの値をもとに初期化するように修正しました
- [gitterより](https://gitter.im/danonicw/community?at=5ff5e496e578cf1e95cfe0b2)
=> AppearanceとOpacityの初期値設定処理を修正

js/danoni_main.js, js/lib/danoni_legacy_function.js
- 非推奨関数（createDivCssLabel, createCssButton, createColorObject）を
danoni_legacy_function.jsへ移動しました。
- v17以降は別関数にて定義しているため。
- 後継関数への移行を進めるため。
- danoni_legacy_function.jsへ移動しただけなので、
danoni_legacy_function.jsを入れておけばこれまでと変わりません。
- 今後、カスタムで利用する場合は
createDivCss2Label, createCss2Button, createColorObject2 の利用を推奨します。
=> [0327/deprecated-func] 非推奨関数をlegacy_functionへ移動

js/danoni_main.js
- gaugeX において、2譜面目以降の指定を省略した場合に1譜面目の設定を補完するよう変更しました。
```
|gaugeHeavy=x,1,20,100|
-> |gaugeHeavy=x,1,20,100$x,1,20,100$...$x,1,20,100|
|gaugeEasy=70,2,5,40$80,2,7,40|
-> |gaugeEasy=70,2,5,40$80,2,7,40$70,2,5,40$...$70,2,5,40|
```
- 現状は全譜面に対して設定が必要であり、数が多くなると手間になるため。
- 中途半端な設定（3譜面のうち最初の2譜面のみ設定）にしていると
ゲージ設定がこれまでのバージョンと変わる可能性があります。
=> [0329/gauge-initial] gaugeXの設定補完に対応

js/danoni_main.js
- 画面初期表示と画面消去を統一しました。
titleInit / optionInit / settingsDisplayInit / loadMusic / MainInit / resultInit の処理の先頭に
clearWindow() 処理を追加しています。
- 処理の単純化のため。
- ボタン処理をコピーしてカスタムしている場合、clearWindowが二重に動く可能性があります。
（二重に動かしても問題はありません）
=> [0330/reset-window] 画面初期表示と画面消去を統一

js/danoni_main.js, js/danoni_setting.js
- danoni_setting.jsにカスタムゲージリストを追加しました。
- 譜面ヘッダー：customGaugeと使い方はほぼ同じです。
customGaugeの指定がある場合は、customGaugeが優先されます。
```javascript
// カスタムゲージ設定(デフォルト)
// 'ゲージ名': `回復・ダメージ量設定`　の形式で指定します。
// (F : 矢印数によらず固定, V: 矢印数により変動)
const g_presetGaugeList = {
'Original': `F`,
'Normal': `V`,
'Hard': `V`,
};
```
- 常時カスタムゲージを設定するケースがあるため。
- danoni_setting.jsに記載するカスタムゲージリストは指定した順に変わります
（上記の場合は、Original -> Normal -> Hard）。
- 合作など、通常のサイトの設定と異なる場合はsettingTypeを別途指定し、分けて管理することもできます。
=> [0331/custom-gauge-list] danoni_setting.jsにカスタムゲージリストを追加

js/danoni_main.js
- タイトルの背景矢印の透明度設定を有効化しました。（titlearrowgrdに対してRGBA指定を可能に）
下記のような指定が可能になります。
```
|titlearrowgrd=#9999ff20:#9999ffff|
```
- Gitter要望より。
https://gitter.im/danonicw/community?at=60058b1d5562a61e9ab284a6
- これまで、影矢印など一部矢印はRGBAのカラーコードに対応していましたが、
タイトルの背景矢印についてはOpacityが強制的に25％になっていました。
背景矢印についても同様の指定ができるように変更します。
- 特になし
=> [0332/title-arrow-opacity] タイトルの背景矢印の透明度設定を有効化

js/danoni_main.js
1. 色名をカラーコードに変換する処理を追加しました。
2. `色名;透明度(0～255)`の形式で、色名と透明度を同時に指定できるようにしました。
```
|titlearrowgrd=midnightblue:tan|
|titlearrowgrd=midnightblue;255:tan;255|
```
3. linear-gradientの方向自動補完で rad, grad, turn についても検知するようにしました。
4. リストのいずれかに部分一致検索（大小文字問わず）する処理を統一しました。
1. PR #942 により、色名をtitlearrowgrdに指定した場合に
デフォルトの透明度が掛からない問題が発生していました。
2. 色名指定であっても、カラーコードと同等の設定が行えるようにするため。
3. rad, grad, turn を指定した場合に余計な補完が入らないようにするため。
4. 下記その他コメントに記載の除外条件が、画像かどうかのチェックと類似しているため。
- 上記は背景矢印の例ですが、グラデーション処理全般に対して修正しているため
グラデーションが使えるところであれば、同じ記述が使えます。（タイトル文字、矢印色など）
- グラデーションの方向名を色名として判断しないよう、除外条件を付けています。
```javascript
// すでにカラーコードのものやパーセント表記、位置表記系を除外
// 'to'のみ、'to left'や'to right'のように方向が入るため、半角スペースまで込みで判断
const exceptHeader = [`at`, `to `, `from`, `circle`, `ellipse`, `closest-side`, `farthest-corner`, `transparent`]; …
```
=> [0333/color-to-rgba] 色名をカラーコードに変換する処理を追加

js/danoni_main.js, js/danoni_setting.js, js/lib/danoni_constants.js
1. 定数系配列をdanoni_constants.jsへ移動しました。
2. ラベルテキストをdanoni_constants.jsへ移動しました。
`g_msgObj` 及び `g_msgInfoObj`、`g_lblNameObj` 内にて設定しています。
今後はこれらのプロパティ値を変えることで表示内容の変更が可能になります。
また、警告メッセージの変数が下記のように変わっています。
```
C_MSG_W_0001 -> g_msgInfoObj.W_0001
C_MSG_E_0011 -> g_msgInfoObj.E_0011
```
3. 譜面ヘッダー：readyHtml にてReady? の文字の代わりを設定できるようにしました。
※文字のスタイルは無視されます。HTMLタグが使用できます。
```
|readyHtml=<span style="color:#ff9999">Start!</span>|
```
4. 各譜面の譜面情報を出力する「データ出力」を押したとき、メッセージが出るようにしました。
5. ラベルテキスト、オンマウスメッセージをカスタムで定義できるようにしました。
```javascript
/**
* ラベルテキスト (g_lblNameObj) に対応するプロパティを上書きする設定
* ※danoni_setting.js の他、customjsにも利用可
* ※設定可能項目についてはdanoni_constants.jsをご覧ください。
*/
const g_local_lblNameObj = {
settings: `オプション`,
};
/**
* オンマウステキスト、確認メッセージ定義 (g_msgObj) に対応するプロパティを上書きする設定
* ※danoni_setting.js の他、customjsにも利用可 …
```
=> [0334/constants] 定数系配列をdanoni_constants.jsへ移動　他

js/danoni_main.js
- 譜面ヘッダー：musicFolderについて、他と同様にカレントディレクトリ指定`(..)`に対応しました。
```
|musicFolder=(..)music|
```
- Resolves #935
=> [0335/music-current] musicFolderのカレントディレクトリ対応

js/danoni_main.js
1. settingType, skinType, customjsにおいてカレント＋サブディレクトリ指定に対応しました。
```
// 作品フォルダ上のサブフォルダ：「setting」にある danoni_setting.js を参照 
|settingType=(..)setting/|
// 作品フォルダ上のサブフォルダ：「setting」にある danoni_setting_extra.js を参照 
|settingType=(..)setting/extra|
// javascriptフォルダにある danoni_setting_extra.js を参照 
|settingType=extra|
// specialフォルダにある danoni_setting_extra.js を参照 
|settingType=../special/extra|
```
- Issue #935 関連。
- カレント＋サブディレクトリ指定を組み合わせる場合、必ずスラッシュ`/`を入れてください。
```
// 作品フォルダ上のサブフォルダ：「setting」にある danoni_setting.js を参照 
|settingType=(..)setting/|
// 作品フォルダ上にある danoni_setting_setting.js を参照 
|settingType=(..)setting|
```
=> [0336/setting-type] settingType, skinType等におけるカレント＋サブディレクトリ指定対応

js/danoni_main.js, js/danoni_setting.js
- customjs、skinの初期値をdanoni_setting.jsで定義できるようにしました。
- Resolves #845 
- 指定方法は譜面ヘッダーと同じですが、danoni_setting.jsではそれぞれ1つのみ指定が可能です。
=> [0337/custom-skin-init] customjs、skinの初期値をdanoni_setting.jsで定義

js/danoni_main.js, js/lib/danoni_constants.js
1. 作品フォルダを従来のサブフォルダに置くことができるようになりました。
js, cssファイルは下記のように、元の場所を指すように変更してください。
```html
<script src="../../js/danoni_main.js" charset="UTF-8">
```
- 作品フォルダ配置場所の融通を利くようにするため。
- 実装に当たり、下記サイトを参考にしました。
https://qiita.com/kijtra/items/472cb34a8f0eb6dde459
https://qiita.com/suzunone/items/ce8894b8e338ee66a9d5
- 将来的に共通のリモートJSファイルを置いて、そこを参照できるようにすることを想定しています。
（バージョンアップをある程度意識する必要が無くなる）
試験的に、data-jsmode="remote"と指定することでjs/libフォルダのみ連動するようになっています。
```html
<script src="https://xxxxxx/js/danoni_main.js" charset="UTF-8" data-jsmode="remote">
```
=> [0341/remote-js] 作品フォルダ位置の変更に対応

js/danoni_main.js
1. ソースをGitHub Pagesにしている場合、
楽曲フォルダ（musicFolder）を自動でローカルのファイル参照とするように変更しました。
下記をしているのと同じです。
```
|musicFolder=(..)../music|
```
2. 実験的に設定していたコードを削除しました。
1. ソースをGitHub Pagesにしている場合、楽曲フォルダを必ず変えることになるため。
2. 今回の変更に伴い、不要なコードとなったため。
=> [0347/remote-default] Github Pages参照時のmusicFolder属性のデフォルト値を自動設定

js/danoni_main.js
1. 譜面明細画面でデータ出力ボタンを押した後、譜面選択できない問題を修正しました。
1. メッセージウィンドウが手前に来ており、その裏側にあるボタンが押せなくなっていました。
メッセージウィンドウそのものは透過させても問題ないため、
メッセージウィンドウ用のオブジェクトに対して、`pointer-events: none`を適用しました。
- 参考リンク
https://developer.mozilla.org/ja/docs/Web/CSS/pointer-events
- ver19.3.0以降でのみ発生する事象です。
=> [0349/window-pointer] 譜面明細画面でデータ出力ボタンを押した後、譜面選択できない問題を修正

js/danoni_main.js
1. Ready? の文字幅を画面幅に合わせるようにしました。
1. 譜面ヘッダー：readyHtmlを追加しましたが、横幅が従来の幅（200px）になっていたため
長い場合、折り返しが発生する状況になっていました。
元々中央寄せされているため、横幅いっぱいに広げても支障はないと考えます。
- Ready?の文字を置き換えることが目的なので、縦幅の変更や細かい位置変更などについては考えていません。
このような場合は、|customReadyUse=true|としてReady?を非表示化したうえで、
mask_dataなどを使って表現する方が自由度が高く、良いと考えます。
=> [0350/ready-width] Ready? の文字幅を画面幅に合わせる変更

js/lib/danoni_constants.js
1. Adjustment設定のショートカットにテンキーの「+」「-」を割り当てました。
1. 利便性向上のため。
- danoni_constants.js のみの修正です。
- 設定のみの修正のため、v19にも反映予定です。
=> [0355/adjustment-shortcut] Adjustment設定のショートカットにテンキーを割り当て

js/danoni_main.js
1. タイトル表示及び設定画面での譜面名のフォントサイズの自動取得処理を変更しました。
Canvas上に仮想的に表示した長さを取得する方法に変更したため、
以前の取得方法と比べて、枠外に外れたり余計に小さくなることが少なくなりました。
タイトル画面の場合は`横幅 - 100px`（サイズ上限：64px）、
設定画面での譜面名はDifficultyの選択ボタン幅（サイズ上限：18px）に合わせて見直します。
1. フォントサイズの自動取得処理が簡易的なため、
ほとんどのケースで譜面ヘッダー：fontsizeを使わざるを得ない状況になっていました。
- この変更により、全角文字は小さく、半角文字はやや大きくなります。
ただ枠内に収まるため、大きな問題にはならないと思います。
- 実装に当たり下記サイトを参考にしました。
https://www.yoheim.net/blog.php?q=20181202
=> [0357/str-length] フォントサイズの自動取得方法を変更

js/danoni_main.js
1. 設定画面内の譜面名のMakerViewのフォントサイズ変更に対応しました。
2. 設定画面内の譜面名のデフォルトサイズを従来に戻しました。
1, 2. ver20.1.0の修正漏れの対応です。
=> [0358/dif-dfsize] 設定画面内の譜面名のMakerViewのフォントサイズ変更に対応

js/danoni_main.js
1. 対象が無いときにショートカットキーを使うとエラーになることがある問題を修正しました。
具体的には、`|scoreDetailUse=false|`時にエラーになります。
また、意図的にボタンを非表示（`display: none` もしくは `pointer-events: none`）にしているとき、
ショートカットキーが動く問題も合わせて修正しています。
1. いずれも意図しない操作であるため。
- ver19.5.0以降で発生します。
=> [0362/shortcut-none] 対象が無いときにショートカットキーを使うとエラーになることがある問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 戻るボタンのショートカットキーにShift+Tabを追加割り当てするようにしました。
※キーコンフィグ画面を除きます。
2. 結果画面のCopyResultのショートカットキー（「C」キー）を押した際、
強制的にkeyUpするよう変更しました。
3. iPad/iPhone/iPod Touch判定用の処理をdanoni_constants.jsへ移動しました。
4. MacOS, iPadのとき、割り当てキーと役割を一部変更しました。
- メイン画面　`Shift`+`Backspace(Delete)`: タイトルバック
- キーコンフィグ画面　`Backspace(Delete)`：スキップ兼代替キーの無効化
※Windowsで言う⌫Backspaceは、Macでは⌫Deleteと呼称します。（codeはBackspaceと同一）
1. MacOSやiPadの場合、Escapeキーが無い場合があるため。
ただし、キーコンフィグ画面では現状代替先キーが無いためそのままにします。
2. iPad (Chrome)にてショートカットキーを使ってクリップボードコピーを行うと、
keyUpが動作しない問題があったため。
3. 今後、OSによる処理分岐が想定されるため。
4. MacOS、iPadOSにWindowsのDelete相当キー (MacではForward Deleteと呼称)が存在しないため。
- その他、MacOS系ではDeleteキーが無い問題があります。
メイン処理のショートカット操作は他と異なるため、一旦保留しています。→　対応しました。
=> [0360/ios-shortcut] 戻るボタンのショートカットキーにShift+Tabを追加割り当て

js/danoni_main.js, js/lib/danoni_constants.js
1. タイトル画面・設定画面・キーコンフィグ画面でボタン・ショートカットキーの有効化時間を設定できるようにしました。PR #964 関連。
`g_btnWaitFrame`で指定できます。
`danoni_constants.js`で定義しているため、`danoni_setting.js`や`danoni_custom.js`で置き換え可能です。
```javascript
// ボタン・ショートカットキーの有効化時間（フレーム数）
// b_frame: ボタンの有効化フレーム数、s_frame: ショートカットキーの有効化フレーム数
// initial: 初回のみ有効化時間を設定する場合、trueを設定
const g_btnWaitFrame = {
initial: { b_frame: 0, s_frame: 0 },
title: { b_frame: 0, s_frame: 0 },
option: { b_frame: 0, s_frame: 0, initial: true },
settingsDisplay: { b_frame: 0, s_frame: 0 },
loading: { b_frame: 0, s_frame: 0 },
main: { b_frame: 0, s_frame: 0 },
keyConfig: { b_frame: 0, s_frame: 0 },
result: { b_frame: 0, s_frame: 120 },
};
```
2. ボタン作成関数で、原則として初期はボタンが使用できない状態に変更しました。
`g_btnWaitTime[グループ名].b_time`ミリ秒後に使用できるようになります。
|引数|型|デフォルト|用途| …
=> [0361/shortcut-wait-time] ボタン・ショートカットキーの有効化時間を設定できるようにする

js/danoni_main.js
1. KeyConfig画面のTo Settingsボタンにg_lblNameObjが適用されていない問題を修正しました。
1. 上記の通り。
=> [0363/display-back] g_lblNameObjの適用忘れを修正

js/danoni_main.js
1. createImg関数でimgタグを生成する際、`crossOrigin="anonymous"`を付与するよう変更しました。
1. キーコンフィグ画面でカーソルを表示する際、この種の警告が表示されていたため。
- 必須の対応ではないですが、他のpreload処理も同様の対処を行っているため、同様に対応します。
優先度は低め。
=> [0365/create-image] imgタグ生成時においてcrossOrigin属性を付与するよう変更

js/danoni_main.js
1. preloadFile関数においてas:image以外が来た時の問題を修正しました。
2. preloadを管理するオブジェクトを `g_preloadImgs`から`g_preloadFiles`に変更しました。
全体を`g_preloadFiles.all`, 画像を`g_preloadFiles.image`で管理するようにします。
1. 現在は利用例がないが、_as引数がimage以外の場合に問題となるため。
2. 上記と同じ理由です。
- Firefox 85以降はrel=preloadに対応したため、将来的にこの分岐は不要となる見通し。
https://hacks.mozilla.org/2021/01/january-brings-us-firefox-85/
- オブジェクト名の変更となるが、このオブジェクトはpreloadFile関数とFirefox時のチェックでしか利用しておらず、影響は局所的と判断。
=> [0366/preload-image] preloadFile関数においてas:image以外が来た時の問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. ショートカット表示部分のフォーマットを拡張しました。
`g_scViewObj`にて各種設定が可能です。
format属性のデフォルト値は`{0})`となっており、`{0}`の部分はショートカット表示に置き換わります。
1. ショートカット表示部分がほぼ固定表示となっていたため。
- これらの設定は基本、設定画面の各種設定用ボタンに対応する設定です。
それ以外のボタンはX座標位置のみ、`g_btnPatterns`にて行うことができます。
=> [0364/shortcut-view] ショートカット表示部分のフォーマット方法を拡張

js/danoni_main.js
- #988 imgタグ生成時においてcrossOrigin属性を付与するよう変更
- #989 preloadFile関数においてas:image以外が来た時の問題を修正
=> [ver18.9.5] imgタグ、preloadの設定に関する修正

js/danoni_main.js
- #986 KeyConfig画面のTo Settingsボタンにg_lblNameObjが適用されていない問題を修正
- #988 imgタグ生成時においてcrossOrigin属性を付与するよう変更
- #989 preloadFile関数においてas:image以外が来た時の問題を修正
=> [ver19.5.5] imgタグ、preloadの設定に関する修正

js/danoni_main.js, js/lib/danoni_constants.js
1. ゼロパディングのコード集約を行いました。 (String.padStartの利用)
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/padStart
2. 設定画面上の譜面選択リストにあるキー別フィルターボタンのID重複を解消しました。
これまで、ID: `keyFilter`となっていましたが ID: `keyFilter0`, `keyFilter1`, ... のように分けます。
3. 結果画面のランク部分のラベル表示をcreateDivCss2Labelに合わせました。
合わせて、画面共通フォントの設定関数`getBasicFont`を拡張し、優先フォントを指定できるようにしました。
4. MacOSのキー表示関係のオンコード部分を改善し、設定に関する部分をdanoni_constants.jsへ極力移しました。
1. 実装方法が統一されていなかったため。標準関数に合わせます。
2. 特定のボタンに対して処理をしたい場合の阻害になるため。
3. 結果画面のランク部分のみ、他と違う動きになっていたため。
4. 無用なif文を減らすため。
- 従来の関数`paddingLeft`, `createDivCustomLabel`は互換として残します。
後者は利用頻度が低いと思われるので、今後削除を検討しています。
=> [0367/code-refactoring] ゼロパディングのコード集約 (String.padStartの利用)　他

js/danoni_main.js, js/danoni_setting.js, js/lib/danoni_constants.js
1. 設定名（Boost, Brake, ...など）をg_lblNameObjに設定することで設定名を置き換える機能を実装しました。
項目名の前に`u_`をつけて指定します。
```javascript
g_lblNameObj.u_Boost = `ブースト`;
```
なお、ハイフンなどが含まれる場合は下記のようにします。
```javascript
g_lblNameObj[`u_R-`] = `(逆)`;
```
2. 結果画面の固定ラベル(Music, Playstyleなど)、Displayオプションの略名(Step, FSなど)を
g_lblNameObjに設定することでラベル名を置き換える機能を実装しました。
項目名の前に`rt_`, `rd_`をつけて指定します。
※この機能は3. の設定の影響を受けません。
```javascript
g_lblNameObj.rt_Music = `曲名`;
g_lblNameObj.rd_StepZone = `ステップ`;
```
3. danoni_setting.jsに設定名（`g_lblNameObj.u_`始まりのもの）を置き換えるかどうかを
画面別に設定できるようにしました。
例えば、設定画面はデフォルトのままにして、結果画面のみ簡略表示にするといった使い分けができます。
```javascript
/**
* 設定名の上書き可否設定
*/
const g_lblRenames = {
option: true,
settingsDisplay: true,
keyConfig: true,
result: true,
};
```
1. 設定名を変更する手段がこれまで無かったため。
2. 結果画面のラベルを変更する手段が直接変更する以外に無かったため。
3. …
=> [0368/setting-name] 設定名を置き換える機能を実装

js/danoni_main.js
1. タイトル文字、譜面名にエスケープ対象の文字がある場合、
その文字分を長さとして取得してしまう問題を修正しました。
今後は一度エスケープを取ってから(unEscapeHtml関数を適用後)長さを計測するように変更します。
2. 譜面名について、前回の譜面名を元にフォントサイズを決定してしまう問題を修正しました。
1. タイトル文字、譜面名にエスケープ文字が含まれる場合、文字列が長くなります。
例：`&` => `&amp;`, `"` => `&quot;` 
これを考慮すると、エスケープ文字を含んだ内容で描画幅が計算され、
結果として全体文字が小さくなってしまうため、これを改善します。
2. コード整理時のミスです。前の譜面名の長さを取得するようになっていました。
- ver20.1.2 で発生する不具合。過去バージョンの適用対象外です。
=> [0370/difname-size] タイトル文字、譜面名のフォントサイズに関する修正

js/danoni_main.js, js/lib/danoni_constants.js
1. フレーム数から分秒に変換する処理、ローカルかどうかの判断処理、
譜面基礎データの取得処理を関数化しました。
2. `(条件式) ? true : false` の記述を `(条件式)` に変更しました。
3. 結果ラベル生成処理を一部集約しました。
1. コード重複回避のため。
2. 条件式そのものが true/false を返しており、三項演算子が不要のため。
3. コードのほとんどが共通化していたため、片側の関数に寄せました。
=> [0369/code-refactoring] 重複記述の見直し

js/danoni_main.js, js/lib/danoni_constants.js
1. ローカル起動チェックの実行方法誤りを修正しました。
関数ではなく、変数として`g_isMac`や`g_isIos`と同じような使い方ができるようにしました。
1. 関数呼び出しが必要なところ、変数として利用されていたため。
変数に置き換えたため、変数名のみ変更しています。
=> [0372/isLocal] ローカル起動チェックの実行方法誤りを修正

js/danoni_main.js, js/lib/danoni_constants.js
1. タイトル画面にショートカットキーを追加しました。
- `C`キー：Commentボタンがあれば開閉
- `/ ?`キー もしくは `F1`キー：プレイ画面説明（Wiki）のページを表示
2. ロード画面（iOS系のみ）のプレイ開始ボタンに対してEnterキーを割り当てました。
3. ロード画面のプレイ開始ボタン周りのコードを整理しました。
4. ショートカットキーでキーコンフィグ画面へ移動した場合、0.5秒の待ち時間を設けるよう変更しました。
5. clearWindow関数に`g_inputKeyBuffer`を初期化する処理を包含しました。
6. setShortcutEvent関数にcreateScTextCommon関数を包含しました。
1. ショートカットキーを割り当てても支障が無いため。
「Reset」ボタンについてはローカルデータの消去になるため、ショートカットキーの割り当てはしていません。
「R(eload)」ボタンについても、リロードキーの一部で利用済みのため割り当てしないようにしました。
2. このボタンのみEnterが未対応だったため。
なお、iPad(Safari)ではこの画面が出ることは無く、iPhoneもしくはiPad(Chromeアプリ)で表示されます。
現在用途としては限定的ですが、今後このあたりの制限が強化される場合を考慮して実装します。
3. コードの見やすさのため。
4. スペースキー連打によるキー割り当てを防ぐため。
5. 画面クリア時にキーを押した状態を管理する変数(g_inputKeyBuffer)は初期化した方が良いため。
また、clearWindow関数に処理を統合することで呼び出し漏れを無くすことが目的です。
6. 連続的に実行されることが多いため、setShortcutEvent関数に集約しました。
- …
=> [0373/shortcut-title] タイトル画面、ロード画面(IOSのみ)にショートカットを追加

js/danoni_main.js
1. drawDefaultBackImage関数をclearWindow関数へ集約しました。
（画面のクリアに加えて、背景を再描画する関数を付加）
clearWindow関数に引数を追加し、引数の指定があった場合のみ
drawDefaultBackImage関数を呼び出すようにします。
- 従来のclearWindow関数はそのまま使えます。（引数が無い場合は画面クリアのみ実行）
=> [0374/clear-window] drawDefaultBackImage関数をclearWindow関数へ集約

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js
- #1002 タイトル画面にショートカットキーを追加
- #1002 ロード画面(iOSのみ)にショートカットキーを追加
- #1002 ショートカットキーでキーコンフィグ画面へ移動した場合、0.5秒の待ち時間を設けるよう変更
- #1003 clearWindow関数にキーを押した状態の初期化処理、背景再描画処理を包含
=> [ver20.4.0] タイトル画面、ロード画面(IOSのみ)にショートカットを追加　他

js/danoni_main.js
1. キーコンフィグ画面内のeval関数を排除しました。
2. キーコンフィグ周りのコードを一部整理しました。
1. すでにeval関数を使わないためのオブジェクトが用意されているため。
2. 同じ処理の繰り返しコードが混在していたため。
=> [0376/code-refactoring] キーコンフィグ画面内のeval関数を排除

js/danoni_main.js
- Base64エンコードした曲データの読み込み時、fetchを使わず直接デコードします
- デベロッパーツールのネットワークタブに元の音声データが表示されてしまうことを防ぎます
=> Base64エンコードした曲データを直接デコードする

js/danoni_main.js
1. グラデーション周りのコード見直しました。
2. setColorを部分的に未指定にした場合（`例：|setColor=,#ff6666|`）、
タイトルの背景矢印や文字が未指定になってしまう問題を修正しました。
デフォルトの色配列から取得するように変更しています。
1. コード集約によるコードの見やすさのため。
2. 上記問題の解消のため。
- 条件式を統一した結果、条件が変わっているものがあるので影響が無いか確認すること。
- 2.のケースはヘッダ一部未指定時の補完処理のため、過去バージョンの適用までは基本行わない。
=> [0378/cr-colorgrd] グラデーション周りのコード見直し

js/danoni_main.js
1. グラデーション変数の初期化漏れを修正しました。
1. makeColorGradation関数のconvertColorStr変数について、これまでは初期化しなくても良い記述になっていましたが、ver20.5.0の変更により文字列結合する箇所が追加されたため、初期化が必要になりました。
=> [0379/colorgrd-init] グラデーション変数の初期化漏れを修正

js/danoni_main.js
1. グラデーション文字列にdeg/radなどが入っているときに文字が表示されない問題を修正しました。
1. 位置表記を抽出する条件式に誤りがあり、
180degや0.5turnが入っている場合でも to left/to right が保管されるようになっていました。
- ver20.5.1に実装した`hasAnglePointInfo`関数の実装間違いによるものです。
=> [0381/titlegrd] グラデーションにdeg/radなどが入っているときに文字が表示されない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. キーコンフィグ周りのコードを整理しました。
- resetCursor, setKeyConfigCursor関数の引数を整理し、冗長な引数をカット。keyConfigInit配下に配置。
- resetCursorMain, resetCursorReplaced, resetCursorALL関数を廃止。
直接resetCursorを呼び出すように変更。
- カーソル移動用の関数としてsearchNextCursor関数を切り出し。
- 二重定義箇所を見直し、基本的にkeyConfigInitで定義した変数を利用するように変更。
1. #1006 にてeval関数を削除したが、構造的にあまり変わっておらずコードの見通しが悪いため。
=> [0384/cr-keyconfig] キーコンフィグ周りのコード整理

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面セレクター表示時、非表示部のショートカットが動かないよう変更しました。
譜面セレクターを表示している間は、`g_currentPage = 'difSelector';`として動作します。
2. 譜面セレクター上選択済の譜面に色が付くよう変更しました。
3. 譜面数が多くスクロールがある場合、譜面セレクターを開き直したときに
選択中の譜面が見えるよう初期スクロール位置を調整しました。
4. 譜面セレクター表示時、上下キーで譜面移動できるようにしました。
また、`Enter`キーもしくは`L`キーでセレクターを閉じます。（逆に開く場合は`L`キー）
5. 譜面セレクターのキー別フィルターとは別に「ALL」を追加しました。（キー別フィルターの解除）
1. 誤操作防止のため。
2. 選択中の譜面が何かわかるようにするため。
3. 2.に関連した修正です。
4. 2.に関連した修正です。
5. 2.に関連した修正です。
- 譜面明細（速度グラフ、密度グラフ、ツール値表示）については画面扱いでは無くそのままです。
- setShortcutEvent関数の第三引数に`_displayFlg`を追加しています。
これを`false`に設定すると、ショートカットキーの表示部を描画しません。
画面を再描画せずそのまま利用する場合に利用します。
- makeDifLblCssButton関数のオブジェクト引数`btnStyle`を追加しました。
ボタンクラスをオプションで変更できるようになります。
- nextDifficulty関数の第二引数を削除しました（引数を分ける意味が無かったため）。
=> [0380/dif-shortcut] 譜面セレクター表示時に関する仕様変更

js/danoni_main.js
1. 初期矢印・フリーズアロー色の展開処理をheaderConvert関数の外へ移動しました。
2. 初期矢印・フリーズアロー色の設定拡張を行いました。
2譜面目、3譜面目、…の初期色をsetColor2/frzColor2, setColor3/frzColor3, ...で指定することができます。
※影矢印についてはsetShadowColor2/frzShadowColor2, ... に対応
3. 譜面分割＆譜面番号固定時、個別の譜面ファイル内にsetColor/frzColor/setShadowColor/frzShadowColorの記述があれば、その値を採用するよう変更しました。
（キーコンフィグ画面にも反映されます）
4. キーコンフィグ画面の影矢印部分がColorTypeを変えても変更しない問題を修正しました。
1. 後から再定義しやすくするため。
2. Issue #390 への対応です。
3. 2.の対応の派生対応です。譜面分割＆譜面番号可変時にも対応しています。
4. 元々仕様でしたが、1～3の対応に合わせて変わるように変更しました。
- 今回追加した`resetBaseColorList`関数はオブジェクトを返却します。
オブジェクトが上書きされるため、`obj = Object.assign(obj, resetBaseColorList(...));`
のように指定が必要です。
- このPull Requestの変更は過去バージョンへの反映対象外です。
=> [0385/ex-setcolor] 初期矢印・フリーズアロー色の定義拡張

js/danoni_main.js, js/lib/danoni_constants.js
- #1023 と基本的に同じですが、getGaugeSetting をheaderConvert関数及びloadDos関数で
事前に設定することで、後からcustomTitleInitを呼び出しても影響が無いように変更しています。
1. customGaugeの複数譜面化に対応しました。
```
|customGauge=Normal::V,Hard::V|
|customGauge2=Easy::V,Normal::V,SuddenDeath::F|
|customGauge3=Original::F,Normal::V,Hard::V|
```
2. danoni_setting.jsにカスタムゲージ(`g_presetGaugeList`)が設定されていれば、
値に`Default`を指定することで`g_presetGaugeList`を参照するよう変更しました。
```
|customGauge=Normal::V,Hard::V|
|customGauge2=Default|                       // 1譜面目では無く、g_presetGaugeListを継承
|customGauge3=Original::F,Normal::V,Hard::V| // 3譜面目は独自
// 以降を未指定にした場合（この場合は4譜面目以降）は1譜面目の設定を継承
```
3. listMatching関数に適用するオブジェクトを`g_checkStr`に集約しました。
（従来のg_cssCheckStrは廃止）
4. getGaugeSetting関数の第三引数を`_headerObj`から`_difLength`に変更しました。
5. gaugeXXXについて、gaugeXXX2, gaugeXXX3 のような分割記法に対応しました。 …
=> [0389/multi-custom-gauge2] customGaugeの複数譜面対応、デフォルト値対応(事前設定版)　他

js/danoni_main.js, js/lib/danoni_constants.js
1. カスタムゲージのデフォルト値設定を見直しました。
- Default から customDefaullt に変更しています。
2. カスタムゲージについて、一部ライフ制ゲージ、ノルマ制ゲージのデフォルト設定を
使えるようになりました。
```
|customGauge2=survival|  
// ライフ制ゲージ設定を継承：[`Original`, `Heavy`, `NoRecovery`, `SuddenDeath`, `Practice`, `Light`]
|customGauge3=border|
// ノルマ制ゲージ設定を継承：[`Normal`, `Hard`, `SuddenDeath`, `Easy`]
|customGauge4=customDefault|
// 共通設定ファイルで定義しているゲージ設定を継承
```
3. g_gaugeOptionObj の初期値を danoni_constants.js へ移動しました。
4. g_gaugeOptionObj を let -> const へ変更しました。
1. Resolves #1026 
2. 部分的にカスタムゲージを採用したいケースに対応するため。
3. 最大ライフ以外は固定値のため。
4. 3.の変更に伴い、直接代入する必要がなくなったため。
- dmgSurvival / dmgBorder プロパティ中にある`maxLife`という文字を検知して、
最大ライフ値が判明した時点で反映するようにしています。
```javascript
const g_gaugeOptionObj = {
// 
dmgSurvival: [40, 50, 50, `maxLife`, 0, 40],
// 
dmgBorder: [7, 50, `maxLife`, 7],
// 
}
```
=> [0391/customg-default] カスタムゲージのデフォルト値設定の見直し

.github/RELEASE_TEMPLATE.md, SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js
- #1024 customGaugeの複数譜面化対応
- #1024 gaugeXXXについて、gaugeXXX2, gaugeXXX3 のような分割記法に対応
- #1024 譜面分割＆譜面番号可変時、初期矢印・フリーズアロー色（setColor2, frzColor2, ...）を
譜面番号固定時と同様、個別の譜面ファイルへ記載できるように変更
- #1024 #1025 文字列関連のコード整理
- #1026 カスタムゲージについて、ライフ制ゲージ/ノルマ制ゲージ/共通設定ファイルで指定のリストを指定できるよう変更
=> [ver21.1.0] カスタムゲージの譜面別設定の実装　他

js/danoni_main.js, js/lib/danoni_constants.js
1. データセーブフラグ切替ボタンをDisplay画面にも表示しました。
1. 各種Display設定がローカルストレージの保存対象になっているため。
=> [0393/display-save] データセーブフラグ切替ボタンをDisplay画面にも表示

js/danoni_main.js, js/lib/danoni_constants.js, skin/danoni_skin_light.js, skin/danoni_skin_skyblue.js
1. 背景状況 (厳密には、スキンCSSの `.title_base`で判断) により、
明暗用のColorTypeを自動適用するよう変更しました。
明背景の場合、明背景用のデフォルトColorTypeが適用されます。
```css
/* タイトル */
.title_base {
color:#222222;
}
```
2. ColorType：Type0について、未指定かつ明背景の場合、自動で中間色を黒にするよう変更しました。
3. 強制的に明暗指定する譜面ヘッダー：backBright を追加しました。`true`: 明色、`false`: 暗色 です。
```
|backBright=true|
```
4. メッセージ周りが正しく表示されない問題を修正しました。
タイトル画面でのエラーメッセージがページ移動時に隠れる問題を改善しています。
1. 明背景のとき、必ずjsファイルの加工が必要となり煩雑なため。
2. 明背景のとき、Type0が見づらくなる傾向があるため。
3. 間違って明背景と判断される可能性があるため。
※背景色は見ていません。標準の文字色を元に背景を推定して判断しています。
4. タイトル画面表示前にclearWindowを挟んだことで、メッセージ表示が隠れてしまったため。
- スキンCSSファイルの先読み処理を行った関係で、処理の一部入れ替えを行っています。
=> [0394/default-grd-color] 背景状況により明暗用のカラーセットを使用するよう変更

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js, js/sample/danoni_custom-003.js, skin/danoni_skin_light.js, skin/danoni_skin_skyblue.js
- #1032 データセーブフラグ切替ボタンをDisplay画面にも表示
- #1033 背景状況により明暗用のカラーセットを使用するよう変更
- #1033 ColorType：Type0について、未指定かつ明背景の場合、自動で中間色を黒にするよう変更
- #1033 メッセージ周りが正しく表示されない問題を修正
- #1034 danoni3.html のカスタムjsサンプルを更新
- danoni_skin_light.js, danoni_skin_skyblue.js にてcolorTypeの独自定義が不要になったため、
独自記述をカットしています。
（残したままでも問題はありません）
=> [ver21.2.0] 背景状況により明暗用のカラーセットを使用するよう変更　他

js/danoni_main.js
1. g_loadObjについて、読込完了時に設定値を`true`に変えるよう統一しました。
※これまでは失敗時のみ`false`にしていたり（loadScript）、未設定（importCssFile）でした。
1. ファイルの読み込み状態を正確に把握し、意図しない動作をブロックするため。
=> [0396/file-loading] ファイルロード時のg_loadObjの管理方法を一部変更

js/danoni_main.js, js/lib/danoni_constants.js
1. 警告ウィンドウで使用するメッセージ(g_errMsgObjのプロパティ)について、配列化管理に変更しました。
`makeWarningWindow`及び`setWindowStyle`の使い方は変わりません。
1. 画面切り替え時、同じメッセージが二重に表示されないようにするための対策です。
=> [0397/warning-window] 警告ウィンドウの仕様変更 (g_errMsgObjのプロパティを配列化)

js/danoni_main.js
1. 空スプライト作成処理を`createSprite`関数から`createEmptySprite`関数に変更しました。
※`createDivCss2Label`と同じように、オブジェクト引数を持っています。
2. `createOptionWindow`, `createSettingsDisplayWindow`関数の引数をオブジェクトに変更しました。
1. 空スプライト作成処理のみ、拡張性に乏しい関数になっていたため。
2. 引数が文字列となっていたことで煩雑になっていたため。
=> [0398/empty-sprite] 空スプライト作成処理を新関数に置き換え

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js
- #1036 ファイルロード完了後に g_loadObj のプロパティ値を `true` にするよう統一
- #1037 警告ウィンドウの仕様変更 (g_errMsgObjのプロパティを配列化)
- #1038 空スプライト作成関数を新関数に置き換え
=> [ver21.3.0] 警告ウィンドウの仕様変更、空スプライト作成処理の置き換え　他

js/danoni_main.js, js/lib/danoni_constants.js, skin/danoni_skin_default.css, skin/danoni_skin_light.css, skin/danoni_skin_skyblue.css
1. キーコンフィグの対応キー箇所をボタン化しました。
ボタンをクリックすることで直接そのキーを変更できます。
- danoni_skin_default/light/skyblue.css の変更があります。
```css
/* デフォルト(色指定なし) */
.button_Default_NoColor {
background-color: #00000000;
}
.button_Default_NoColor:hover {
background-color: #666666;
}
```
1. キー数が多いとき、一部のみ変更したいことがあるため。
=> [0400/keyconfig-button] キーコンフィグの対応キー箇所をボタン化

js/danoni_main.js, js/lib/danoni_constants.js
1. キー数周りのコード整理を行いました。
- 特殊キー作成時、colorX/charaX/stepRtnX/shuffleX/keyCtrlX/posXについて処理が類似しているため
`newKeyMultiParam`関数に処理集約を行っています。
- blank, scale再設定処理を`updateKeyInfo`関数で集約しました。
- `newKeySingleParam`, `newKeyPairParam`関数についてアロー関数に変更しました。
2. キーコンフィグ画面のキー割り当て色の変更処理について、
`removeClassList`関数と色割り当て処理を統合し、`changeKeyConfigColor`関数へ移行しました。
1. 類似の記述が多かったため。
2. CSSクラスの付け替えは基本、セットで行われるため。
=> [0401/cr-keys] キー数周りのコード整理

js/danoni_main.js
1. 特殊キーのキーコンフィグのリセットに失敗する問題を修正しました。
1. PR #1041 にてコード集約を行った影響で、デフォルト配列作成時にシャローコピーを行っていたため。
`JSON.parse(JSON.stringify(多次元配列));`の形式に変更しました。
=> [0402/extra-keys] 特殊キーのキーコンフィグのリセットに失敗する問題を修正

js/danoni_main.js
- 矢印データが空または不正なときarrowDataを空の配列にするようにします
- [izkdicさんのツイート](https://twitter.com/vdos2643/status/1379451476024561670)
- `|frzSpace_data=|`のような空データではarrowDataの中身が`[""]`となり、S-Ran時この`""`が残ってしまいます
- これにより、`g_allArrow`を数えるときそのキーを無視する条件を満たしてしまいます
- `parseFloat("")`がNaNなので`isNaN(parseFloat(g_scoreObj.arrowData[j][0]))` がtrue
- 総ノート数が足りないため通常より早くフルコン演出が発動します
=> 空の矢印データを含む譜面にS-Ranをかけるとフルコン演出が通常より早く出てしまう問題の修正

js/danoni_main.js
1. #1044 に対するコード見直しを行いました。
総矢印数、総フリーズアロー数について毎回計算するのではなく、
すでに計算済みの g_detailObj から取得するようにしました。
1. 重複コード回避のため。
=> [0404/empty-score] #1044 に対するコード見直し

css/danoni_main.css, js/danoni_main.js
1. 警告ウィンドウをcreateDivCs2Labelにて作成するよう変更しました。
2. 警告ウィンドウについて、上下ゆれをCSSで制御するよう変更しました。
1. 他と作り方が異なる方法だったため。
2. Resolves #823
=> [0399/window-margin] 警告ウィンドウのデザインに関する変更

js/danoni_main.js
1. 明背景時、キーコンフィグ画面の文字が薄い問題を修正しました。
1. キーコンフィグ画面の割り当てキー表示をボタン化した際、color属性を定義できていませんでした。
=> [0405/white-keycon-color] 明背景時、キーコンフィグ画面の文字が薄い問題を修正

js/danoni_main.js
1. 総矢印数、総フリーズアロー数のカウント方法を従来の方法に戻しました。
1. 譜面ファイルが外部データで、かつ譜面が更新されリロードを行わなかった場合、
総矢印数、総フリーズアロー数が更新されないため総数が合致しない場合があります。
- v21.4.1のみ発生します。
=> [0406/real-arrowcnts] 総矢印数、総フリーズアロー数のカウント方法を従来の方法に戻す

SECURITY.md, css/danoni_main.css, js/danoni_main.js, js/lib/danoni_constants.js, skin/danoni_skin_default.css, skin/danoni_skin_light.css, skin/danoni_skin_skyblue.css
- #1050 総矢印数、総フリーズアロー数のカウント方法を従来の方法に戻す
- #1047 , #1049 の変更を含みます。
=> [ver21.4.2] 総矢印数、総フリーズアロー数のカウント方法を従来の方法に戻す

js/lib/danoni_constants.js
1. タイトル・結果画面でCtrl+Cを使うとショートカットキーが動作する問題を修正しました。
1. 不具合というほどでもないが、画面上でテキストコピーしたいときにショートカットキーが使えないため。
- danoni_constants.js のみの修正です。
=> [0408/ctrl-c] タイトル・結果画面でCtrl+Cを使うとショートカットキーが動作する問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面明細表示の逆回しに対応しました。
右クリックで ToolDif -> Density -> Speed の順に移動するようになります。
また、Shift+Qキーでも逆回しが可能です。
1. 他のボタンの操作方法に合わせるため。
- 実装上、「Speed」「Density」などを表示するボタンの裏に
逆回しするボタン(id: lnkScoreDetailB)を非表示で挿入しています。
これはショートカットキーが、実体のボタン操作が無いと動作しないためです。
=> [0407/switch-scoredetail] 譜面明細表示の逆回しに対応

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面選択ボタンを押したときの処理を`changeDifficulty`へ集約しました。
また合わせて、右クリック時かつ譜面セレクター表示ありのとき、譜面セレクターの開閉を
左クリックのときと同様に行えるように処理を統一しました。
2. シャッフル適用関数の呼び出し処理をdanoni_constants.jsへ移動しました。
3. キー数基礎情報取得処理を`getKeyInfo`関数に集約しました。
4. ステップゾーンの表示可否フラグ用の変数について、display属性を直接返す仕様に変更しました。
5. 速度データの初期値設定を集約しました。
1. コードの見やすさの改善です。
2. 設定別に何をしているかがわかるようにするため。
実際に処理を行う applyShuffle, applyMirror, applyRandom, applySRandom はそのまま使えます。
3. 同様の取得処理を複数行っている箇所があったため。
4. ステップゾーンの表示可否からdisplay属性を設定するまでの処理が同じため。
5. 同様の処理が連続していたため。
=> [0410/cr-common] 共通部分のコード整理

js/danoni_main.js
1. Save切替ボタン、Display切替ボタンについて右クリックでも切替できるようにしました。
1. 他のボタンと処理を統一するため。
=> [0411/switch-right-click] Save切替ボタン、Display切替ボタンの右クリック対応

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js
- #1052 譜面明細表示の逆回しに対応（右クリック or 「Shift」+「Q」キー）
- #1053 タイトル・結果画面で「Ctrl+C」でショートカットキーが反応しないよう修正
- #1054 ローカルストレージの初期値に関するコード見直し
- #1055 共通系処理のコード見直し
- #1056 Save切替ボタン、Display切替ボタンの右クリックでの切替対応
=> [ver21.5.0] 譜面明細表示の逆回し、右クリックによるON/OFF切替　他

js/danoni_main.js
1. 一時的に初期矢印色の割当先を変更できる機能を実装しました。
キーコンフィグ画面にて矢印本体を左クリック or 右クリックで他の割り当て色に切り替えます。
- 割り当て対象は初期矢印色（と、それに対応する初期フリーズアロー色）のみです。
- 保存期間はリロードするまでです。ローカルストレージへの保存は行いません。
- 割り当てできる色は、設定中のColorTypeに対応したsetColor（5色）から選べます。
- 色変化した場合は上書きされます。必要に応じてDisplayオプションからColorをOFFにする必要があります。
- 一部のキー種について、プレイヤーにより特定の割り当てキーのみ色を変えたい場合がありますが、
個別に対応することが難しいため、一時的に色を割り当てられるようにしました。
=> [0414/temp-color-change] 一時的に初期矢印色の割当先を変更できる機能を実装

js/danoni_main.js
1. 結果画面に表示するRandom+/S-Random+表記を統一しました。
1. シャッフルグループが変わっても、Random+/S-Random+の内容自体は同じため。
=> [0417/shuffle-name] シャッフルグループが複数の場合のRandom+/S-Random+表記を統一

js/danoni_main.js
1. 譜面ヘッダーで |shuffleUse=group| と指定することで、
「OFF」「Mirror」「Random」「S-Random」のみ選択できるように制御する設定を追加しました。
1. Resolves #1065 
- 従来の |shuffleUse=false|や|shuffleUse=true|はそのまま使えます。
- 現状、Shuffle設定は設定名末尾に「+」が入っているものが
シャッフルグループを跨いでシャッフルされるため、
設定名末尾に「+」が入っているものを除外しています。
これに沿わない設定が今後追加された場合は注意が必要です。
=> [0418/shuffle-group] shuffle設定でシャッフルグループのみ選択可のオプションを追加

js/danoni_main.js, js/lib/danoni_constants.js
1. Shuffle設定に「Asym-Mirror」（非対称ミラー、Asymmetric-Mirror）を実装しました。
反転した後、「↓」と「↑」のみさらに反転するイメージです。
※個別のシャッフルグループが4の倍数のみ有効です。それ以外の場合は「Mirror」と同じです。
```
[0, 1, 2, 3] -> [3, 2, 1, 0]
[0, 1, 2, 3, 4, 5, 6, 7] -> [7, 6, 5, 4, 3, 2, 1, 0]
```
<pre>
[0, 1, 2, 3] -> [3, <b>1, 2, </b>0]
[0, 1, 2, 3, 4, 5, 6, 7] -> [7, <b>5, 6, </b>4, 3, <b>1, 2, </b>0]
</pre>
1. 9Akey, 11ikeyのミラー反転時、上下が逆になり操作しにくいケースがあるため。
また、このケースの対応のために多くのシャッフルグループを作るのは非効率のため。
- 上下左右の反転を目的とするため、下記の事象が発生しますが仕様とします。
- 7, 8, 14keyでは「Mirror」と「Asym-Mirror」が同一になる。
- 17keyの場合、上下左右の棲み分けが無いがシャッフルグループが4の倍数のため、
「Asym-Mirror」は設定できるが想定した反転にはならない。
- 元々「A-Mirror」とする予定でしたが、わかりにくいため「Asym-Mirror」に変更しました。
=> [0419/asym-mirror] 非対称ミラーの実装

js/danoni_main.js
1. 一時矢印色変更時に影矢印も色変更するよう見直しました。
2. 影矢印取得処理を集約しました。
3. changeTmpColor関数をfor文の外に移動しました。
1. 一時矢印色変更時に影矢印の色は追随できていなかったため。
2. 影矢印取得処理がほぼ同じ処理のため。
3. 毎回定義し直す必要が無いため。
=> [0421/change-tmp-shadow] 一時矢印色変更時に影矢印も色変更するよう見直し

js/danoni_main.js
1. 一時的にシャッフルグループ番号を変更する機能を実装しました。
仕様は矢印色の場合 ( PR  #1060 ) と同じで、リロードするまでの間有効です。
キーコンフィグ画面のシャッフルグループ番号をクリックして変更します。
グループ番号は1～10まで割り当て可能です。
1. シャッフルグループがすでにありますが、それに当てはまらないケースに柔軟に対応するため。
従来のシャッフルグループは良く使用するグループとして保持しておくこととします。
- ラベルをボタン化しただけなので、ID名は変わりません。
- 変更した場合、矢印色とは異なり譜面内容が変わるため、
カスタムしたことがわかるようにした方が良いかどうかは検討中です。→一旦そのままにしました。
=> [0425/change-tmp-shuffle] 一時的にシャッフルグループ番号を変更する機能を実装

js/danoni_main.js
1. shuffleUse=group時にシャッフルグループ番号が変更できないよう修正しました。
1. シャッフルグループを変更してはいけないパターンが存在するため。
=> [0428/shuffle-group] shuffleUse=group時にシャッフルグループ番号が変更できないよう修正

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js
- #1074 9A/11ikeyにおいてシャッフルグループを追加
- #1075 一時的にシャッフルグループ番号を変更する機能を追加
- #1076 デフォルトキーコンフィグ配列の二重記載を廃止（コード見直し）
- #1077 カーソル処理の処理集約
- #1079 shuffleUse=group時にシャッフルグループ番号が変更できないよう修正
=> [ver22.3.1] シャッフルグループ番号の一時変更、9A/11ikeyのシャッフルグループ追加　他（再）

js/danoni_main.js
1. shuffleUse=group時にシャッフルグループ番号が変更できないよう修正しました。
#1079 と同じですが、ボタンが押せないように修正しています。
1. ボタンが押せる状態にもかかわらず、何も反応しない状態でメッセージも出ない状況だったため。
=> [0429/shuffle-group] shuffleUse=group時にシャッフルグループ番号が変更できないよう修正（再）

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js
- #1074 9A/11ikeyにおいてシャッフルグループを追加
- #1075 一時的にシャッフルグループ番号を変更する機能を追加
- #1076 デフォルトキーコンフィグ配列の二重記載を廃止（コード見直し）
- #1077 カーソル処理の処理集約
- #1079 shuffleUse=group時にシャッフルグループ番号が変更できないよう修正
- #1081 shuffleUse=group時にシャッフルグループ番号が変更できないよう修正（再）
=> [ver22.3.2] シャッフルグループ番号の一時変更、9A/11ikeyのシャッフルグループ追加　他

js/danoni_main.js, js/lib/danoni_constants.js
1. メイン画面以外でキーリピート禁止を緩和しました。
引き続き禁止するキーはKeyBoardEvent.codeの指定に従い、danoni_constants.jsで定義します。
※ただし、キーコンフィグ画面、ロード画面は引き続きリピート禁止にします。
```javascript
// メイン画面以外でキーリピートを許可しないキーを設定
const g_unrepeatObj = {
key: [`Enter`, `Backspace`, `Delete`, `Escape`, `NumpadEnter`, `Tab`],
page: [`keyConfig`, `loading`, `loadingIos`],
};
```
```javascript
/**
* キーを押したときの動作（汎用）
* @param {object} _evt 
* @param {string} _displayName 
* @param {function} _func
*/
const commonKeyDown = (_evt, _displayName, _func = _code => { }) => {
const setCode = transCode(_evt.code);
if (_evt.repeat && (g_unrepeatObj.page.includes(_displayName) || g_unrepeatObj.key.includes(setCode))) {
return blockCode(setCode);
}
g_inputKeyBuffer[setCode] = true;
```
2. メイン画面で、PageUp/PageDownボタンのみキーリピートを許可しました。
1. 過去、PR #810 …
=> [0432/unrepeat-key] メイン画面以外でキーリピート禁止を緩和

js/danoni_main.js
1. 譜面詳細開閉ボタンで右クリックでも動作するよう変更しました。
1. 他のボタンとの処理統一のため。
- 動作の変更はありません。
=> [0433/right-click] 譜面詳細開閉ボタンで右クリックでも動作するよう変更

js/lib/danoni_constants.js
1. リモート画像が使用できない問題を修正しました。
1. 先の #1090 にてサブフォルダを参照するように変更しましたが、
リモート先の画像パスが `../img//cursor.svg` のような形式ではアクセスできなかったため。
- 将来拡張しやすいように、g_imgObjの定義位置を`loadBinary`関数より前に変更しています。
これにより、`loadBinary`関数を直接変更し、埋め込み画像をカスタム定義させることも可能になります。
=> [0436/img-link] リモート画像が使用できない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
- 曲開始位置をWebAudioAPIで微調整することでAdjustmentを0.1単位で設定できるようにしました
- [Adjustmentが小数点以下で合わない](https://twitter.com/vdos2643/status/1429445149143146503)と感じる場合があるようです
- 私は1f未満の差は正直よく分かりません
- [自サイトに適用済](https://suzume.kirara.st/atmosphere/)なので分かる方に試していただけるとありがたいです
- WebAudioAPIが利用できない条件では小数点以下切り捨てで動作します
=> Adjustmentを0.1単位で設定できる機能の追加

js/danoni_main.js
1. blankFrameや譜面データが極端に小さいフレーム数のとき、Adjustmentが一部利かない問題を修正しました。
対処方針として、Adjustmentの整数値部分は従来のやり方に戻し、
小数部分のみ音源位置調整に委ねる方法を取っています。
1. Resolves #1101 
- v23.0.0のみ発生する事象です。
=> [0442/decimal-adjustment] 譜面データが極端に小さいフレーム数のときにAdjが一部利かない問題を修正

js/lib/danoni_constants.js
- タイトル画面からのスタートやプレイ開始ボタンなど、ショートカットにエンターキーが割り当てられていた動作に対してテンキーエンターも追加しました
- 利便性向上およびFlash版ソースと仕様統一のため
- 特になし
=> プレイ開始ボタンなどのショートカットにテンキーエンターを割り当て

js/danoni_main.js, js/danoni_setting.js
1. ImgType: Original の位置を自由な位置に入れられるよう変更しました。
空文字で挟むことで対応します。
```
|imgType=$classic,png$classic-thin,png|　// Original, classic, classic-thinの順
|imgType=classic,png$$classic-thin,png|   // classic, Original, classic-thinの順
```
```javascript
const g_presetImageSets = [``, `classic,png`, `classic-thin,png`];　// Original, classic, classic-thinの順
```
1. デフォルトの画像セットを最初に持ってくるといった場合に対応するため。
=> [0443/imgtype-org] ImgType: Original の位置を自由な位置に入れられるよう変更

js/danoni_main.js, js/lib/danoni_constants.js
- オプション項目の最内側に不可視ボタンがあるとき、中央のラベルボタンの動作を最内側ではなく内側ボタンと同じにするよう修正
- Alt+←or→のショートカットでスピードをx0.05単位で変更できる機能を追加
- #1096 にてAdjustmentボタンの仕様が変わりましたが、
他のオプション項目とは違い中央ボタンのみ独自の動作をするのは統一性がなく違和感があるため
- より正確な適正倍速でプレイできるようにするため
- g_btnAddFunc などでボタンをカスタムしているときに影響を与える可能性があります
=> オプション画面のボタン動作見直し、速度設定細分化

js/danoni_main.js
1. フリーズアローを押し直したとき終端がズレる問題を修正
2. フリーズアローを離したとき全体の位置がズレる問題を修正
1. フリーズアローを押し直すたびに changeHitFrz が実行されていたため、初回のみ実行するようにしました
2. ステップゾーンと実際にフリーズアローを押し始めた位置のズレ幅（delFrzLength）を
g_attrObj[frzName].y に対しても反映するようにしました
以下のバグも見つかっていますが、現時点では良い解決法が見つかっていません
3. boost, brake 使用時に、早めにフリーズアローを押し始めると終端の位置がズレる
4. 遅めにフリーズアローを押し始めると、終端の直後に次のフリーズアローが存在する場合にのみ、
最後まで押し切ってもイクナイ判定となってしまう（#341 からのバグ）
3は対応したいですが、4は根が深そうなので別件としたほうがいいかもしれません
=> フリーズアローの挙動見直し

js/danoni_main.js, js/lib/danoni_constants.js
1. Boostオプション付加時の起動計算を見直しました。
（変化イメージはスクリーンショットを参照）
従来のBoostと比較した場合の差異は下記の通りです。
- 従来：ステップゾーンの到達時速度＝Speedで設定した倍速× 2.4
- 今後：ステップゾーンの到達時速度＝Speedで設定した倍速＋2x 程度
1. 従来の計算方法では加算値の振れ幅が速度成分に比例するため、
ほとんどのケースで常時高速となり、低速Boostしか使えていない状況でした。
Brakeと同じ振れ幅に制限することで本来のBoostらしい、
徐々に加速する動きになると思います。
- 試験的に自サイトの作品に適用しています。
https://cw7.sakura.ne.jp/danoni/2013/0237_Cllema.html
=> [0446/boost-frames] Boost時の軌道計算を見直し

SECURITY.md, js/danoni_main.js
- #1110 
- フリーズアローを押し直したとき終端がズレる問題を修正
- フリーズアローを離したとき全体の位置がズレる問題を修正
- boost, brake 使用時に、早めにフリーズアローを押し始めると終端の位置がズレる問題を修正
- 遅めにフリーズアローを押し始めると、終端の直後に次のフリーズアローが存在する場合にのみ、
最後まで押し切ってもイクナイ判定となってしまう問題を修正
- #1111
=> [ver23.1.1] フリーズアローの挙動見直し、Boost時の軌道計算見直し

js/danoni_main.js, js/lib/danoni_constants.js
1. Adjustmentのオンマウス説明文（ボタンの仕様）が一部間違っていたのを修正しました。
2. 設定画面の前/次ボタンのコードを一部見直しました。
1. ver23.2.0よりボタンの刻み幅が再度変わっているため。
2. 意味合いは同じですが、できるだけ初期思想に合わせた実装にしました。
- 機能的な不具合ではなく、軽微なものです。
=> [0449/msg-setting] Adjustmentのオンマウス説明文の修正、コード修正

js/danoni_main.js, js/lib/danoni_constants.js
1. ReverseのショートカットキーをRキーに統一しました。
2. Scrollのショートカットキーを上下キーに変更しました。
3. Scroll無効時、Reverseの左キーとラベルボタンの一部が押せない問題を修正しました。
4. Scroll有効かつ拡張スクロールが無い（9ikeyや17key）場合、
Reverseの左右キーが押せない問題を修正しました。
1. Scroll設定がある場合、「R」キーを押すと見た目はReverseが変更していないにもかかわらず、
設定上は変更されてしまうため。
2. 1.の変更により「↑」キーに空きができたことと、上下キーでScroll設定とした方がわかりやすいため。
3. `reverseSprite`の上に表示されている`scrollSprite`は見えない状態になっていたが、
存在はしている状態だったため、ボタンが押せない状況になっていた。
4. `scrollSprite`上の左右ボタンが常時可視状態になっていたため。
詳細は下記の「その他コメント」を参照。
- Scroll横のショートカット表記が長いため、フォントによっては二段になる。
表示に支障はないため、一旦そのままで様子を見る。
- 3.について、ver10.2.1 ( #530 ) からの既存の問題であることが判明。
ボタン類が無くても、オブジェクト自体は存在していることが考慮されていなかったと推測。
- 4.について、ver23.0.0 ( #1096 )で発生した問題。
makeMiniCssButton関数で明示的にvisibilityを定義するようにしたため、
本来非表示にすべきボタンが、後で子要素のみ表示されてしまったことが原因。
この部分は親要素のdisplay属性を「none」に指定することで親要素配下が最初から存在しないような動きにできるので、今回 …
=> [0452/rev-shortcut] ReverseのショートカットをRキー、Scrollのショートカットを上下キーに変更

.github/CONTRIBUTING.md, README.md, SECURITY.md
1. Readme, Contributing などの各種文言の見直しを行いました。
- 要望事項の連絡先を(PR以外の場合) GitHubのIssue, Gitterにする。
- グローバル変数について、最近は既存のグローバルオブジェクトの中の1プロパティとして定義することが多いため、その実態に合わせる。
- Flash Playerのサポート終了に伴い、Readmeの説明文を修正。 
1. 時間経過と共に内容が変化しているため、現在の実態に合わせます。
- 優先度低め。他の機能更新時に合わせてマージする予定です。
=> [0451/contributors] Readme, Contributingの文言修正　他

js/danoni_main.js
1. PR #1120 の修正で、main側でbtnAddFuncを使わず、別引数にて実現するよう変更しました。
1. カスタム側でbtnAddFuncを使って処理追加するケースに対応するため。
- createGeneralSetting に引数を追加する方法で実現しています。
これは共用関数であり、またショートカット文字を表示するための条件の中で
指定したidの形式が`lnk_____R`の形式であるという制約があるため、このような対処にしています。
本来は`addRFunc`があれば十分ですが、今後左側カーソルの処理を入れないとも限らないため、
今回は使用しないものの、`addLFunc`を追加しています。
- 過去バージョン適用時、同様の考慮が必要なためマークを入れています。
=> [0453/rev-shortcut2] main側ではbtnAddFuncを明示的に使わないよう修正

.github/CONTRIBUTING.md, README.md, SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js
- #1120 
- ReverseのショートカットキーをRキーに統一
- Scrollのショートカットキーを上下キーに変更
- Scroll無効時、Reverseの左キーとラベルボタンの一部が押せない問題を修正
- Scroll有効かつ拡張スクロールが無い（9ikeyや17key）場合、
Reverseの左右キーが押せない問題を修正
- #1121
=> [ver23.3.1] Reverse, Scroll周りのボタンの問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. All Perfect達成時のランクをAPに変更しました。
- 黒背景時は白、白背景時に黒になるように設定しています。
1. Discordサーバーでの要望より。
- 変数名を一部変更しています。
- g_rankObj.rankColorPF -> g_rankObj.rankColorPerfect
- g_rankObj.rankMarkPF -> g_rankObj.rankMarkPerfect
=> [0454/AP-rank] ランクAPの実装

js/danoni_main.js, js/lib/danoni_constants.js
1. プレイ画面に譜面名を表示するよう変更しました。
2. プレイ画面の曲名・アーティスト名について、
横長に合わせて文字サイズを調整するよう変更しました。
また、スコアや速度変化表示などカスタムを行っている場合を想定し、
クレジット表示を被せたくない幅をpx単位で設定できるようにしました。
```
|customCreditWidth=150|
```
3. タイトル画面のクレジットリンクサイズを調整しました。
こちらのMaker, Artistについても全体枠に入るようにサイズ調整するようになります。
（最小で12px）
1. Gitter要望より。
https://gitter.im/danonicw/community?at=614d9e3363dca81891792046
2. 1.の変更により横幅が足りなくなる可能性があるため。
3. クレジットが長い場合、改行されて崩れる場合があるため。
- クレジット欄がアーティスト名含め12px未満となる場合は、
アーティスト名を譜面名の行へ移動したうえでそれぞれの行サイズを調整
- タイトル画面（アーティスト名が長い場合）
- 曲名・アーティスト名が長すぎる場合、
フォント最小値の関係で折り返しが発生する可能性があります。
- 曲名・アーティスト名及び曲時間の位置を5pxほど上にしています。
- 譜面名について、Onigiriなしや制作者名（makerView指定時）は表示しますが
別キー表示は行いません。
=> [0455/difficulty-name] プレイ画面に譜面名を追加、曲名長に合わせて文字サイズを調整

js/danoni_main.js
1. バージョン名のフォントサイズを調整できるよう変更しました。
1. PR #1124 関連の修正です。タイトルのMaker, Artistと同様に枠内に収めるようにしています。
=> [0457/fontsize] バージョン名のフォントサイズを調整できるよう変更

danoni/danoni1.html
1. サンプルhtml (danoni1.html)の画像リンク間違いを修正しました。
1. classicフォルダへの移動に伴い、リンク切れとなっていたため。
- 本体ソースに影響するものではないため、過去バージョンには反映しません。
=> [0459/sample-html] サンプルhtmlの画像リンク間違いを修正

js/danoni_main.js
1. カスタムキーの名前を変更できる機能を追加しました。
```
|keyExtraList=11C|
|keyName11C=11|  // 11Ckeyではなく11keyとして表示
|color11C=...|  // 他の設定は11Cとして設定
```
1. 見た目は既存キーで、中身をカスタムしたい場合に
既存のキー設定に引きずられることがあるため。
```
|keyExtraList=11a|
|keyName11a=11|
|color11a=3,3,3,3,4,0,1,0,2,0,1,0$4,3,3,3,3,0,1,0,2,0,1,0|
|chara11a=sleft,sdown,sup,sright,oni,left,leftdia,down,space,up,rightdia,right$oni,sleft,sdown,sup,sright,left,leftdia,down,space,up,rightdia,right|
|div11a=7$7|
|stepRtn11a=0,-90,90,180,onigiri,0,-45,-90,onigiri,90,135,180$onigiri,0,-90,90,180,0,-45,-90,onigiri,90,135,180|
|keyCtrl11a=37,40,38/0,39,32,83,68,70,32,74,75,76$32,37,40,38/0,39,83,68,70,32,74,75,76|
|pos11a=2,3,4,5,6,7,8,9,10,11,12,13,14$2,3,4,5,6,7,8,9,10,11,12,13,14|
|transKey11a=$|
|scroll11a=Flat::1,1,1,1,1,-1,-1,-1,-1,-1,-1,-1|
```
=> [0458/keyname] カスタムキーの名前を変更できる機能を追加

js/danoni_main.js
1. word_data（歌詞表示）の初期色をCSSに任せる設定に変更しました。
1. 明背景のとき、初期色が白なので強制的に色を変える必要がありました。
今後はCSSに従うので、`skinType=white`とすれば文字色のデフォルトが黒になります。
=> [0461/lyrics-white] word_dataの初期色をCSSに任せる設定に変更

js/danoni_main.js
1. 矢印データが昇順で無い（厳密には最初の矢印データのフレーム数より小さいフレーム数がデータの真ん中に存在する）場合に矢印が出てこない問題を修正しました。
```
|left_data=200,300,400,500,600,700,800,50,55,60,65,70,75,80|
```
1. Gitterからの報告より。
https://gitter.im/danonicw/community?at=61595d062197144e84443743
本来はエディター側で並び替えが行われるため、本体側で考慮していませんでしたが
簡易的にできる範囲で対応します。
- 矢印データ、速度変化、色変化、矢印モーションデータに対して並び替え処理を追加しています。
極力、今のコード構成を壊さないように修正しました。
- 歌詞表示、背景・マスク表示は元々順序系には依存しないため、そのままです。
=> [0462/chart-sorting] 矢印データが昇順で無い場合の問題を修正

js/danoni_main.js
1. Firefox時、警告ウィンドウの高さが最小化される問題を修正しました。
`range.getClientRects().length`(ver24以降採用)と
`_text.split('<br>').length + _text.split('<p>').length - 1`(ver23以前)を比較して
大きい方を採用する方式に変えています。
1. Firefoxの場合、警告ウィンドウの行数を取得する`range.getClientRects().length`が常に1となり
正しい高さが取得できないため。
https://developer.mozilla.org/ja/docs/Web/API/Element/getClientRects
- Firefoxで、自動改行かつ高さが150pxに満たない場合に問題となる可能性がありますが
大半の問題は解消できるため、一旦この内容でPull Requestを出します。
- ver24.0.0 #1144 の項番2に起因する問題です。
=> [0471/warning-window] Firefox時、警告ウィンドウが最小化される問題を修正

js/danoni_main.js
1. 音楽ファイル指定が無いときに止まる問題を修正しました。
2. ローカルファイル起動時のコードを見直しました。
3. 音楽ファイルが無いとき、Backボタンで復帰できるようにしました。
4. musicUrlが未指定で強制スタートした場合、nosound.mp3を見るように変更しました。
1. 警告メッセージ「W-0012」の表示条件を取得するため、musicUrlの値を取得していましたが
musicUrlが存在しない場合にエラーで止まっていました。
2. Firefox時の警告メッセージ表示条件が間違っていたため。
またIEではこのメッセージは出せないこと、旧Edgeも終了後しばらく経過することから
ブラウザ警告の対象外としました。
3. 従来はF5リロードが必要で、ひと手間掛かっていたため。
4. 1.に関連して、初期値を空にしてしまうとサーバ上で動かした際に途中で止まる問題があるため。
=> [0472/cr-common] 音楽ファイル指定が無いときに止まる問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. デフォルト音源利用時、無音であることをプレイ画面で表示するようにしました。
1. musicUrlが無指定であることを明示的にわかるようにするため。
#1151 の変更により、musicUrlが無指定でもプレイできるようになったため、無指定もしくはデフォルト音源を使用していることがわかるように明示する必要がありました。
=> [0473/silence-mode] デフォルト音源利用時、無音であることをプレイ画面で表示するよう変更

js/danoni_main.js, js/lib/danoni_constants.js
1. 判定キャラクタ位置（X座標）とコンボ位置の間を少し広げました。
2. 英語時の判定名を大文字のみ⇒小文字混じりに変更しました。
|判定種類|キャラクタ位置<br>(従来との差分)|コンボ位置, Fast/Slow<br>(従来との差分)|
|矢印|-20px|0px|
|フリーズアロー|-20px|0px|
1. 英語版の場合、判定名が長くコンボ数が10000を超えると重なる可能性があるため。
2. 他の表記と統一するため。判定幅を広く取りすぎないための対策。
=> [0474/judge-posX] 判定キャラクタ位置（X座標）の微調整

js/danoni_main.js
1. 歌詞表示、背景・マスクモーションにおいて多言語化に対応しました。
以下のように言語分けができます。
未指定時は言語指定なしのものが優先されます。
|言語指定なし|日本語指定|英語指定|用途|
|word_data|word**Ja**_data|word**En**_data|歌詞表示|
|back_data|back**Ja**_data|back**En**_data|背景データ|
|mask_data|mask**Ja**_data|mask**En**_data|マスクデータ|
- backtitle_data, backresult_data, back2_data なども同様に使えます。
- (言語指定) > (言語指定なし) の順に適用されます。
- maskJa_data と mask2_data の場合、maskJa_data が優先されます。 
- 2譜面目の指定方法は maskJa2_data や backEn2_data のように指定します。
1. 言語により表示内容を変える場合があるため。
=> [0477/lang-data] 歌詞表示、背景・マスクモーションにおいて多言語化に対応

js/danoni_main.js
1. リバース時の歌詞表示位置の問題を修正しました。
2. 1.に伴い、歌詞表示、背景・マスクモーションの言語別設定の優先度を見直しました。
例えば、歌詞表示関連で言えば次の順で適用されます。
wordRevEn2_data > wordRevEn_data > wordRev2_data > wordRev_data > wordEn2_data > wordEn_data > word2_data > word_data
1. 言語別設定が入ったことでリバース用フラグがおかしくなっていたため。
2. 1.の問題解消によるものです。
- #1157 の変更影響のため、既存のバージョンには影響しません。
=> [0478/cr-lang] コード整理、リバース時の歌詞表示位置の問題を修正

js/danoni_main.js
1. playbackRate使用時に小数フレーム値が考慮されるよう変更しました。
矢印個別のフレーム数は整数に丸められるため、通常時は変わりません。
- Math.round((parseInt(指定フレーム数) - blankFrame) / g_headerObj.playbackRate + adjustment)
- Math.round((parseFloat(指定フレーム数) - blankFrame) / g_headerObj.playbackRate + adjustment)
1. playbackRate（音楽再生速度）を変更した場合、それに応じたフレーム数を計算しますが、
変更前のフレーム数が整数になっていたため、ズレが生じやすくなっていました。
計算上の誤差を少なくするのが目的です。
=> [0479/decimal-frame] playbackRate使用時に小数フレーム値が考慮されるよう変更

js/danoni_main.js
1. 特殊キーパターンの設定を一部省略指定できるようにしました。
各設定について、(キー数)_(パターン番号-1) で指定できます。
すでに定義済みであることが条件です。他キーパターンの設定も指定できます。
```
|color6=0,1,0,1,0,2$6_0|
|chara6=arrowA,arrowB,arrowC,arrowD,arrowE,arrowF$6_0|
|div6=6$3|
|stepRtn6=0,45,-90,135,180,onigiri$6_0|
|keyCtrl6=75,79,76,80,187,32/0$6_0|
```
```
|color6=0,1,0,1,0,2$0,1,0,1,0,2|
|chara6=arrowA,arrowB,arrowC,arrowD,arrowE,arrowF$arrowA,arrowB,arrowC,arrowD,arrowE,arrowF|
|div6=6$3|
|stepRtn6=0,45,-90,135,180,onigiri$0,45,-90,135,180,onigiri|
|keyCtrl6=75,79,76,80,187,32/0$75,79,76,80,187,32/0|
```
1. Resolves #947 
同様の指定方法を何度も記載するのが手間なため。
- 今回の設定は、キーコンフィグが異なる場合や、矢印の回転量の設定が違う場合などに
他の設定を流用するためのものです。
- キーの数が違うものを指定した場合、意図した設定にならないことがあります。
- keyExtraListの指定は必要ですが、今は既存キーを上書きしない方法ができるので
その方法を取った方が既存キーに影響することはありません。
- blank, transKeyのみ、無指定があるため流用できないことがあります。 …
=> [0482/default-keyptn] 特殊キーの略記指定に対応

js/lib/danoni_constants.js
1. 保存済みキー数設定の一部設定誤りを修正しました。
`g_keyCopyLists`の項目をver24.2.1以前の状態に戻しています。
1. ver24.3.0にて `g_keyCopyLists`の項目を一部修正したが、結果的に修正不要だったため。
- この部分は修正しなくても不具合にはつながらないため、次回更新時に反映する方向とします。
=> [0483/key-copylist] 保存済みキー数設定の一部設定誤りを修正

js/danoni_main.js, js/lib/danoni_constants.js
1. キーコンフィグ画面のPlayボタンにショートカットを追加しました。
「Backspaceキー (MacではDeleteキーと呼ぶ)」＋「Enterキー」の組み合わせで動作します。
※必ず「Backspaceキー」を押してから「Enterキー」を押す必要があります。
1. このPlayボタンのみ、ショートカットキーの割り当てが無かったため。
Enterキーは割り当てキーで使用するため、組み合わせにて対処しました。
- 「Backspaceキー」＋「Enterキー」を押した場合、カーソルが動く挙動がありますが
基本問題ないため、そのままにします。
=> [0485/keycon-shortcut] キーコンフィグ画面のPlayボタンにショートカットを追加

js/danoni_main.js, js/lib/danoni_constants.js
1. Hidden+/Sudden+/Hid&Sud+の初期位置の設定、ロック機能を実装しました。
「Lock」をクリックすると、プレイ中のPageDown/PageUpの操作が無効になります。
また、ロック中はレーンカバーの境界線の色が水色になります。
2. createGeneralSetting関数で真ん中のボタンに対してボタン拡張が行えるようにしました。
1. Gitterからの要望より。
https://gitter.im/danonicw/community?at=61b3598ecdb5c1081a57b0d1
2. 今回の1.の変更で必要になったため。
- 左側が従来、右側が変更後のもの。
- レーンカバー位置は微調整するため、1%ごとに変更できるようスライダーを採用しています。
- Appearance設定の位置を若干上に移動しています。
- 変更関数について
- Add: setLockView, dispAppearanceSlider
- Mod: createGeneralSetting
=> [0487/hidsud-lock] Hidden+/Sudden+の初期位置・ロック機能の実装

js/danoni_main.js
1. カラーグループが複数あるパターンAが保存済みのパターンBで無いとき、
保存済みのパターンBの色情報をパターンAで上書きしてしまう問題を修正しました。
2. データ保存有効時、シャッフルグループを変更してもタイトルに戻った後シャッフルグループが元に戻ってしまう問題を修正しました。
3. シャッフルグループ・カラーグループが複数ある場合、保存済みのキーパターン（Self）から保存元のキーパターンに反映されてしまう問題を修正しました。
1. Gitterでの指摘より。仕様誤りと思われます。
https://gitter.im/danonicw/community?at=61b5b044abdd6644e3d30f14
2. データ保存時の挙動について、シャッフルグループは他の情報と異なり
ローカルストレージの保存対象で無いため、既存の情報を保持する必要がありました。
3. 保存済みのキーパターン（Self）と保存元のキーパターンは別であるため、
反映させない動きが正しい。
- シャッフルグループにも似たような問題がありそうなので、合わせて確認します。
=> [0489/keyptn-groupset] カラーグループが複数あるときの挙動誤りを修正

js/danoni_main.js
1. シャッフルグループが利かない問題を修正しました。
1. PR #1174 の変更による不具合の修正です。
- この修正により、保存済みのキーパターン（Self）のシャッフルグループを変更すると
保存元のキーパターンに反映される問題が出ますが、
微細な問題で保存対象でも無いため、今回は対応保留します。
=> [0490/shuffle-group] シャッフルグループが利かない問題を修正

js/danoni_main.js
1. シャッフルグループ、カラーグループが単一のとき、初期化されない問題を修正しました。
1. 以下の問題が発生し、うまく初期化できていませんでした。
- 設定画面に入ったときsetDifficulty関数を通過しますが、
このときに保存済みのキー設定を読み出す処理があります（getKeyCtrl関数）。
この中にg_keyObjの「shuffle」や「color」の番号配列が含まれていたため、
一時的にこれらの番号を変更しても、元に戻る挙動になっていました。
⇒ 前にプレイした状態が「KeyPattern : Self」の場合は、g_keyObjの「shuffle」「color」「chara」「pos」「stepRtn」を変更しないようにしました。
- キーコンフィグ画面に入ったとき、setColorType関数を通過する処理があります。
このとき、「color」の番号配列の1番目（ColorGroup: 1）を適用するようになっていました。
これだと、ColorGroup: 2 などを指定してプレイし、元に戻った際にColorGroup: 1が呼び出されてしまう問題があります。
⇒ カラーグループが複数ある際は、現在のカラーグループに対するg_keyObjの「color」の番号配列を取得するように変更しました。
- これらの修正を行っても、以下の挙動になりますがこれは仕様とします。
- シャッフルグループやカラーグループが単一のキーパターンの場合、
キーを変えると設定が元に戻る。
- これは、シャッフルグループやカラーグループが複数保持しているパターンでは
グループ内で個別に設定を保持している（shuffleX_Y_Z：Zはグループ個別番号）のに対して、
グループが単一の場合、1つしか設定を持っていないためである（shuffleX_Y）。
- …
=> [0491/sc-group] シャッフルグループ、カラーグループが初期化されない問題を修正

js/danoni_main.js
1. シャッフルグループ・カラーグループの処理を見直し、
`shuffleX_Y_Z`や`colorX_Y_Z`の番号配列をベースとしたやり方に変更しました。
2. KeyPattern: selfとそれ以外の設定を独立させるようにしました。
1. 部分的に`shuffleX_Y`や`colorX_Y`を使っていたことで処理が複雑になっていたため。
2. これまで、保存元のシャッフルグループ・カラーグループが変更された場合、
KeyPattern: self のシャッフルグループ・カラーグループも合わせて変更するようになっていたが、他の設定はそのような仕様になっていないため。
- PR #1176 の処理整理版です。
キーを変更すると設定が戻る件については仕様です。
=> [0492/sc-group2] シャッフルグループ・カラーグループの処理見直し

js/danoni_main.js
1. フェードイン時にそれまでの色変化・モーションデータを保持するようにしました。
フェードイン以前の色変化(color_data, acolor_data)とモーションデータ(arrowMotion_data, frzMotion_data)を溜め込んでおき、開始時に全て適用するようにします。
開始順に溜め込むようにしているため、後のものが適用されるようにしています。
1. フェードイン時でも色変化データやモーションデータを保持させるため。
- モーションデータについて、タイマーは現状を引き継ぎます。
アニメーションが掛かっている場合は矢印、フリーズアロー出現時から適用されます。
- このプルリクエストでは対応しませんが、今後背景、マスクに対して同様の措置を取る場合、フェードインかつアニメーションが途中にあるときの扱いを考える必要がありそうです。
=> [0495/color-motion-init] フェードイン時にそれまでの色変化・モーションデータを保持するように変更

js/danoni_main.js, js/danoni_setting.js, js/lib/danoni_constants.js
1. 歌詞表示、背景・マスク表示において、フェードイン時に
フェードインより前のデータを蓄積（＝プリロード）するよう変更しました。
#1181 の歌詞表示、背景・マスク表示版です。
- フェードイン時にそれ以前のデータを蓄積しない種別(word, back, mask)を作品別に指定できる設定を追加しました。
追加すると、従来通りフェードイン以前のデータは蓄積（プリロード）しません。
```
|unStockCategory=back,mask|  // back_data, mask_dataはプリロード対象外
```
- フェードイン時にそれ以前のデータをプリロードする条件を指定できるようにしました。
例えば下記の場合、back_dataやmask_dataに「fade」や「Fade」、「FADE」といった文字列がフェードイン直前に含まれているとプリロードしません。
カンマ区切りで複数指定が可能です。英字は「小文字」で指定が必要です。
```
|wordStockForceDel=|         // 無指定のため、除外条件なし
|backStockForceDel=fade|  // leftToRightFade、fadeoutなどのアニメーションが除外対象
|maskStockForceDel=fade,disappear|
```
- `unStockCategory`の共通設定ファイル版です。
配列形式で指定できます。指定するとまとめて今回の変更を無効にできます。
```javascript
const g_presetUnStockCategories = [`word`, `back`, `mask`];
```
- `wordStockForceDel`, `backStockForceDel`, …
=> [0497/stock-animation] 歌詞表示、背景・マスク表示においてフェードイン時に前のデータを蓄積するよう変更

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js
- #1187 
- defaultFrzColorUse=false のとき、矢印の色変化に追随してフリーズアローにも色変化を適用する機能を実装
- フェードイン時に個別色変化と全体色変化が混在している場合に色変化が反映されない問題を改善
=> [ver25.1.0] 条件付きで矢印と同時にフリーズアローに色変化を適用　他

js/danoni_main.js, js/lib/danoni_constants.js
1. キーコンフィグが隠れる場合に横スクロールできるよう対応しました。
ドラッグボールで動かせる他、カーソルの移動に合わせて画面もスライドします。
※タイトルやボタンはスライドしません。
2. 設定画面間のページ移動を関数化しました。
1. 必要となるケースは通常ありませんが、疑似キリズマなど一部のキーが隠れるケースがありえるため。
またキーの割り当て以外に一時的な色変更など、キーコンフィグの位置づけが変わってきているためです。
2. 今後、画面が増えた場合に備えた対応です。
- 1.の変更に合わせ、keyconSpriteの位置をY方向に12px下に移動し、
高さを300px -> 500px（ウィンドウの縦の長さ）に変更しています。
横スクロールを有効にすると、枠外のものが見えなくなってしまうのと、
横スクロールバーが見えてしまうと画面デザインに影響を与えるためです。
- 初期表示、リセット時は中央になるように表示されます。
何かキーを押したり、カーソル位置やシャッフルグループ番号を押すとスクロール位置を自動調整します。
=> [0499/cr-setting] キーコンフィグが隠れる場合に横スクロールできるよう対応、コード整理

js/danoni_main.js, js/lib/danoni_constants.js
1. js/cssファイルの読み込み方法を見直しました。
これによりcustomjs、skinTypeが3つ以上指定できるようになります。
2. カスタム関数の呼び出し方法を変更しました。
customjsの場合は「g_customJsObj.画面名」、skinTypeの場合は「g_skinJsObj.画面名」に
関数を追加していく形になります。
- 互換のため、従来の関数も呼び出しできるようにしています。
- この変更により、3つ目以降のファイルについて新たなカスタム関数を呼び出すことが可能になりますが、
呼び出し方法が変わりますので、ご注意ください。
3. カスタム関数 （XXXInit, XXXInit2 など）について、XXXInitが無くてもXXXInit2の直接呼び出しが可能になりました。
```javascript
function customMainEnterFrame2() {
// 省略
}
```
- カスタムファイル中、追加したい箇所へ記述することで可能です。
- 添え字を使わないため、これまでのやり方に近いと思います。
```javascript
function anotherCustomFunction() {
}
// anotherCustomFunctionをメインのフレーム毎処理に追加
g_customJsObj.mainEnterFrame.push(anotherCustomFunction); 
```
- g_customJsObjもしくはg_skinJsObjに直接関数を追加します。
- 既存関数を置き換える場合や、順序性を重視する場合はこちらの方が良いかもしれません。
※現状、既存関数を廃止する予定はありません。
```javascript
// 配列の添え字は0番目が1つ目、1番目が2つ目の関数となる
// …
```
=> [0500/multiple-files] js/cssファイルの読み込み方法の見直し

js/danoni_main.js, js/danoni_setting.js
1. cssファイルを追加で外部読込できる機能を追加しました。
使い方はcustomjs、g_presetCustomJsと同じです。
- 譜面側：customcss
- danoni_setting.js：g_presetCustomCss
2. loadMultipleFile -> loadMultipleFiles に関数名を変更しました。
1. アニメーションなどの格納にcssファイルを外部で持たせる場合があるため。
2. 他の関数との名称整合のため。
=> [0502/custom-css] cssファイルを追加で外部読込できる機能を追加

js/danoni_main.js
1. g_scoreObj.baseFrameの設定誤りを修正しました。
1. Resolves #1196 
`g_scoreObj.baseFrame`の設定について、従来はcustomMainInitの前に定義されていたが、
ver25.3.0のコード整理の際に消してしまったため。
g_scoreObj.frameNum - g_stateObj.intAdjustment が正しい。
(g_stateObj.intAdjustment = preblankFrame + ヘッダのAdjustment + 設定でのAdjustmentの整数値) 
- ver25.3.0でのみ発生します。
=> [0503/baseframe] g_scoreObj.baseFrameの設定誤りを修正

js/danoni_main.js
1. skinTypeがDefaultのとき、divBackが作成されない場合がある問題を修正しました。
1. ver25.3.0にてg_headerObj.skinTypeが使えなくなっているが、それを使った条件式があるため、代替手段が必要。
=> [0505/default-skin] skinTypeがDefaultのとき、divBackが作成されない場合がある問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. クリップボードコピーの方法を変更しました。
2. copyTextToClipboard関数の中にmakeInfoWindow関数を内包するようにしました。
3. makeInfoWindow関数の引数に _backColor を追加しました。
1. `document.execCommand`が非推奨になっているため。
代替として、Clipboard APIを使用します。
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
2. 現状、クリップボードコピーが完了した場合にメッセージを表示しているため。
3. クリップボードコピーに失敗することがあり、そのときのメッセージカラーを変える必要が出てきたため。
=> [0506/clipboard-api] クリップボードコピーの方法を変更

js/danoni_main.js, js/lib/danoni_constants.js
1. getStgDetailName関数における冗長な名称呼び出しを取り止めました。
2. `key`や`k-`のような部分についても `g_lblNamesObj` で変更できるようにしました。
3. スライダーの入力処理を共通化しました。
1. getStgDetailName関数は、g_lblNameObj['u_(名前)']の変数を呼び出すためのものだが、
`x`や`f`などの単位についてはすでに`multi`や`frame`が定義されているため。
2. キー数部分はボタン部分にあり、これまで置き換える方法が無かったため。
3. CodeClimateからの指摘より。
=> [0508/get-name] 冗長な名称呼び出しを取り止め、key名の変更に対応

js/danoni_main.js, js/danoni_setting.js
1. back/maskデータで画像パスのカレントディレクトリ指定に対応しました。
別のフォルダに作品ファイルを移動しても、danoni_main.jsの場所が適切に指定されていればそれに追随します。
2. 1.を設定で切り替えられるようにしました。
譜面ヘッダーでは「syncBackPath」、danoni_setting.jsでは「g_presetSyncBackPath」で指定します。
「true」にすると有効化します。デフォルトは「false」です。
1. このデータのみ、他と違ってフォルダの追随設定・カレントディレクトリ指定ができなかったため。
2. 既存作品に影響を与える可能性があるため。
- 最初からサブディレクトリなど違う場所に作品ページを置いている場合、
今回の変更を適用すると画像が反映されない可能性があります。
念のため、譜面ヘッダーかdanoni_setting.jsでの代替手段を用意する方向で考えます。
=> [0507/back-current-path] back/maskデータで画像パスのカレントディレクトリ指定に対応

js/danoni_main.js
1. http環境でクリップボードコピーに失敗する問題を修正しました。
1. ver25.4.0で使用した navigator.clipboard.writeText はローカル及びhttps環境で無いと使用できないため、
http環境の場合は従来のクリップボードコピーを使用する必要がありました。
https://propg.ee-mall.info/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0/javascript/js-http%E7%92%B0%E5%A2%83%E3%81%A7%E3%81%AFnavigator-clipboard-writetext%E3%81%8C%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%AB%E3%81%AA%E3%82%8B/
=> [0509/clipboard-http] http環境でクリップボードコピーに失敗する問題を修正

js/danoni_main.js, js/lib/danoni_constants.js, jsconfig.json
1. オブジェクト内で二重定義している箇所を見直しました。
2. カスタムキー定義に誤りがある場合にメッセージが表示されない問題を修正しました。
3. jsconfig.json の target属性を `es6`から`es2020`に変更しました。
1. エラーにはならないが、厳密にはやめた方が良い記述のため。
2. 引数の割り当て誤りのため。
3. es6以降で適用された機能を一部使用しているため。
https://code.visualstudio.com/docs/languages/jsconfig
- 2.について優先度は低いが過去バージョンにも適用する予定。
=> [0510/dupli-definition] 二重定義箇所を見直し

js/danoni_main.js, js/lib/danoni_constants.js
1. fast/slowを呼び出している関数を使って、結果画面に適正Adjustment値を表示する機能を実装しました。
イイ～マターリの判定領域に引っ掛かったジャストからの差分値を蓄積して、
その平均値から適正Adjustment値を0.1フレーム単位で表示します。
括弧無しが設定すべきAdjustment、括弧付が現在のAdjustmentからの差分を表します。
1. Fast/Slowである程度どちらに向ければ良いかはわかるが、具体的な補正先がわかりにくいため。
- 適正Adjustment値を、0.1フレーム単位にするのか、0.5フレーム単位にするのかは判断が要りそうです。
- わかりやすい略名が思いつかないため、一旦仮の名前を入れています。
- 日本語名：推定Adj、英語名：Est-Adj. (Estimated Adjustmentの略)と表記するようにしました。
差分値については、表示するメリットが薄い（推定Adjで事足りる）ことから表記を見送る予定です。
=> [0511/adjustment-view] 適正Adjを表示する機能を実装

js/danoni_main.js, js/danoni_setting.js
1. フリーズアローのデフォルト色セットの利用有無（defaultFrzColorUse / g_presetFrzColors）と
矢印色変化に対するフリーズアローの追従設定（frzScopeFromAC / g_presetFrzScopeFromAC）
を一部分離しました。
#1187 関連の変更です。
追従範囲を「Normal（通常時）」「Hit（ヒット時）」から選択して設定します。（未指定も可能）
```
|defaultFrzColorUse=false|  // フリーズアロー初期色(frzColor)が未定義のときは矢印初期色(setColor)から取得
|frzScopeFromAC=Normal|        // 通常時のみ追従
|frzScopeFromAC=Normal,Hit|    // 通常時、ヒット時両方追従
```
```javascript
// 通常時、ヒット時両方追従（ g_presetFrzColors を定義しないときは  |defaultFrzColorUse=false| を譜面側で定義）
const g_presetFrzScopeFromAC = [`Normal`, `Hit`];
```
デフォルトは「いずれにも追従しない」設定にします。
なお、この設定は `defaultFrzColorUse=false` もしくは `g_presetFrzColors=false` の**場合にのみ有効**です。
1. Gitter要望より。機能が異なるため分けて管理する必要がありました。
https://gitter.im/danonicw/community?at=61f0389c9a335454063e2e1d
- ver25.1.0～ver25.4.1のように、矢印色変化に対するフリーズアローを追従するには …
=> [0512/frz-with-arrowcolor] 矢印色変化に対するフリーズアローの追従設定を一部分離

js/danoni_main.js
1. 推定Adjの計算誤りを修正しました。
1. 上述の通り。g_stateObj.adjustmentの値が小さく評価され、正しい値になっていませんでした。
=> [0513/adjustment-view] 推定Adjの計算誤りを修正

js/danoni_main.js
1. 結果画面のNo Recordの文字が推定Adjと重なる問題を修正しました。
(No Record)の文字サイズを24px -> 20px に変更し、位置を15px左へずらしています。
1. Mirror/Randomなどでプレイしたときに発生します。
Gitterより報告がありました。
https://gitter.im/danonicw/community?at=61f4147fd41a5853f9728967
- 右側が変更後イメージです。
=> [0516/norecord-view] No Recordの文字が推定Adjと重なる問題を修正

js/danoni_main.js
1. シャッフル・カラーグループを変更した際にその内容が反映されない問題を修正しました。
1. ver24.5.1でコード整理を行った際、シャッフル・カラーグループ変更処理 (setGroup) で
実際の設定を反映する処理が抜けていたため。
Gitterより報告がありました。
https://gitter.im/danonicw/community?at=61f42696bfe2f54b2e3f0422
- 矢印やAAを直接選択して変更するパターンでは問題なく動作します。
=> [0515/group-change] シャッフル・カラーグループを変更した際にその内容が反映されない問題を修正

js/danoni_main.js
1. ダミー矢印、フリーズアローに対して色変化・モーションを適用できるようになりました。
使い方はダミー矢印、フリーズアローの方法と同じです。
```
|dummyId=101|
|color101_data=0,20,#999999|
|acolor101_data=3000,20,#9999cc|
```
1. 仕様定義が中途半端だったことと、一部より要望があったため。
- setColor/frzColorには現状仕様が複雑なため、非対応です。
- defaultFrzColorUse=false, frzScopeFromAC を指定した場合、
ダミー矢印の色変化にダミーフリーズアローが追随します。
- 内部関数が大半のため、影響はほぼないと思います。
|関数名|従来|変更後|
|mergeColorData|_header|_header<br>(引数は同じだが中身が異なる)|
|changeArrowColor|ー|新規追加|
|changeFrzColor|ー|新規追加|
|changeColors|_mkColor, _mkColorCd, _objType|_mkColor, _mkColorCd, _header, _name|
|changeCssMotions|_mkCssMotion, _mkCssMotionName, _name|_header, _name, _frameNum|
=> [0514/dummy-effects] ダミーエフェクト（色変化・モーションデータ）の実装

js/danoni_main.js
1. メイン画面のスキン拡張が利いていない問題を修正しました。
※従来のカスタム関数は変更前でも使用できます。拡張できていなかったというだけです。
1. 他の機能との整合のため。
- 不具合ではありませんが、機能不十分となるためv24には変更差分を適用する予定です。
=> [0517/skinjs] メイン画面のスキン拡張が利いていない問題を修正

js/danoni_main.js
1. コメントエリアを選択できるように変更しました。
2. コメントボタンの位置、サイズを調整しました。
1. コメント部分を選択するケースが考えられるため。
2. 横幅500pxのとき、コメントボタンとClick Here!!の文字が隠れてしまうため。
=> [0518/comment-select\] コメントエリアを選択できるように変更、ボタンサイズ調整

js/danoni_main.js, js/lib/danoni_constants.js
1. コメント文中に定義済み変数を埋め込む機能を追加しました。
次のように、`{定義済み変数}`の形で指定することで定義済み変数から値を取得して表示します。
```
|commentVal=
[7key / Normal]
BPM: 140, ツール値: {g_detailObj.toolDif[0].tool}
|
```
2. 中括弧に対して特殊文字を指定できるようにしました。
|指定文字|変換先|
|----|----|
|{|\*lbrace\*|
|}|\*rbrace\*|
1. コメント文の利便性向上のため。
2. 1.の変更に伴い特殊文字を指定する必要が出てきたため。
- この処理はタイトル用カスタム関数（g_customJsObj.title）の実行後に変数を読み込みます。
このためカスタムJsでグローバル変数として定義したものも読み込めます。
=> [0519/val-comment] コメント文中に定義済み変数を埋め込む機能を追加

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面密度グラフで二重押し/多重押し状況を表示するよう変更しました。
濃い色が二重押しの割合、さらに濃い色が3つ押し以上の割合を表します。
また、最大密度のときはピンクが二重押し、青が多重押しを表します。
1. 譜面密度傾向を細かく見ることができるため。
※実装に当たり、Tarwilさんのコードを一部参考にしました。
- 二重押し、多重押しの判断は矢印とフリーズ始点を基準にカウントしています。
このため、フリーズ中の矢印や始点位置の異なる多重フリーズアローはカウントしていません。
=> [0520/density-expantion] 譜面密度グラフで二重押し/多重押し状況を表示するよう変更

js/danoni_main.js
1. 推定Adjの計算方法を単純平均から誤差が正規分布になると仮定した場合の推定値になるよう変更しました。
1. Tarwilさんからの指摘より。
単純平均の場合、難譜面になるほど外れ値に影響されやすくなっていました。
https://twitter.com/Tarwil1503/status/1489681464681963521
=> [0521/estimated-adj] 推定Adjの計算方法を単純平均から正規分布ベースに変更

js/danoni_main.js
1. danoni_setting.jsで定義できる g_lblRenamesが未定義時に名称上書きができない問題を修正しました。
1. g_lblRenames未定義時には本来上書きできる仕様が正しいため。
=> [0524/lbl-renames] g_lblRenames未定義時に名称上書きができない問題を修正

js/danoni_main.js, js/template/danoni_setting.js
1. danoni_setting.js 上で共通のカスタムキー定義ができるようにしました。
- 作品別と同じ指定方法で定義します。**keyExtraList指定は必須**です。
```javascript
const g_presetKeysData = `
|keyExtraList=6,9v|
|color6=0,1,0,1,0,2$2,0,1,0,1,0|
|chara6=left,leftdia,down,rightdia,right,space$space,left,leftdia,down,rightdia,right|
|div6=6$6|
|stepRtn6=0,45,-90,135,180,onigiri$onigiri,0,45,-90,135,180|
|keyCtrl6=75/0,79/0,76/0,80/0,187/0,32/0$32/0,75/0,79/0,76/0,80/0,187/0|
|shuffle6=1,1,1,1,1,0$0,1,1,1,1,1|
|chara9v=9B_0$9B_0|
|color9v=1,0,1,0,2,0,1,0,1$9B_0|
|div9v=9$9|
|keyCtrl9v=52/0,82/0,70/0,86/0,32/0,78/0,74/0,73/0,57/0$9B_0|
|pos9v=0,1,2,3,4,5,6,7,8$0,1,2,3,4,5,6,7,8|
|scroll9v=---::1,1,-1,-1,-1,-1,-1,1,1/flat::1,1,1,1,1,1,1,1,1$9B_0|
|shuffle9v=9B_0$9B_0|
|stepRtn9v=90,120,150,180,onigiri,0,30,60,90$9B_0|
|transKey9v=$9B|
`;
```
2. …
=> [0525/keys-extension] 共通のカスタムキー定義実装、作品別のkeyExtraList指定を任意化

js/danoni_main.js
1. 作品別のkeyExtraList指定時に余計なキーを検出する問題を修正しました。
1. PR #1231 でkeysConvert関数の引数に配列を入れるべきところ、一部文字列が混在する箇所がありました。
=> [0526/keys-extension] 作品別のkeyExtraList指定時に余計なキーを検出する問題を修正

js/danoni_main.js
1. ファイル読込部分をasync/await形式に書き換えました。
互換性保持のため、一部関数を置き換えています。
|以前の関数名|変更後の関数名|関数概要|
|loadScript|loadScript2|jsファイルの読み込み|
|importCssFile|importCssFile2|cssファイルの読み込み|
|loadMultipleFiles|loadMultipleFiles2|複数ファイルの読み込み|
|loadSettingJs<br>initAfterDosLoaded<br>initAfterCssLoaded|loadBaseFiles|各種ファイル読込|
※loadDos関数についても、一部async/await形式に書き換えています。
2. customjsファイルの読み込み順を見直しました。
スキンcssファイルの読み込み直後、headerConvert関数の直前に移動しています。
1. callback関数のために関数呼び出しが複雑になっていたため。
2. headerConvert関数の前にカスタムファイルを差し込んだ方が利便性が高いため。
- 従来関数のうち、loadScript / importCssFile / loadMultipleFiles は互換のために残しますが、
次期バージョンでは danoni_legacy_function.js へ移動する予定です。
=> [0528/async-loading] ファイル読込部分をasync/await形式に書き換え

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js, js/template/danoni_setting.js, package.json
- #1235 
- danoni_setting.js で定義されている変数群を、g_presetObjへ移行
- 共通設定ファイルの変数を使った部分のコード見直し 
- #1236 
- ファイル読込部分をasync/await形式に書き換え
- customjsファイルの読み込み順をスキンcssファイルの後、headerConvert関数の前に移動
=> [ver26.3.0] 共通設定ファイルの変数統合、ファイル読込部分のコード見直し

js/danoni_main.js
1. PR #1240 関連。
loadChartFile, resetColorAndGauge関数について、
ファイル分割時以外は初期の譜面毎のファイル読込を止めるよう修正しました。
1. 同じ処理を繰り返しているだけで冗長のため。
=> [0531/loading-chart2] 余計な譜面ファイル読込をしないよう処理を見直し

js/danoni_main.js
1. loadScript2関数未使用の箇所を修正しました。（エンコード済み音楽データの読込）
2. コードの見直しを行いました。
3. 外部ファイル名末尾のランダム値を一部固定化しました。
1, 2. コード統一性のため。
3. 譜面ファイル以外は一度しか読み込まないため。
譜面ファイルはリトライ反映に対応するため、そのままとしました。
=> [0532/cr-loading] loadScript2関数未使用の箇所を修正　他コード見直し

js/danoni_main.js
1. カスタムキー定義のpos項目について小数点に対応しました。
下記のような指定が可能になります。
```
|pos8i=0.7,1.4,2,3,4,5,6,7|
```
1. ステップ間を等間隔にしないケースに柔軟に対応するため。
=> [0533/keypos-decimal] カスタムキー定義のpos項目について小数点に対応

js/danoni_main.js
1. 関数の順序を見直しました。 PR #1246 関連です。
処理内容に変化はありません。
1. 処理順に並んでいない部分があるため。
今後、コード整理を行うにあたり関数群がバラバラだと流れがわかりにくいため。
=> feat: [0536] 関数の順序を見直し

js/danoni_main.js
1. マターリを出すとキーが利かなくなる問題を修正しました。
1. PR #1249 の見直しの際、引数名の見直しも行いましたが、その中で修正漏れがありました。
=> fix: [0537] マターリを出すとキーが利かなくなる問題を修正

js/danoni_main.js
1. プレイ画面からリザルト画面移行時の100ミリ秒を廃止しました。
1. 以前は`resultInit()`を即時実行すると矢印・フリーズアローの移動処理が後に残っていたことがあったため
エラーが表示されることがありました。
ただ、上記問題が発生しやすい即時Failedやショートカット操作でも猶予秒はすでに廃止されており、
プレイ終了時であえてこの猶予秒を残す意味は無いため、廃止とする予定です。
- プレイ上の支障はないと思いますが、プレイ画面から結果画面に移行する際のモーションが100ミリ秒（60fpsの場合、6フレーム分）短くなる可能性があります。
- リザルトモーションのタイミングが重要となる作品の場合、
6フレーム後ろに設定する必要がある可能性があります。（未検証）
このため、同一バージョンでのマージは見送ることを考えています。
=> feat: [0541] プレイ画面からリザルト画面移行時の100ミリ秒を廃止

js/danoni_main.js
1. 文字列の置き換え方法を見直しました。
split -> join のような記述を replaceAll に置き換えています。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
2. フリーズアロー名の自動生成部分で不要な条件文を削除しました。
1. 本来の使い方ではないため。
2. 最初の文字列置換で吸収できる上、この条件があることで意図しない挙動になる可能性があるため。
=> refactor: [0542] 文字列の置き換え方法を見直し

js/danoni_main.js
1. プレイ画面から結果画面への移行フレーム差を埋める対応を行いました。
1. Resolves #902 
- ローカルで試した限りでは平均3フレームほど遅延しますが、殆ど気にならないと思われます。
遅れは時間経過と共にリカバリーされます。
https://github.com/cwtickle/danoniplus/wiki/AboutFrameProcessing
=> feat: [0545] プレイ画面から結果画面への移行フレーム差を埋める対応

js/danoni_main.js
1. タイトル文字で使用している -webkit-text-fill-color を color に変更しました。
https://developer.mozilla.org/ja/docs/Web/CSS/-webkit-text-fill-color
1. -webkit-text-fill-colorが非標準であり、colorに置き換えても違いが無いため。
=> refactor: [0547] webkit-text-fill-colorをcolorに変更

danoni/dTemplate.html, danoni/danoni0.html, danoni/danoni0_remote.html, danoni/danoni1.html, danoni/danoni2.html, danoni/danoni3.html, danoni/danoni4_skin.html, js/danoni_main.js
1. danoni_main.cssの記述を任意化しました。
今後は`danoni_main.js`と文字コード指定があればcssファイルも合わせて読み込みます。
従来通りcssファイルを指定した場合でも動作します。
※記述を任意にしただけで、`danoni_main.css`そのものは**今後も必要**です。
```html
<meta charset="utf-8">
<script src="../js/danoni_main.js"></script>
```
2. サンプルHTMLから以下の記述を削除しました。
```html
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta http-equiv="Content-Style-Type" content="text/css">
<link rel="stylesheet" type="text/css" href="../css/danoni_main.css">
```
1. 記載する量を減らすことで手軽に導入しやすくするため。
2. Content-Script-Type, Content-Style-Type の記述はHTML5以後ではデフォルト不要のため。
cssファイル部分については、1.の理由で不要となったため。
- danoni_main.cssの自動読込は、スキンcssを読み込む方法と同じ方法で実装しています（遅延読み込み）。
- htmlに記載している`<link>`要素を見て、`danoni_main.css`という記述がhref属性にいればすでに`danoni_main.css`が読込済みであると見做します。
=> feat: [0548] danoni_main.cssの記述を任意化

js/danoni_main.js
1. 作品別のカスタムファイル指定（customjs, customcss）に対して、共通設定ファイル上のカスタムファイル指定（g_presetObj.customJs, g_presetObj.customCss）を参照できる機能を実装しました。
- danoni_setting.js で`g_presetObj.customJs`が定義されているとき、
作品側の譜面ヘッダー「customjs」で「*」を指定すると、
`g_presetObj.customJs`で指定しているファイルに置き換えます。
※customcssも同様に設定可能です。
```javascript
g_presetObj.customJs = `danoni_init.js,danoni_init_type2.js`;
```
```
|customjs=*,special.js|
-> |customjs=danoni_init.js,danoni_init_type2.js,special.js| と同じ意味
```
1. g_presetObj.customJsがすでにあるにもかかわらず、
作品別のcustomJsを指定する場合は同じファイル名を記載する必要があるため。
=> feat: [0551] 作品別のカスタムファイル指定に対して共通設定を参照する機能を追加

js/danoni_main.js
1. canvas要素があるとき背景部の表示が欠けることがある問題を修正しました。
1. canvasで指定した幅がキー別の最小横幅より小さい場合、
デフォルトでは横幅が引き延ばされますが、canvasの幅はそのままのため、
背景が一部表示されない事象が発生していました。
- 現状、canvas要素をあえて指定する必要はありません。
=> fix: [0553] canvas要素があるとき背景部の表示が欠けることがある問題を修正

css/danoni_main.css, js/danoni_main.js, js/lib/danoni_constants.js
1. ColorType:1～4に対してColorPickerに対応しました。
左端にColorPickerが表示され、それを選択・変更することで
対応する矢印・フリーズアロー色が変わります。
2. 矢印のカラーセットをフリーズアローにコピーする機能を追加しました。
（ColorPickerに対応しているColorTypeのみ）
1. 現状、既定色以外の色変更が難しいため。
2. フリーズアローについて1つ1つ設定するのは手間のため。
- ColorType: Default, Type0は譜面別の色保持方法やグラデーションの問題があり煩雑なため、見送ります。
- 今回のcolorPickerは`colorPickSprite`にまとめているので、
カスタムで移動させたい場合はこのオブジェクトを移動すれば問題ありません。
- 現状、以下の問題があります。ただ殆どの場合問題にならないので、このまま進める予定です。
- 色配列をリセットする方法がない。
- キリズマ、パンパネのように横スクロールが発生する場合、左端の表示が隠れる。
=> feat: [0552] ColorType:1～4に対してColorPickerに対応

js/danoni_main.js
1. titleInit実行前にカスタム関数を挿入できるよう変更しました。
```javascript
function preTitleInit() {
// 処理
}
// g_customJsObj.preTitleに関数を挿入することで有効化（titleInit実行直前に処理）
g_customJsObj.preTitle.push(preTitleInit);
```
1. #1275 の対応により、画面表示が行われる前に固有の設定を変更するケースが出てくると思われるため。
=> feat: [0559] titleInit実行前にカスタム関数を挿入できるよう変更

js/danoni_main.js
1. createDiv関数を拡張し、クラスを付与できるようにしました。
```javascript
const createDiv = (_id, _x, _y, _width, _height, _classes = []);
```
2. カラーオブジェクト作成部分を拡張し、矢印以外の回転に対応しました。
stepRtnについて`onigiri:90`のようにコロン区切りで指定すると90度回転できるようになります。
```javascript
g_keyObj.stepRtn5_0 = [0, -90, 90, 180, `onigiri:90`];
```
1. 使用しているほとんどの部分でクラスを付加しているため。
2. 現状矢印のみ特別扱いになっていたため。
=> feat: [0562] div作成部分、カラーオブジェクト作成部分の拡張

js/danoni_main.js, js/lib/danoni_constants.js
1. キャメル表記に反している関数名を見直しました。
互換のため、従来の名前も転送するように変更しています。
|変更前|変更後|
|----|----|
|convertreplaceNums|convertReplaceNums|
|MainInit|mainInit|
1. 過去のコード見直しの過程で、小文字・大文字で置換してしまった影響です。
=> refactor: [0563] 意図していない関数名を見直し

js/danoni_main.js
1. カレントパス取得部分のURIエンコード処理を元に戻しました。
1. Gitterでの指摘より。
https://gitter.im/danonicw/community?at=628912bcdb6f627d25931313
PR #1277 にてカレントパス取得部分のURIエンコード処理を追加しましたが、
`document.currentScript.src`及び`document.getElementsByTagName(`script`)[i].src`では
すでにURIエンコードが行われているため、この処理自体不要でした。
=> fix: [0566] カレントパス取得部分のURIエンコード処理を元に戻す

js/danoni_main.js, js/lib/danoni_constants.js
1. カスタムキーのパターン追記方法を拡張しました。
`|appendX=true|`(X: 既存キー数)を指定すると、既存パターンに追加する設定を指定できます。
従来のように、既存パターンを繰り返す必要はありません。
```
|keyExtraList=12|
|minWidth12=675|
|append12=true|
|chara12=oni,left,leftdia,down,sleft,sdown,sup,sright,space,up,rightdia,right$12_4|
|color12=1,0,1,0,3,3,3,3,0,1,0,1$12_4|
|pos12=0,1,2,3,4,5,6,7,8,9,10,11$12_4|
|div12=12$12|
|stepRtn12=45,0,-45,-90,giko,onigiri,iyo,c,90,135,180,225$12_4|
|keyCtrl12=112/0,113/0,114/0,115/0,116/0,117/0,118/0,119/0,120/0,121/0,122/0,123/0$81/0,87/0,69/0,82/0,84/0,89/0,85/0,73/0,79/0,80/0,192/0,219/0|
|shuffle12=0,0,0,0,1,1,1,1,2,2,2,2$12_4|
|blank12=50$50|
|scroll12=Cross::1,1,1,1,-1,-1,-1,-1,1,1,1,1/Split::1,1,1,1,1,1,-1,-1,-1,-1,-1,-1$12_4|
|transKey12=12i$12i|
```
1. 既存キーの設定を上書きするリスクがあるため。
- パターンの略記指定は、既存パターンを追加した後の状態のものを指定します。
- …
=> [0569/append-keyptn] カスタムキーのパターン追記方法を拡張

js/lib/danoni_constants.js
1. Dランクを追加し、B, Cランクの基準を見直しました。
|ランク名|ランク基準(変更前)|ランク基準(変更後)|
|B|スコアが50万以上70万未満でクリア|スコアが**65万**以上70万未満でクリア|
|C|スコアが50万未満でクリア|スコアが**60万以上65万未満**でクリア|
|D|-|スコアが60万未満でクリア|
1. 現状でCランク（スコア50万未満）でクリアできる作品が主にPracticeくらいしかないため。
- danoni_constants.js のみの変更です。
=> feat: [0571] Dランク追加、B, Cランク基準見直し

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面明細ボタン「i」の位置をDifficultyラベル左に移動しました。
2. 譜面リスト（DifSelector）有効時、譜面リストを開いた状態から
譜面明細へ直接移動できるようにしました。
1. 譜面明細系のボタン（Speed, Density, ToolDif）が画面左側にあるにもかかわらず、
ON/OFFは右側にあり、動線が手間に感じることがあるため。
2. 譜面リスト（DifSelector）が表示中のとき、譜面明細が裏側にあるためON/OFFを押しても
何も起きないような動きになっていました。この動きを見直しています。
=> improve: [0572] 譜面明細ボタンの位置変更、譜面リストから譜面詳細への移動対応

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面明細系のボタンを役割毎に分割し、それぞれにショートカットキーを割り当てました。
それぞれ「1」「2」「3」のボタンに割り当てています。
2. Speed/Density/ToolDif選択時、どれが選択中かがわかるようなレイアウトに変更しました。
1. Speed/Density/ToolDifの移動がページ送りとなっており、わかりにくく感じることがあるため。
https://twitter.com/FUJI_kt/status/1553612119362650115
2. 譜面リストの画面レイアウトと仕様が合っていないため。
- 譜面リストとの重ね合わせ
- この時点で「1」「2」「3」キーを押すと、譜面リストを閉じて譜面明細画面へ切り替わる
- idの改廃状況は次の通りです。
- 削除: lnkScoreDetail, lnkScoreDetailB (共通ボタン廃止のため)
- 追加: lnkSpeedG, lnkDensityG, lnkToolDifG (個別ボタン追加のため)
- ラベル名の変更は従来通り `g_lblNameObj`で変更が可能です。
- u_Speed, u_Density, u_ToolDif
=> improve: [0573] 譜面明細系のボタンを役割毎に分割

js/danoni_main.js
1. 譜面明細画面周りでID名が重複していた問題を修正しました。
（共通処理のため、関連するID名も一部変更があります）
2. g_lblNameObjの設定により、譜面明細ラベル名に英数字以外が入りうる問題も合わせて修正しました。
|No|該当箇所|元ID名|変更後ID名|
|1|譜面明細 - Speedボタンのショートカット|scSpeed|scSpeedG|
|2|譜面明細 - Densityボタンのショートカット|scDensity|scDensityG|
|3|譜面明細 - ToolDifボタンのショートカット|scToolDif|scToolDifG|
|4|譜面明細 - Speed > 全体速度変化回数(Speed)|lblSpeed / dataSpeed|lblSpeedS / dataSpeedS|
|5|譜面明細 - Speed > 個別速度変化回数(Boost)|lblBoost / dataBoost|lblBoostS / dataBoostS|
1. デザイン全般を変える際に支障となるため。
2. updateScoreDetailLabel関数において、2番目の引数はラベル名の元情報となっているが、
`g_lblNameObj`を指定していたため、英数字以外のラベル名となる可能性があった。
（ラベル名の項目は5番目の引数があるため、本来はそれを使うべき）
- 1～3はver27.8.0起因、4～5は従来から発生していました。
=> fix: [0574] 重複するid名の解消

js/danoni_main.js, js/lib/danoni_constants.js
1. 設定画面内の譜面明細表示にて、従来のショートカットキー「Q」を復活させました。
「Q」キーを押すことで次の明細表示へ移動します。画面レイアウトは変えていません。
次のように押したときの挙動が変わります。
- 明細を開く＆Speed -> Density -> Tooldif -> 明細を閉じる -> 明細を開く＆Speed -> ...
- すでに明細が開いた状態の場合は次のカーソルへ移動します。
2. 未使用のラベル・設定類を削除しました。
- g_settings.scoreDetailNum
- g_lblPosObj.lnkScoreDetail
- g_lblPosObj.lnkScoreDetailB
1. 次の明細を表示する際に1ボタンで移動したいことがあるため。
2. ボタン廃止により現在は使用していないため。
- `g_shortcutObj.option.KeyQ.id` で指定している値は、「Q」キーを押すごとに変わるようになっています。
具体的には、`g_settings.scoreDetails = ['Speed', 'Density', 'ToolDif'];`の配列に従って変わります。
- 「Q」キーでカーソル移動するという表示は今のところ考えていません。
- 逆回しは明細表示が現状3つしかないため、実装しない予定です。
=> feat: [0575] 譜面明細画面の従来のショートカットを実装

js/danoni_main.js, js/lib/danoni_constants.js
1. ローカルファイル時にAdjustmentの小数設定ボタンを非表示化しました。
1. ローカルファイル時はAdjustmentの小数が使用できないため。
なお、不可視の±0.1Frame刻みはそのままにしています（画面上見えないため）。
- ローカルファイル時
- ローカルサーバー、リモートサーバー時
- 一部コード整理を行っています。
=> improve: [0576] ローカルファイル時にAdjustmentの小数設定ボタンを非表示化

js/danoni_main.js
1. 二次元配列のコピー関数(copyArray2d)の処理を
`JSON.parse(JSON.stringify(data))`から`structuredClone(data)`に変更しました。
https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
現状、ほとんどのブラウザはstructuredCloneを使える状況にあるため、差し替えても影響は無いと思います。
https://caniuse.com/?search=structuredClone
1. 今後、ディープコピーしている箇所の処理統一のため。
- 今回の変更はディープコピーが本当に必要な箇所に絞っており、それ以外の箇所はそのままです。
今後、structuredCloneを使うべきかどうかは個別に検討予定です。
=> improve: [0577] 二次元配列のコピー関数の実体をstructuredCloneに変更

js/lib/danoni_constants.js
1. ローカルファイル時にAdjustmentの小数設定ボタンの非表示化を取り止めました。
1. ローカルファイルでも、エンコード済み音源ファイルのときは小数Adjustmentが使用できるため。
エンコード済み音源ファイルかどうかはプレイ開始後で判断しているため、この仕様は見送りました。
- danoni_constants.js のみの変更です。
=> hotfix: [0578] ローカルファイル時にAdjustmentの小数設定ボタンの非表示化を取り止め

js/danoni_main.js, js/lib/danoni_constants.js
1. これまで画面を開いているときだけ有効になっていた、カラーセットをキー別に丸ごと保存するようにしました。
Type1～4を選択している場合に有効で、保存後は`TypeS`という表記に変わります。
Default/Type0についてはこれまで通りです。
なお、ColorTypeの設定はこれまで通り作品別に保存されます。
2. カラーグループ、シャッフルグループの保存に対応しました。
- カラーグループ、シャッフルグループが保存された場合は「S」と表記されます。
1. これまでは必要時に毎回再設定が必要になっていたため。
2. 1.と同じ理由です。
- 別キーに切替時、ColorType = `TypeS`が存在しない場合は ColorType = `Default` に切り替わります。
=> feat: [0581] カラーセットのキー別一括保存対応

js/danoni_main.js
1. ColorType: Type0が既定値にならない問題を修正しました。
1. ver28.1.0で修正した際の影響です。
Type0のとき、ColorTypeを`Default`に戻す動作になっていました。
ColorType: `TypeS`が保存済みのColorTypeで、`TypeS`が存在しないキーの場合のみ、`Default`に戻します。
=> fix: [0582] ColorType: Type0が既定値にならない問題を修正

js/danoni_main.js
1. カラーグループを変更した際、個々の矢印のカラーグループが反映されない問題を修正しました。
1. 値の代入する先が、変更前のカラーグループを指していたためこのような事象が発生していました。
直接矢印を変更して色を変更した場合や、設定を変更した場合は発生しません。
=> fix: [0583] カラーグループを変更した際、個々の矢印のカラーグループが反映されない問題を修正

js/danoni_main.js
1. シャッフル名の表示をグループ毎に区別しないよう変更しました。
1. シャッフルグループが個別に設定できるようになったことで、区別する意味が無くなったため。
=> improve: [0584] シャッフル名の表示をグループ毎に区別しないよう変更

js/danoni_main.js
1. キーパターン変更時、カラー・シャッフルグループが前の設定を引きずってしまう問題を修正しました。
1. すでにカラー・シャッフルグループが複数存在するキーに影響します。
今回の対応で、キーパターン変更都度、カラー・シャッフルグループ配列を作り直す方式に変更しました。
- なおこの変更を行っても、KeyPattern: Self 時にカラー・シャッフルグループが一時的に複数化できない問題が残ります。リロードすれば元に戻るため、一旦これで様子を見ます。
具体的な方法が判明した後に修正予定です。
=> fix: [0585] キーパターン変更時、カラー・シャッフルグループが前の設定を引きずってしまう問題を修正

SECURITY.md, js/danoni_main.js, package.json
=> [ver28.1.2] パターン変更時、カラー・シャッフルグループが前の設定を引きずってしまう問題を修正　他

js/danoni_main.js
1. カラー・シャッフルグループ変更後、各グループが一時的に複数化できない問題を修正しました。
1. PR #1313 関連。
退避するはずのカラー・シャッフルグループが一部漏れていました。
- これもver28.1.0関連の問題ですが、重要度は低いため次の更新時に取り込む予定です。
=> fix: [0586] カラー・シャッフルグループ変更後、各グループが一時的に複数化できない問題を修正

js/danoni_main.js
1. キーパターンがselfのとき、カラー・シャッフルグループが1種類になってしまう問題を修正しました。
2. グループボタンの不要な初期表示処理を見直しました。
1. 当初は意図して入れていたif文が弊害になっていたため。
2. グループボタンを作成後、ボタン名を表示する処理を`viewGroup`にて行っていたため二重処理となっていました。
- おそらく変更しても問題は無いと思いますが、念のため発端のPull Requestを調べてからマージする予定です。
=> fix: [0588] キーパターンがselfのとき、カラー・シャッフルグループが1種類になってしまう問題を修正

js/danoni_main.js
1. データセーブしない場合にカラー・シャッフルグループの設定が引き継がれない問題を修正しました。
2. キーパターン変更ボタン周りの処理を見直しました。
1. ver28.1.0にて`resetColorType`関数を導入しましたが、この関数内でカラー・シャッフルグループを初期化する処理を入れていました。タイトルバックで戻ってきた場合やキーパターンを切り替える場合は問題ないのですが、以下の場合に初期化されると問題となるケースがありました。キーパターン変更ボタンを押したときに初期化するよう見直しています。
- データセーブしない場合にタイトルバックした場合
- プレイ開始前にカラー・シャッフルグループを変更後、再度設定画面・キーコンフィグ画面を行き来した場合
2. 上記に伴い、同じコードの繰り返しが見られたため。
=> fix: [0589] データセーブしない場合にカラー・シャッフルグループの設定が引き継がれない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. カラー・シャッフル用のローカルストレージキーを変更しました。
互換のため、ver28.1.0以降のものも取り込めるようにしています。
|変更前|変更後|用途|
|shuffleX_-1_-1|shuffle(X)|保存するシャッフルのセット配列|
|colorX_-1_-1|color(X)|保存するカラーのセット配列|
2. キーコンフィグ画面のカラー・シャッフルグループの説明文言を見直しました。
3. g_dfKeyObjを使ってデータ退避している部分を、keyCtrlと同様にg_keyObjへ移行しました。
4. ローカルストレージ（作品別）の保存対象からDisplay設定を対象外としました。
- StepZone, Judgment, FastSlow, Lifegauge, Score, MusicInfo, FilterLine
1. キー名が冗長でわかりにくいため。
なお、この古いキー名はプレイ開始時（かつデータ保存時）にローカルストレージから削除するようにしています。
2. カラー・シャッフルグループの変更が一時的で無く、保存できるようになったため。
3. 処理統一のため。
4. いずれも恒久的な設定というより一時的に設定する意味合いが強く、
作品別に保存する必要性が薄いため。
Appearance/Opacityは作品によりそのままの設定でプレイする可能性があるため、残します。
- 1.についてはこの更新が反映された作品を「Data Save」を有効にした状態でプレイすると反映します。
- 4.はこの更新が反映された作品を読み込んだ時点で反映します。
=> improve: [0591] キーコンフィグ周りの文言、ローカルストレージキー変更

css/danoni_main.css, js/danoni_main.js, js/lib/danoni_constants.js
1. 画面内の意図しない文字の折り返し設定を無効化しました。
具体的には、画面枠のid: canvas-frame に対して`white-space: nowrap;`を指定しています。
2. ColorPickerのCSSにPadding: 1px指定を追加しました。
1. 通常、自然折り返しで改行するケースは少ないと思われるため。
頻度は少ないかもしれませんが、WordPressで表示する場合に
自動折り返しが利いてしまうことがあり、
画面要素に指定することで、その影響を抑えることができます。
2. 環境により、Paddingのデフォルト値指定でColorPickerの色が見えないことがあるため。
- 強制改行`<br>`を入れている箇所は従来通り折り返しされます。
- この設定はダンおに画面内にのみ適用しているため、画面外への影響はないと思われます。
=> improve: [0590] 画面内の意図しない文字の折り返し設定を無効化

js/danoni_main.js, js/lib/danoni_constants.js
1. キーコンフィグ画面のColorType: Type1～4, TypeSで選択可能な、カラーピッカー及び[↓]ボタンに対して説明文を追加しました。
1. カラーピッカーだけでは何を意味しているかが分かりにくいため。
=> improve: [0592] カラーピッカー関連の説明文を追加

js/lib/danoni_constants.js
1. 17key(KeyPattern: 1)の矢印拡大率を0.85から0.95に見直しました。
合わせて、最小横幅を800pxから825pxへ見直ししています。
1. 当時は17key以外横に長いキーが存在しなかったため横幅を狭める対応を行いましたが、
23keyが存在する現在では狭めるメリットが薄いと思われるため。
- danoni_constants.js のみの変更です。
=> improve: [0593] 17key(KeyPattern: 1)のサイズ見直し

js/danoni_main.js
1. シャッフルグループのデフォルトからの差分に対して色付けするようにしました。
グループ1のパターンを常にデフォルトとして比較します。
1. Resolves #1327 
割り当てキーや色であれば、何が変わったか判断できますが
シャッフルグループは数字しかないため何が変わったかがわかりにくいため。
|----|----|
|Add|changeConfigColor, changeShuffleConfigColor|
|Change|ー|
|Delete|ー|
=> feat: [0594] シャッフルグループのデフォルトからの差分に対して色付け

js/danoni_main.js
1. シャッフル無効時にシャッフルグループの色付け処理が動く問題を修正しました。
1. PR #1328 関連。
この処理はシャッフルが有効であることが前提になっているため。
他の部分は問題ないですが、この箇所のみキーパターン変更時に
必ず通る処理になっていたためエラーになっていました。
=> fix: [0595] シャッフル無効時にシャッフルグループの色付け処理が動く問題を修正

css/danoni_main.css, js/danoni_main.js
1. CSSのベンダープレフィックス指定を一部削除しました。
1. Can I Useの状況より、ベンダープレフィックスが不要でも動くようになってきたため。
https://caniuse.com/?search=clip-path
https://caniuse.com/?search=user-select
https://caniuse.com/?search=appearance
https://caniuse.com/?search=audio-context
- webkit-touch-calloutも不要になってきましたが、今回は据え置きます。
https://caniuse.com/?search=touch-callout
- CSS Masks 及び background-clip はまだベンダープレフィックスが必要なブラウザが多いため据え置きます。
https://caniuse.com/?search=mask
https://caniuse.com/?search=background-clip
=> improve: [0596] CSSのベンダープレフィックス指定を一部削除

js/danoni_main.js, js/lib/danoni_constants.js
1. 警告ウィンドウ、コメントエリアについて自然折り返しを有効化しました。
1. PR #1322 にて自然折り返しを無効にしましたが、警告ウィンドウ（英語）にて自然折り返しを使用している箇所があったため仕様を見直しました。コメントエリアも同様のため、念のため自然折り返しを有効に戻しています。
=> fix: [0597] 警告ウィンドウ、コメントエリアについて自然折り返しを有効化

js/danoni_main.js
1. Display画面のFilterLineについて、Appearanceが「Hidden+/Sudden+/Hid&amp;Sud+」のときのみ表示するように変更しました。
2. Judgment/FastSlow/Appearanceの全てが設定不可かつ無効のとき、
Opacity設定を非表示化するよう変更しました。
1. FilterLineは、Appearanceが「Hidden+/Sudden+/Hid&amp;Sud+」のときに表示される
フィルターの境界線を表示する線の表示／非表示を行うためのものであるため。
2. Opacityの対象が全て無効のとき、設定を表示する必要が無いため。
=> improve: [0598] Display画面の特定項目未使用時に非表示化する設定を追加

js/danoni_main.js
1. Opacity設定の非表示条件誤りを修正しました。
1. PR #1333 にてOpacity設定の条件付き非表示化を実装しましたが、その条件に誤りがありました。
Judgment, FastSlow, FilterLineの設定がいずれも無効で、その設定値がOFFになっている必要がありました。
=> fix: [0599] Opacity設定の非表示条件誤りを修正

js/danoni_main.js
1. Motion(Boost, Brake)を含めた矢印・フリーズアローの移動計算式を変更しました。
||計算式|
|----|----|
|変更前|( Settingで指定した速度 × 全体加速分 + **Motionで指定した加算分** ) × 個別加速 |
|変更後| Settingで指定した速度 × 全体加速分 × 個別加速 + **Motionで指定した加算分** |
- また、矢印・フリーズアローの生存時間についても変更があります。
以前より生存時間が長くなり、移動距離がMotionで指定した加算分だけ長くなります。
||生存時間|
|----|----|
|変更前|( Settingで指定した速度分 + **Motionで指定した加算分** )が<br>画面外からステップゾーンへ到達する時間 |
|変更後| Settingで指定した速度分 が画面外からステップゾーンへ到達する時間 |
1. 従来の方法では、全体加速＝0.5倍、個別加速＝2倍のときにBoost/Brakeを掛けると
1倍速のBoost/Brakeにならず、高速に流れる事象が発生していました。
計算式を変えることで、この事象を解消します。
- 今回の変更により、Boost/Brake使用時、全体的に矢印が存在する時間が増えるため
処理量がやや多くなる傾向にあります。
- 個別加速にマイナスが指定された場合、Boost/Brakeの組み合わせによっては相殺されて思ったような逆走にならない場合があります。
- 個別加速の逆走を検知してBoost/Brakeの軌道を反転するようにすれば一応可能だと思われる。
⇒対応しました。ただし、フリーズアローの帯については非対応です。MotionがOFFのときも同様のため、一旦据え置きます。
=> feat: [0601] Motionの加算部分が個別加速の影響を受けないよう変更

js/danoni_main.js, js/lib/danoni_constants.js
1. MotionオプションにHi-Boostを追加しました。以前のBoostと同じ軌道です。
2. Motion軌道周りのソースコードを見直しました。
1. 以前のBoostに一定の需要があるため。
2. Motionオプションが増えたときの冗長性回避のため。
=> feat: [0600] MotionオプションにHi-Boostを追加

js/danoni_main.js
1. 左上に表示されるフレーム数を見かけのフレーム数に変更しました。
※左下に表示されている時間表記に連動し、AdjustmentやpreblankFrameが加味されるようになります。
1. 背景・マスクなどの実装時に、AdjustmentやpreblankFrameが異なることで異なるフレーム数が表示されてしまうため。
=> improve: [0602] 左上に表示されるフレーム数を見かけのフレーム数に変更

js/danoni_main.js
1. フェードイン中の個別加速の保持範囲を見直しました。
これまでは boost_data がフェードイン位置より前の場合はデータを除外していましたが、
一度矢印位置を考慮して個別加速位置を検索し、それがフェードイン位置より前であれば
そのデータを個別加速として含めるように変更しました。
1. 初回だけ個別加速が掛かっているパターン（|boost_data=0,1.5|）ではフェードインを掛けると従来の方法では外れるようになっていました。
=> improve: [0603] フェードイン中の個別加速の保持範囲を見直し

js/danoni_main.js
1. フリーズアローを強制削除した場合の引数誤りを修正しました。
削除する対象のフリーズアローの残余フレームではなく、
チェック対象のフリーズアローの残余フレームになっていました。
1. 処理には影響しませんが、カスタムjsで引数を使用していた場合に影響するため。
PR #341 関連です。
- この場合の引数は本来ウワァン/イクナイではない残余フレームのため、
強制的にイクナイの領域にかかる残余フレームに修正が必要かという話がありますが、
強制的に変えてしまうと本来のフレーム数がわからなくなるため、一旦そのままの値を入れています。
=> hotfix: [0606] フリーズアローを強制削除した場合の引数誤りを修正

js/danoni_main.js
1. Motion加算部分のコード整理を行いました。
ロード部分でMotion加算分を事前に配列へ格納するように変更しています。
1. Motion加算部分についてプレイ画面の計算量を抑えるため。
=> improve: [0604] Motion加算部分のコード整理

js/danoni_main.js
1. 左上のフレーム数表記をg_scroeObj.baseFrameに変更しました。
1. ver28.4.0よりこの左上のフレーム数はnominalFrameNumを採用していますが、本来は制作者が使うもののため、frameNumやnominalFrameNumよりbaseFrameを採用する方が自然と考えます。
- 各フレームの意味については下記が参考になります。
https://github.com/cwtickle/danoniplus/wiki/AboutFrameProcessing
- 参考：PR #1338
=> improve: [0607] 左上のフレーム数表記をbaseFrameに変更

js/danoni_main.js
1. 左上のフレーム数、左下の経過時間表記をg_scoreObj.baseFrameに変更しました。
2. g_scoreObj.baseFrameについてpreblankFrameが反映されていない問題を修正しました。
3. g_scoreObj.nominalFrameNum を廃止しました。
1. 従来nominalFrameNumを使用していましたが、この場合ヘッダーで指定したadjustmentが加算される問題があり、この分だけ譜面側のデータとずれる問題がありました。
2. g_headerObj.baseFrameの生成箇所がpreblankFrameを加算するより前に記載されていました。
3. 1の変更で不要となったため。基本的にg_headerObj.baseFrameを利用しているため影響は少ないと思われます。
- g_scoreObj.baseFrame の preblankFrameが考慮されていない問題はadjustmentの値に影響するため、
過去バージョンも修正対象と考えます。
=> feat: [0608] 左上のフレーム数、左下の経過時間表記をbaseFrameに変更

js/danoni_main.js
1. クレジットリンク表示が長い場合、折り返しが利いていない問題を修正しました。
1. PR #1322 の変更に対する自然折り返し箇所の洗い出し漏れです。
- v28.2.1以降で発生している問題のため、過去バージョンは修正不要です。
=> fix: [0609] クレジットリンク表示の折り返しが利かない問題を修正

js/danoni_main.js
1. フリーズアロー（始点）に対して始点判定によらず、Fast/Slowを常時カウントするよう変更しました。
表示の際は、フリーズアローの判定キャラクタの下に表示します。
なおフリーズアロー（始点）を押したときにFast/Slowを出すため、
キター/イクナイの表示タイミングとは異なります。
2. countFastSlow, displayDiff関数のデフォルト引数 _justFrames を `g_headerObj.justFrames`に変更しました。
1. フリーズアロー（始点）の始点判定が無い場合、Fast/Slowが無いため
フリーズアローが多い譜面のときにFast/Slowが適切に作用しない可能性がありました。
2. _justFrames (ジャストと判断するフレーム)は作品中で一意であるため。
- フリーズアローの始点判定がある場合は、従来通りFast/Slowを矢印判定側に出します。
=> [0612] フリーズアロー（始点）に対してFast/Slowを常時カウントするよう変更

js/danoni_main.js
1.  フリーズアローの始点判定範囲についてマターリ/ショボーンも対象に加えるようにしました。
※厳密にはイクナイの枠外判定フレーム（＋8フレーム）より手前が対象です。
この変更により、フリーズアローの始点で早押しがあった場合にイクナイになる可能性があります。
また、フリーズアローの始点判定でマターリ/ショボーンが出現するようになります。
1. PR #1354 の変更にてFast/Slowをカウントするようにしましたが、
従来、コード簡略のため始点判定に失敗した場合はすべて枠外判定になるようになっていました。
この方法ではFast/Slowが拾えないため、今回の変更で始点判定範囲を広げる変更を行っています。
=> feat: [0613] フリーズアローの始点判定範囲を拡大

js/danoni_main.js
- リタイア時は強制的にクリア失敗判定となっていましたが、全ノーツ判定済みであればクリア判定を行うようにしました
- endFrameが設定されていない作品などで、譜面終了からリザルト遷移まで時間がかかる場合の利便性向上のため
=> リタイア時にもクリア判定を行うように変更

js/danoni_main.js
1. 曲名、アーティスト名について言語別に表記を変えられるようにしました。
現状、譜面ヘッダー「musicTitle」が対象で、英語用が「musicTitleEn」、日本語用が「musicTitleJa」です。
指定が無い場合は、「musicTitle」が優先されます。
```
|musicTitleJa=クレマ,木下たまき,https://...|
|musicTitleEn=Cllema,Kinoshita Tamaki,https://...|
```
1. クレジット表記で、言語別に表記を分けている場合があるため。
- 言語別の設定を追加した場合、アーティストURLはそれぞれに指定が必要です。
- 多言語対応は現状日本語（Ja）と英語（En）のみとなっていますが、他の言語を追加することも可能です。
その場合、g_localeObj.list に対象の言語を追加し、
g_lang_lblNameObj, g_lang_msgObj, g_lang_msgInfoObj に追加した言語の訳名を追加する必要があります。
=> feat: [0614] 曲名、アーティスト名の多言語対応

js/danoni_main.js
1. changeJudgeCharacterのフリーズマークの引数名を `_freezeflg`から`_fjdg` に変更しました。
1. displayDiff関数の引数と同じ意味のため。
また、元の名前`_freezeflg`については、他の関数が別の意味で`_frzFlg`を利用しているため。
- 引数名を変えても呼び出し方に変化はないので、影響はありません。
=> refactor: [0615] changeJudgeCharacterの引数名を見直し

js/danoni_main.js
1.  fast/slowのカウンターと表示関数を統一しました。
この変更により、ショボーン（Bad）時にFast/Slowを表示するようになります。
1. ショボーン（Bad）時のFast/Slowのカウント自体は行っていたが、表示していませんでした。
現在はフリーズアローで7, 8Framesズレを表示するようになっており、表示しない意味がなくなってきたため、
今回の変更で表示するように変更します。
=> feat: [0616] fast/slowのカウンターと表示関数を統一

js/danoni_main.js, js/lib/danoni_constants.js
1. シャッフル設定が無効もしくは一部無効のとき、表示メッセージを変更しました。
1. 画面内に存在しない説明文への対応のため。
=> improve: [0618] シャッフル設定が無効もしくは一部無効のとき、表示メッセージを変更

js/danoni_main.js
1. 矢印・フリーズアロー処理部分のコード整理を行いました。
2. Motionオプションを使用し、フリーズアローについてタイミングをずらして押したとき、そのズレの中にストップが含まれていると、処理が止まる可能性がある問題を修正しました。
1. コードの見やすさと、意味付けをわかりやすくするため。
2. ほとんど影響のない問題ですが、Motionオプションで保持する残余時間`boostCnt`と、
フリーズアロー（始点）の残余時間`cnt`がストップ時、ずれることがあるため生じることがあります。
（＝g_workObj.motionOnFrames の配列の添え字がマイナスになる可能性がある）
フリーズアロー（始点）間際にストップを差し込まない限り、起こりません。
#1110 の修正漏れです。
=> refactor: [0620] 矢印・フリーズアロー処理部分のコード整理

README.md, js/danoni_main.js, js/lib/danoni_constants.js
1. ヘルプのリンクを言語別に切替できるよう変更しました。
1. 英訳版のリポジトリを別に作成したため。
https://github.com/cwtickle/danoniplus-docs
=> feat: [0621] ヘルプのリンクを言語別に切替できるよう変更

js/danoni_main.js
1. フリーズアローの始点判定有のとき、始点判定でNGを出すと矢印側判定が二重になる問題を修正しました。
1. フリーズアローの判定ではヒット時（途中で離す）、枠外のときに判定終了フラグを立てていましたが、
始点判定失敗時には判定終了フラグを立てていませんでした。
これまで、始点判定失敗時は枠外判定として処理されており、区別する必要はありませんでしたが、
#1355 の変更でマターリ/ショボーンを考慮することになったため、新たに区別する必要が生じました。
- Gitterリンク：
https://gitter.im/danonicw/community?at=63a2fa730dba3574233bc3fa
=> fix: [0625] フリーズアローの始点判定有のとき、始点判定でNGを出すと矢印側判定が二重になる問題を修正

SECURITY.md, js/danoni_main.js, package.json
=> [ver29.3.2] フリーズアロー始点判定有効時、始点NGのときに矢印判定が二重になる問題を修正

js/danoni_main.js
1. フリーズアロー始点判定が有効で、以下の条件のときに判定が二重判定になる問題を修正しました。
- 該当のフリーズアローの始点判定が遅ショボーン( :( Bad )
- 該当のフリーズアローが残っている状態で、同一レーンの次のフリーズアローを判定させる
1. この箇所のみ、判定終了フラグ (judgEndFlg) を条件に含めていなかったため、
判定終了後に追加の判定を出してしまう可能性がありました。
(Discordリンク)
https://discord.com/channels/698460971231870977/944491021918683196/1058056741142671441
- ver29.0.1以降で上記の条件を満たした場合のみ発生します。
=> fix: [0626] フリーズアロー始点判定有で遅ショボーンを出したときに二重判定することがある問題を修正

SECURITY.md, js/danoni_main.js, package.json
=> [ver29.3.3] フリーズアロー始点判定有で遅ショボーンを出したときに二重判定することがある問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 同時押し関連の英訳を見直しました。
- 単押し：1push -> Single
- 同時押し：2push -> Chord
- 3つ押し以上：3push+ -> Triad+
- 多重押し位置：3-Push positions -> Polychord positions
- 同時補正：N-Push -> Chords
1. 直訳のままになっていたため、見直しました。
=> chore: [0627] 同時押し関連の英訳を見直し

js/danoni_main.js, js/lib/danoni_constants.js
1. フリーズアロー始点に対するモーション「frzTopMotion_data」を実装しました。
使い方は arrowMotion_data, frzMotion_data と同じです。
1. キリズマでフリーズアローを使用する際に必要となるため。
他の部位についても同様のモーションが要りそうですが、一旦必要なもののみ実装します。
=> feat: [0628] フリーズアロー始点に対するモーションを実装

js/lib/danoni_constants.js
1. divXの第2要素がposX末尾要素の最大値で無い場合、
キーコンフィグ保存後にステップゾーン（下段）がずれる問題を修正しました。
下記のキー定義で再現できます。
```
|minWidth10X=650|
|color10X=0,0,0,0,2,1,1,1,1,2|
|chara10X=left,down,up,right,space,sleft,sdown,sup,sright,sspace|
|div10X=9,19|
|stepRtn10X=0,-90,90,180,onigiri,0,-90,90,180,onigiri|
|keyCtrl10X=83/0,68/0,69/82,70/0,32/0,74/0,75/0,73/79,76/0,13/0|
|blank10X=52.5|
|shuffle10X=0,0,0,0,1,2,2,2,2,3|
```
1. 上記問題の解消のため。
- おそらく初期時からの問題だと思います。
=> fix: [0629] divXの第2要素がposX末尾要素の最大値で無い場合の問題を修正

js/danoni_main.js
1. ファイル読込で404エラー時にフルパスを表示するよう変更しました。
2. サーバー起動時、楽曲ファイル読込時のエラーとして「E-0041」を割り当てるように変更しました。
1. 相対パス記述時、どこに対するエラーかがわかりにくいため。
2. 従来のE-0032では対象のファイル名が無くわかりにくいため。
E-0041であればファイル名が特定できるため、採用しています。
- 左側がローカルファイル、右側がサーバー版での表示です。
- danoni_constants.js については諸々の関数定義前のため、エラーウィンドウは出ません。
ここについてはこれまで通りです。
- 関数追加：getFullPath
=> improve: [0630] ファイル読込で404エラー時にフルパスを表示するよう変更

js/danoni_main.js, js/lib/danoni_constants.js
1. 拡張スクロール設定（Scroll）に「Reverse」を追加するとReverse設定を無効化するよう変更しました。
- 「Cross」や「Split」を「Reverse」と並列で設定した場合も無効になるため、必要に応じて対応するリバース設定の追加（この場合は「R-Cross」「R-Split」）が必要です。
1. カスタムキーの設定によっては、Reverseを単純反転させたくない場合があるため。
- 下記の例では、拡張スクロール（Scroll）に「Reverse」を追加しているため、
Reverseの設定が「X」となり、ボタンが押せない状態になります。
```
|scroll10=Reverse::-1,-1,-1,-1,-1,-1,-1,-1,-1,1|
```
- すでに「Reverse:ON」で保存されている場合を想定し、そういった場合には強制的に「Reverse:OFF」にします。
上記に当てはまらない場合は関係ありません。
- Reverseを切り替えるショートカット(`g_shortcutObj.option.KeyR`)について従来の設定では不都合が出るため、
通常時は「lnkReverseR」、今回のケースでは「btnReverse」を見るよう変更しました。
直書きにすると設定の意味が無いため、プロパティとして「dfId」「exId」と定義を分けています。
```javascript
KeyR: { id: `lnkReverseR`, dfId: `lnkReverseR`, exId: `btnReverse` },
```
=> feat: [0632] 拡張スクロール設定に「Reverse」を追加するとReverse設定を無効化するよう変更

js/danoni_main.js, js/lib/danoni_constants.js
1. 曲中でキー変化する機能を実装しました。詳細は下記参照。
1. キーコンフィグ周りのカーソル移動処理を見直しました。
- キー変化作品に配慮し、カーソル移動配列として `g_keycons.cursorNumList` を作成しました。
- キーを切り替えるのではなく、切り替えるキー全体をカバーするカスタムキー定義を使って
部分的に一部のキーを見せることでキーの切り替えを行います。
参考：https://cw7.sakura.ne.jp/danoni/2016/0273_DefeatIDoll.html
- **keych_data** を使用します。2つ1セットで、`フレーム数,キーラベル`のように使います。
※キー数ではありません。`keyGroup`で定義するキーラベルを使用します。
- キーラベルに`X`など`keyGroup`で未定義のものを入れれば、ステップゾーンを一時的に消すことも可能です。
```
|keych_data=0,11L,1951,5,1955,11L,2810,5,2814,11L,3264,5,3275,11L|
|keych2_data=0,11,1951,5,1955,11,2810,5,2814,11,3264,5,3275,11|
```
- キー数別の仕様の一つで、部分キーをどう割り振るかを **keyGroupXX** で指定します。（XXはカスタムキー名）
ここで指定したラベル名を、**keych_data**の偶数番目で使用するとキーを変更（部分キーを適用）できます。
- ある矢印/AAを複数の部分キーで共用して使うときは `11/11L/11W`のようにスラッシュ区切りにすると、
複数の部分キーで使用できます。
``` …
```
=> feat: [0633] 曲中でキー変化する機能の実装

js/danoni_main.js
1. 直接キー割り当てボタンを押したときにカーソル位置が保存されない問題を修正しました。
1. PR #1390 を行った際の考慮漏れです。
=> fix: [0634] 直接キー割り当てボタンを押したときにカーソル位置が保存されない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. Reverse設定無効時、R-FlatをFlatと見做す設定を追加しました。
1. PR #1388 を有効にした場合、「R-Flat」を入れた場合に現状ではステップゾーンが見えてしまうため、
明示的にリスト化したもののみ、「Flat」扱いとするようにしました。
リバース可否についてはスクロール名の先頭が「R-」が付いているかどうかで判断します。
- なお、「R-Flat」を設定した場合でもスクロール方向は個別に指定する必要があります。
=> feat: [0635] Reverse設定無効時、R-FlatをFlatと見做す設定を追加

js/danoni_main.js
1. 別キーモード用の歌詞表示・背景/マスクモーションを実装しました。
- wordA_data, wordRevA_data, wordAltA_data のように使用します。
名前が違うだけで、使い方は従来の歌詞表示・背景/マスクモーションと同じです。
1. 別キーモードまで考慮する場合、表現が変わる可能性があるため。
=> feat: [0636] 別キーモード用の歌詞表示・背景/マスクモーションを実装

js/danoni_main.js
1. shuffleUse=false時にキーコンフィグ画面が動作しない問題を修正しました。
1. shuffleUse=false時はシャッフルグループ番号用のボタンをそもそも生成していませんでした。
PR #1390 にて、シャッフルグループ番号用のボタンの表示・非表示を行うようになった結果、問題が表面化しました。この問題を修正しています。
=> fix: [0638] shuffleUse=false時にキーコンフィグ画面が動作しない問題を修正

js/danoni_main.js, js/template/danoni_setting.js
1. 背景・マスクモーションにカラーオブジェクト（色付きオブジェクト）が使えるよう対応しました。
https://github.com/cwtickle/danoniplus/wiki/AboutColorObject
```
|backtitle_data=
330,3,[c]giko/#ff9999,,5,200,200,200,0,spinY,120,forwards
480,3
|
```
- 3番目の記法以外は画像の場合と同じです。
なお、回転量についてはアニメーションを含ませる場合、
CSSアニメーション側にも回転量を指定する必要があります。
- 3番目の記法にある**color**には色名やグラデーション記法が指定可能です。
譜面ヘッダーの`defaultColorgrd`とは連動しません。
```
|backtitle_data=
330,3,[c]giko/#ff9999:yellow,,5,200,200,200,0,spinY,120,forwards
480,3
|
```
|番号|論理名|設定例|内容|
|1|Frame|200|変更するタイミングのフレーム数を指定します。|
|2|Depth|0|背景の深度を数字で指定します。0以上の値を指定。<br>深度は大きくすることもできますが、その分背景スプライトの数が増えるので重くなる可能性があります。|
|3|**ColorObject/Color**|[c]giko/#ff9999|`[c]カラーオブジェクト名:回転量/カラーコード` の形式で指定します。<br>矢印の場合のみ、カラーオブジェクト名の省略が可能です。|
|4|**ColorObject …
=> feat: [0640] 背景・マスクモーションにカラーオブジェクトが使えるよう対応

js/danoni_main.js
1. ScrollがDefault以外のときに別キーモード用のword/back/maskデータが
適用されない場合がある問題を修正しました。
1. データの取得優先順 ( PR #1393 )に関する不具合です。
=> fix: [0642] ScrollがDefault以外のときに別キーモード用のデータが取得されない問題を修正

js/danoni_main.js
1. スクロール固有のword/back/maskデータを作成できるよう変更しました。
- `backCross_data`, `maskFlat_data`のようにScroll設定に登録済みの名前を指定できます。
- 別キーモード用の設定は `backCrossA_data`や`maskFlatA_data` のように使います。
2. 別キーモードのword/back/maskデータの優先順を変更しました。
- `maskRevA_data` > `maskA_data` > `maskRev_data` > `mask_data` で先に見つかったものが適用されます。
1. 色付きオブジェクトがback/maskデータで使えるようになったことで、
スクロール固有の設定が必要になってきたため。
2. これまでは `maskA_data` と `maskRev_data` が逆になっていました。別キーモードは別譜面の意味合いが強いため、通常のリバース専用より前に来るのが適切と考え、見直しています。
=> feat: [0643] スクロール固有のword/back/maskデータを作成できるよう変更

js/danoni_main.js, js/lib/danoni_constants.js
1. 矢印・フリーズアローのスクロール方向を反転する機能を実装しました。
`scrollch_data`で指定します。改行区切りで`フレーム数, 矢印番号, スクロール方向`の3つで1セットです。
矢印番号は色変化や矢印モーションで使っているものと同じです。
スクロール方向は`-1`で反転、`1`で元に戻します。
```
|scrollch_data=
1100,20,-1
1200,21,-1
1300,22,-1
2000,20,1
2000,21,1
2000,22,1
|
```
2. キー変化`keych_data`について改行区切りに対応しました。
1. 演出系で一時的にスクロールを反転したい場合にcustomjsが必要となるため。
2. 他機能との機能統一のため。
=> feat: [0644] 矢印・フリーズアローのスクロール方向を反転する機能を実装　他

js/danoni_main.js
1. フェードイン、スクロール反転機能を同時に利用した場合に
スクロール初期位置が正しく反映されない問題を修正しました。
1. スクロール反転処理について`calcDataTiming`という色変化・モーションデータと同じ関数を使用していましたが、この関数を使用するためには配列グループの2番目に色番号（矢印番号）を指定する必要がありました。
※コメントに但し書きを追記しています。
- スクロール反転固有の問題のため、ver30.2.0のみで発生する問題です。
=> fix: [0645] フェードインでスクロール反転の初期位置が正しく反映されない問題を修正

SECURITY.md, js/danoni_main.js, package.json
=> [ver30.2.1] フェードインでスクロール反転の初期位置が正しく反映されない問題を修正

js/danoni_main.js
1. キーグループが未指定のとき、keych_dataが使えない問題を修正しました。
- デフォルトのキーグループ名が「0 (数字)」となっていました。「0 (文字列)」が正しいです。
2. keych_dataの指定がある場合でも、自動で「0フレーム、キーグループ0」が
挿入されるように修正しました。
1. ステップゾーンを一時的に消す演出などで利用用途があると考えていましたが、
それが使えない状態になっていました。
2. 挿入されても支障がないのと、キー変化作品以外で`keych_data=0,0`を前挿入するのが手間のため。
=> fix: [0647] キーグループ未指定のときにkeych_dataが使えない問題を修正

js/danoni_main.js
1. カスタムキーのdivMax値がposXの最大値を取得していない問題を修正しました。
1. ver30.2.2で PR #1410 を行いましたが、カスタムキーで適用されていませんでした。
=> fix: [0648] カスタムキーのdivMax値がposXの最大値を取得していない問題を修正

js/danoni_main.js
1. カスタムキーのdivXが未定義のとき、ステップゾーンが並ばない問題を修正しました。
2. カスタムキーのshuffleXが未定義のとき、エラーで止まる問題を修正しました。
1, 2. いずれも意図しない挙動のため。
divX, shuffleXがそもそもない場合の考慮がされていませんでした。
- 過去バージョンにも影響がある部分のため、合わせて修正予定です。
=> fix: [0649] カスタムキーのdivX, shuffleXが未定義のときの問題を修正

js/danoni_main.js
1. カスタムキー定義におけるdivX, posX部分のコードを整理しました。
キーパターン別のposXの最大値+1をdivXの初期値となるように処理を見直しています。
（これまではposXの最初のキーパターンで決まっていたため、
　別キーモード時にdivXを指定しない場合に意図しない値が設定されるようになっていました）
2. divXが部分的に未定義でも、posXの値を元に補完するようにしました。
以下のように、値の一部省略が可能になります。
```
|div11f=$$6$|  // 1, 2, 4番目はposXの最大値+1を適用、3番目のみ6とする
```
1. 重複した処理を無くすことでコードの見通しを良くするため。
2. divXの省略条件があいまいでわかりにくかったため。
- 一部、`setIntVal`ではなく`setVal`でNUMBER型を指定していますが、
これは`setIntVal`関数ではデフォルト値に`undefined`を充てることができないためです。
（`setIntVal`関数のデフォルト値に`0`が設定されており、`undefined`より優先されてしまう）
=> improve: [0650] カスタムキー定義におけるdivX, posX部分のコード整理

js/danoni_main.js
1. カスタムキー定義のshuffleXについて部分省略指定に対応しました。
`shuffleX`について、下記のように部分的に空指定ができるようになります。
何も指定しない場合は、全てのシャッフルグループがグループ1に割り当てられます。
```
|shuffle10p=$$11i_0$11i_1|
|minWidth10p=650|
|color10p=0,1,2,1,0,0,1,2,1,0$10p_0$11i_0$11i_1|
|chara10p=left,down,gor,up,right,sleft,sdown,siyo,sup,sright$10p_0$11i_0$11i_1|
|stepRtn10p=-45,45,onigiri,135,-135,-45,45,onigiri,135,-135$10p_0$11i_0$11i_1|
|keyCtrl10p=88/90,69/87,68/70/83,84/82,86/67,66/78,89/85,72/74/75,73/79,77/188$88/90,87/81,68/83/70,82/84,67/86,77/78,85/89,75/74/76,79/80,188/190$11i_0$11i_1|
|blank10p=50$50$50$50|
|scroll10p=Cross::1,1,1,-1,-1,-1,-1,1,1,1/Split::1,1,1,1,1,-1,-1,-1,-1,-1/Alternate::1,-1,1,-1,1,1,-1,1,-1,1$10p_0$11i_0$11i_1|
|transKey10p=$$11i$11i|
```
- キーの上書きなどでシャッフルグループを変えたくないときは、略記指定が使えます。（変化なし）
```
|shuffle7=7_0$7_1|
```
1. …
=> improve: [0651] カスタムキー定義のshuffleXについて部分省略指定に対応

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
1. GitterのリンクをGitLab Issuesに変更しました。
バッジ名はGitterを継承し「Community」としています。
1. GitterからElementへの移行に伴い、モバイルアクセスは良化したが、GitHubとの紐づけが弱くなったため。
GitLabはGitHubと似ており、Twitter, Googleアカウントも使えるため従来のGitterに近い使い方ができる。
また、リスト化されることで何が完了して何が議論中かの確認が可能。
- 本来はGitHubに統合するのが良いが、GitHubアカウントを保持していないメンバーもいるため
他アカウントとの親和性が高く、機能が類似しているGitLabを選択。
- 得点報告用のGitter（Element）はそのままのため、結果画面のリンクには手を入れません。
=> chore: [0655] GitterをGitLab Issuesに変更

js/danoni_main.js
1. カスタムキーのカラー、シャッフルグループについて組み合わせ参照に対応しました。
具体的には以下のような指定が可能になります。
```
|shuffle8i=8_0/0,0,0,2,0,0,0,3|
// シャッフルグループ1:  8keyのグループ1から参照
// シャッフルグループ2:  指定パターン(0,0,0,2,0,0,0,3)を適用
|color11j=2,0,0,0,0,2,3,3,3,3,2/11_0/11W_0$11j_0/11L_0|
// キーパターン1:
//      カラーグループ1: 指定パターン(2,0,0,0,0,2,3,3,3,3,2)を適用
//      カラーグループ2: 11keyのグループ1から参照
//      カラーグループ3: 11Wkeyのグループ1から参照
// キーパターン2:
//      カラーグループ1～3: 先ほど定義した11jkeyのグループ1から参照
//      カラーグループ4: 11Lkeyのグループ1から参照
```
2. カスタムキーのcolorXの省略に対応しました。
指定が無い場合は、一律charaXのキーパターン指定数に合わせて一律同じグループへ割り当てします。
1. カラー・シャッフルグループについてはグループ毎の指定になり、
少しの変化で全てのパターンを記載するのが手間のため。
2. カラー・シャッフルグループで未定義時の扱いに差があったため。
- 現状、カスタムキーのcharaXの完全省略には対応していないため、影響は無いと思います。
=> feat: [0657] カスタムキーのカラー、シャッフルグループについて組み合わせ参照に対応

js/danoni_main.js
1. 既存キー上書き時に相対パターン番号を略記で指定できるよう変更しました。
カスタムキー指定で`|appendX=true|`（既存キー上書き）にした場合、
カスタム部分の番号参照で`12_(0)`のように記載すると、カスタムパターンの1番目のデータを流用できます。
下記の例では、`12_(0)`と指定することで追加パターンの1番目（実際には`12_4`）として割り当てられます。
```
|keyExtraList=12|
|minWidth12=675|
|append12=true|
|chara12=oni,left,leftdia,down,sleft,sdown,sup,sright,space,up,rightdia,right$12_(0)|
|color12=1,0,1,0,3,3,3,3,0,1,0,1$12_(0)|
|pos12=0,1,2,3,4,5,6,7,8,9,10,11$12_(0)|
|div12=12$12|
|stepRtn12=45,0,-45,-90,giko,onigiri,iyo,c,90,135,180,225$12_(0)|
|keyCtrl12=112/0,113/0,114/0,115/0,116/0,117/0,118/0,119/0,120/0,121/0,122/0,123/0$81/0,87/0,69/0,82/0,84/0,89/0,85/0,73/0,79/0,80/0,192/0,219/0|
|shuffle12=0,0,0,0,1,1,1,1,2,2,2,2$12_(0)/12_(0)|
|blank12=50$50|
|scroll12=Cross::1,1,1,1,-1,-1,-1,-1,1,1,1,1/Split::1,1,1,1,1,1,-1,-1,-1,-1,-1,-1$12_(0)| …
```
=> feat: [0659] 既存キー上書き時に相対パターン番号を略記で指定できるよう変更　他

js/danoni_main.js, js/lib/danoni_constants.js
1. キーコンフィグ画面においてキーパターンのスキップボタンを追加しました。
次の別キーモードに該当するまで、キーパターンをスキップします。
1. キーパターンが増えてきたときに、毎回ボタンを押すのが手間のため。
なお、利用頻度は低いと思われるためボタンサイズは小さめに調整しています。
右側のボタンが「Play」ボタンに近いですが、
利用頻度的に問題にはなりにくいと思われるため、このままにします。
- スキップボタンは「btnPtnChangeRR」「btnPtnChangeLL」を追加しています。
- 従来のキーパターン変更ボタンの色を `g_cssObj.button_Mini`に変更しています。
=> feat: [0661] キーパターンのスキップボタンを追加

js/danoni_main.js
1. キーコンフィグ画面で割り当てキーを直接クリックしたときのキー連続チェックを取り止めました。
1. 元々、割り当てキーを直接クリックされていないときの名残（誤爆対策）であり、
意図的に割り当てキーを直接クリックする場合は誤爆とは言えないため。
=> improve: [0664] キーコンフィグ画面で割り当てキーを直接クリックしたときのキー連続チェックを取り止め

js/danoni_main.js
1. ユーザ定義とは別のカスタムキー定義ができるよう対応しました。
下記のように、`g_presetObj.keysDataLib`にデータを`push`することで
カスタム定義を追加できるようになります。
```javascript
const customLibData = `
|keyExtraList=27k|
|chara27k=...|
|color27k=...|
`;
g_presetObj.keysDataLib.push(customLibData);
```
1. キリズマやパンパネのように、標準搭載とは別の共通定義が必要になってきたため。
これにより、キリズマやパンパネのカスタム定義をユーザ定義から切り離すことが可能になり、
キーパターンの略記も利用できるようになります。
- `g_presetObj.keysDataLib`は配列で定義しています。
- `g_presetObj.keysData`が定義された場合、`g_presetObj.keysDataLib`よりも優先されます。
=> feat: [0662] ユーザ定義とは別のカスタムキー定義ができるよう対応

js/danoni_main.js
1. キーコンフィグ画面でキー割り当て先をクリックしたときの挙動を変更しました。
- ConfigTypeが「Main」のとき、代替キーをクリックした場合は「Replaced」に切り替えます。
- ConfigTypeが「Replaced」のとき、通常キーをクリックした場合は「Main」に切り替えます。
- ConfigTypeが「ALL」のときはいずれのキーをクリックしても変わりません。
1. 現状はConfigTypeが「Replaced」のとき、通常キーをクリックした場合は
ConfigTypeが「ALL」になっていました。
これは割り当てキーをクリックする機能が無いとき、代替キーが無いときの機能の名残で、
代替キーが常時存在する現状の仕様にはそぐわないと思われるため、見直しました。
- 代替キー部分を押すと、ConfigTypeが切り替わる例です。
- 現状は代替キーを最低1つのみ残す設定のため起こりませんが、
仮に代替キーが無い場合を含むキーの場合の挙動は次のように変わります。
- ConfigTypeが「Replaced」のとき：次の代替キーが存在するまでスキップ
- 代替キーが1つも無い場合：ConfigTypeで「Replaced」「ALL」が選択できなくなる
=> improve: [0663] キーコンフィグ画面でキー割り当て先をクリックしたときの挙動を変更

js/danoni_main.js, js/lib/danoni_constants.js, skin/danoni_skin_default.css, skin/danoni_skin_light.css, skin/danoni_skin_skyblue.css
1. 矢印・フリーズアローのヒット位置をステップゾーン位置からずらす機能を実装しました。
PR #1436 の設定をDisplay設定に移したバージョンです。
1. 目押しによる早押しに対応するため。
なお、この設定を変えてもステップゾーンの位置は変わりません。
- 設定用ボタンの縦サイズを`23px`から`22px`に見直しています。
- 対応するショートカットキーがうまく表示されない問題があります。
=> feat: [0666] ヒット位置をステップゾーン位置からずらす機能を実装（Display設定版）

js/danoni_main.js, js/lib/danoni_constants.js
1. キャラクタの回転パターン（ShapeGr.）を実装しました。
カラー・シャッフルグループと同様に、**stepRtnX_Y**に対して複数パターンが定義できるようになります。
2. ConfigTypeを廃止しました。内部的に変数は残しています。
合わせてColorTypeを画面左側へ移動し、カラー・シャッフルグループを右上のスペースへ移動しました。
3. 11ikeyに対して、キャラクタの回転パターン追加に合わせキーパターンを見直しました。
1. 同じキーのキャラクタの変更や回転だけのためにキーパターンを追加するのは非効率のため。
Resolved #1430 
2. 1の追加に当たり、キーコンフィグ画面にスペースが無いため。
現在はキー割り当て部分のクリックで対象のキー割当ができるため、無くても影響はほぼ無いと考えています。
3. 1の追加で余計と思われるキーパターンをShapeGr.へ移動しました。
- 3の変更により、キーパターン番号が変更になるキーがあります。
対象は9Akey（の11ikeyコンバート）、11ikeyです。
特殊キーで該当のキーを使用している場合（略記を使用している場合）は変更が必要です。
=> feat: [0668] キャラクタの回転パターン実装、ConfigTypeの廃止

js/danoni_main.js, js/lib/danoni_constants.js
1. copyArray2d関数を使わないコードに変更しました。
2. キー数関連のコメントを修正しました。
1. copyArray2d関数の実体は`structuredClone`ですが、すでに`structuredClone`を使っているコードが混在しているため、今回書き方を統一しました。
2. 過去のコメントと入り混じっている箇所があったため、修正しました。
=> refactor: [0672] copyArray2dを使わないコードに変更、コメント部分修正

js/danoni_main.js
1. 譜面リストで、上下キーを使って選択した譜面がキー数違いのときに
キーコンフィグ画面へ移動すると画面が止まる問題を修正しました。
1. 譜面を切り替える際、キー数が変わったことをチェックするために`g_keyObj.prevKey`という変数に
前の譜面のキー数を格納していました。
Difficultyのボタン及び譜面リストのボタンをクリックした場合は`g_keyObj.prevKey`が更新されるようになっていましたが、譜面リストを上下に切り替える際に`g_keyObj.prevKey`が更新されるようになっていませんでした。
- ver24.5.1以降で発生します。
=> fix: [0673] 譜面リスト中、上下キーを使って選択した譜面がキー数違いのときの問題を修正

js/lib/danoni_constants.js
1. キーコンフィグ画面のShapeGroup及びColorGroupの説明文を追加・変更しました。
1. キーコンフィグ画面のShapeGroupについて説明文が無かったため。
また、ColorGroupについては説明文が実態からずれてきたため。
=> improve: [0674] キーコンフィグ画面のShapeGroup及びColorGroupの説明文を変更

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面密度グラフについて、上位3番目まで色付けするよう変更しました。
上位3番目で同率の場合は同率すべてに対して色付けします。
1. これまで同率の場合は1か所しか色付けされていなかったため。
また最大だけを色付けするより、複数の上位を色付けした方が譜面傾向がつかみやすいため。
- 今回の変更で、`g_detailObj.densityData[_scoreId]`を単独の数字から配列に変更しています。
=> feat: [0675] 譜面密度グラフについて、上位3番目まで色付けするよう変更

js/danoni_main.js
1. 譜面エフェクトデータに別の変数が入っていた場合、その変数を参照する仕様を追加しました。
現状対応している対象は以下の通りです。
- 速度変化(speed_data, boost_data)
- 色変化(color_data, acolor_data)
- 歌詞表示(word_data)
- 背景・マスクモーション(back_data, mask_data)
- リザルトモーション (backresult_data, maskresult_data, backfailedB_data)
- 矢印モーション(arrMotion_data, frzMotion_data)
- キー数変化 (keych_data)
- スクロール変化 (scrollch_data)
```
|color_data=200,20,#66ffff,300,20,#ff9999|
|color2_data=color_data|   // 2譜面目の色変化データは1譜面目のものを利用
|word2_data=...|
|word3_data=word2_data|  // 3譜面目の歌詞データは2譜面目のものを利用
```
2. `makeBackgroundResultData`関数の引数を変更しました。
```javascript
makeBackgroundResultData (_header, _scoreNo, _defaultHeader);  // 変更前
makeBackgroundResultData (_header, _resultType, _scoreNo, _defaultType);  // 変更後
```
3. 初期矢印色・初期フリーズアロー色に別の変数が入っていた場合、その変数を参照する仕様を追加しました。
```
|setColor2=....| …
```
=> feat: [0676] 譜面エフェクトデータに別の変数が入っていた場合、その変数を参照するよう変更

js/danoni_main.js
1. 共通設定ファイルにおけるカスタムキーでkeyExtraListが原則不要になりました。
既存キー、カスタムキーによらずcharaX (Xにはキー数が入る) が指定されていれば、今後は省略できます。
2. `makeDedupliArray`関数で、`undefined`が渡された場合に`undefined`を除外するように変更しました。
3. `dosConvert`関数で、引数の初期値として空を指定するよう変更しました。
1. 現状は共通設定ファイルのみとなったとはいえ、記述するのは手間のため。
※作品ページ内の`keyExtraList`指定は現状でも不要です。
2. 通常、`undefined`を配列に追加する必要があることは無いため。
3. `dosConvert`関数で`undefined`が渡されたとき、エラーとなることを避けるため。
- charaXが指定されている場合で、意図して特定のキーを外したい場合には
従来通り`keyExtraList`が使えます。
=> improve: [0678] 共通設定ファイルにおけるカスタムキーでkeyExtraListの省略に対応

js/danoni_main.js, js/lib/danoni_constants.js
1. カスタムキーで`charaX`を任意化しました。
`charaX`が未指定の場合、`keyCtrlX`の指定があれば`1a, 2a, 3a, ...`のように値を補完します。
2. カスタムキーの一部設定が必要長に満たない場合、他の値で代替するよう変更しました。
※単一指定設定（`blankX`など）は除きます。
```
|keyCtrl6=75,79,76,80,187,32|
|shuffle6=1|            -> |shuffle6=1,0,0,0,0,0|
|chara6=left,down|      -> |chara6=left,down,3a,4a,5a,6a|
|color6=,,,,,1|         -> |color6=0,0,0,0,0,1|
```
1. 変数名指定（charaX）について、必ずしも必要なものではないため。
2. カスタムキーの指定の簡略化により実装を容易にするため。
- 今回、g_keyObjでの必須プロパティとして`g_keyObj.defaultProp`を定義しています。
このプロパティは変更されると問題になるため、変更禁止に設定しています。
- 内部的には、`newKeyTripleParam`と`newKeyPairParam`、`setKeyDfVal`にて値補完処理を行っています。
`newKeyMultiParam`については生成される変数の種類が通常の配列 or 二次元配列と変わることがあり、
補完ルールが複雑になることから値補完はしていません。
また、単純に値補完できないものもあるため（charaX, posX）、`setKeyDfVal`にてまとめて行っています。
=> improve: [0679] カスタムキーの必須項目をkeyCtrlXのみに変更　他

js/lib/danoni_constants.js
1. 上下スクロールがあるキーで、キーパターン違いがあるときに
ステップゾーンの配置が想定と異なる問題を修正しました。
1. PR #1456 に対する考慮漏れ。
- `setKeyDfVal`について、keyCtrlX_Yが存在するものに対して初期化していましたが、
これにスクロールの折り返しを管理する`divX_Y`の初期化が含まれていました。
- keyCtrlX_Yが定義されているパターン(X, Y)の中には`divX_Y`がいないパターン(X, Y)があり、後で別パターンからコピーする仕様になっていましたが`setKeyDfVal`の時点で初期化されてしまうため、`divX_Y`が存在する状態となってしまい、コピーができませんでした。
※別パターンからのコピーは、`divX_Y`が未定義の場合のみ適用される
- この部分だけは、`charaX_Y`が存在するものを基準に初期化する必要がありました。
- すでにリリース済みのバージョンには影響しません。
=> fix: [0680] 一部キーでスクロールの折り返しが外れてしまう問題を修正

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js, package.json
=> [ver31.3.1] keyExtraListの任意化、位置管理系変数をdanoni_constants.jsに集約　他

js/danoni_main.js
1. カスタムキーのposXに空が指定されたときに初期化できない問題を改善しました。
具体的には下記のように一部譜面が無指定の場合、ステップゾーン位置が正しく表示されませんでした。
```
|pos10=$$0,1,2,3,4,5,6,7,8,9|
```
1. 部分的に未指定にする場合も正しく表示されるように動く想定だったため。
=> improve: [0682] カスタムキーのposXに空が指定されたときに初期化されるよう処理を改善

js/danoni_main.js, js/lib/danoni_constants.js
1. 別キーモード、ミラー（Mirror, Asym-Mirror）時のハイスコア保存に対応しました。
なお、Mirror, Asym-Mirrorのハイスコアは区別されず「Mirror」として保存します。
別キーモードは KeyPattern表示時に明記されるキー（**transKeyX**での指定キー）毎に保存します。
2. 別キーモードのときローカル保存が有効になっていれば、Appearance, Opacity, HitPosition, Adjustment, Volume を保存するように挙動を変更しました。
3. Shuffle設定に「Turning」を追加しました。他ゲーで言うところの「R-Random」に相当します。
グループレーンごとに流れてくるレーンが左右にずれて流れてきます。ミラーになることもあります。
例1）1,2,3,4,5,6,7 -> 3,4,5,6,7,1,2
例2）1,2,3,4,5,6,7 -> 5,4,3,2,1,7,6
グループレーンが複数ある場合は、あるグループが正順で、
別のグループがミラーといったことも起こりえます。
1. 別譜面として独立した譜面と見做せるため。
なお、RandomやS-Random系については一意の譜面にすることができないため、
今後もハイスコアの更新対象からは外します。
- 厳密には、シャッフルグループが個別に変更できるためミラーでも一意に特定はできません。
通常のプレイではハイスコア管理を一つにしても大きな支障にならないと思われるため、
今回実装しています。
2. 別キーモードのとき、ローカル保存の有無によらず常に無効となっていましたが、
実際には環境設定など有効にした方が良い設定も含まれているため。
3. …
=> feat: [0683] 別キーモード、ミラー時のハイスコア保存に対応　他

js/danoni_main.js
1. 設定系のサブ関数をグローバル関数に変更しました。
対象は次の通りです。
- resetDifWindow ()
- makeDifList (_difList, _difCover, _targetKey)
- nextDifficulty (_scrollNum)
- makeDifBtn (_scrollNum)
- createDifWindow (_key)
- changeDifficulty (_num)
- getScoreBaseData(_scoreId)
- drawSpeedGraph (_scoreId)
- drawDensityGraph (_scoreId)
- drawBaseLine (_context, _resolution)
- drawLine (_context, _y, _lineType, _fixed)
- updateScoreDetailLabel(_name, _label, _value, _pos, _labelname) 
- makeDifInfoLabels (_scoreId)
- makeDifInfo (_scoreId)
- setReverse (_btn)
- setReverseView (_btn)
- setGauge (_scrollNum)
- gaugeChange (_gaugeNum)
- setLife (_baseProperty, _setProperty, _magnification)
- setLifeCategory (_baseObj, { _magInit = 1, _magRcv = 1, _magDmg = 1 }
- changeLifeMode (_baseObj)
- gaugeFormat (_mode, _border, _rcv, …
=> refactor: [0684] 設定系のサブ関数をグローバル関数に変更

js/danoni_main.js
1. 譜面リスト選択時にキーコンフィグ画面で止まることがある問題を修正しました。
1. 譜面リストを「L」キーで開き、一番最初から「↑」キーで一番最後に移動したときに発生します。
PR #1446 の修正漏れです。
=> fix: [0688] 譜面リスト選択時にキーコンフィグ画面で止まることがある問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. フリーズアローヒット時の割込み処理を実装しました。
下記のカスタム関数オブジェクトに関数を追加することで実装します。
- 通常のフリーズアロー： `g_customJsObj.judg_frzHit`
- ダミーフリーズアロー： `g_customJsObj.judg_dummyFrzHit`
- 引数にジャスト時からの差分フレーム数を指定できます。
```javascript
function addProcessInFrzHit(_difFrame) {
// 割込み処理を記述
}
// 定義した関数を追加
g_customJsObj.judg_frzHit.push(addProcessInFrzHit);
```
1. 判定時の処理割り込みはありましたが、フリーズアローヒット時の処理割り込みは無かったため。
- `changeHitFrz`関数の処理末尾に追加する形となります。
=> feat: [0690] フリーズアローヒット時の割込み処理を実装

js/danoni_main.js
1. 同じキー数の譜面が複数存在するときに譜面リストのフィルタが複数表示される問題を修正しました。
1. PR #1475 でキー数フィルタを定義する配列を変更しましたが、その配列の重複排除処理が抜けていました。
=> fix: [0693] 同じキー数の譜面が複数存在するときに譜面リストのフィルタが複数表示される問題を修正

SECURITY.md, js/danoni_main.js, package.json
=> [ver31.7.1] 同じキー数の譜面が複数存在するときに譜面リストのキー別フィルタが重複表示される問題を修正

js/danoni_main.js
1. カスタムキーの部分略記に対応しました。
下記のような略記指定が使えるようになります。
使用できる対象は、「keyCtrlX」「charaX」「colorX」「stepRtnX」「posX」「shuffleX」「keyGroupX」「scrollX」「assistX」です。
```
|keyCtrl9j=Tab,7_0,Enter|
-> |keyCtrl9j=Tab,S,D,F,Space,J,K,L,Enter|            // "keyCtrl7_0=S,D,F,Space,J,K,L" を補完
|stepRtn9j=giko,7_0,iyo|
-> |stepRtn9j=giko,0,-45,-90,onigiri,90,135,180,iyo|  // "stepRtn7_0=0,-45,-90,onigiri,90,135,180" を補完
|color9j=2,7_0,2|
-> |color9j=2,0,1,0,2,0,1,0,2|                        // "color7_0=0,1,0,2,0,1,0" を補完
```
- ただし、「colorX」「shuffleX」「stepRtnX」については複数グループ分存在する場合があります。
この場合、「(キー数) _ (キーパターン -1) _ (グループ -1)」のように指定することができます。
```
|color10=9B_0_1,2|
-> |color9j=4,3,1,0,2,0,1,3,4,2|                      // "color9_0_1=4,3,1,0,2,0,1,3,4" を補完
```
- scrollX, assistXの場合は、対応する名前のパターンが存在する場合、値補完します。
``` …
```
=> improve: [0695] カスタムキーの部分略記に対応

js/danoni_main.js, js/lib/danoni_constants.js
1. Shift, Ctrl, Altキーの左右キーの割り当てを分離しました。
画面中で使用できるショートカットキーは例外的に左右両方使えるようにしています。
なお、従来のキーコードは左側のキーに対応します。対応状況は下記の通りです。
|KeyCode|KeyboardEvent.code|
|----|----|
|16|ShiftLeft|
|17|ControlLeft|
|18|AltLeft|
|256|ShiftRight|
|257|ControlRight|
|258|AltRight|
2. カスタムキー定義で使用できるキー名を一部拡張しました。
主に日本語キーボードを意識した変更です。
|KeyCode|KeyboardEvent.code|対応している名称|
|186|Quote|Quote, **Ja-Colon**|
|192|BracketLeft|BracketLeft, **Ja-@**|
|219|BracketRight|BracketRight, **Ja-[**|
|221|Backslash|Backslash, **Ja-]**|
|222|Equal|Equal, **Ja-^**|
1. 左右キーどちらも反応することで、意図しない誤爆が起こる可能性があるため。
また左右キーを分離することにより、分離性を活かしたキーが作成できる可能性がありそうなため。
2. KeyboardEvent.codeそのままの場合、直感的で無いため。
- 既存キーについては現状左シフトキーのみに割り当てています。
代替キーに右シフトキーを割り当てれば、両方に対応させることも可能です。
=> feat: [0696] Shift, Ctrl, Altキーの左右キーの割り当てを分離　他

js/danoni_main.js
1. カスタムキー指定でblankX, scaleX, keyRetryX, keyTitleBackX, transKeyXの略記指定に対応しました。
```
|keyCtrl9g=F1,F2,F3,F4,F5,F6,F7,F8,Enter/ShiftRight$D1,D2,D3,D4,D5,D6,D7,D8,Enter/ShiftRight|
|blank9g=52.5|  -> |blank9g=52.5$52.5|     // 省略時はパターン1のものをコピー
|append12=true|
|keyCtrl12=F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12$Q,W,E,R,T,Y,U,I,O,P,Ja-@,Ja-[|
|blank12=50$12_(0)|  -> |blank12=50$50|    // パターン名指定時はそのパターンの情報をコピー
```
1. 複数パターン別指定のうち、これらのみ略記指定ができなかったため。
=> feat: [0697] カスタムキー指定でblank, scaleなどの略記指定に対応

js/danoni_main.js
1. 曲開始までの空白フレーム数設定(blankFrame)の複数譜面別設定に対応しました。
```
|blankFrame=300|     // 全譜面共通
|blankFrame=200$300| // 譜面別の設定（$区切り、譜面別）
```
1. 曲が変わると本来は曲開始までの空白フレーム数も変える可能性があるため。
読み込む楽曲別にすることも考えましたが、
途中フェードインを前提とした譜面が考えられることから譜面別としました。
=> feat: [0698] 曲開始までの空白フレーム数設定(blankFrame)の複数譜面対応

js/danoni_main.js
1. ボタンのデフォルト処理を参照する機能を追加しました。
```javascript
g_btnFunc.base.lnkDificulty;  // lnkDifficultyのボタン処理
g_btnFunc.reset.lnkDificulty;  // lnkDifficultyのボタン処理（画面遷移系）
g_btnFunc.cxt.linkDifficulty;   // lnkDifficultyの右クリック時処理
```
これを使うと、次のようにボタンを押したときの処理をコピーすることができます。
```javascript
const newBtn = createCss2Button(`newId`, (`btnStart`, g_lblNameObj.clickHere, g_btnFunc.base.lnkDificulty, {
w: g_sWidth, siz: g_limitObj.titleSiz, resetFunc: g_btnFunc.reset.lnkDificulty,
}, g_cssObj.button_Start),
```
1. 既存ボタンの機能をつぶして、他のボタンで代用させたいときに現状はその手段が無いため。
座標系は`cloneNode`で対処できるが、処理系はコピーすることができませんでした。
=> feat: [0699] ボタンのデフォルト処理を参照する機能を追加

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面明細画面の部分表示に対応しました。既定はすべて表示です。
なお、`|scoreDetailUse=true|`は廃止しました。
```
|scoreDetailUse=false|   // 非表示
|scoreDetailUse=Density,ToolDif|  // 譜面密度、ツール値のみ表示
```
設定可能値は次の通りです。カンマ区切りで複数の項目を表示します。
|設定可能値|意味|
|----|----|
|false|非表示|
|Speed|速度変化グラフを表示|
|Density|譜面密度グラフを表示|
|ToolDif|譜面情報を表示|
1. 譜面明細画面の全部を非表示にする状況がほぼ無く、一部のみ非表示にする方が利用しやすいため。
- クリア状況で全部表示したいといった場合は、customjsが必要となります。
=> feat: [0700] 譜面明細画面の部分表示に対応

js/danoni_main.js, js/lib/danoni_constants.js
1. 速度変化の平均値表示を追加しました。次の表示が増えています。
|表示項目|表示内容|
|----|----|
|Avg.|全体加速(Speed)の平均×個別加速(Boost)の平均の値を小数第2位で表示します。|
|AvgS)|全体加速(Speed)に**1倍以外が掛かっている部分**について、平均値を小数第2位で表示します。|
|AvgB)|個別加速(Boost)に**1倍以外が掛かっている部分**について、平均値を小数第2位で表示します。|
1. 速度変化グラフがありますが、平均してどのくらいの速度変化があるかはわかりにくいため。
また平均の情報だけでは不十分と思われるため、実際に速度変化が掛かっている部分のみを取り出して
その平均も表示するようにしました。
=> feat: [0702] 速度変化の平均値表示を追加

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面明細画面でQキーを押してもカーソル移動しない問題を修正しました。
1. PR #1487 で`g_settings.scoreDetails`が可変になったため、それに合わせて`g_settings.scoreDetailCursors`も連動する必要がありました。
- ver32.2.0のみで発生する問題です。
=> fix: [0703] 譜面明細画面でQキーを押してもカーソル移動しない問題を修正

js/danoni_main.js
1. blankFrameが未指定のときにblankFrameが正しく反映されない問題を修正しました。
1. PR #1484 の際、`blankFrameDefs`という変数を作成しましたが、未指定のときに正しく値が入らないようになっていました。
下記で`blankFrameDefs`を使用しているため、未定義のときにg_headerObj.blankFrame が正しく入りません。
- ver32.1.0以降で発生する問題です。
=> fix: [0705] blankFrameが未指定のときにblankFrameが正しく反映されない問題を修正

js/danoni_main.js
1. customCreditWidthが使用できない問題を修正しました。
1. PR #1124 において譜面ヘッダー名を`customViewWidth`にしていました。
互換のため、`customViewWidth`と`customCreditWidth`の両方が使えるようにしておきます。
=> fix: [0706] customCreditWidthが使用できない問題を修正

js/danoni_main.js
1. 矢印数がゼロの場合にツール値がNaNになる問題を修正しました。
- PR #1474 でコードを修正しましたが、ゼロ除算が考慮されていませんでした。
- ver31.7.0以降で発生します。
=> fix: [0708] 矢印数がゼロの場合にツール値がNaNになる問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面明細表示の順番について、「Speed」と「Density」の位置を入れ替えました。
ショートカットも入れ替えています。
2. 速度変化グラフの名前を「Speed」から「Velocity」に変更しました。
また、全体加速を表す「Speed」を「Overall」に変更しました。
3. 難易度レベル表示の名前を「ToolDif」から「DifLevel」に変更しました。
4. 譜面ヘッダーの「scoreDetailUse」について、変更後の名前「Velocity」「DifLevel」が使えるように対応しました。
下記はどちらも動作し、同じ意味です。
```
|scoreDetailUse=Velocity,DifLevel|
|scoreDetailUse=Speed,ToolDif|
```
5. 譜面明細部分の「i」部分をON/OFFした場合で、「Q」キー動作時に動かなくなることがある問題を改善しました。
1. 速度変化状況よりも、矢印数やプレイ時間、密度といった情報の方が参照時に便利と思われるため。
ToolDif（ツール値やレーン別の矢印数）については、どちらかと言えばわかる人向けの機能のため、据え置きます。
2. Flash時代の名前をそのまま引き継いでおりわかりにくい名前になっているため。
- Speedは速さ、Velocityは速度(＝速さ＋向き)を表します。マイナス表記があるため後者が適切と考えました。
- Speed/Boostの表記は譜面データ由来です(speed_data, boost_data)。
前者は全体的な加速を意味するため「Overall」が適切と考えました。
後者は押し上げるという意味の「Boost」で違和感はないため、そのままとしています。
3. 従来はレベル計算ツールという意味での「Tool」でしたが、現状一体化されています。 …
=> improve: [0711] 譜面明細表示の順番、名称を変更

js/danoni_main.js, js/lib/danoni_constants.js
1. 結果画面で表示するExcessiveの名前をdanoni_constants.jsから変更できるよう対応しました。
Fast/Slow/推定Adjと同様、`g_presetObj.lblName.ja.j_excessive` 及び `g_presetObj.lblName.en.j_excessive` にて設定します。
1. PR #1503 関連。他機能との統一性のため。
=> improve: [0712] Excessiveの名前をconstantsから変更できるよう対応

css/danoni_main.css, js/danoni_main.js
1. フリーズ始点判定有効時、DifLevelでの矢印数表記を一部変更しました。
1. フリーズ始点判定が有効かどうかが画面からでは視認できないため。
- 右側がフリーズ始点判定有のときの表示です。
=> improve: [0714] フリーズ始点判定有効時、DifLevelでの矢印数表記を一部変更

js/danoni_main.js
1. Difficultyを変更するごとにGaugeを初期化しないよう変更しました。
例えばGauge:「Hard」を選択し、Difficultyを変更した場合に
次の譜面のゲージ設定にGauge:「Hard」があれば、ゲージ設定を変更しません。
2. ゲージ設定周りのコードを見直しました。
1. ゲージ設定のみ、譜面を変えると初期化するようになっていたため。
2. ゲージ設定を制御する`gaugeChange`関数について、ゲージ設定配列を入れ替える処理とゲージ明細を設定する処理が一緒になっており、使いづらい処理になっていたため分離しました。
=> improve: [0715] Difficultyを変更するごとにGaugeを初期化しないよう変更

js/lib/danoni_constants.js
1. Excessive設定に対してショートカットキーを割り当てました。
「E」キーで切り替えが可能です。
1. 設定画面では基本的にショートカットキーが割り当てされているが、
Excessive設定に対するショートカットキーが無かったため。
=> improve: [0716] Excessive設定に対してショートカットキーを割り当て

js/danoni_main.js, js/lib/danoni_constants.js
1. 結果画面のSNS投稿用画像コピー機能を実装しました。
右上のスクリーンショットボタンからコピーできます。
ショートカットは「P」キーを割り当てています。
※現行のFirefox及びhttp環境ではコピー用の画像が表示されます。
1. 元々html2canvasで実装することを考えていましたが、
余計な項目が多いため新たにCanvasを作ってそこに必要データを埋め込む形で実装しました。
- customFontで指定したフォントは反映されます。
- All Perfect, Perfect, FullCombo, Failedといった表記と、Displayオプションは表示していません。
- 横幅が変わっても、画像サイズは400x410で固定です。
=> feat: [0722] 結果画面のSNS投稿用画像コピー機能を実装

js/danoni_main.js
1. Firefoxでドメイン外のCSSファイルを読み込んだ場合、起動できない問題を修正しました。
1. PR #1519 にてCSSをリセットするためにFirefoxのみ別処理にしましたが、ドメイン外（フォントなど）を読み込んだ場合、CORSに引っ掛かり起動できない問題が発生していました。
=> fix: [0723] Firefoxでドメイン外のCSSファイルを読み込んだ場合、起動できない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 画像コピー時の譜面作成者名の表記を見直しました。
makerViewが`true`のとき、譜面作成者名が譜面名として表示されてしまうため、その表記を止めました。
1. 譜面作成者表記が重複するため。
=> feat: [0724] 画像コピー時の譜面作成者名の表記を見直し

css/danoni_main.css
1. フォントサイズが小さいものに対してbackground-clip:textを取り止めました。
```
.common_ii
.common_shakin
.common_matari
.common_shobon
.common_uwan
.common_kita
.common_iknai
.common_combo
.common_comboJ
.common_comboFJ
.common_diffFast
.common_diffSlow
.common_estAdj
.common_excessive
```
1. Discord指摘より。
cssのbackground-clip:textで文字のくり抜きによる色付けを行う場合、
塗りつぶし範囲が違う（おそらく文字の内側を塗りつぶす）ため、文字色が細く見えることから
文字サイズが小さいものについてはこの方法を取り止めました。
これに伴い、上記に指定したものについてはグラデーション指定が無効となります。
- CSSカスタムプロパティ名は変更しません。
=> fix: [0726] フォントサイズが小さいものに対してbackground-clip:textを取り止め

js/danoni_main.js
1. 背景・マスクモーションのフレーム計算誤りを修正しました。
タイトル/リザルト時の背景・マスクと、本体の背景・マスクの計算方法が逆になっていました。
（後者は、AdjustmentやplaybackRateに合わせてフレーム数の修正が必要）
1. PR #1519 でコード集約した際のコード誤りです。
- コード中の「resultType」というのはタイトル/リザルトモーションのことを指します。
- 下記修正で、`const calcFrameFunc = resultTypes.length > 0 ? calcFrame : undefined;`としていますが
これだとタイトル/リザルトモーションに対してフレーム補正が掛かってしまいます。
本当に必要なのは本体の方なので、条件式が逆です。
=> fix: [0727] 背景・マスクモーションのフレーム計算誤りを修正

js/danoni_main.js
1. フリーズアローの終点と次のフリーズアローの始点が近い場合に、
後のフリーズアローの判定がスルーされる場合がある問題を修正しました。
1. Resolves #1529 
- フリーズアローのFast/Slow実装時 ( PR #1352 ) の考慮漏れと思われます。v29.0.0以降が対象。
- 判定対象のフリーズアローより前の同レーンのフリーズアローは自動消去する仕様です。
=> fix: [0728] フリーズアローの終点と次のフリーズアローの始点が近い場合の判定不具合を修正

js/danoni_main.js
1. 画像コピー用のテキストのエスケープ文字が戻されていない問題を修正しました。
1. PR #1521 の考慮漏れです。
X (Twitter)投稿用のテキストにはエスケープを元に戻す処理が入っていましたが、
リザルト画像用の方にはされていませんでした。
なお前者は全体に対してunEscapeHtmlを適用していますが、
後者はできないため、外部から入力する項目のみunEscapeHtmlを適用しています。
(X (Twitter)投稿画像より)
- ver33.1.0以降で発生する問題です。
- g_lblNameObjで変更可能な項目はエスケープの必要が無いため、対処していません。
=> fix: [0729] 画像コピー用のテキストのエスケープ文字が戻されていない問題を修正

js/danoni_main.js
1. stockForceDelを使用中に、背景・マスクモーションで使用しているanimationNameが空の場合、
エラーになる問題を修正しました。
背景・マスクモーションでアニメーションを利用しない場合があり、backStockForceDel（もしくはmaskStockForceDel）と併用したときに問題になっていました。
アニメーション名抽出の際に`listMatching`という関数を使っていますが、
文字列がundefinedの場合は受け付けないため、エラーとなっていました。
=> fix: [0731] stockForceDel使用中に背景・マスクのanimationNameが空の場合、エラーになる問題を修正

css/danoni_main.css
1. 画面の上下に共通の枠線を一律追加するよう対応しました。
CSSカスタムプロパティ上は`--back-border-x`にて定義しています。
1. 画面の境界線がわかりにくいため。また、v9以前のcanvas描画との互換性のため。
- 上下に `#666666` の境界枠を追加しています。
=> improve: [0732] 画面の上下に共通の枠線を一律追加するよう対応

js/danoni_main.js, js/template/danoni_setting.js
1. デフォルトスキン時、Canvas背景を有効化するかどうかの設定を追加しました。
作品別/共通共に`bgCanvasUse`で制御します。初期値は有効(true)です。
```
|bgCanvasUse=false|  // スキンDefault時、Canvas背景を無効にする
```
```js
g_presetObj.bgCanvasUse = false;   // スキンDefault時、Canvas背景を無効にする（全体）
```
1. ページ共通化の影響でCanvasタグを外せない場合があるため。
別スキン化すれば問題ないのですが、
スキン定義更新時の手間とCSSキャッシュの問題を考慮してこの実装にしました。
- v9以前の互換性用の設定です。通常は無視して問題ありません。
- スキンをDefault以外にした場合は、Canvas背景は強制的に無効です。（従来通り）
=> feat: [0733] デフォルトスキン時、Canvas背景を有効化するかどうかの設定を追加

js/danoni_main.js
1. エラー時に表示される音楽ファイルの参照先URLが実際と異なる問題を修正しました。
読込先は合っているのですが、エラー時に表示するURLが間違っていることがありました。
1. 上述の通り。
- ver29.4.1 ( PR #1387 ) 以降で発生する事象です。ファイルから開く場合は問題ありませんでしたが、サーバーから開くと常時作品ファイル直下になっていました。
=> fix: [0734] エラー時に表示される音楽ファイルの参照先URLが実際と異なる問題を修正

js/danoni_main.js, js/template/danoni_setting.js
1. リザルト画像用にカスタム変数を追加できるよう対応しました。
`resultFormat`で使用する`g_presetObj.resultVals`を定義していれば、そこで定義した値を
リザルト画像へ反映するようになります。
ただし、`g_presetObj.resultVals`で定義した名前を`g_resultObj`のプロパティで定義していなかったり、
そのプロパティの値が空の場合は印字されません。
参考：https://github.com/cwtickle/danoniplus/wiki/dos-h0072-resultFormat
- 譜面ヘッダーもしくは共通設定で、カスタムで表示する項目を制御できます。
```javascript
g_presetObj.resultVals = {
exScore: `exScores`,   // g_resultObj.exScores として定義
extra: `extraMark`,     // g_resultObj.extraMark として定義
};
```
※カンマ区切りで定義します。
```
|resultValsView=exScore,extra|
```
※配列で指定します。
```javascript
g_presetObj.resultValsView = [`exScore`];
```
1. 現状のリザルト画像はカスタム用の変数を表示する方法が無いため。
- 現状は`g_presetObj.resultVals`及びそれに対応する`g_resultObj`が定義されている場合、表示します。
=> feat: [0735] リザルト画像用にカスタム変数を追加できるよう対応

js/danoni_main.js
1. https環境向けにリザルトコピー用画像のプレビュー機能を追加しました。
「Shift」キーを押しながら「:camera:」ボタンもしくは「P」キーでプレビューができます。
http環境もしくはFirefox時は特に変わりません。
1. 通常は不要ですが、ローカル環境などでの確認用や何らかの理由でコピーができないときのため。
機能としてはhttp環境時に表示するものと同じ機能を使っています。
=> feat: [0718] リザルトコピー用画像のプレビュー機能を追加

js/danoni_main.js
1. forEach周りのコード整理を行いました。
`forEach...if` の組み合わせについて、`filter...forEach`となるように見直しました。
また合わせて、for文から`filter...forEach`に変更できる部分を変更しています。
2. `array[array.length - 1]` を `array.at(-1)` の記述に置き換えました。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/at
1. if文が多いことでコードの見通しが悪くなっていたため。
2. 記述の簡素化のため。
`array.at`は現在のブラウザで利用可能なため、今回より使用することにしました。
- filterの後のforEachで配列番号を使用する場合、
filterすると番号が変わってしまうためその部分は据え置きにしています。
- 逆に、filterで配列番号を使用していても、その後のforEachで配列番号を使っていない場合は
影響が無いため、変更対象としています。
=> improve: [0741] forEach周りのコード整理

js/danoni_main.js
1. グラデーション記法のセパレート文字を見直しました。
グラデーション指定以外の指定について、セパレート文字`;`から`;;`に変更しました。
```
|--background=;;url("../img/backgroundfile.png")|
|--background=none;;url("../img/backgroundfile.png")|
```
1. グラデーション記法のセパレート文字(`;`)について、別用途(色名;透明度)で使われているため
その部分が機能しなくなっていました。
仕様矛盾が発生しているため、仕様を見直します。
- ver33でのみ発生します。
PR #1519
=> fix: [0742] グラデーション記法のセパレート文字を見直し

js/danoni_main.js, js/lib/danoni_constants.js
1. ウィンドウの高さやY座標調整ができる機能を実装しました。
```
|windowHeight=570|    // ウィンドウサイズ（高さ）を570pxに変更
|playingY=50|         // プレイウィンドウのY座標を50pxに変更
|playingHeight=520|   // プレイウィンドウの高さを520pxに変更
```
2. 高さを変えたときの各画面の基準位置を中央から上寄せに変更しました。
1. 従来から高さを変える機能は存在しましたが、プレイウィンドウを調整する機能が無かったため。
2. カスタムで高さを拡大する際に下側の余白を使う余地ができるため。
中央寄せの場合、上下に空白ができるためある程度大きく取らないと余白が取れない問題がありました。
- PR #1553 を受けての修正です。
- 現実的にプレイ側のブラウザサイズ依存にするのは難しいですが、制作側でウィンドウサイズを調整できる機能はあっても良いと思い、今回実装に至っています。
=> feat: [0743] ウィンドウの高さやY座標調整ができる機能を実装

js/danoni_main.js
1. 空のレーンが存在するときに、preblankframeが正しく計算されない問題を修正しました。
空のレーンに対して最小のフレーム数がゼロ扱いになっていたと思われます。
この問題の影響範囲は不明ですが、キー変化作品の一部でタイミングがずれることを確認しています。
1. preblankframeが正しく計算されないと、意図したタイミングで矢印が出現されないといった問題が出ます。
- PR #1551 のコードミスです。
=> fix: [0744] 空のレーンが存在するときに、preblankframeが正しく計算されない問題を修正

js/danoni_main.js, js/template/danoni_setting.js
1. 共通設定ファイルに画面位置調整を行う設定を追加しました。
いずれも譜面ヘッダーに存在する設定の共通版です。
```js
/** 個人サイト別の最小高さ設定 */
g_presetObj.autoMinHeight = 550;
/**
* プレイ画面の位置調整
* - 譜面ヘッダーのplayingX, playingY, playingWidth, playingHeightと同じ
*/
g_presetObj.playingX = 0;
g_presetObj.playingY = 0;
g_presetObj.playingWidth = 600;
g_presetObj.playingHeight = 500;
```
1. カスタムで配置しているテキスト等の関係でずらすことを考慮すると、共通設定できた方が利便性が高いため。
=> feat: [0745] 共通設定ファイルに画面位置調整を行う設定を追加

js/danoni_main.js, js/lib/danoni_constants.js
1. 歌詞表示、背景・マスク・スタイルデータについてキー名毎に設定する機能を追加しました。
```
|transKey9A=$$9B|
|mask<9B>_data=...|  // 別キーモード:9Bの場合
|mask[2]_data=...|  // キーパターン:2の場合
|mask<9A>2_data=...|  // 別キーモード外 かつ 2譜面目の場合
|mask[1]2_data=...|  // キーパターン:1の場合 かつ 2譜面目の場合
```
2. 譜面エフェクトデータについて、既存の類似データが存在していればその設定を引用する設定を追加しました。
```
|mask_data=
/* mask_dataの定義内容 */
|
|mask2_data=
mask_data
700,0,test,....
|
```
```
|mask_data=
/* mask_dataの定義内容 */
|
|mask2_data=
/* mask_dataの定義内容 */
700,0,test,....
|
```
1. 既存の別キーモード時の設定として`|maskA_data=...|`などがありますが
別キーモードが複数種あるときに個別に設定したい場合があるため。
2. 他の定義内容を一部引用したい場合があるため。
- 別キーモード定義が下記のとき、以下のように適用されます。
```
|transKey9A=$$9B$9C|
|mask_data=...|         // 全体共通
|mask2_data=...|        // 2譜面目共通
|maskEn2_data=...|      // 2譜面目、英語モードのみ適用
|maskEnA2_data=...|     // 2譜面目、英語モード、別キーモード(9B, 9C)のみ適用 …
```
=> feat: [0747] 歌詞表示、背景・マスク・スタイルデータの優先順条件追加

js/danoni_main.js
1. 歌詞表示で途中にカンマがある場合でも、後ろが数字以外ならカンマと見做す処理を追加しました。
```
8945,0,They search my face in a silky voice, <br>but they&#039;re scared of me at the bottom of their heart.
9097,0,It makes me annoyed tremendously...<br>Their behavior disgusts me !
```
- 末尾がカンマで、それを区切り文字としたくない場合はカンマの後に半角スペースを入れる必要があります。
- 連続してカンマがある場合は、一つのカンマに集約される仕様です。
- カンマの次の項目が数字でないことを条件に文字結合しています。
このため、歌詞非表示でカンマで囲われた数字をフレーム数としてみなしたくない場合はスペースを入れるか、従来通りカンマの特殊文字指定を行う必要があります。
1. カンマは英語歌詞では多く発生するため、カンマをそのまま使えるようにすることで利便性が上がります。
=> feat: [0748] 歌詞表示で途中にカンマがある場合でも、後ろが数字以外ならカンマと見做す処理を追加

js/danoni_main.js
1. musicTitleの曲名及びアーティスト名で条件付きでカンマがそのまま使えるようにしました。
カンマ+半角スペースの組み合わせがあれば、区切り文字で無いカンマと見做します。
```
|musicTitle=Hello, world,test,https://...|
-> |musicTitle=Hello*comma* world,test,https://...|  <- 自動でエスケープ処理
```
1. 曲名・アーティスト名でカンマを使うケースがそれなりにあるため。
- 他の部分にも転用は可能ですが、区切り文字としてのカンマとそれ以外の区別がつかなくなるため、現状はタイトルと歌詞表示限定にします。
- 区切り文字としてのカンマで、カンマ直後に半角スペースを入れることは通常考えにくいためこの仕様としました。
=> feat: [0749] musicTitleの曲名及びアーティスト名で部分的にカンマがそのまま使えるよう変更

js/danoni_main.js
1. 譜面明細画面のショートカット表示位置を変更しました。
1. 言語が「En」のとき、数字のショートカットが「1 !」「2 @」「3 #」と長くなってしまい、
従来の位置でははみ出してしまうため。
=> improve: [0751] 譜面明細画面のショートカット表示位置を変更

js/danoni_main.js
1. difDataで指定したノルマが反映されない問題を修正しました。
譜面ヘッダーのdifDataで定義した設定の後にデフォルトゲージで上書きしていました。
1. Resolves #1574 
- ver32.6.0 以降で発生する問題です。PR #1509 の対応に起因しています。
=> fix: [0754] difDataで指定したノルマが反映されない問題を修正

js/danoni_main.js
1. HitPosition設定が機能していない問題を修正しました。
1. オート時にHitPositionをリセットする条件に間違いがありました。
当初実装時の PR #1438 のv0.9.0にて該当処理の追加があり、ここから機能しなくなっていました。
- 当初（ver31.0.0）以降で発生します。
=> fix: [0757] HitPosition設定が機能していない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 右シフトキーがキーコンフィグで「Unknown」と表記される問題に対応しました。
今後はキーコンフィグ上、「R-Shift」と表示されるようになります。
（従来のものは「R)Shift」となり、別キーとして区別されます）
なお、キーコンフィグ画面ではkeyBoardEvent.keyまで見て変更していますが、
プレイ上ではkeyBoardEvent.keyは参照せず、keyBoardEvent.code=`''`だけを見て判断します。
2. カスタムキーで「ShiftRight」を指定した場合、自動で1.で追加した「R-Shift」も付加するようにしました。直接指定する場合は「260」を指定します。
3. キーコンフィグ画面で割り当てる文字のサイズを16pxから15pxに変更しました。
1. Chrome系ブラウザが`keyBoardEvent.code=ShiftRight`に対応しなくなったため。
2. ブラウザ対応により、当面両方が必要となると思われるため。
3. 割り当て文字の長さが長い場合、枠をはみ出るため。
- 右シフトキーの場合、keyboardEvent.codeが空のキーが全て反応することになりますが、
そういったキーが阻害となることは少ないと思われるため、このままとします。
- 下記の例では、「R-Shift」と「Unknown」の2キーがありますが、実際の割り当ては同じです。
- Chrome系ブラウザ
- Firefoxブラウザ
=> feat: [0758] 右シフトキーがUnknownと表記される問題への対応

js/danoni_main.js, js/lib/danoni_constants.js
1. R-ShiftとUnknownキーが区別されず、どちらも反応してしまう問題を修正しました。
2. ローカルのキーコードを直に書いていた部分を定数化しました。
1. PR #1583 の考慮漏れです。
KeyboardEvent.codeが空のときに押した状態を保存していたため、「R-Shift」「Unknown」どちらでも反応するようになっていました。
KeyboardEvent.codeが空のときは押した状態をリセットし、
その後独自に割り当てたキーに割り当てるといった形を取るように変更しています。
2. ローカルのキーコードが変わったときに関係個所全てを直す必要があるため。
=> fix: [0761] R-ShiftとUnknownキーが分離できていない問題を修正

js/danoni_main.js
1. keyGroupOrderが一部の譜面で空で設定されている場合、
他の譜面にその設定が適用されてしまう問題を修正しました。
下記のように設定されていると、本来2譜面目に適用するはずの設定が
1譜面目に設定されてしまいます。
1譜面目ではkeyGroupを考慮していないため、
キーコンフィグ画面に何も表示されない状態になります。この問題を修正しています。
```
|keyGroupOrder=$11,11L|  // 本来は2譜面目に設定
```
1. PR #1551 のコード考慮漏れです。
- ver33.5.0以降で発生する問題です。
=> fix: [0765] keyGroupOrderが一部の譜面で空の場合、他の譜面にその設定が適用されてしまう問題を修正

css/danoni_main.css, js/danoni_main.js, js/lib/danoni_constants.js
1. 設定画面の譜面情報表示（DifLevel）にて、レーン別の矢印数・フリーズアロー数の最大・最小値に色を付け、上下段位置の折り返し位置がわかるように変更しました。
最大・最小値についてはCSSカスタムプロパティを定義しています。
```css
/* 設定画面：レーンごとの矢印数 */
.settings_maxArrowCnts {
color: var(--settings-maxArrowCnts-x, var(--common-kita));
}
.settings_minArrowCnts {
color: var(--settings-maxArrowCnts-x, var(--common-ii));
}
```
2. 設定画面の譜面情報表示（DifLevel）の3つ以上の位置が複数あった場合でも、1つにまとめるように変更しました。
3. 譜面明細表示（scoreDetail）の横幅について、画面横幅に合わせて右に拡張するよう変更しました。
1. 数字の羅列だけではわかりにくいため。
2. 3つ押し表示位置と3つ押し数は本来異なるため。
3. キー数が多くなると横スクロールがほぼ必須となっていたため。
- 上下段の区分けは現在のレーン別の矢印数、フリーズアロー数表示に合わせて
キーパターン：１を基準にしています。
=> feat [0764]: 譜面情報表示の仕様変更

js/danoni_main.js
- startFrameに空白を指定したときプレイ開始できない問題を修正しました。
- `|startFrame=$0|`のように特定の譜面のstartFrameに空白を指定すると`g_scoreObj.frameNum`の値が`NaN`となり曲再生開始に失敗します。
#1573 以降発生していると思います。
- [くいなちゃんフュージョン](http://www.omission0.com/danoni/175-186-kuina/)で実際に発生していました。
=> startFrameに空白を指定したときプレイ開始できない問題を修正

js/danoni_main.js
1. 譜面リストに現在選択中譜面番号と総譜面数の表示を追加しました。
RANDOMボタンの下に配置しています。
この関係で、キー別フィルタボタン位置を若干下に動かしています。
1. 譜面数が多い場合に現在位置がわからなくなることがあるため。
- g_headerObj.viewListsをベースにしているため、カスタムで絞り込みを行っていた場合でも問題はないはずです。
=> feat: [0767] 譜面リストに現在選択中譜面番号と総譜面数の表示を追加

js/danoni_main.js, js/lib/danoni_constants.js
1. デフォルトのリザルトフォーマットの出力機能を追加しました。
リザルト画面で「Shift」キーを押しながら「CopyResult」もしくは「C」キーを押します。
```
【#danoni】(^^)(7k-Normal) /tickle /Rank:F/Score:0/Playstyle:1x, Hid&Sud+/0-0-0-0-0//0 
```
1. リザルトフォーマットについてはカスタムできるようになっており、
プレイヤーイベント時にデータ解析がカスタムパターン毎に必要となっていました。
互換性の問題を考慮し、デフォルトのリザルトフォーマットが出力できるようにしました。
=> feat: [0768] デフォルトのリザルトフォーマットの出力機能を追加

js/danoni_main.js
1. 譜面リストでキーフィルター適用時に対象がいない場合、「-」を表示するよう変更しました。
1. 譜面リストでキー別フィルターを選択したとき、選択中の譜面がそのキーで無かった場合は
（そのキーとしては）未選択状態になります。それを表現する対応です。
=> feat: [0769] 譜面リストでキーフィルター適用時に対象がいない場合、「-」を表示するよう変更

js/danoni_main.js
1. 譜面番号固定時に他の譜面ファイル番号や譜面番号を参照できる機能を追加しました。
これまでは譜面番号固定時は譜面番号が１のときしかデータが取得できませんでした。
1譜面目はファイル1の1譜面目、2譜面目はファイル1の2譜面目、3譜面目はファイル2の1譜面目、
といった取り方ができるようになります。
譜面ヘッダーに「dosNo」を追加しています。$区切りで譜面毎の設定です。
譜面ファイル番号、譜面番号の順にカンマ区切りで指定します。
なお譜面番号は省略が可能で、その場合は同一譜面ファイル番号の連番が割り当てられます。
下記の2つの設定は同じ意味です。
```
|dosNo=1,1$1,2$2,1$2,2$3,1|
|dosNo=1$1$2$2$3|
```
この場合、読み込むファイルが「dos.txt」なら
1譜面目：「dos.txt」の1譜面目
2譜面目：「dos.txt」の2譜面目
3譜面目：「dos2.txt」の1譜面目
4譜面目：「dos2.txt」の2譜面目
5譜面目：「dos3.txt」の1譜面目
となります。
ただし、difDataについてはこれまで通り1ファイル目（上記ならdos.txt）に書く必要があります。
また、「externalDosDivide」「externalDosLock」がどちらも有効（true）で無いと「dosNo」は動作しません。
```html
<input type="hidden" name="externalDosDivide" id="externalDosDivide" value="true">
<input type="hidden" name="externalDosLock" id="externalDosLock" value="true">
```
1. …
=> feat: [0770] 譜面番号固定時に他の譜面ファイル番号や譜面番号を参照できる機能を追加

js/danoni_main.js, js/lib/danoni_constants.js
1. キー別フィルターのスクロール範囲を変更しました。
「RANDOM」「ALL」ボタンの位置を固定にし、キー別フィルターの部分を可変スクロールにしています。
1. キー別フィルターが増えたときに、RANDOMボタンやALLボタンを押すためにスクロールが必要なため。
=> improve: [0771] キー別フィルターのスクロール範囲を変更

js/danoni_main.js
1. キー別フィルター、譜面リストのカーソル位置を画面縦長に合わせて調整しました。
下記の計算式に沿って表示するように変えています。
- 選択中の位置+500px縦幅のときの中央値×
(今回の縦幅時のdiv要素の高さ / 500px縦幅時のdiv要素の高さ)
1. それぞれ、画面の縦長に合わせたカーソル位置になっていなかったため。
=> improve: [0772] キー別フィルター、譜面リストのカーソル位置調整

js/danoni_main.js, js/lib/danoni_constants.js
1. デフォルトのタイトル矢印について、ImgTypeの変更によらず初期値を表示するようにしました。
1. デフォルトのタイトル矢印をデザインとして使っている場合、ImgTypeを変更すると意図と外れてしまうため。
=> improve: [0773] デフォルトのタイトル矢印がImgTypeによらず初期値を表示されるよう変更

js/danoni_main.js
1. タイトル矢印の回転・種別を自由に決められるよう変更しました。
コロン(`:`)区切りでImgType、矢印の回転量を指定する。
デフォルトは`Original`、180度。
```
|titleArrowName=classic:90|
```
1. タイトル矢印の種類を変更する方法がこれまで無かったため。
- ImgTypeはローカルファイルの場合は強制的に`Original`のみとなります。（従来通り）
=> feat: [0774] タイトル矢印の回転・種別を自由に決められるよう変更

js/danoni_main.js
1. 背景矢印でカラーコードを0x始まりにしたときにアルファが適用されない問題を修正しました。
1. Discordでの指摘より。意図しないカラーコードになっていたため。
- 発生起因バージョンは ver33.5.0 ( PR #1551 )です。
forEach処理でまとめた際に変更前のカラーコードを参照していたために起こりました。
=> fix: [0776] 背景矢印でカラーコードを0x始まりにしたときにアルファが適用されない問題を修正

SECURITY.md, js/danoni_main.js, package.json
=> [ver34.7.1] 背景矢印でカラーコードを0x始まりにしたときにアルファが適用されない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js, js/template/danoni_setting.js
- 表記上の速度は1x～10xですが、同じ1xでもウィンドウサイズ(高さ)とステップゾーン位置によって1フレームあたりに進む速度が変わるようになります。
- 言い換えると、同じ1xであればウィンドウサイズやステップゾーン位置が変わっても
矢印の可視時間が同じになるように調整されます。
- Appearanceのオプションには依存しません。
- playingHeight, windowHeight, stepY, stepYRという可視範囲の初期値を変えるような場合にのみ、上記ルールが適用されます。
- 基準速度 = (ウィンドウサイズやステップゾーン位置を加味した矢印の移動距離) / (高さ:500px、ステップゾーン位置が標準のときの移動距離)
```javascript
obj.baseSpeed = 1 + ((g_posObj.distY - (g_posObj.stepY - C_STEP_Y) * 2) / (500 - C_STEP_Y) - 1) * 0.85;
```
- Hidden+ : `矢印の移動距離 × (100% - フィルタ位置[%] )` と `矢印の移動距離 - ステップゾーン位置` のどちらか大きい方
- Sudden+ : `矢印の移動距離 × (100% - フィルタ位置[%] ) - ステップゾーン位置`
- Hid&Sud+ : `(Sudden+の可視範囲) - (矢印の移動距離 - ステップゾーン位置 - Hidden+の可視範囲)`
- 合わせて、意図して変更できないようにする設定も追加しています。
- 譜面ヘッダーと共通設定は下記の通りです。どちらもデフォルトは`false`(高さ変更不可)です。
```
|heightVariable=false|
```
```javascript …
```
=> feat: [0775] ウィンドウサイズとステップゾーン位置により基準速度を変更

js/danoni_main.js
1. keyGroupOrder（キーグループの表示制御）をカスタムキーの1項目として追加しました。
譜面ヘッダー側と併用した場合は、譜面ヘッダーの方が優先されます。
＜利用例＞
- デフォルトのキーグループが`0`に割り当てされることを利用して、
部分キーグループを1～4に割り当て、キーコンフィグ上は1～4のグループのみを表示する例です。
```
|keyCtrl25=D2,D3,D4,D7,D8,D9,W,E,R,U,I,O,7_0,Z,X,C,M,Comma,Period|
|chara25=aleft,aleftdia,adown,aup,arightdia,aright,bleft,bleftdia,bdown,bup,brightdia,bright,7_0,cleft,cleftdia,cdown,cup,crightdia,cright|
|color25=4,4,4,4,4,4,3,3,3,3,3,3,0,0,0,2,0,0,0,1,1,1,1,1,1|
|stepRtn25=0,-45,-90,90,135,180,0,-45,-90,90,135,180,7_0_0,0,-45,-90,90,135,180|
|pos25=0,1,2,4,5,6,0.01,1.01,2.01,4.01,5.01,6.01,0.02,1.02,2.02,3.02,4.02,5.02,6.02,0.03,1.03,2.03,4.03,5.03,6.03|
|keyGroup25=0/1,0/1,0/1,0/1,0/1,0/1,0/2,0/2,0/2,0/2,0/2,0/2,0/3,0/3,0/3,0/1/2/3/4,0/3,0/3,0/3,0/4,0/4,0/4,0/4,0/4,0/4|
|keyGroupOrder25=1,2,3,4|
```
2. …
=> feat: [0777] keyGroupOrderをカスタムキーの1項目として追加　他

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js, package.json
- #1616 
- ver35.2.0 ( #1614 )の変更も含みます。
=> [ver35.2.1] posXの略記記法について下段記法にも対応　他

js/danoni_main.js
1. カスタムキーの略記指定の組み合わせに対応しました。
PR #1614 の拡張です。**posX**だけ、**keyCtrlX**だけという制約が無くなり、単一選択を除くほぼすべての設定で略記指定が使えるようになります。
<pre>
|keyGroup25=0/1,0/1,0/1,0/1,0/1,0/1,0/2,0/2,0/2,0/2,0/2,0/2,0/3,0/3,0/3,0/1/2/3/4,0/3,0/3,0/3,0/4,0/4,0/4,0/4,0/4,0/4|
-> |keyGroup25=0/1<b>@:6</b>,0/2<b>@:6</b>,0/3<b>@:3</b>,0/1/2/3/4,0/3<b>@:3</b>,0/4<b>@:6</b>|
(0/1の組み合わせが6回、0/2の組み合わせが6回、...)
|scroll18=Flat::1,1,1,1,1,1,1,1,1,-,-,-,-,-,-,-,-,-|
-> |scroll18=Flat::1<b>@:9</b>,-<b>@:9</b>|
|color9n=0,1,2,3,0,1,2,3,4|
-> |color9n=<b>0...3@:2</b>,4|
|pos20=0,1,2,3,5,6,7,8,10,11,12,13,14,15,16,17,18,19,20,21|
-> |pos20=<b>0...3</b>,<b>5...8</b>,<b>10...21</b>|
-> |pos20=0...3,5...8,<b>10...13</b>,<b>b0...+11</b>|
|stepRtnXX=onigiri,onigiri,onigiri|
-> |stepRtnXX=onigiri<b>@:3</b>| …
=> feat: [0780] カスタムキーの略記指定の組み合わせに対応

js/danoni_main.js, js/lib/danoni_constants.js
1. **charaX**におけるカスタムキーパターン略記を拡張しました。
部分キー定義だけでなく標準実装キー、既存定義キーにも使えるようになり、拡張性が上がりました。
- `|charaX=a>7_0|` -> `|charaX=aleft,aleftdia,adown,aspace,aup,arightdia,aright|`
- `|charaX=b>5_0|` -> `|charaX=bleft,bdown,bup,bright,bspace|`
- `|charaX=c>4A|` -> `|charaX=cleft,cdown,cup,cright|`
1. カスタムキー定義の簡潔な記述ができるようにすることで利用しやすくするため。
- 従来の部分キー定義の拡張記法 `4A_a`, `3S_b` は、`a>4A`, `b>3S`に置き換え可能なため、
ver36以降は廃止することを予定しています。
- `g_keyObj.ptChara7`は、今回の変更で`7_0`や`a>7_0`に置き換え可能なため、ver36以降は廃止する予定です。
=> feat: [0782] カスタムキーパターン略記の拡張

js/danoni_main.js
1. 環境によりタイトルの背景矢印が表示されない問題を修正しました。
1. 発生条件はわかっていないですが、404ページを別に用意している場合で
矢印種類がOriginalの場合だけ発生する可能性があります。
`(ドメイン名)/danoni/img//arrow.svg` のように、矢印種類がOriginalの場合だけ
パスに二重スラッシュが入るようになっていました。
この部分だけ他と実装方法が違うため、実装方法を合わせた形です。
=> fix: [0784] 環境によりタイトルの背景矢印が表示されない問題を修正

js/danoni_main.js
- フリーズの終点と次のフリーズの始点が近いとき、キーを押しても次のフリーズが判定されないことがあるバグを修正
フリーズAの終点と次のフリーズBの始点が近いとき、
Aを見逃しイクナイで判定するとBの始点でキーを押しても反応しないというバグが報告される https://github.com/cwtickle/danoniplus/issues/1529
（途中離しイクナイなら反応し、早押しイクナイは実質的に見逃しイクナイと同等の処理になるので反応しない）
↓
https://github.com/cwtickle/danoniplus/pull/1530 にて修正される
↓
Speedの速さなどにより、Bが作成済みか否かで現象が分岐するようになる
1. Bが作成済みのとき、Aが削除されるので反応する
2. Bが未作成のとき、Aが削除されないので反応しない
おそらく1の条件のみをチェックしたのでプルリクが取り込まれてしまった
↓
Aを削除するのではなく、judgeArrow にて判定を次のフリーズに移すことで対応しました
=> フリーズアローの判定処理を修正

js/lib/danoni_constants.js
1. カスタムキー定義のkeyGroupOrderがコピーされない問題を修正しました。
1. 本来表示したくないキーグループが表示されない場合があります。
なお、この事象はカスタムキー定義の`keyGroupOrderX`のみで発生し、
譜面ヘッダーの`keyGroupOrder`は問題なく動作します。
- v35.1.0以降で発生します。
=> fix: [0786] カスタムキー定義のkeyGroupOrderがコピーされない問題を修正

js/lib/danoni_constants.js
1. カスタムキー定義のflatModeXのローカル保存後、その情報が取り出せない問題を修正しました。
1. PR #1630 関連。修正漏れです。
- ver35.4.1以降で発生します。
=> fix: [0787] カスタムキー定義のflatModeXのローカル保存後、その情報が取り出せない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
1. 横幅が900pxを超えるときに伸縮するボタンを固定化するよう変更しました。
900px以下の場合は従来のレイアウトと変わりません。
現状カスタムキー以外での最小横幅の最大値が900px（23key）なので、それを基準にしました。
2. キーコンフィグ画面でオブジェクトが画面外になるとき、
キーを押しても画面が見える位置に移動しない問題を修正しました。
3. キーコンフィグ画面で横スクロールが必要な場合に、表示するよう変更しました。
またこれに合わせ、ショートカットキー表示と別キーモードの表示位置を若干上に上げています。
1. 横幅が広い場合、その分ボタンが広がってしまい使い勝手がよくないため。
2. 主にキリズマ・パンパネ限定ですが、デフォルトが中央になってしまうため何に変更しているかがわかりにくい問題が出ていました。ダイレクトに対象オブジェクトを指定したときは画面移動しますが、キーを押したときには画面移動が起こっていませんでした。
⇒ ver30.0.1以降で発生していました。
　 PR #1390 で対応した内容に問題がありました。
　 ver29ではリセット時に中央に戻るものの、問題となるレベルでは無いのでそのままにします。
3. 横スクロールが無いため、どの位置にあるかがわかりにくい問題がありました。
- キーコンフィグ画面のカラーパレット、トランスキー時に使用するKeySwitchボタンの位置は横幅に依存するので、そのままの位置にしています。
- 背景・マスクの位置も従来と変わりません。
- キリズマの場合、オブジェクトの縮小の関係でスクロール位置が若干上になり、
別キーモードの表示が見えないことになりますが、
キリズマで別キーモードを扱う可能性は低いため、そのままにします。
=> feat: [0788] 横幅が900pxを超えるときに伸縮するボタンを固定化するよう変更

js/danoni_main.js, js/lib/danoni_constants.js
1. 色変化仕様を全体的に見直しました。
矢印・フリーズアローの塗りつぶし部分の変化に対応しました。
フリーズアローについて、矢印同様レーン個別の色指定を可能にしました。
- 従来の色変化の方法を踏襲しつつ、複雑になっていたグループ番号の仕様を変更。
- 個別/全体色変化の区別をなくし、色変化の中の1設定として追加。
- 「ncolor_data」として実装することで従来の「color_data」「acolor_data」との互換性を保持する。
- 従来の3つで1セットという区切り方は廃止。改行区切りのみとする。
- フリーズアローのヒット時の個別色変化について、これまで例外的にフレーム数から出現時までの遡りを行わずに、指定したフレーム数で変わるようにしていましたが、その例外処置を止めました。
- 従来のcolor_data/acolor_dataでこの変更をそのまま適用すると影響が出るため、
フリーズアローのヒット時の色が個別色変化（color_data）として指定された場合、
全体色変化（acolor_data）扱いとなるよう処理を変更しています。
この設定を解除する場合は、|colorDataType=v6|を設定すれば`ncolor_data`と同じ扱いになります。
- `フレーム数,矢印番号:色変化対象,カラーコードor色名,即時適用フラグ`
- 左上を0として数えた場合の矢印位置。カスタムキー定義で言うところの**posX**に当たる。
- スラッシュ区切りで複数指定が可能。例：`0/2/4/6`
また連続した範囲であれば`0...7`のように`...`を入れれば0～7までが自動適用される。
- 従来のグループ（20～24）は、g0, g1, g2, g3, g4にそれぞれ対応する。
フリーズアローについてもg0～g4でグループ指定が可能。 …
=> feat: [0789] 色変化仕様を見直し、フリーズアローの塗りつぶし部分の変化に対応

js/danoni_main.js
1. 歌詞・背景・マスクデータのタブや前後の半角スペースを自動除去するよう変更しました。
2. 上記の実装に合わせて、新仕様の色変化についても同様の実装を行いました。
1. 歌詞・背景・マスクデータは項目が多くタブや半角スペースを入れた方が見やすいことがあるため。
2. コード実装の統一化によるものです。機能変更はありません。
=> feat: [0790] 歌詞・背景・マスクデータのタブや前後の半角スペースを自動除去するよう変更

js/danoni_main.js, js/lib/danoni_constants.js
1. 譜面別のハイスコア削除機能を実装しました。
1. 現状は全消去しかなく、個別に削除したい場合に対応できていないため。
=> feat: [0795] 譜面別のハイスコア削除機能を実装

js/danoni_main.js
1. 矢印がゼロのときに結果画面でエラーになる問題を修正しました。
1. ハイスコア表示追加に伴うクリアランプ点灯条件で、Accuracyが`----`であることを除外していましたが、
プレイ画面突入時に`g_resultObj`配下のプロパティを全て0に初期化していたため、
この条件に合致しない問題が出ていました。
これにより、Practiceのクリアランプを除外しているつもりでも、うまく除外できていませんでした。
=> fix: [0796] Accuracyが計算外のときに結果画面でエラーになることがある問題を修正

js/lib/danoni_constants.js
1. ncolor_dataの対象「all」についてグループ指定を最大50個まで拡張しました。
1. PR #1650 にてカラーグループ数を拡張しましたが、ncolor_dataの対象「all」について拡張できていなかったため。
=> improve: [0799] ncolor_dataの対象「all」についてグループ指定を最大50個まで拡張

js/danoni_main.js
1.  空押し設定（Excessive）が変更不可かつ有効のときに設定画面にその旨を表示するよう変更しました。
1. この場合、設定画面上は空押し設定が有効かどうかが判断できないため。
=> feat: [0801] 空押し設定が変更不可かつ有効のときに設定画面にその旨を表示するよう変更

css/danoni_main.css, js/danoni_main.js, js/lib/danoni_constants.js, skin/danoni_skin_default.css, skin/danoni_skin_light.css, skin/danoni_skin_skyblue.css
1. 設定画面の各項目のオンマウスで下線が出るよう変更しました。
2. 譜面明細画面の各ボタンのオンマウス説明文を追加しました。
3. 譜面明細画面と譜面選択リストの組み合わせにより、ウィンドウの端が見えてしまう問題を修正しました。
1. オンマウス説明文がどこに対するものかがわかりにくいため。
2. 譜面明細ボタン毎のオンマウス説明文がこれまで無く、タイトルだけではわかりにくい場合があるため。
3. レイアウトの調整です。譜面明細画面のレイアウトを拡張したことで位置ズレが出ていたので見直しました。
- レイアウトの調整はありますが、実処理には影響しない範囲だと思います。
- ColorGroup, ShuffleGroup, StepRtnGroupのCSSクラスを分離しました。
- スキンCSSファイルはテンプレートの更新だけで、更新は必須ではありません。
=> improve: [0802] 譜面明細画面の各ボタンのオンマウス説明文追加　他

js/danoni_main.js
1. 色変化、歌詞表示、背景・マスクモーションにおけるトリム処理において、
全角空白や改行など本来不要なトリムまで行われている問題を修正しました。
1. トリムを行う際にtrimStart/trimEndを使っていましたが、適用範囲に認識違いがありました。
このため、単純にタブと前後の半角スペースだけ取るように関数を見直しました。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/trim
- #1638, #1639 関連です。過去バージョンには影響ありません。
=> fix: [0806] 不要な文字までトリムしてしまう問題を修正

js/danoni_main.js
1. 背景・マスクで深度が空のときに[loop][jump]コマンドがスキップされる問題を修正しました。- 
1. hasVal関数の拡張時に #1650 にてコード整理をしたときの影響漏れです。
- 従来と同じ書き方ではなく、深度が空のときは`[loop]`もしくは`[jump]`のキーワードが入っていることをチェックするようにしました。
=> fix: [0807] 背景・マスクで深度が空のときに[loop][jump]コマンドがスキップされる問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
現行のShuffleオプションに、S-Random/S-Random+と同じく矢印個別にシャッフルするものの、
縦連打が発生しにくいオプションを追加しました。
散らばりの条件は現状次のようにしています。
- フリーズアローの始端/終端から前後10フレームは同じレーンの矢印・フリーズアローを配置しない
- 矢印の前後10フレームは同じレーンの矢印を配置しない
- 直前にいる矢印と同じレーンに矢印を配置しない
- 上記が破綻する場合は、S-Randomと同じルールで配置する
全押し中にフリーズアローがいた場合、S-Randomロード中にエラーで止まる問題を修正しました。
1. キーによって運指が大きく異なるので、運指練習としてS-Randomを緩和したオプションが必要と感じたため。
2. 通常存在しえないですが、代替キーを想定した譜面やプレイングが実際にあるので、念のため対策しました。
通常のS-Randomでは、フリーズアロー位置と重ならないように矢印を配置しますが、
上記が発生した場合に限り、重なりを無視して配置します。
=> feat: [0808] 矢印・フリーズアローが散らばるS-Randomの設定を追加

js/danoni_main.js, js/lib/danoni_constants.js
- シャッフルグループ数の上限を`（対応キー - 1）`になるように修正しました。
- 7keyであれば6、12keyであれば11が上限となります。
- キーコンフィグ画面右上の `ShuffleGr: 1` と同じシャッフルグループで無い場合、
Mirror/X-Mirrorのハイスコアを更新しないよう変更しました。
- 更新条件に合致しない Mirror / X-Mirror 譜面の場合、プレイ開始時にメッセージが表示されるようになります。
- キーコンフィグ画面右上の `ShuffleGr: 1` と同じシャッフルグループで無い場合、
譜面名のシャッフル名に`(S)`を付加するようにしました。
OFF/Random+/S-Random+/Scatter+のようにグループに関係のないシャッフルの場合は付加されません。
1. 対応キー数を超えて設定を可能にすると、正規と同じ譜面をミラーとしてプレイ可能となってしまうため。
最低でも1組は2キー以上属するように変更しています。
※対応キーの半分まで、といった閾値も考えましたが多様性を考慮して正規と合致しない上限としました。
2. 1.関連ですが、これを許してしまうと何の譜面に対するハイスコアかが特定できなくなるため。
3. 2.関連の修正です。これを適用すると`ShuffleGr: 2, 3`の場合も`(S)`が表示されますが、
あえて区別する必要性が薄いため今回は一律同じ記号にしました。
- (S) は (Self) の略名です。
=> improve: [0810] シャッフルグループ数の上限を見直し、ミラー譜面のハイスコア保存条件を変更

js/danoni_main.js
- キー数変化 (keych_data) を機能拡張し、スラッシュ区切りで
複数の部分キーを指定できるようにしました。
さらに、コロン(`:`)区切りでその部分キーの透明度（アルファ）が指定できるようになります。
透明度は０～１の間で指定し、１が完全に見える状態、０が全く見えない状態です。
```
|keych_data=
0,11L                            // 11Lkey: 100％
200,11:0.3/11L                   // 11key: 30%、11Lkey: 100％
3000,11/11L:0.3                  // 11key: 100%、11Lkey: 30％
|
```
- 後ろに指定した方が手前に来るので、アルファが小さいものを先に指定する必要があります。
- `keych_data`で指定する部分キー名は、カスタムキーの定義`keyGroupX`で指定する名前です。
difDataで指定するキー名と同じとは限りません。
- `keych_data`はステップゾーンの表示・非表示を切り替える機能です。
その部分キーを指定したからと言って、部分キー以外の矢印・フリーズアローが使えなくなるわけではありません。
```
|keyGroupX=11L/11,11L/11,...|
```
- 部分キー指定箇所が複雑になるので、背景・マスクモーションと同じ仕様としました。
1. キー数変化演出で、アルファを徐々に掛けていく方法がこれまで無く、
背景・マスクモーションを駆使する必要があったため。
2. 上記で記述の通りです。
- この例では5keyを透明度30%で表示させています。
https://github.com/cwtickle/danoniplus/wiki/keys
=> feat: [0813] キー数変化で同時に複数のキーを共存させる機能を実装

js/danoni_main.js
- 歌詞表示ではリバース有効時、改行が無い場合に限りword_dataを記載すれば自動反転する機能がありました。
- しかし、ver30以降のコード整理により、それが機能していませんでした。その問題を修正しています。
- 具体的には、下記の条件で判断します。
- 歌詞表示に改行などが含まれていないこと
- 11keyのような上下スクロールがデフォルトのキーで無いこと
- 拡張スクロールがデフォルトであること　※追加
- パターンを優先度順に並べて最初にヒットした名前がリバース系の歌詞表示で無いこと　※追加
https://discord.com/channels/698460971231870977/944491021918683196/1252669246207557652
起因となるPRは #1393 (ver30.0.0)です。
元々はwordRev_dataがいればその値を優先し、word_dataのみであれば自動反転するという処理でしたが、機能拡張してコード整理した結果、機能しなくなっていました。
- word2_dataなども同様に自動反転の対象とする必要があるので、追加で修正予定です。
⇒修正しました。検索して最初にヒットした対象がリバース系（wordRev_data）では無かった場合に限り適用するように変更しました。
- 今回の問題に直接影響はないものの、背景・マスクでも同様の処理があるので後で見直しをする予定です。
=> fix: [0816] Reverseのときに歌詞表示の自動反転が効かない問題を修正

js/danoni_main.js
- ダミーフリーズアロー生成時に、フリーズアローの通常色の値が指定できずにエラーが発生していました。この問題を修正しています。
```
|difData=9A,Normal|frzLeft_data=200,300|
```
- ダミーフリーズアローでは開始矢印の塗りつぶし部分を表示したままにしますが、それが消えてしまっていました。
- スキンがデフォルトのとき、ダミーフリーズアローでは矢印の塗りつぶし色は黒ですが、矢印の枠色と同じ灰色が適用されていました。
https://discord.com/channels/698460971231870977/944491021918683196/1252996678634438686
PR #1638 (ver36.0.0) でのコード間違いによるものです。
2. PR #1438 (ver31.0.0) にてHitPosition実装時に開始位置を補正する処理を省略してopacity=0を掛けたことが原因です。また位置補正はフリーズアロー失敗時しか考慮できていなかったため、成功時も考慮するように変更しました。
3. PR #1638 (ver36.0.0) にてフリーズアローの塗りつぶし色のデフォルト値に矢印の枠色と同じデフォルト色を与えてしまったことが原因です。塗りつぶし色の場合は未指定（空）を与えるように変更しています。
=> fix: [0817] ダミーフリーズアロー生成時に画面が止まってしまう問題を修正　他

js/danoni_main.js
- ReverseのときにwordRev_data時でも歌詞表示の自動反転が起きてしまうようになっていました。
1. PR #1679 の考慮漏れです。
「パターンを優先度順に並べて最初にヒットした名前がリバース系の歌詞表示で無いこと」の条件部分においてループを途中で切る処理が抜けており、上記事象が発生しました。
- この時点でv34の修正には反映済みです。
=> fix: [0818] ReverseのときにwordRev_data時でも歌詞表示の自動反転が起きてしまう問題を修正

js/lib/danoni_constants.js
- Hidden+/Sudden+/Hid&Sud+のときに表示される「Lock」ボタンにショートカットキー「L」を割り当てました。
1. Resolves #1683
=> feat: [0819] Appearance設定のLockボタンにショートカットキーを割り当て

js/danoni_main.js, js/lib/danoni_constants.js
- playbackRateが1以上の場合はAdjustmentの間隔を狭く、未満の場合は広くなるように自動調整します。
- 調整後のAdjustmentはplaybackRate＝1以外の場合、画面上に表示されます。
- 小数Adjustmentが使えない環境の場合は、整数への丸め処理を行います。 
- 曲名の横に表示するように変更しています。
- 本来の内容とは別扱いのため、ハイスコアを保存しないようにしました。
- 設定ボタンの制御関数（setSetting）の引数にオブジェクト引数を追加し、
その中で後続関数を指定できるようにしました。
- 合わせて、`createGeneralSetting` の全てのボタンに対して拡張関数（addRFunc, addLFunc）を適用するよう変更しました。
1. 頻度はそれほど多くないですが、低速再生したいときにAdjustmentにズレがあると再生倍速ごとにAdjustmentを調整し直す必要がありました。
2. playbackRateの値が画面上のどこにも表示されないため。
設定の変更というより、楽曲が変わっているため楽曲のカスタマイズという扱いにしています。
3. 上述の通りです。
4. 同じ内容の繰り返し記述を避けるため。
=> feat: [0821] playbackRateの値に合わせてAdjustmentの設定幅を伸縮するよう変更

css/danoni_main.css, js/danoni_main.js
- v36.1.0以降にベンダープレフィックスの設定（mask, background-clip）を外しましたが、
古いOSの場合、ブラウザの更新ができないことがあり、プレイに支障が出ることがありました。
1. 上述の通りです。PR #1641 の内容を元に戻します。
ただ、画像読込（preload）についてはFirefox 85以降（2021年1月）でも対応済みのためそのままとします。
- v36以降で同様の修正が必要です。
=> fix: [0822] ベンダープレフィックスの設定を元に戻す

js/danoni_main.js
- 譜面で指定した矢印・フリーズアローのフレーム数について、内部的に逆算して生成フレーム数を算出しています。
具体的には、ステップゾーン位置から速度を逆算して、画面外に出たときまでを到達フレーム数として計算しています。画面外に出た位置が画面枠を超える場合は、その差分だけY座標をずらしてスタートさせる方式です。
- この生成フレーム数について、急激に減速させた場合に譜面で指定した矢印・フリーズアローのフレーム数が異なる場合でも逆算した結果同じフレーム数になってしまうことがあり、この場合にこれまで対応できていませんでした。
- 今回の変更で、こういった場合でも区別して表示できるようにしました。
https://discord.com/channels/698460971231870977/944491021918683196/1258466625632342100
- 現状、生成フレームが同一フレームでY座標違いの場合、個別加速・個別色変化・矢印／フリーズアローモーション・スクロール方向変更は区別されません。
（＝逆算した結果、生成フレームが同一フレームとなってしまう区間に対して、個別加速等を区別することはできません）
上記対応の修正影響が大きいため、今回は見送る予定です。
- 同時表示するには、Y座標・移動フレーム数といった追加情報が要るため、
今回の対応でそれを矢印個別に保持するように変更しました。
- また、移動フレーム数が短い順に並んでいないと判定時にエラーになるため、
生成データを作成するのと合わせて挿入順の処理も追加しています。
```javascript
// 200フレーム時に矢印0, 矢印1を出現
g_workObj.mkArrow[415] = [0, 1];
```
```javascript
// …
```
=> feat: [0823] 同一フレームでY座標違いの場合でも矢印・フリーズアローを生成できるよう対応

js/danoni_main.js
- フリーズアローは本来2つ1セットのため、データ数が奇数の場合は譜面が成立しませんが、
対になっていない最終のフリーズアロー始端を除去することでプレイに支障が出ないようにしました。
- 単純に最後のデータを無効化します。途中に矢印が存在するかどうかは見ません。
- 無効化したフリーズアローはカウントしないように修正しました。
- レーン別フリーズアロー数は対が無いかどうかがわかるように、小数まで表示し色付けしました。
- なお、ツール値については元から対が無いフリーズアローは対象にしていない仕様になっています。
- フリーズアロー数が小数のため、AP時でも数が合わずAP表示がされない状況でした。
1. Discordでの話題より派生。
https://discord.com/channels/698460971231870977/1195445736851124254/1259339629220466698
2. 従来の表示方法では無効化分も含まれており、紛らわしいため。
3. 1.を対応することで新たに生じた問題のため。
=> improve: [0824] フリーズアローの終端がいない場合に末尾のフリーズアロー始端を自動除去する仕様に変更

js/danoni_main.js
- 以前、PR #1714 で修正して直しましたが、同じ条件で問題が発生したため再度修正しました。
1. replaceStr関数を PR #1717 で修正しましたが、文字列をStringに変換していたためundefinedが文字列化され想定外の動きになっていました。undefined時はそのままの値を戻すよう変更しています。
=> fix: [0846] 色変化（ncolor_data）で矢印種類を省略したときに色変化対象が正しく反映されない問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
- 矢印・フリーズアローが流れる反対側から出現し、画面中央で折り返してステップゾーンへ向かうモーションオプション（Fountain）を追加しました。
- 速度により矢印・フリーズアローが表示するフレーム数が異なるため、折り返しするフレームを動的に買えるようにしています。
1. 矢印・フリーズアローモーションでは実現しにくいオプションとしてプレイの選択肢を増やすため。
- 速度変化による影響は少ないと考えています。
- 数式については改良の余地があるかもしれません。
=> feat: [0848] MotionオプションにFountainを追加

js/lib/danoni_constants.js
- 矢印が元の速度から徐々に減少しながらステップゾーンへ近づくオプション（Compress）を追加しました。
- 従来のBrakeは元の速度から加速した状態で進み、最終的に元の速度に戻るため意味が異なります。
1. プレイの選択肢を増やすため。
以前、PRで出したことがありますが速度変化で0.5倍がかかると逆走する問題がありました。
逆走の幅を緩和したので、0.375倍までは逆走しないようになっています。
- Fountainなど他のモーションと同様、矢印の出現時間は変わらないため途中から出現します。
=> feat: [0849] MotionオプションにCompressを追加

js/danoni_main.js
- Fountainオプション適用時、全体変速が1倍未満・個別加速が1倍以上が掛かっているとき、
モーションの適用範囲が全体変速１倍を基準としているため個別加速で矢印表示範囲が引き延ばされると
余計な部分が見えてしまい、視認性が悪くなることがありました。これを改善しています。
- 具体的には、200フレーム分のモーションを固定で設定するように変更しました。
1. 上述の通りです。PR #1729 関連。
=> fix: [0850] Fountainで全体変速が1倍未満、個別加速が1倍以上のときにモーションが見づらくなる問題を修正

js/danoni_main.js
- 加算するモーションフレーム数の計算方法に誤りがあり、1フレーム分が反映されていませんでした。
- Boost、Brakeについてはモーション適用範囲が狭かったため影響はほぼありませんでしたが、
最近追加したFountainについては直近の変更 #1732 により、出現部分ギリギリまでフレーム加算があるため問題が表面化しました。
1. PR #1732 の考慮漏れです。
過去バージョンにFountainオプションは存在しないため影響はないと思いますが、
同じ処理を使っているため一応修正は必要と考えます。
=> fix: [0851] 加算するモーションフレーム数の計算方法の誤りを修正

js/danoni_main.js
- Shuffleオプションの1つである、「Scatter」「Scatter+」について、
同時押しが続いた時の矢印のシャッフル方法を見直しました。
- 具体的には、直前の矢印が重ならないように配置するのはフレームが変わった最初の矢印だけで、
同時押しの対の矢印については従来のS-Randomと同じ処理にしました。
1. 4keyを従来の「Scatter」でシャッフルした場合、同時押しが連続すると単調な配置になってしまうため。
また、本来の目的としては単発矢印に対して散らばっていれば良いため。
=> feat: [0852] Scatterオプションのシャッフル方法を一部見直し

js/danoni_main.js
- 従来の色変化(color_data / acolor_data)では、キーパターンごとに同じ矢印でも矢印番号が異なるため、convertReplaceNums関数を使って割当先のコンバートを行っていました。
- 従来の色変化では矢印単発と矢印グループで処理分岐しており、矢印グループ時はconvertReplaceNums関数で生成した g_workObj.replaceNums によりコンバートが行われないように処理されていましたが、色変化(ncolor_data)では矢印単発・グループに関係なくコンバートが掛かるようになっていたため、矢印グループ時に想定しない色変化になっていました。
- setColor2Dataで行っていた箇所を、convertReplaceNums関数を通しても問題が無いように修正することで解消しています。
- ver36以降で発生していると思われます。
=> fix: [0853] 色変化(ncolor_data)でキーパターンを変えると適用する矢印グループが想定と異なる問題を修正

js/danoni_main.js
- PR #1738 にて当初の問題は修正しましたが、別キーモードにしか存在しないレーンに矢印がいた場合、
その矢印が属する矢印グループを適用した際に色が変わらない問題がありました。
- 従来関数同様、pushColors内で矢印グループを扱う方法に変更しました。
1. 直接的な問題ではないですが、従来の色変化では対応しているため。
- 過去バージョンに影響しますが、変更箇所が多いのでv36～37への適用は見送ります。
=> fix: [0854] 色変化(ncolor_data)で別キーモードにしか存在しないレーンを含む矢印グループ指定ができるよう修正

js/danoni_main.js, js/lib/danoni_constants.js
- キーコンフィグ画面より、プレイ中ショートカットキーの変更をできるようにしました。
プレイ中ショートカットキーが表示されているエリアがボタンに代わり、そこをクリックしてから
キーを押すことで割り当てキーを変えることができます。
- ローカルストレージには未対応です。
- キーブロックの関係でEscapeキーが実質無効になっているため、例外的に「IME」（全角/半角）を設定可能にしました。
1. 作品により、プレイ中ショートカットを変えたい場合があるため。
- 現状、ショートカットキーを変更すると右下にショートカットキーを表示する機能があり、それが動いてしまっています。カスタムJSによりスコア等を表示しているため、どう対応するか考える必要があります。
⇒ danoni_setting.js の scAreaWidth, playingLayoutの設定で可能だがデフォルトは未設定。
⇒ scAreaWidth、scAreaの両方が未指定の時は、プレイ側が割当を変えてもプレイ画面には反映しないようにしました。
- カーソルがキーコンフィグのオブジェクト上にいるため、スクロールが発生する場合カーソルも合わせて移動してしまいますが、それを実際の位置に合わせて追従させるのは容易ではないため、この実装は見送る方向にします。
- Mac環境の場合はリトライとタイトルバックがセットになっているため、
変更できるのはリトライキーに限定されます（リトライキーに応じて、タイトルバックキーも変わります）。
=> feat: [0855] プレイ中ショートカットの変更に対応

SECURITY.md, js/danoni_main.js, js/lib/danoni_constants.js, package.json
- #1779 
- リリースが詰まっているので、ver39.7.1とマージします。
#1777 もご覧ください。
=> [ver39.7.2] Data Management画面のJSON表示でカスタムキーの場合に色データが上下両方に出てしまう問題を修正

js/danoni_main.js
- g_scoreObjの不要なプロパティを動的に削除するようにしました。
後でデバッグで確認したいプロパティは残しています。
1. デバッグでも不要なプロパティを保持しているため。
=> refactor: [0918] 不要プロパティの整理

danoni/danoni0.html, js/danoni_main.js, js/lib/danoni_constants.js
- タイトル画面上に選曲機能を実装しました。
- `|packageName=パッケージ名|`を指定することで、タイトルの代わりに選曲画面が表示されるようになります。
- デフォルトは最初にパッケージ名が表示された後、選曲画面を表示します。
`customTitleUse`を有効にすれば、最初の表示を非表示にすることもできます。
- 複数の譜面情報から、musicNoで割り当てた楽曲ごとに譜面の対応づけを行い、フィルターします。
- URLクエリに`musicId`(musicNoに対応)を指定することで、ダイレクトにその楽曲を表示します。
- `scoreId`がURLクエリとして渡されたときだけ、単品モードに変わります。
- 選曲機能有効時は、クレジットボタンが作成されません。Click Hereボタンは「>」ボタンに置き換えられます。
- 選曲機能及び、初期表示されるパッケージ名の表示位置は背景とマスクデータの間にいます。タイトル画面の背景・マスクはそのまま使えます。
- musicTitleについて、5番目の項目としてBPM表記を追加しました。
- 4番目は別で使われているため、通常はカンマを2回つけることになります。
```
|musicTitle=
Destiny,Silvia,https://cw7.sakura.ne.jp/rdart/?artistId=11,,120-145
Destiny -Precious memories-,,,,145
JEWELS -more brightness mix-<br>(radio edit),Y.W,https://cw7.sakura.ne.jp/rdart/?artistId=2,,190
R176,Cranky,https://cw7.sakura.ne.jp/rdart/?artistId=1,,190 …
```
=> feat: [0919] 選曲機能を実装

js/danoni_main.js
- 通常モードでdifDataに製作者名が含まれていた場合、
タイトル画面のMaker表記がdifDataの製作者名になることがあります。
その問題を修正しました。
1. PR #1839 の考慮漏れ。
=> fix: [0920] difDataで製作者名を含む場合にタイトル画面のMaker表記が想定と異なることがある問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
- ゲージ設定のAccuracyをオンマウスで許容ミス数が表示されるようになっていましたが、
ソース更新により表示されていませんでした。
- 選曲画面の曲詳細表示部分の高さが、他の情報に重なっている状況が発生していたため、修正しました。
- 特に不具合というわけではありませんが、ボタン等を配置する際に問題となる可能性があり、対応しています。
1. ver39.4.1以降で発生。PR #1762 の考慮漏れです。
2. div要素の重ね合わせの際の支障を取り除くため。
=> fix: [0921] ゲージ設定の許容ミス数が表示されない問題を修正、選曲画面の曲表示部分の高さ修正

js/danoni_main.js
- 譜面ヘッダーのtuning項目を省略したとき、共通設定ファイルの製作者情報を取得する処理があります。
このとき、製作者名は取得できるようになっていますが、URLが対応できていませんでした。
1. PR #1839 の考慮漏れと思われます。
=> fix: [0922] 通常モードで製作者情報が省略されたときにデフォルトの製作者URLが取得できない問題を修正

js/danoni_main.js
- 選曲モードで縦スクロールするときに、ブラウザもスクロールするようになっていました。
画面上のみスクロールブロックするようにしていたつもりでしたが、条件式の中だったため反応していませんでした。
1. PR #1839 の考慮漏れです。
=> fix: [0923] 選曲モード時、選曲スクロールに合わせてブラウザもスクロールする問題を修正

js/danoni_main.js
- 選曲対象の楽曲がオリジナルの派生といった場合、別々でなく1つにまとめたいことがあります。
その際に1つにまとめる機能を実装しました。
- 譜面ヘッダー：musicGroupを使用します。
musicUrlの1つ1つに対して、どの楽曲に集約するかを指定します。
指定方法はmusicNoで指定する番号と同じく、0, 1, 2, ...の順で指定します。
- 下記の例の場合、`0365_Destiny.mp3` と `0365_Destiny_precious.mp3` を1つにまとめます。
```
|musicUrl=
0365_Destiny.mp3
0365_Destiny_precious.mp3
0252_JEWELS_brightness.mp3
0043_R176.mp3
0200_CarelessPrince.mp3
|
|musicGroup=0,0,2,3,4|
```
- 譜面ヘッダー：musicGroupについては相対指定が可能です。
-1, -2などを指定することで現在番号から-1, -2した方に集約するようになります。
また、特に集約しない場合は省略が可能です。
```
|musicGroup=0,-1|
```
- 譜面名を切り替えるごとに、楽曲名やBPMが切り替わるようにしました。
- 選曲モードでない場合も、BPMが変わる場合は切り替わります。
- 楽曲別のコメント欄にスクロールがあるとき、ホイール処理が動かないようにしました。
1. 上述の通りです。
2. 1.の変更に伴い、対応しました。
3. 意図しないホイールを防ぐため。
=> feat: [0924] 選曲モードで複数楽曲を部分的にまとめる機能を実装

js/danoni_main.js, js/lib/danoni_constants.js
- 選曲画面時にBGMを流すようにしました。初期値は50%で、左下のボタンから増減が可能です。
ショートカットキーは左右キーに対応しています。
- 譜面ヘッダー：musicUrlにカンマでつなげて区間設定を行います。既定は0:00-0:20。
```
|musicUrl=
0365_Destiny.mp3,1:12-1:40
0365_Destiny_precious.mp3
0252_JEWELS_brightness.mp3,0:30-0:50
0043_R176.mp3,0:40-0:50
0200_CarelessPrince.mp3,0:20-0:30
0320_TrickStyle.js,0:25-0:35
|
|musicGroup=,-1|
```
- base64エンコードの音源のとき、ロードの関係で再生にやや時間がかかります。
- ランダムの処理の問題で、同一曲が選択されやすくなっていました。
1. 選曲時に、どの音源かをわかりやすくするため。
2. PR #1848 起因と思われます。
=> feat: [0925] 選曲画面時にBGMを流す処理を実装

js/danoni_main.js, js/lib/danoni_constants.js
- 前のPRの状態の場合、上下キーを押しっぱなしにするとBGM再生処理が
同時並行に複数再生されてしまう問題がありました。
- 今回の修正で、次の場合にはBGMを再生しないように変更しています。一周回って同じ曲を指す場合も同様です。
- 500ms以内に別の曲が選択されている場合
- 楽曲読み込み後の再生前に別の曲が選択されている場合
- BGM再生で使うことがあり、途中で不要になることがあることからclose()を実装しました。
1. PR #1850 の考慮漏れのため。
2. レビュー結果を踏まえた内容より。
=> improve: [0926] 選曲画面でキー押しっぱなしにより複数の楽曲が同時に再生されないよう対応

js/danoni_main.js
- 選曲画面のBGMがフェードアウトした直後に設定画面へ移動すると、Uncaught (in promise) NotSupportedError: The element has no supported sources. が出ることがありました。
- Audio.srcを削除することで対応しています。
1. 直接問題にはならないが、エラーとして表示されるため。
=> fix: [0927] BGMフェードイン時にNotSupportedErrorが出ることがある問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
- 選曲画面のBGM音量設定の横にミュート・ミュート解除ボタンを追加しました。
- 「M」キーでも動作します。
- 他のランダムと同様、「R」キーで動作するように変更しました。
1. 音量を出したくないときに手軽にOFFにできるため。
2. 他の機能との整合のため。
=> feat: [0928] ミュート・ミュート解除ボタンを実装、ショートカットキーの追加

js/danoni_main.js
- 設定画面右上に表示している曲名にエスケープ文字（`&quot;`など）がそのまま表示されてしまう問題を修正しました。
1. PR #1839 の考慮漏れです。
=> fix: [0929] 設定画面で表示する曲名のエスケープ文字が残ってしまう問題を修正

js/danoni_main.js
- playBGM関数について、現在の画面位置を見ていなかったためロード中に設定画面に移動してしまうと
その後にBGMが流れる問題が発生していました。この問題を修正しています。
1. PR #1850 の考慮漏れです。
=> fix: [0930] 選曲画面のBGMが設定画面以降に流れてしまうことがある問題を修正

js/danoni_main.js
- サイト共通のローカルストレージ（danoni-locale）に対象を追加し、保存するようにしました。
1. 利便性向上のため。
また、作品別というよりはサイト全体で保存すべき内容のため。
=> improve: [0931] 選曲画面のBGM音量のローカル保存に対応

js/danoni_main.js
- 1つの曲に対して複数譜面があり、それぞれ別々の曲を流す場合にBPMが取得できなくなっていました。
- BPM以外の項目はそれぞれ単一楽曲用の変数があったため対応できていましたが、
BPMは後から足された項目で、その部分の考慮ができていませんでした。
（単一楽曲用の変数は互換のために残している項目であり、本来は不要）
- この部分の処理自体、わかりにくいため処理を見直しています。
- musicNoで定義される最大数とmusicTitleの定義曲数の多い方で定義する曲数を決定する方式としました。
1. PR #1839 の考慮漏れ。
- v41.0.0以降でのみ発生する問題です。
- 処理的にはv40以前のものも直した方が良いですが、動作上の問題はないのでそのままとします。
=> fix: [0932] 楽曲情報（musicTitle）の定義数より大きいmusicNoを定義した場合に、BPMが取得できない問題を修正

SECURITY.md, js/danoni_main.js, package.json
=> [ver41.3.1] 楽曲情報（musicTitle）の定義数より大きいmusicNoを定義した場合に、BPMが取得できない問題を修正

js/danoni_main.js
- 1つの曲に対して複数譜面がある場合に処理が止まる問題を修正しました。
1. PR #1860 の考慮漏れです。
=> fix: [0933] 楽曲情報（musicTitle）で定義している以上のmusicNoを指定したときに処理が止まる問題を修正

js/danoni_main.js
- これまで、danoni_main.jsに付随して読み込まれるjsファイルおよびcssファイルについては
読込ごとに既存のキャッシュを使わないようにしていました。
- ただ、同じバージョンと判断できる場合やドメインがCDNといった場合はキャッシュを使っても支障がないため、
今回の変更でこのような場合にキャッシュを使えるように変更しています。
- これまで、URLに「`?`+ 現在日付を使った文字列」で読み込んでいた部分が、
同じバージョンと判断できる場合やドメインがCDNといった場合に「`?`+ バージョン名」に変わります。
- danoni_localbinary.jsについては基本変更がないため、キャッシュクリアの対策自体削除しました。
- legacy_functions.jsについてはメジャーバージョンアップ時以外の変更はないため、
「`?`+ メジャーバージョン名」としています。
1. 毎回ファイルを読み込み直すことで、ロードに時間が掛かるため。
なお、画像ファイルについてはもともとキャッシュを許可しています。
=> improve: [0934] 必要以上にキャッシュクリアを行わないよう処理を見直し

js/danoni_main.js, js/lib/danoni_constants.js, js/lib/legacy_functions.js
- フォントサイズ取得関数として、getFontSize2関数を作成しました。
従来のgetFontSize関数の置き換え版です。getFontSize関数はlegacy_functions.jsへ移動しています。
- フォント、最大フォントサイズ、最小フォントサイズをオブジェクト引数へ移動することで使いやすくしています。
- また、最大フォントサイズについても比較的使われやすい14pxをデフォルトとしました。
1. 従来関数について、フォント名の指定はほぼデフォルトであるにも関わらず、最大フォントサイズの指定が必要だったために再指定することが殆どになっていました。これを改善しています。
=> refactor: [0940] フォントサイズ取得関数を更新

js/danoni_main.js
- jsファイルやcssファイルについてはカレントパス指定時、`g_workPath`の値を基準にパスを決定する方式でした。
ただし、音楽データについてはmusicUrlとmusicFolderの組合せのみで、
カレントパスを指定しても`g_workPath`の値を使用していないため、 基本的には同じ仕様ですが条件によっては異なる条件になっていました。
musicFolderの仕様を考慮しつつ、getFilePath関数を利用するように見直しました。
1. コードの整理及び、仕様をわかりやすくするため。
=> improve: [0942] 音楽データの読み込みパスの仕様を他のファイルと統一

js/lib/danoni_constants.js
- 9A, 9B, 9i, 9dkeyの最小横幅をデフォルトの600pxに変更しました。
- |transKeyUse=false|に設定していない限りは11ikeyの横幅である650pxに引きずられるので、実影響は限定的です。
1. 必要な横幅を指定し、必要以上に横幅が広がるのを防ぐため。
- 16ikeyも同形状だが、こちらは9key系と違いステップゾーン間の距離が
7keyと同じ55px（9key系は52.5px）のため据え置きとする。
=> improve: [0947] 9key系のデフォルトの最小横幅を本来必要な横幅長に戻す

js/danoni_main.js
- 選曲モード時、作品全体のコメント機能を使えるように見直しました。
- 曲別のコメントのidを`lblCommentM`に変更しています。
- 選曲モードのときだけ、作品全体のコメント欄が若干大きくなっています（ボタンの関係）。
1. 曲別と作品全体で同じidを使用していたため。
元々両方を使う想定はありませんでしたが、共存できた方が便利で、中途半端に設定だけ残っていたため。
- 不具合というより機能追加ですが、v41では共存できるかのような挙動になるので、
v41の場合は共存機能が使えないように修正する予定です。
=> improve: [0950] 曲個別のコメントと作品全体のコメントが共存できるよう変更

js/danoni_main.js
- カスタムキーで使用できる、layerGroupXについてlayerTransXの対応付けが間違っており、機能していませんでした。
1. 数式の適用間違いです。
- ver39.1.0以降の機能のため、それ以降に影響します。
=> fix: [0951] layerGroupXに対するlayerTransXの対応ズレを修正

js/danoni_main.js
- 一部のオプションで、同一スクロール扱いのものについて処理を変えている部分がありましたが、
その条件について、レイヤー違いであっても同一スクロールであれば同一と見做すよう変更しました。
1. 一部のオプションが有効にならなくなるため。
- PR #1752 関連の変更となります。
=> improve: [0953] 同一スクロール条件を一部変更

js/danoni_main.js
- musicTitleの4番目要素の表示はmusicNoの値が存在する場合のみタイトル画面に表示する項目ですが、
musicNoが無くても表示するようになっていました。
- 選曲モードの有無によらず、musicNoの値に応じた楽曲名が表示されるようになっていました。
- 従来通り、選曲モードで無い場合はmusicTitleの4番目要素を利用するよう修正しました。
2. 想定された動きになっていなかったため。
参考：musicTitle
https://github.com/cwtickle/danoniplus/wiki/dos-h0001-musicTitle
- PR #1860 (ver41.3.1) 以降で発生した問題と思われます。
=> fix: [0961] musicTitleの4番目要素の反映方法における問題を修正

js/danoni_main.js, js/lib/danoni_constants.js
- 譜面毎に空押し設定の初期設定と有効化有無を設定できるようにしました。
- いずれも`excessiveUse`で指定します。$区切りで譜面毎、有効化有無/初期設定の組合せで指定します。
- 初期設定の指定がない場合はOFFが既定になります。
```
|excessiveUse=false,ON$true,OFF|
```
- excessiveJdgUseは全体設定用としての役割になり、`true`が指定されると一律初期設定が有効になります。
- 譜面毎の設定に変更になった関係で、譜面毎にExcessiveの設定がリセットされるように変更になりました。
1. 譜面毎に切り替える需要があるため。
=> feat: [0963] 譜面毎の空押し設定に対応
